### PR TITLE
CLI and Client & Agent Service test splitting

### LINKED ISSUE #306: Fix node claims throughout `tests/`
### Specification

There are several occurrences of node claims that are being incorrectly set up throughout the testing suites. 

Consider the situation where we have two nodes, `B` and `C`, with a cryptolink between them (i.e. part of the same gestalt). The cryptolink should be represented by a **single** claim on each node's sigchain (that's been signed by both `B` and `C`). That is, `B` will have a single claim signed by both itself and `C`, and `C` will have a single claim signed by both itself and `B`.

However, there are some tests that aren't setting this up correctly. For example, in `tests/bin/identities.test.ts`:

```ts
      // Adding sigchain details.
      const claimBtoC: ClaimLinkNode = {
        type: 'node',
        node1: nodeB.nodeManager.getNodeId(),
        node2: nodeC.nodeManager.getNodeId(),
      };
      const claimCtoB: ClaimLinkNode = {
        type: 'node',
        node1: nodeC.nodeManager.getNodeId(),
        node2: nodeB.nodeManager.getNodeId(),
      };
      await nodeB.sigchain.addClaim(claimBtoC);
      await nodeB.sigchain.addClaim(claimCtoB);
      await nodeC.sigchain.addClaim(claimCtoB);
      await nodeC.sigchain.addClaim(claimBtoC);
```

Here we're incorrectly adding 2 claims, that are singly signed by the owner of the respective sigchain the claim is added to. From the git blame, it seems like this was added prior to the refactoring of node claims though, so just something that's been missed.

### Additional context

* originally discovered in https://github.com/MatrixAI/js-polykey/pull/278#issuecomment-985219792
* original nodes claims MR https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/209

### Tasks

1. Create a `tests` utility function to create a node claim (a doubly signed claim, signed by both nodes' private keys).
2. Find and fix all instances where the nodes claims are being incorrectly set up.

### LINKED ISSUE #308: Split CLI and GRPC API tests
### Specification

It's time to split up the test modules for these areas, this will our test performance, and give us understanding of the test coverage of all our API behaviour:

* `tests/bin`
* `tests/agent`
* `tests/client`

For `tests/bin`, each command can have its own test. Look at `tests/bin/agent` as a template for what to do. Right now all the other commands are single test modules in their own directory like `tests/bin/identities/identities.test.ts`. These should all be split up into individual commands. Note that most of the tests should be using the shared global agent. However some tests may be independent. This is where you can use the nested describe pattern as demonstrated in `tests/bin/agent/status.test.ts`.

Some tips:

* Use the global shared agent
* Use module mocking for prompting
* Use the correct `pkExec`, `pkStdio`, `pkSpawn`, `pkExpect` utility
* Use 1 nested describe at the bottom in case there is a need to use a the global shared agent and also have independent tests
* Make sure to revert all side effects in the global shared agent! In every test!

We may optimise it further when realising that some tests can just use their own agent instead of sharing the agent. This is because by using the global keypair, starting agents is really fast now. This will probably need to be used in the nodes commands anyway.

For `tests/agent` and `tests/client`, this is about the GRPC API. We have now split up each RPC handler into their own file, this allows much more isolated and specific unit testing of each handler. Refer to `tests/client/service/agentStop.test.ts` as the template for each handler test. All `rpc*.test.ts` should be converted appropriately. Refer to #249 when you have questions or discussions about API design. This is just about splitting the tests up, however we may find we can fix things up regarding the API as this issue is tackled.

### Additional context

* #264 - concurrent testing scalability should improve as we separate our tests out
* #292 - PR for CI/CD that brought in changes that allows isolated GRPC API tests in for client service and agent service
* #249 - Overall GRPC API review
* #306 - Node claims tests are still broken and need to be fixed

### Tasks

1. Split up `tests/bin`
2. Split up `tests/client/service` and refer to `src/client/service` and `tests/client/service/agentStop.test.ts`
3. Split up `tests/agent/service` and refer to `src/agent/service`
4. Check for other API conformance/design issues, such as error handling.

### LINKED ISSUE #312: Propagate root keypair changes to domains external to `KeyManager`
### Specification
When the root keypair is changed, this needs to be propagated to other places that rely on knowing this information. In particular, the new Node Id generated by a new keypair needs to be propagated to the `NodeManager` and `Status`, among other places. This can be achieved either through the use of the Observer Pattern, or by using [Event Emitters](https://nodejs.org/api/events.html#class-eventemitter) (preferred due to looser coupling).

### Additional context
- Example implementation of the Observer Pattern for this purpose: https://github.com/MatrixAI/js-polykey/pull/311/commits/f0976715a6b5fecd430712adbbfbe210e092ae02
- Discussion of Observer Pattern vs. Event Emitters (Pub/Sub Pattern): https://github.com/MatrixAI/js-polykey/pull/311#issuecomment-1003234571
- Discussion of dependency injection + coupling issues: https://github.com/MatrixAI/js-polykey/pull/311#issuecomment-1003237027
- Discussion of propagation of keypair renewal: https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/209#note_676525054

### Tasks
1. Find all places where keypair renewal/resetting must be propagated to
2. Expose a property in `KeyManager` that allows events to be propagated to dependent classes
3. Register keypair renewal and resetting as such events
4. Ensure that errors are correctly handled asynchronously

### PR DESCRIPTION
**Pull request by emmacasolin**
### Description
This PR will split our CLI and GRPC API tests into individual files for each command/handler, as well as refactor the tests to improve performance and coverage.

### Issues Fixed
* Fixes https://github.com/MatrixAI/js-polykey/issues/308
* Fixes https://github.com/MatrixAI/js-polykey/issues/306
* Fixes https://github.com/MatrixAI/js-polykey/issues/312

### Tasks
1. [x] For all `tests/bin`, `tests/client`, and `tests/agent`: 
  - Split tests for each command/handler into their own individual files (except for commands that directly correspond to another command, e.g. `identitiesTokenGet`/`identitiesTokenPut`/`identitiesTokenDelete`)
  - Have all tests use the global shared agent and/or the nested describe pattern used by `tests/bin/agent/status.test.ts` where appropriate
  - Use module mocking for prompting
  - Use the correct `pkExec`, `pkStdio`, `pkSpawn`, `pkExpect` utility
  - Only use nested describe if there is a need to use own agent (rather than global agent)
  - Revert all side effects in the global shared agent and the end of each test
  - Remove all state setup/teardown from `beforeEach` and `afterEach`
  - Make sure `WARN` is the default wherever `LogLevel` is used
9. [x] Remove any unnecessary tests from `GRPCClientClient.test.ts` and `GRPCClientAgent.test.ts`
10. [x] Check for other API conformance/design issues, such as error handling
11. [x] Check order of stopping (in particular proxy stopping in notifications manager)
11. [x] Replace all use of `clearXXX()` with destroy methods in tests
12. [x] Restart method for agent for clearing side effects from the global agent that cannot be otherwise undone
13. [x] Replace `polykeyStartupTimeout` with `defaultTimeout`
14. [x] Fix up node claiming in tests (some tests set them up as singly-signed claims when they should be signed by both nodes) - from MatrixAI/Polykey#306
15. [x] Integrate `EventBus` into PK to be used for asynchronously emitting root keypair changes
16. [x] Fix up imports to only be using selective imports (except for '../utils')
17. [x] Fix identities bin tests and gestalts client service tests

Tests that need splitting:

`tests/bin` (these should be fully simulated wherever possible using the global agent, then own agent using global keypair, then own agent fully created from scratch)
- `agent`
  - [x] lock
  - [x] lockall
  - [x] start
  - [x] status
  - [x] stop
  - [x] unlock
- `identities`
  - [x] authenticate (must create own agent in order to undo authentication)
  - [x] claim (must create own agent in order to unclaim)
  - [x] search (must create own agent in order to register provider)
  - [x] allow
  - [x] disallow
  - [x] discover
  - [x] get
  - [x] list
  - [x] permissions
  - [x] trust
  - [x] untrust
- `notifications`
  - [x] send
  - [x] read
  - [x] clear
- `keys`
  - [x] cert
  - [x] certchain
  - [x] decrypt
  - [x] encrypt
  - [x] password
  - [x] renew
  - [x] reset
  - [x] root
  - [x] sign
  - [x] verify
- `nodes` - ETA [Thur 13/1]
  - [x] add (must create own agent to un-add + remote agent(s) to add)
  - [x] claim (must create own agent to unclaim + remote agent to claim)
  - [x] find (must create own and remote agent(s) for same reason as add)
  - [x] ping (must create own and remote agent(s) for same reason as add)

`tests/client` (these can be mocked as much as possible and usually don't need a whole agent) - ETA [Wed 12/1]
- [x] agentLockAll (only needs sessionManager)
- [x] agentStatus (needs keyManager, grpcServerClient, grpcServerAgent, fwdProxy, revProxy)
- [x] agentStop
- [x] agentUnlock
- [x] gestaltsActionsGetByIdentity (needs gestalt graph)
- [x] gestaltsActionsGetByNode (needs gestalt graph)
- [x] gestaltsActionsSetByIdentity (needs gestalt graph)
- [x] gestaltsActionsSetByNode (needs gestalt graph)
- [x] gestaltsActionsUnsetByIdentity (needs gestalt graph)
- [x] gestaltsActionsUnsetByNode (needs gestalt graph)
- [x] gestaltsDiscoveryByIdentity (needs discovery)
- [x] gestaltsDiscoveryByNode (needs discovery)
- [x] gestaltsGestaltGetByIdentity (needs gestalt graph)
- [x] gestaltsGestaltGetByNode (needs gestalt graph)
- [x] gestaltsGestaltList (needs gestalt graph)
- [x] identitiesAuthenticate (needs identities manager)
- [x] identitiesClaim (needs identitiesManager, sigchain, nodeManager - mock authentication + claiming process)
- [x] identitiesInfoGet (needs identities manager)
- [x] identitiesInfoGetConnected (needs identities manager)
- [x] identitiesProvidersList (needs identities manager)
- [x] identitiesTokenDelete (needs identities manager)
- [x] identitiesTokenGet (needs identities manager)
- [x] identitiesTokenPut (needs identities manager)
- [x] keysCertsChainGet (needs keyManager)
- [x] keysCertsGet (needs keyManager)
- [x] keysDecrypt (needs keyManager)
- [x] keysEncrypt (needs keyManager)
- [x] keysKeyPairRenew (needs keyManager, nodeManager, fwdProxy, revProxy, grpcServerClient)
- [x] keysKeyPairReset (needs keyManager, nodeManager, fwdProxy, revProxy, grpcServerClient)
- [x] keysKeyPairRoot (needs keyManager)
- [x] keysPasswordChange (needs keyManager)
- [x] keysSign(needs keyManager)
- [x] keysVerify (needs keyManager)
- [x] nodesAdd (needs nodeManager)
- [x] nodesClaim (needs nodeManager + notificationsManager - mock claiming process)
- [x] nodesFind (needs nodeManager - mock connecting to other node)
- [x] nodesPing (needs nodeManager - mock connecting to other node)
- [x] notificationsClear (needs notificationsManager - mock receiving notifications)
- [x] notificationsRead (needs notificationsManager - mock receiving notifications)
- [x] notificationsSend (needs notificationsManager - mock receiving notifications + connecting to other node)

`tests/agent` (these should be fully simulated wherever possible) - ETA [Mon 17/1]
- [x] nodesCrossSignClaim (must create own agent and agent to claim)
- [x] notificationsSend (must create a second agent)

########################################################################

Tests that cannot yet be addressed:

Commands that may be removed

`tests/bin/agent/restart`

`tests/client/service/agentRestart`

Commands that will be implemented/fixed in https://github.com/MatrixAI/js-polykey/pull/266

`tests/bin/secrets`
- env
- create
- delete
- dir
- edit
- get
- list
- mkdir
- update

`tests/bin/vaults`
- clone
- permissions
- pull
- scan
- share
- stat
- unshare
- create
- delete
- list
- log
- rename
- version

`tests/client/service`
- vaultsClone
- vaultsPermissions
- vaultsPermissionsSet
- vaultsPermissionsUnset
- vaultsPull
- vaultsScan
- vaultsSecretsStat
- vaultsCreate
- vaultsDelete
- vaultsList
- vaultsLog
- vaultsRename
- vaultsSecretsDelete
- vaultsSecretsEdit
- vaultsSecretsGet
- vaultsSecretsList
- vaultsSecretsMkdir
- vaultsSecretsNew
- vaultsSecretsNewDir
- vaultsSecretsRename
- vaultsVersion

`tests/agent/service`
- vaultsGitInfoGet
- vaultsGitPackGet
- vaultsPermissionsCheck
- vaultsScan

Tests that are yet to be written in https://github.com/MatrixAI/js-polykey/pull/326
- nodesChainDataGet
- nodesClosestLocalNode
- nodesHolePunchMessage

Other unimplemented commands

`tests/agent/service/nodesClaimsGet`

### Final checklist
* [x] Domain specific tests
* [x] Full tests
* [x] Updated inline-comment documentation
* [x] Lint fixed
* [x] Squash and rebased
* [x] Sanity check the final build

### CODE REVIEW

**Comment by emmacasolin** [comment]
I've encountered a problem with the identities CLI - as far as I can see there isn't a command to add a node or identity to the gestalt graph, or any other command that would do this as a side-effect. Since the node/identity needs to be added to the graph before we can allow/disallow permissions (and probably other operations too), I can't see a way for these commands to work from a CLI perspective?

These tests were previously setting the nodes/identities manually (e.g. `await polykeyAgent.gestaltGraph.setNode(node1)`), however, this isn't possible with the shared agent. While I could probably mock the gestalt graph for testing purposes there's still the issue of these commands potentially not working for real users, unless I'm missing something.

**Comment by emmacasolin** [comment]
Related to my previous comment - there also aren't CLI commands for the identities token manipulation grpc handlers (i.e. `identitiesTokenGet`, `identitiesTokenPut`, `identitiesTokenDelete`), which means I don't think identities can be authenticated or claimed using solely the CLI.

**Comment by CMCDragonkai** [comment]
I believe that you can definitely authenticate via the CLI. But it involves using the browser.

@joshuakarp had previously mocked the TestProvider/browser call so that it was fully automated in the tests.

All other identities related functionality would require mocking and enhancing the flexibility of the TestProvider. Right now I'm not sure if the TestProvider is applied on the global shared agent. This was something we had discussed but didn't get around to.

In which case I suggest you focus on the other test areas to first split. We can then circle back to the TestProvider problem and mock it's behaviour.

And yes there should probably be more identities CLI calls, we hadn't fully reviewed the workflow here yet.

**Comment by CMCDragonkai** [comment]
Just a note about the final describe block that exists for bin tests that use the global agent. Make sure to name the describe like this:

```
  describe('status with global agent', () => {
```

Replace the `status` with the relevant command, and this section should always be at the bottom.

**Comment by emmacasolin** [comment]
Decided to move onto the GRPC tests since there are a lot of things blocking the CLI tests (need to look into mocking the identities manager + gestalt graph and/or adding more CLI calls to fill gaps), however there are errors in `tests/client/service/agentStop.test.ts` that prevent it from compiling so I'm hesitant to use it as a base before this is resolved. All of the errors are the same:
```
tests/client/service/agentStop.test.ts:103:20 - error TS2339: Property 'running' does not exist on type 'PolykeyAgent'.

    103     expect(pkAgent.running).toBe(false);
                           ~~~~~~~
```
Not sure what change between when the file was created 9 days ago and now has caused this issue.

**Comment by emmacasolin** [comment]
The tests that have been split up so far and that are passing are:
- `keys/cert.test.ts`
- `keys/certchain.test.ts`
- `keys/decrypt.test.ts`
- `keys/encrypt.test.ts`
- `keys/password.test.ts`
- `keys/renew.test.ts`

I've also done `identities/allow.test.ts`, `identities/authenticate.test.ts`, and started on `identities/claim.test.ts` and `notifications/send.test.ts`, but all of these won't be able to be completed until we're able to mock the identities manager (test provider) and the gestalt graph. Similarly, I'm expecting the nodes domain will be difficult as well due to the side effects that can't be cleared, unless these tests use their own individual agents rather than the shared one.

**Comment by CMCDragonkai** [comment]
All uses of the global shared agent is serialised with mutual exclusion. So any test with side-effects just needs to reverse those side-effects at the end. As long as the ability to reverse is available, then testing should be possible.

**Comment by emmacasolin** [comment]
The keys CLI tests have all been split into their own files. I was having issues with keys reset where the agent was needing to be stopped and restarted after calling `keys reset` in order for subsequent commands to work, so this test creates it's own agent process rather than using the shared agent. It also needed a timeout due to this, as it can take a while to run, particularly when run with the rest of the keys tests.

**Comment by CMCDragonkai** [comment]
@emmacasolin when you get to the TestProvider mocking stage. Consider that there are 3 ways of doing mocking.

1. Mocking a single function in a module
2. Mocking an entire module
3. Mocking a single method inside an class/object instance

We have used all 3 mocking patterns in other test areas. Consult with @tegefaulkes to get an idea of how to do it.

I reckon we would need to mock the `IdentitiesManager` in the global shared agent. This can be done because the global agent is using `pkStdio`. Since it currently registers the `GitHubProvider`, all we may need to do is just pre-register it on our mock prior to running `pkStdio`. You'll have to prototype the different ways of doing it, perhaps by creating the mock instance and then just registering the provider and expect that inside the `pkStdio` it would acquire the same instance... Or by mocking out the constructor of `IdentitiesManager` or `createIdentitiesManager` static method and add it there. This mock wouldn't need to be cleared because it's long running and global in the agent.

**Comment by CMCDragonkai** [comment]
Btw if you find places where side effects can't be reversed (and no, not with a clear method), those places should add the opposite method to keep their APIs symmetric.

However I know that say Sigchain may not be capable of doing this. At least not for a single claim. But then a general reset of the sigchain can be exposed to the client service that allows complete wipe.

**Comment by CMCDragonkai** [comment]
When this is ready, feel free to merge back into `qa-testing`.

**Comment by CMCDragonkai** [comment]
> Decided to move onto the GRPC tests since there are a lot of things blocking the CLI tests (need to look into mocking the identities manager + gestalt graph and/or adding more CLI calls to fill gaps), however there are errors in `tests/client/service/agentStop.test.ts` that prevent it from compiling so I'm hesitant to use it as a base before this is resolved. All of the errors are the same:
> ```
> tests/client/service/agentStop.test.ts:103:20 - error TS2339: Property 'running' does not exist on type 'PolykeyAgent'.
> 
>     103     expect(pkAgent.running).toBe(false);
>                            ~~~~~~~
> ```
> Not sure what change between when the file was created 9 days ago and now has caused this issue.

To resolve this. Go to `src/PolykeyAgent.ts` and find the statement `pkAgent[running]`.

Replace test expectations using `pkAgent.running` with `pkAgent[running]`.

Import the symbol `running` from async-init.

**Comment by CMCDragonkai** [comment]
> The keys CLI tests have all been split into their own files. I was having issues with keys reset where the agent was needing to be stopped and restarted after calling `keys reset` in order for subsequent commands to work, so this test creates it's own agent process rather than using the shared agent. It also needed a timeout due to this, as it can take a while to run, particularly when run with the rest of the keys tests.

Why do we need to restart the agent when calling keys reset? It should work without doing this. If it requires a restart, that would be a bug.

**Comment by emmacasolin** [comment]
> Why do we need to restart the agent when calling keys reset? It should work without doing this. If it requires a restart, that would be a bug.

In that case I'll play around with it and see what's going on. It could just be an issue with timing, not sure.

**Comment by emmacasolin** [comment]
The error that's occurring on commands that follow `keys reset` is coming from `verifyServerCertificateChain()` in the network utils. After the root keypair is reset the root certificate chain is also reset, so the certificate claiming the nodeId used to contact the server is removed. This means that the client can't be authenticated to the server. I think the reason that stopping and re-starting the agent removes this issue is that this allows the nodeId to be updated? Otherwise the old nodeId is used, which can no longer be verified against the updated tls config.

**Comment by CMCDragonkai** [comment]
Ah yes so basically when this happens the new node ID should be used by the client GRPCClient.

Or if this is between agent to agent, then the new TLSConfig must be set for the Forward and Reverse proxies.

This was something we had to a while ago for agent to agent networking and we provisioned for this instance.

Look at the handler for key reset and the associated KeyManager method, see how it's supposed to rencrypt all the keys and reset the TLSConfig. The whole process is meant to be a graceful swap.

**Comment by emmacasolin** [comment]
The problem with `keys reset` in the end came down to the status file not being updated when the root keypair is changed, so I injected the `Status` into `KeyManager` and added a method to `Status` to allow the node id to be updated, and called this in both `resetRootKeypair()` and `renewRootKeypair()`. Now the agent doesn't need to be restarted in order to write the new node id into the status file, since previously this was the only way of writing anything to the file.

**Comment by emmacasolin** [comment]
During my meeting today with @tegefaulkes, we decided that the simplest way to "mock" the Test Provider usage was to just register it during the setup of the global agent in `tests/utils.ts`. As @CMCDragonkai mentioned, registering the test provider is a long-running, global operation and doesn't need to be cleared, so registering it during setup seems like the best way to go about it.

**Comment by CMCDragonkai** [comment]
Yea I think that's a good idea. But the question is how to do it, whether by module mocking or class method mocking? Do we use the jest.mock or jest.spyOn?

**Comment by CMCDragonkai** [comment]
> The problem with `keys reset` in the end came down to the status file not being updated when the root keypair is changed, so I injected the `Status` into `KeyManager` and added a method to `Status` to allow the node id to be updated, and called this in both `resetRootKeypair()` and `renewRootKeypair()`. Now the agent doesn't need to be restarted in order to write the new node id into the status file, since previously this was the only way of writing anything to the file.

I'm thinking that injecting status like this isn't the best idea and instead composition should be used. But I need to think how to propagate changes of keypair changes to all the places that need to be updated when the keypair changes.

**Comment by CMCDragonkai** [comment]
Example: https://www.sitepoint.com/three-design-patterns-that-use-inversion-of-control/

**Comment by emmacasolin** [comment]
> Yea I think that's a good idea. But the question is how to do it, whether by module mocking or class method mocking? Do we use the jest.mock or jest.spyOn?

Just simply calling the `registerProvider()` function as usual:
```ts
    const pkAgent = await PolykeyAgent.createPolykeyAgent({
      password: globalAgentPassword,
      nodePath: globalAgentDir,
      keysConfig: {
        rootKeyPairBits: 1024
      },
      seedNodes: {}, // explicitly no seed nodes on startup
      logger,
    });
    pkAgent.identitiesManager.registerProvider(new TestProvider());
```

This has already been added to `tests/utils.ts` (lines 112-121) and the `authenticate` test is passing with this method of doing it. We're actually registering the test provider so no mocking is needed.

**Comment by CMCDragonkai** [comment]
But the global shared agent doesn't give you access to the PK agent.

On 30 December 2021 7:35:21 pm AEDT, emmacasolin ***@***.***> wrote:
>> Yea I think that's a good idea. But the question is how to do it, whether by module mocking or class method mocking? Do we use the jest.mock or jest.spyOn?
>
>Just simply calling the `registerProvider()` function as usual:
>```ts
>    const pkAgent = await PolykeyAgent.createPolykeyAgent({
>      password: globalAgentPassword,
>      nodePath: globalAgentDir,
>      keysConfig: {
>        rootKeyPairBits: 1024
>      },
>      seedNodes: {}, // explicitly no seed nodes on startup
>      logger,
>    });
>    pkAgent.identitiesManager.registerProvider(new TestProvider());
>```
>
>This has already been added to `tests/utils.ts` (lines 112-121) and the `authenticate` test is passing with this method of doing it. We're actually registering the test provider so no mocking is needed.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/MatrixAI/js-polykey/pull/311#issuecomment-1002925466
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by emmacasolin** [comment]
> But the global shared agent doesn't give you access to the PK agent.

We don't need to access it - the registration is being done inside the `setupGlobalAgent` function

**Comment by CMCDragonkai** [comment]
Yep I forgot it was changed over to like that. So that should be sufficient, you can proceed with that solution.

**Comment by emmacasolin** [comment]
I've implemented the observer pattern to enable places that need to be updated when the keypair is changed to do so automatically. The relevant tests are passing, but the naming I've used isn't great so I want to fix that at some point. At the moment only `NodeManager` and `Status` are "observers" of the `KeyManager` - is there anything else that should be an observer as well? It's easy enough to change this later on by simply having whatever class needs to monitor the keypair  implement the `ObserverKeypair` interface in `src/keys/types.ts`.

**Comment by CMCDragonkai** [comment]
**Observer Pattern or Pub/Sub Pattern**

Ok I think a good and simple solution would be like this:

* Expose a read-only `keyManager.events` property that is an EventEmitter instance. Should be instantiated at the class property location.
* On the keys reset and various other commands events are emitted via `this.events.emit`. The event names should be standardised and simple. Like `rootKeyPairReset` which would be camel cased. We can organise the names later.
* Client classes register handlers by doing `keyManager.events.on(...)`.
* The handlers should be registered at the `PolykeyAgent.start` or `PolykeyAgent.createPolykeyAgent`. This is the "bootstrap" point and where everything gets wired up. Note that if it is done in `start`, then `stop` should be removing the listeners with `keyManager.events.off`. This keeps everything quite flexible, and we connect up the event triggers at the "root" or bootstrap point of the application.

However there are some trade offs using event emitter for this. The problem is what happens when the handlers are asynchronous. Discussed here https://nodejs.org/api/events.html#capture-rejections-of-promises, if the handlers are async, any thrown exception would have to be caught by the event emitter error handler. This is not within the callstack of the original method call like `keyManager.resetRootKeyPair`. Which means exception handling and debugging the callstack would be decoupled from the original method call that triggered the emission of the event. As per the documentation, to ensure that the event doesn't cause the nodejs process to crash, you would need an error handler on `keyManager.events.on('error', ...);`. And this error handler would simply log out the error with `this.logger.error(...)`, the `KeyManager` cannot do anything else since it doesn't know why it occurred.

Comparing it with a direct observer pattern implementation, the handlers would be called by the methods in `KeyManager`. which means exceptions raised during those calls would be part of the callstack of doing `keyManager.resetRootKeyPair`. It's a bit easier to debug, but it couples up the calls to other domains within the KeyManager context, and it doesn't allow us to make use of the existing event emitter infrastructure. It's not as flexible, and not as extendable.

There's another tradeoff with using event emitter pub/sub over observer pattern. And that's the asynchronicity of handling. Which is that, in observer pattern, it is guaranteed that all the other domains received the changes and handled it due to the usage of `await` by the time you finished your method call of `await keyManager.resetRootKeyPair`, but with event emitter, there's no such guarantee. This is an eventual consistency problem. So if we `resetRootKeyPair()`, and then expect all other domains to have reacted within that time, then it's going to cause a race condition. All other domains will react, but only eventually and they will be placed onto the event loop queue. Is this a problem or not? Depends on what the change is?

I reckon to deal with this trade off, we have to be able to do both. Use DIed observers for when changes have to be synchronously asynchronous. And use event emitter when the changes can be asynchronously asynchronous. We already do this with our DIed dependencies, but this is somewhat tighter coupling than the loose coupling of event-emitter/pub-sub.

The cool thing is that all of this can lead to a data flow architecture later that can be consumed by the GUI client.

Anyway I'm in favour of using the event emitter system. But you must have the error handler attached and `captureRejections: true` set.

Note that by using the event emitter, we technically change from "Observer pattern" to "Pub/Sub pattern".

**Comment by CMCDragonkai** [comment]
In the case of `NodeManager` or `Status`, I can safely say that:

* `Status` should not be aware of `KeyManager`, don't inject `KeyManager` into `Status` nor `Status` into `KeyManager`. These are really independent things.
* `NodeManager` can take `KeyManager` as a dependency, but not the other way around.

It does appear that observer pattern is only a slight upgrade over DIed dependencies. Since you can pass in a handler that will be executed by the `KeyManager` without having to inject in the domain. So for example you want `KeyManager` to notify `NodeManager` about the root key reset. Well we know we can't inject `NodeManager` into `KeyManager`, therefore DI is not suitable. If we inject `KeyManager` into `NodeManager`, this still isn't sufficient as the `KeyManager` changes are not something that can be subscribed to. So then observer pattern allows something else whether that is `NodeManager` itself or `PolykeyAgent` to register a handler that `KeyManager` will call when key pair gets reset, and this handler can then call `NodeManager`. If this is done inside `NodeManager`, you would use `this.*` but if it is in `PolykeyAgent` then this would be `nodeManager.*`. The tradeoff is that `PolykeyAgent` can't call protected or private methods in `NodeManager`. So `PolykeyAgent` would be providing loose coupling of the 2 classes and joining them together via this handler.

So in terms of tight to loose coupling spectrum:

* Just use DI (not always suitable)
* Observer Pattern with registration inside `NodeManager` -  this requires DI of `KeyManager` into `NodeManager`
* Observer Pattern with registration inside `PolykeyAgent` - this requires handlers that only call public methods
* Event emitter pub/sub pattern with registration in `NodeManager` - requires DI, but it is asynchronously asynchronous, and error context is independent
* Event emitter pub/sub pattern with registration in `PolykeyAgent` - same but doesn't require DI.

Anyway this should be a separate issue @emmacasolin can you create this issue and copy this discussion over.

**Comment by emmacasolin** [comment]
> Anyway this should be a separate issue @emmacasolin can you create this issue and copy this discussion over.

New issue created here: https://github.com/MatrixAI/js-polykey/issues/312

**Comment by emmacasolin** [comment]
What is the purpose of the `identities trust`/`identities untrust` commands? Because all they currently do is set/unset the `notify` permission for a node or identity, which can be achieved with the `identities allow`/`identities disallow` commands anyway. Should the `identities trust`/`identities untrust` commands instead be setting/unsetting a node or identity in your gestalt graph? Because there currently isn't any command for this, so it isn't possible to allow/disallow permissions at all without directly accessing the agent because you can't add a node or identity to set the permissions of.

**Comment by CMCDragonkai** [comment]
That is the only purpose to identities trust and untrust. It is to allow notifications to pass through. We keep it as is for now until we find better uses of it later. It's elevated to its own command compared to allow or disallow which is more generic.

On 31 December 2021 2:30:21 pm AEDT, emmacasolin ***@***.***> wrote:
>What is the purpose of the `identities trust`/`identities untrust` commands? Because all they currently do is set/unset the `notify` permission for a node or identity, which can be achieved with the `identities allow`/`identities disallow` commands anyway. Should the `identities trust`/`identities untrust` commands instead be setting/unsetting a node or identity in your gestalt graph? Because there currently isn't any command for this, so it isn't possible to allow/disallow permissions at all without directly accessing the agent because you can't add a node or identity to set the permissions of. 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/MatrixAI/js-polykey/pull/311#issuecomment-1003255172
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by emmacasolin** [comment]
In that case should there be new commands for adding/removing a node/identity from the gestalt graph? Or should this be happening inside the existing `allow`/`disallow`/`trust`/`untrust` commands? Because right now all of the gestalt actions CLI tests fail because you can't modify the permissions of a node/identity that doesn't exist in your gestalt graph, which is what these commands are currently attempting to do.

**Comment by CMCDragonkai** [comment]
Atm there's no way to unclaim in the sigchain. The revoke ability was still a TBD. 

I'm not sure what you mean by modifying permissions of nodes/identities not in a gestalt. Not every node is supposed to be in your gestalt. Only a select few are supposed to be in Ur gestalt. Whether in or not in gestalt shouldn't have any relationship to modifying permissions.

On 31 December 2021 4:32:59 pm AEDT, emmacasolin ***@***.***> wrote:
>In that case should there be new commands for adding/removing a node/identity from the gestalt graph? Or should this be happening inside the existing `allow`/`disallow`/`trust`/`untrust` commands? Because right now all of the gestalt actions CLI tests fail because you can't modify the permissions of a node/identity that doesn't exist in your gestalt graph, which is what these commands are currently attempting to do.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/MatrixAI/js-polykey/pull/311#issuecomment-1003275149
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by CMCDragonkai** [comment]
Due to lacking the unclaim/revoke ability, sigchain operations end to be idempotent. So one can reclaim the same thing over and over without any problems. Adjust the tests and src accordingly.

**Comment by emmacasolin** [comment]
> I'm not sure what you mean by modifying permissions of nodes/identities not in a gestalt. Not every node is supposed to be in your gestalt. Only a select few are supposed to be in Ur gestalt. Whether in or not in gestalt shouldn't have any relationship to modifying permissions.

I'll go through one of the tests to show what I mean. So right now I have a test for `identities allow` that goes as follows:
1. Run command `identities allow [nodeId] notify`
2. Check for successful exit code
3. Run command `identities permissions [nodeId]`
4. Check for successful exit code and for permission "notify"

Without making any changes to the codebase, this test fails at step 2 with the error `ErrorGestaltsGraphNodeIdMissing`, which is being thrown inside `GestaltGraph.ts` inside the method `setGestaltActionByNode()`. The Gestalt Graph has it's own DB, and this method asserts that the provided nodeId is in that DB before calling any ACL commands. If the nodeId isn't in the Gestalt Graph DB the `ErrorGestaltsGraphNodeIdMissing` error is thrown.

If we remove that DB check from `setGestaltActionByNode()` the `identities allow` command is perfomed successfully, but then we get an error at step 4 coming from the subsequent `identities permissions` command where the "notify" permission is not returned. This command, which calls `getGestaltActionsByNode()` (also inside `GestaltGraph.ts`) is also searching the Gestalt Graph's DB for the provided nodeId before calling any ACL commands. Again, removing this DB check causes the command to be performed successfully, and now the entire test passes.

If I'm understanding you correctly, do these gestalt actions commands actually have no relation to the Gestalt Graph DB? And if this is the case, can the DB checks in these commands be safely removed?

**Comment by emmacasolin** [comment]
Would it be possible for `setupGlobalAgent()` to expose a `reset` function that resets the global agent to its original, fresh state that can be called by the tests? I think this would be safer than expecting every test to undo all of its side-effects, especially since some, such as sigchain operations and authenticating an identity, have no way to undo themselves and/or don't make sense to expose an undo operation to the client. Since the expectation in each test is that the command is being run on a fresh agent, it seems to me like doing a full reset of the global agent at the end of each test is not only convenient, but also expected behaviour?

**Comment by emmacasolin** [comment]
When the global agent is created, `rootKeyPairBits` is set to 1024, however, signed claims on the sigchain (which use RS256) require this to be 2048 or higher. I've changed this accordingly, because otherwise claims commands will not work on the global agent as they are now. If we switch to a different algorithm in the future then this can likely be reverted back to 1024.

**Comment by CMCDragonkai** [comment]
Just change it to 2048. I'm doing it in qa-testing.

**Comment by CMCDragonkai** [comment]
> Would it be possible for `setupGlobalAgent()` to expose a `reset` function that resets the global agent to its original, fresh state that can be called by the tests? I think this would be safer than expecting every test to undo all of its side-effects, especially since some, such as sigchain operations and authenticating an identity, have no way to undo themselves and/or don't make sense to expose an undo operation to the client. Since the expectation in each test is that the command is being run on a fresh agent, it seems to me like doing a full reset of the global agent at the end of each test is not only convenient, but also expected behaviour?

The global agent setup uses `PolykeyAgent.createPolykeyAgent`.

This means we have access to the `agent` object.

Which means we could access individual subdomains and reset their state.

State reset could be doing by doing `await agent.stop(); await agent.start();`.

I think that could work actually. Can you prototype this by returning the `globalAgent` in the dictionary and then see what happens when you do `await agent.stop();` and `await agent.start();`. Note that any port readings would have to be re-read.

Note that this preserves the state. If you must reset state, then after `agent.stop();` reach in and call the relevant domain's `destroy()`.

At this point here be dragons. You are messing with its internal consistency. Which may cause problems in the future.

Again the whole point was to reduce the amount of restarts, otherwise you just use your own agent in your own test module.

**Comment by CMCDragonkai** [comment]
Actually I just realised you can do `await agent.stop();` and then `await agent.start({fresh: true});`. Try this and see how it goes. Does it break other things?

**Comment by CMCDragonkai** [comment]
> > I'm not sure what you mean by modifying permissions of nodes/identities not in a gestalt. Not every node is supposed to be in your gestalt. Only a select few are supposed to be in Ur gestalt. Whether in or not in gestalt shouldn't have any relationship to modifying permissions.
> 
> I'll go through one of the tests to show what I mean. So right now I have a test for `identities allow` that goes as follows:
> 
> 1. Run command `identities allow [nodeId] notify`
> 2. Check for successful exit code
> 3. Run command `identities permissions [nodeId]`
> 4. Check for successful exit code and for permission "notify"
> 
> Without making any changes to the codebase, this test fails at step 2 with the error `ErrorGestaltsGraphNodeIdMissing`, which is being thrown inside `GestaltGraph.ts` inside the method `setGestaltActionByNode()`. The Gestalt Graph has it's own DB, and this method asserts that the provided nodeId is in that DB before calling any ACL commands. If the nodeId isn't in the Gestalt Graph DB the `ErrorGestaltsGraphNodeIdMissing` error is thrown.
> 
> If we remove that DB check from `setGestaltActionByNode()` the `identities allow` command is perfomed successfully, but then we get an error at step 4 coming from the subsequent `identities permissions` command where the "notify" permission is not returned. This command, which calls `getGestaltActionsByNode()` (also inside `GestaltGraph.ts`) is also searching the Gestalt Graph's DB for the provided nodeId before calling any ACL commands. Again, removing this DB check causes the command to be performed successfully, and now the entire test passes.
> 
> If I'm understanding you correctly, do these gestalt actions commands actually have no relation to the Gestalt Graph DB? And if this is the case, can the DB checks in these commands be safely removed?

Ok I understand. The gestalt graph and the gestalt are 2 different things. Yes you need the node to be in the gestalt graph first before you can add any permissions.

Therefore, the command `pk identities allow` might need to add that node ID to the gestalt automatically.

However there is no verification being done here... so one could add any string or it could be just a dummy node id.

The same is true if allowing an third party provider ID, again it can any id and one that may not yet exist.

I think based on the original workflow, you are meant to refer to an existing gestalt ID that has been discovered either by going through the DHT or the social network by searching provider identities. And this would be the case via the GUI.

However the CLI allows you to just add any ID... so the question is, is this something that can just be added to the gestalt graph at that point? Can you look up back the original workflow. I think our identities workflow wasn't entirely fleshed out and so I haven't had the time to think through these cases as I've been working on other parts of the system.

**Comment by emmacasolin** [comment]
> However the CLI allows you to just add any ID... so the question is, is this something that can just be added to the gestalt graph at that point? Can you look up back the original workflow. I think our identities workflow wasn't entirely fleshed out and so I haven't had the time to think through these cases as I've been working on other parts of the system.

I wasn't able to find much that was relevant, however I did find this comment https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/144#note_501361799. There was a small amount of discussion on verification that seemed to link back to the sigchain, since claims must be verified during the discovery process. So it looks like discovery is the main way to add nodes/identities to the gestalt graph, however there needs to be an initial node added to the gestalt graph before discovery can commence. This also expects that an identity must always be linked to a node, so identity gestalt permissions cannot be set if there are no linked nodes in the gestalt graph (i.e. just a single identity since identities cannot be linked to each other directly).

Most of this discussion is also from a very long time ago, so some things have changed since then.

**Comment by CMCDragonkai** [comment]
There are 2 kinds of discovery. One is just node DHT discovery. Another is via the identity providers. So as soon as you find identities or nodes you can add it to the gestalt graph since it's just a giant contact database. But I also thought that it would be incremental and only add entities you needed to interact with. So we don't accumulate all entities in the entire world.

**Comment by emmacasolin** [comment]
> There are 2 kinds of discovery. One is just node DHT discovery. Another is via the identity providers. So as soon as you find identities or nodes you can add it to the gestalt graph since it's just a giant contact database. But I also thought that it would be incremental and only add entities you needed to interact with. So we don't accumulate all entities in the entire world.

The discovery process implemented in `Discovery.ts` I don't think is capable of discovering the entire pk database from one node/identity - it will only discover the gestalt that the node/identity belongs to. In this case, discovery can't be used to add a node to the gestalt graph unless we have already discovered at least one of its connected nodes/identities. As such, I think that `identities allow`/`identities trust` should be calling `setNode()`/`setIdentity()` BUT only if the node/identity we want to modify the permissions of does not already exist in the gestalt graph.

**Comment by emmacasolin** [comment]
> > There are 2 kinds of discovery. One is just node DHT discovery. Another is via the identity providers. So as soon as you find identities or nodes you can add it to the gestalt graph since it's just a giant contact database. But I also thought that it would be incremental and only add entities you needed to interact with. So we don't accumulate all entities in the entire world.
> 
> The discovery process implemented in `Discovery.ts` I don't think is capable of discovering the entire pk database from one node/identity - it will only discover the gestalt that the node/identity belongs to. In this case, discovery can't be used to add a node to the gestalt graph unless we have already discovered at least one of its connected nodes/identities. As such, I think that `identities allow`/`identities trust` should be calling `setNode()`/`setIdentity()` BUT only if the node/identity we want to modify the permissions of does not already exist in the gestalt graph.

Actually, after doing some prototyping it looks like plain old discovery (`Discovery.ts`) **doesn't add nodes/identities to the gestalt graph at all**. All it does is create links between existing nodes/identities in the gestalt graph. In order to perform discovery, the nodes/identities you want to discover have to have been already manually set in your gestalt graph using `setNode()`/`setIdentity()`, which seems a little counterintuitive...

I'm not entirely sure what node DHT discovery is, but if it's specific to the nodes domain (e.g. `findNode()`) then this has no relationship to the gestalt graph, only the node graph. The node graph and gestalt graph are not linked in any way as far as I can tell.

**Comment by CMCDragonkai** [comment]
The discovery is meant to be for gestalt discovery. DHT discovery is just a nodes domain operation codified as a `find` or resolve. When doing social discovery via the discovery domain, you have to use the DHT discovery too in order to resolve NodeIds. But yea the `discovery` is for social discovery.

**Comment by CMCDragonkai** [comment]
@emmacasolin a few extra things:

1. I'm changing `setupRemoteKeynode` to just using `PolykeyAgent.createPolykeyAgent`
2. Any nested describes should be removed unless strictly necessary. The only place necessary is when we use the global agent. All other ones should be their own test modules that we are splitting up.
3. Make sure to use `beforeAll`, `afterAll`, `beforeEach`, `afterEach` together. With one, there should always be the other.
4. The `clearDB` and `clearNotifications` methods should all be changed to using create and destroy. Ideally! I know that in some cases we will need `restart` method. But I'd rather not be littering clearing methods. State creation and destruction should be carefully managed without the need for these methods. I see these being used in alot of tests, and side-effects should generally be removed by each test explicitly, not rely on these methods.

In some cases, the `dataDir` is used in the `beforeAll`, this would be different from the `dataDir` used in `beforeEach`. The `beforeAll` should be using a named data directory like `agentDataDir`, while `beforeEach` can stay with `dataDir`.

**Comment by emmacasolin** [comment]
> 4. The `clearDB` and `clearNotifications` methods should all be changed to using create and destroy. Ideally! I know that in some cases we will need `restart` method. But I'd rather not be littering clearing methods. State creation and destruction should be carefully managed without the need for these methods. I see these being used in alot of tests, and side-effects should generally be removed by each test explicitly, not rely on these methods.

I agree with this, however `clearNotifications()` is used by the cli (`notifications clear`). Is it ok for the `clearNotifications()` method to remain for that purpose or should the `notifications clear` command be using `destroy()` instead?

**Comment by emmacasolin** [comment]
Adding a node/identity to the gestalt graph during grpc calls is actually more complicated than I originally thought, since this requires the chain data as well. So the process for say `gestaltsActionsSetByIdentity` would be:

1. Determine whether the identity exists in the gestalt graph already (check if `gestaltGraph.getGestaltByIdentity()` returns undefined)
2. If the identity already exists skip to step 8, else get the provider of the identity from the identities manager (`identitiesManager.getProvider()`) - as a note, the identities manager would need to be injected into the grpc handler for `gestaltsActionsSetByIdentity` as it is not currently (and any others that require this process)
3. Get the identity data for the required identity (`provider.getIdentityData()`) - as a note, this method requires both an `authIdentityId` and an `identityId`, and I'm not entirely sure what the difference between these are. There also doesn't seem to be a method to get a single `authIdentityId`, only all of them, adding extra complexity here
4. Get the claims from the identity (`provider.getClaims()`) - as a note, this returns an async generator, so we would need to iterate through this to get all the claims on the identity. Again, this also needs both an `authIdentityId` and an `identityId`
5. Convert the list of identity claims we receive (`IdentityClaim` type) into an `IdentityClaims` object (`Record<IdentityClaimId, IdentityClaim>`)
6. Construct an `IdentityInfo` object from the identity data and identity claims
7. Finally, set the identity into the gestalt graph (`gestaltGraph.setIdentity()`)
8. Continue as normal (`gestaltGraph.setGestaltActionByIdentity()`)

**Comment by CMCDragonkai** [comment]
Yea in that case it's fine.

On 5 January 2022 8:43:45 am AEDT, emmacasolin ***@***.***> wrote:
>> 4. The `clearDB` and `clearNotifications` methods should all be changed to using create and destroy. Ideally! I know that in some cases we will need `restart` method. But I'd rather not be littering clearing methods. State creation and destruction should be carefully managed without the need for these methods. I see these being used in alot of tests, and side-effects should generally be removed by each test explicitly, not rely on these methods.
>
>I agree with this, however `clearNotifications()` is used by the cli (`notifications clear`). Is it ok for the `clearNotifications()` method to remain for that purpose or should the `notifications clear` command be using `destroy()` instead?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/MatrixAI/js-polykey/pull/311#issuecomment-1005192505
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by emmacasolin** [comment]
The main problem that I seem to be running into with `agent restart` is ordering issues. The `restart` method cannot be called while the GRPC connection is still open, since it needs to call `stop`, however if it's called after the GRPC connection is closed it is no longer awaited, causing issues later on. I've combed through the entire codebase and there are definitely no missing awaits, so that's not the problem. I'm not sure if there's another way to "force" the command to be awaited (using `status.waitFor` also doesn't work, again due to the same ordering issues).

On top of this is the issue that, even if we're able to get `agent restart` working, this will then cause the fix for registering the test provider to the agent to no longer work, because as soon as you restart the agent the test provider will no longer be registered.

**Comment by CMCDragonkai** [comment]
**It will have to done completely asynchronously similar to how `pk agent stop` is run, see the stop handler in client service. In that it answers that it can do it without holding the connection. You would then rely on `Status` to know when the restart has finished.**

As you can see doing this sort of whole system clearing of state can be problematic, which is why it's better to ensure that state is always reversed when it can be, or you have to be ware of system integrity.

**Comment by CMCDragonkai** [comment]
@emmacasolin make sure to use ticks instead of cross outs. Crossouts should be used for when a task is not being addressed for some reason.

When rebasing on `qa-testing` it will be easier if you squash down your commits as well.

**Comment by emmacasolin** [comment]
After rebasing, the `agent restart` command now appears to be working with no issues. However, now that we've solved the problem of being unable to undo side-effects that couldn't otherwise be reset, the previous fix for registering the test provider to the global agent no longer works (as soon as the global agent is restarted the test provider is no longer registered). Some sort of mocking will likely need to be used here, but it could be tricky due to needing to mock both the identities manager and the test provider in order to register it.

**Comment by CMCDragonkai** [comment]
Areas that require restarting the PolykeyAgent entirely:

1. Nodes add - no way to unadd a node
2. Sigchain operations - undoing on the sigchain is not allowed, but revoking claims is not yet available
3. Discovery - no way to undo this

**Comment by emmacasolin** [comment]
Due to the gestalts rpc handlers being incomplete and requiring a thorough review, these CLI commands will not work yet. This will likely require a later PR, and as such the relevant tests for the commands will not be split yet and the previous tests will remain for now. The tests for the grpc handlers for these commands will test the behaviour as it is now (i.e. will expect that nodes/identities need to be added to the gestalt graph manually before their permissions can be modified), and then the manual setting of nodes can be removed from these tests once the handlers are completed.

**Comment by CMCDragonkai** [comment]
> Adding a node/identity to the gestalt graph during grpc calls is actually more complicated than I originally thought, since this requires the chain data as well. So the process for say `gestaltsActionsSetByIdentity` would be:
> 
> 1. Determine whether the identity exists in the gestalt graph already (check if `gestaltGraph.getGestaltByIdentity()` returns undefined)
> 2. If the identity already exists skip to step 8, else get the provider of the identity from the identities manager (`identitiesManager.getProvider()`) - as a note, the identities manager would need to be injected into the grpc handler for `gestaltsActionsSetByIdentity` as it is not currently (and any others that require this process)
> 3. Get the identity data for the required identity (`provider.getIdentityData()`) - as a note, this method requires both an `authIdentityId` and an `identityId`, and I'm not entirely sure what the difference between these are. There also doesn't seem to be a method to get a single `authIdentityId`, only all of them, adding extra complexity here
> 4. Get the claims from the identity (`provider.getClaims()`) - as a note, this returns an async generator, so we would need to iterate through this to get all the claims on the identity. Again, this also needs both an `authIdentityId` and an `identityId`
> 5. Convert the list of identity claims we receive (`IdentityClaim` type) into an `IdentityClaims` object (`Record<IdentityClaimId, IdentityClaim>`)
> 6. Construct an `IdentityInfo` object from the identity data and identity claims
> 7. Finally, set the identity into the gestalt graph (`gestaltGraph.setIdentity()`)
> 8. Continue as normal (`gestaltGraph.setGestaltActionByIdentity()`)

I believe the `authIdentityId` is the ID of the identity that is authenticated in the provider. The `identityId` is the target identity you want info about.

Social discovery should be engaged to do this process. I reckon the discovery domain and expose this functionality and then be triggered by the user via CLI.

**Comment by CMCDragonkai** [comment]
There's a complex interaction between:

1. GestaltGraph
2. Sigchain
3. ACL
4. Nodes
5. Identities
6. Discovery

That all has to work together. Recommend going through it all in detail and coming up with a cohesive plan of the functionalities that is exported on the CLI interface.

We will work it out soon after the bits and pieces are done.

**Comment by emmacasolin** [comment]
All of the agent and gestalt GRPC tests have now been split, minus `agentRestart` (not sure what's happening with this command) and `gestaltsGestaltList` (didn't get up to that one). I used mocking for all of the `get` calls to mock a return rather than having to set any state. I also mocked the discovery methods to just do nothing and simply checked that the mocked functions were called, since discovery requires a lot of setup and has already been tested elsewhere.

I also removed the check for the agent to not be `running` in `tests/client/service/agentStop.test.ts` from before the agent has fully stopped, since this is no longer expected behaviour from changes made in https://github.com/MatrixAI/js-polykey/pull/292.

**Comment by CMCDragonkai** [comment]
Rebase please!

**Comment by CMCDragonkai** [comment]
@emmacasolin can you make sure this PR gets rid of `polykeyStartupTimeout`:

```
[nix-shell:~/Projects/js-polykey/tests]$ ag 'polykeyStartupTimeout'global.d.ts
10:declare var polykeyStartupTimeout: number;

bin/identities/identities.test.ts
131:  }, global.polykeyStartupTimeout * 2);
721:    }, global.polykeyStartupTimeout * 2);

bin/nodes/ping.test.ts
80:  }, global.polykeyStartupTimeout * 3);

bin/nodes/claim.test.ts
85:  }, global.polykeyStartupTimeout * 2);
115:    global.polykeyStartupTimeout * 4,

bin/nodes/add.test.ts
56:  }, global.polykeyStartupTimeout * 3);

bin/keys/keys.test.ts
38:  }, global.polykeyStartupTimeout * 2);
166:      global.polykeyStartupTimeout * 4,
195:      global.polykeyStartupTimeout * 4,
219:      global.polykeyStartupTimeout * 4,

bin/secrets/secrets.test.ts
41:  }, global.polykeyStartupTimeout);

bin/vaults/vaults.test.ts
94:  }, global.polykeyStartupTimeout);

bin/nodes/find.test.ts
93:  }, global.polykeyStartupTimeout * 3);

bin/notifications/notifications.test.ts
88:  }, global.polykeyStartupTimeout * 2);

client/rpcNotifications.test.ts
84:  }, global.polykeyStartupTimeout);
147:    }, global.polykeyStartupTimeout * 2);

client/rpcIdentities.test.ts
88:  }, global.polykeyStartupTimeout);

client/rpcSessions.test.ts
69:  }, global.polykeyStartupTimeout);

client/rpcGestalts.test.ts
126:  }, global.polykeyStartupTimeout);

client/rpcKeys.test.ts
75:  }, global.polykeyStartupTimeout);

client/rpcNodes.test.ts
126:  }, global.polykeyStartupTimeout);

client/rpcVaults.test.ts
86:  }, global.polykeyStartupTimeout);

discovery/Discovery.test.ts
79:      global.polykeyStartupTimeout,
160:    }, global.polykeyStartupTimeout * 3);
295:    }, global.polykeyStartupTimeout * 4);

agent/GRPCClientAgent.test.ts
162:  }, global.polykeyStartupTimeout);

grpc/utils.test.ts
19:  }, global.polykeyStartupTimeout);

nodes/NodeManager.test.ts
165:    }, global.polykeyStartupTimeout);
359:    global.polykeyStartupTimeout,
467:    }, global.polykeyStartupTimeout * 2);

nodes/NodeConnection.test.ts
246:  }, global.polykeyStartupTimeout * 2);

vaults/VaultManager.test.ts
777:    }, global.polykeyStartupTimeout * 2);

notifications/NotificationsManager.test.ts
213:  }, global.polykeyStartupTimeout * 2);
269:  }, global.polykeyStartupTimeout * 2);
```

It should all be replaced with `defaultTimeout`, and the usage of either the global keypair or the global agent. In some cases, you shouldn't even add it in. I only use `globalThis.defaultTimeout * 2` for when PolykeyAgent is being spawn raw without global keypair mocking. And remember this is only for when the test function itself does it. If using global agent, no timeout configuration should be necessary. Your test should complete within 5 seconds. When you're working on this make sure to mark out the changes too for me to review.

Once done, remove the variable from `jest.config.js`.

**Comment by CMCDragonkai** [comment]
In your client service tests, when dealing with `authenticate`, just create a mocked function for it.

For example in `network/index.test.ts` see:

```ts
   const authenticate = async (_metaClient, metaServer = new grpc.Metadata()) =>
      metaServer;
```

Note that this doesn't use `jest.fn` at all, because I'm not interested in the calls or parameters. But if you're testing that, then use `jest.fn` as well.

**Comment by CMCDragonkai** [comment]
For mocking async generators, use `mockReturnValue` or `mockImplementation`.

Note that this can be applied to either `jest.fn` or `jest.spyOn`.

**Comment by CMCDragonkai** [comment]
Beware that these test areas should not be worked on until MatrixAI/Polykey#266 is merged. https://github.com/MatrixAI/js-polykey/pull/266#issuecomment-1008817579

**Comment by emmacasolin** [comment]
> In your client service tests, when dealing with `authenticate`, just create a mocked function for it.
> 
> For example in `network/index.test.ts` see:
> 
> ```ts
>    const authenticate = async (_metaClient, metaServer = new grpc.Metadata()) =>
>       metaServer;
> ```
> 
> Note that this doesn't use `jest.fn` at all, because I'm not interested in the calls or parameters. But if you're testing that, then use `jest.fn` as well.

Assuming `authenticate` is being tested elsewhere, is there a need to test that each grpc handler works with both the password and token and that they fail if no authentication is provided/authentication is invalid? For example, the three tests in `agentStop.test.ts` for "stops the agent with password", "stops the agent with token", and "cannot stop the agent if not authenticated" could be reduced to just "stops the agent" with mocked authentication.

**Comment by emmacasolin** [comment]
I'm not sure what the best way to go about writing tests for the handlers for `keysKeyPairRenew` and `keysKeyPairReset` is. Since these calls change the root keypair, if I were to test their functionality fully then this would mean that I wouldn't be able to use the global keypair. The alternative is to use mocking, however these handlers are fairly complex and call multiple functions from different domains, so I'm not sure if mocking everything in the tests is a good idea. The existing tests for these functions in `rpcKeys.test.ts` create a full agent and run the tests against this, which goes against the approach of trying to use mocking as much as possible for the grpc tests.

**Comment by emmacasolin** [comment]
All of the client service tests (expect for the vaults ones, which need to wait until MatrixAI/Polykey#266 is merged) have now been split into separate files and are passing. The total time for the entire `tests/client/service/*` folder to run is around 70 seconds! I used quite a lot of mocking for these tests, however if time is permitting at some point I could probably go in and add more mocking to some of the tests to further improve coverage + speed. I'll move on to splitting the rest of the bin tests for now though.

**Comment by CMCDragonkai** [comment]
> I'm not sure what the best way to go about writing tests for the handlers for `keysKeyPairRenew` and `keysKeyPairReset` is. Since these calls change the root keypair, if I were to test their functionality fully then this would mean that I wouldn't be able to use the global keypair. The alternative is to use mocking, however these handlers are fairly complex and call multiple functions from different domains, so I'm not sure if mocking everything in the tests is a good idea. The existing tests for these functions in `rpcKeys.test.ts` create a full agent and run the tests against this, which goes against the approach of trying to use mocking as much as possible for the grpc tests.

In this case just don't use the global keypair. Well you can use it at the beginning, then afterwards change the keypair and test for the effects of the change. Make sure to give enough time for the change to take place and for the key size to be 2048 if sigchain is involved or 1024 otherwise.

**Comment by emmacasolin** [comment]
> In this case just don't use the global keypair. Well you can use it at the beginning, then afterwards change the keypair and test for the effects of the change. Make sure to give enough time for the change to take place and for the key size to be 2048 if sigchain is involved or 1024 otherwise.

For those tests I ended up just mocking everything that gets called in those handlers and replacing them with empty functions. I then just checked to see that all of the mocks were called. So whether or not the keypair actually gets changed isn't being tested here and this is assumed to be tested in the higher level tests (i.e. `tests/bin/keys/renew.test.ts` and `tests/bin/keys/reset.test.ts`). The client service tests for the most part are just checking that the methods that should be called are called, and that they're called with the expected parameters, and that any data that's returned is parsed correctly. Is that approach ok?

**Comment by emmacasolin** [comment]
I've noticed that the secrets bin commands are a bit buggy (the tests weren't very complete so it looks like things were missed, e.g. `secrets get` doesn't seem to actually be able to retrieve a secret). Due to this I'll leave those tests until after MatrixAI/Polykey#266 is merged as well. With so many tests out of the picture I'll most likely be able to get everything else for this PR done by Monday.

**Comment by CMCDragonkai** [comment]
> > In this case just don't use the global keypair. Well you can use it at the beginning, then afterwards change the keypair and test for the effects of the change. Make sure to give enough time for the change to take place and for the key size to be 2048 if sigchain is involved or 1024 otherwise.
> 
> For those tests I ended up just mocking everything that gets called in those handlers and replacing them with empty functions. I then just checked to see that all of the mocks were called. So whether or not the keypair actually gets changed isn't being tested here and this is assumed to be tested in the higher level tests (i.e. `tests/bin/keys/renew.test.ts` and `tests/bin/keys/reset.test.ts`). The client service tests for the most part are just checking that the methods that should be called are called, and that they're called with the expected parameters, and that any data that's returned is parsed correctly. Is that approach ok?

I think in this case it's better to test the real side effects of key change. The client service may be interacted by things outside of the bin CLI so it's worth it to ensure the client service does it. Plus this key change has alot of effects, it's a good idea to test this for real. Especially once we figure out the best event structure for propagating key change.

**Comment by CMCDragonkai** [comment]
> I've noticed that the secrets bin commands are a bit buggy (the tests weren't very complete so it looks like things were missed, e.g. `secrets get` doesn't seem to actually be able to retrieve a secret). Due to this I'll leave those tests until after MatrixAI/Polykey#266 is merged as well. With so many tests out of the picture I'll most likely be able to get everything else for this PR done by Monday.

Can you have a look into these commands anyway and understand why they are buggy. The MatrixAI/Polykey#266 isn't dealing with secret commands particularly but may help after merging.

**Comment by emmacasolin** [comment]
I've been stuck on the `nodes find` bin test for while now with the "fails to find an unknown node" test never completing (I tried setting the relevant timeouts to 1 second, as well as using jest's timer mocks, both with no success). I just ran the original version before I made changes to it to see if it had the same problem and it did. Not sure where this bug came from (this test wasn't one of the ones that was failing after https://github.com/MatrixAI/js-polykey/pull/296 was merged), and I'm also having difficulty working out where exactly it's getting stuck and timing out. Will come back to this later.

Edit: `nodes ping` has the same problem, however I think there may be an async issue somewhere since the failures occasionally appear to leak into other tests

**Comment by tegefaulkes** [comment]
Node tests are getting checked and updated in MatrixAI/Polykey#310, so I think don't worry if it's failing or not for now.

**Comment by emmacasolin** [comment]
`keysKeyPairRenew` and `keysKeyPairReset` are no longer mocking the calls, but still use mocking to spy on the outcome of these calls. On their own they each take just under 30 seconds, however when run with the rest of the client service tests they can take up to a minute each. Since I wasn't sure how they would go in the CI/CD I set their timeouts to `global.defaultTimeout * 3`, but I'll see if that can be lowered.

**Comment by emmacasolin** [comment]
> Can you have a look into these commands anyway and understand why they are buggy. The MatrixAI/Polykey#266 isn't dealing with secret commands particularly but may help after merging.

Yeah I can do that, although the issues are coming from the handlers, which have been changed by MatrixAI/Polykey#266, so the problems might have already been fixed

**Comment by emmacasolin** [comment]
I've broken up the squashed WIP commit into several separate commits. Some of them could potentially be cherry-picked into master, for example https://github.com/MatrixAI/js-polykey/pull/311/commits/829e5479fcfab15bc30ebac83bb7b0861b4b5629 which is just splitting the sessions client service tests. I would hold off on anything involving keypair renewal/resetting and the gestalt graph until changes in those domains have been figured out though.

**Comment by CMCDragonkai** [comment]
Fleshed out details regarding this new `Observer` class: https://github.com/MatrixAI/js-polykey/issues/312#issuecomment-1012793375. It can used for general loosely coupled "push-based" communication across PK. I'm also thinking that it can be extended to 2 kinds of event emission, one being `observers.emit()` which behaves similar to event emitters, and another being `await observers.notify()/observers.update()` which is a promise-aware form of emission that waits for the updates to be resolved.

The method names are not concrete though.

**Comment by CMCDragonkai** [comment]
> I've broken up the squashed WIP commit into several separate commits. Some of them could potentially be cherry-picked into master, for example [829e547](https://github.com/MatrixAI/js-polykey/commit/829e5479fcfab15bc30ebac83bb7b0861b4b5629) which is just splitting the sessions client service tests. I would hold off on anything involving keypair renewal/resetting and the gestalt graph until changes in those domains have been figured out though.

Are these in-order of how you'd like them merged/cherry-picked?

**Comment by emmacasolin** [comment]
The commits aren’t, no - they’re closer to the order I worked on things. Most of the client tests are probably ok to merge, as are the bin identities tests that don’t involve the Gestalt Graph. Everything else is likely to change or be removed entirely.
________________________________

**Comment by CMCDragonkai** [comment]
Ok, but they will need to be re-ordered in cherry-picking order, otherwise rebase may not work to eliminate those commits.

**Comment by CMCDragonkai** [comment]
@emmacasolin I've prototyped an `EventBus`, can you integrate it into PK and replace your current observer pattern with it: https://github.com/MatrixAI/js-polykey/issues/312#issuecomment-1013833504.

You'll need to create an `src/events` subdirectory, and add a class `EventBus.ts`. This can then be imported by `PolykeyAgent.ts` and bootstrapped and injected into the relevant domains like `KeyManager`. Which can then perform `emitAsync()` instead of `emit()` which updating the topic about a key change.

I suggest that the event value/args should be kept simple, with just a record type inside `keys/types.ts` to represent the packet of data.

You'll need to create a topic string for this event. It turns out event systems can use symbols now. So you could use a symbol instead of an event string which will be more type-safe and prevent name clashes. The symbol description could be "rootKeyPairChange". Such symbols should be defined into `src/keys/utils.ts`.

This kind of change should be in a separate commit, if you're able to separate this change from the test splitting?

**Comment by emmacasolin** [comment]
> @emmacasolin I've prototyped an `EventBus`, can you integrate it into PK and replace your current observer pattern with it: [#312 (comment)](https://github.com/MatrixAI/js-polykey/issues/312#issuecomment-1013833504).
> 
> You'll need to create an `src/events` subdirectory, and add a class `EventBus.ts`. This can then be imported by `PolykeyAgent.ts` and bootstrapped and injected into the relevant domains like `KeyManager`. Which can then perform `emitAsync()` instead of `emit()` which updating the topic about a key change.
> 
> I suggest that the event value/args should be kept simple, with just a record type inside `keys/types.ts` to represent the packet of data.
> 
> You'll need to create a topic string for this event. It turns out event systems can use symbols now. So you could use a symbol instead of an event string which will be more type-safe and prevent name clashes. The symbol description could be "rootKeyPairChange". Such symbols should be defined into `src/keys/utils.ts`.
> 
> This kind of change should be in a separate commit, if you're able to separate this change from the test splitting?

All of the observer pattern changes I made have been separated into their own commit, so I should be able to group these changes in with that commit. I'll work on integrating the Event Bus today.

**Comment by emmacasolin** [comment]
I've incorporated the `EventBus` from https://github.com/MatrixAI/js-polykey/issues/312 into the codebase, as well as set it up for propagating root key pair changes from within the `PolykeyAgent`. I also wrote some tests for the `EventBus` class inside `tests/events/EventBus.test.ts` that I think should cover the majority of cases, but some more tests for the error handling mechanism may be needed.

**Comment by CMCDragonkai** [comment]
Note that because when we cherry picked the first test split wasn't lintfixed. It might be a good idea to ensure that your first commit, or at least early on that the lintfixing is applied to those specific spots.

File: src/client/service/identitiesClaim.ts [hunk 1]
```diff
@@ -53,7 +53,7 @@ function identitiesClaim({
       const claimData = await provider.publishClaim(identityId, claimDecoded);
       response.setClaimId(claimData.id);
       if (claimData.url) {
-        response.setUrl(claimData.url)
+        response.setUrl(claimData.url);
```
Comment (CMCDragonkai) [inline src/client/service/identitiesClaim.ts]: Was all that was needed to be linted for master?

File: src/client/service/keysKeyPairRenew.ts [hunk 2]
```diff
@@ -30,22 +18,9 @@ function keysKeyPairRenew({
...
-        };
-        fwdProxy.setTLSConfig(tlsConfig);
-        revProxy.setTLSConfig(tlsConfig);
-        grpcServerClient.setTLSConfig(tlsConfig);
-        // Finally, refresh the node buckets
-        await nodeManager.refreshBuckets();
-      });
+      const metadata = await authenticate(call.metadata);
+      call.sendMetadata(metadata);
+      await keyManager.renewRootKeyPair(call.request.getName());
```
Comment (CMCDragonkai) [inline src/client/service/keysKeyPairRenew.ts]: Please add a comment here indicating that other domains are expected to change the `EventBus`.

**Comment by emmacasolin** [comment]
Everything up to and including acb3b61e56bcacee2cf6b3e2d9b6a424358341dd is working and lintfixed, so should be okay to be cherry-picked into master. Everything else I think should wait until vaults/nodes/gestalts changes have been merged.

File: src/client/service/identitiesClaim.ts (hunk 1 above)
Comment (emmacasolin) [reply src/client/service/identitiesClaim.ts]: Yeah that was it

File: src/events/index.ts [hunk 3]
```diff
@@ -0,0 +1,2 @@
+export { default as EventBus } from './EventBus';
+export { captureRejectionSymbol } from 'events';
```
Comment (CMCDragonkai) [inline src/events/index.ts]: This should be ahead of the above export. Always export native packages first.

Comment (emmacasolin) [reply src/events/index.ts]: Fixed

File: src/client/service/keysKeyPairRenew.ts (hunk 2 above)
Comment (emmacasolin) [reply src/client/service/keysKeyPairRenew.ts]: Done for reset as well

File: src/PolykeyAgent.ts [hunk 4]
```diff
@@ -455,6 +471,26 @@ class PolykeyAgent {
   }) {
     try {
       this.logger.info(`Starting ${this.constructor.name}`);
+      // Set up error handling for event handlers
+      this.events[captureRejectionSymbol] = (err, event, ...args) => {
+        this.logger.error(
```
Comment (CMCDragonkai) [inline src/PolykeyAgent.ts]: Have a look at `src/bin/utils/utils.ts` `outputFormatter`:

```
    output += `${msg.name}: ${msg.description}`;
    if (msg.message) {
      output += ` - ${msg.message}`;
    }
    output += '\n';
```

This would produce a message like:

```
ErrorName: Description - Message
```

Now of course since we are in the event bus system, we can add additional context:

```
EventBus error for <event>: <errorname>: <errordescription> - <errormessage>
```

Note that `errordescription` can be swapped for the `errormessage` if it doesn't exist. Because not all errors are Polykey errors. You just have to do an `if` condition like:

```
if (err.description != null) {
  // add description in and message in
  msg += `${err.name}: ${err.description}`
  if (err.message != '') {
    msg += ` - ${err.message}`;
  }
} else {
  // add message in
  msg += `${err.name}`
  if (err.message != '') {
    msg += `: ${err.message}`;
  }
}
```

Maybe there's even slimmer way with just ternary conditions.

Anyway we will be refactoring how errors/log messages are reported in the future in #304, but this is good enough solution for now.

File: src/PolykeyAgent.ts [hunk 5]
```diff
@@ -562,6 +598,7 @@ class PolykeyAgent {
       await this.keyManager?.stop();
       await this.schema?.stop();
       await this.status?.stop({});
+      this.events.removeAllListeners(keysUtils.eventRootKeyPairChange);
```
Comment (CMCDragonkai) [inline src/PolykeyAgent.ts]: Is this in the right order? Order of shutdown should be opposite of order of startup.

So if A, then B, then C, then shutdown is C, then B, then A.

File: src/bootstrap/utils.ts [hunk 6]
```diff
@@ -92,6 +97,9 @@ async function bootstrapState({
       keysPath,
       password,
       fs,
+      rootKeyPairChange: async (keyPairData: RootKeyPairChangeData) => {
```
Comment (CMCDragonkai) [inline src/bootstrap/utils.ts]: This is not necessary in the `bootstrapState` function. The agent isn't actually running during this point.

The `rootKeyPairChange` callback should be optional so it doesn't need to be passed in here.

File: tests/vaults/VaultManager.test.ts [hunk 7]
```diff
@@ -91,6 +91,7 @@ describe('VaultManager', () => {
     keyManager = await KeyManager.createKeyManager({
       password,
       keysPath: keysPath,
+      rootKeyPairChange: async () => {},
```
Comment (CMCDragonkai) [inline tests/vaults/VaultManager.test.ts]: This callback should be optional, so if you don't pass it in, it's by default set to a noop function if you don't want to check `undefined`.

**Review by CMCDragonkai — CHANGES_REQUESTED** [review]

**Comment by CMCDragonkai** [comment]
The rebasing effort each time is a bit of an anti-pattern. Ideally the event bus should have been a separate PR.

File: src/keys/KeyManager.ts [hunk 8]
```diff
@@ -67,6 +71,7 @@ class KeyManager {
   }: {
     keysPath: string;
     password: string;
+    rootKeyPairChange: RootKeyPairChange;
```
Comment (CMCDragonkai) [inline src/keys/KeyManager.ts]: Needs to be optional.

File: src/keys/KeyManager.ts [hunk 9]
```diff
@@ -56,6 +59,7 @@ class KeyManager {
   static async createKeyManager({
     keysPath,
     password,
+    rootKeyPairChange,
```
Comment (CMCDragonkai) [inline src/keys/KeyManager.ts]: An async noop function could be used instead of `undefined`.

File: tests/vaults/VaultManager.test.ts (hunk 7 above)
Comment (CMCDragonkai) [reply tests/vaults/VaultManager.test.ts]: This comment applies to all the other tests where `rootKeyPairChange` is being passed a noop function.

File: src/PolykeyAgent.ts (hunk 4 above)
Comment (emmacasolin) [reply src/PolykeyAgent.ts]: So use this for now?

```
if (err.description != null) {
  // add description in and message in
  msg += `${err.name}: ${err.description}`
  if (err.message != '') {
    msg += ` - ${err.message}`;
  }
} else {
  // add message in
  msg += `${err.name}`
  if (err.message != '') {
    msg += `: ${err.message}`;
  }
}
```

Comment (CMCDragonkai) [reply src/PolykeyAgent.ts]: **Oh yea and I forgot to mention, do not show the arguments of the events. This can leak sensitive information to the logs, so we don't do this.**

File: src/PolykeyAgent.ts (hunk 5 above)
Comment (emmacasolin) [reply src/PolykeyAgent.ts]: Yeah the handlers are registered right at the top

File: src/PolykeyAgent.ts (hunk 4 above)
Comment (CMCDragonkai) [reply src/PolykeyAgent.ts]: Not just that, also make sure that `EventBus ${event}: ` is also there.

Comment (CMCDragonkai) [reply src/PolykeyAgent.ts]: Try with ternary conditions:

```
const s = `${(true) ? 'abc': 'what'}`;
```

File: src/PolykeyAgent.ts (hunk 5 above)
Comment (CMCDragonkai) [reply src/PolykeyAgent.ts]: I have a feeling that event handlers should be done after all the domains are constructed. So they should be the first to be deregistered.

Comment (CMCDragonkai) [reply src/PolykeyAgent.ts]: And therefore you can refer to the objects, not using `this`, but just by referring to the objects in the function closure. Like instead of `this.fwdProxy.setTLSConfig`, you just do `fwdProxy.setTLSConfig`.

Comment (emmacasolin) [reply src/PolykeyAgent.ts]: They're being registered in `start`, so all of the domains are already constructed. Since `start` doesn't have access to the objects the only way to do it without the `this` would be to move the registering into `createPolykeyAgent`, in which case deregistering would go into `destroy` instead of `stop`.

File: src/bootstrap/utils.ts (hunk 6 above)
Comment (emmacasolin) [reply src/bootstrap/utils.ts]: Fixed everywhere

File: src/PolykeyAgent.ts (hunk 5 above)
Comment (CMCDragonkai) [reply src/PolykeyAgent.ts]: Ah yes, I forgot about that. Ok this is fine then.

File: src/PolykeyAgent.ts (hunk 4 above)
Comment (emmacasolin) [reply src/PolykeyAgent.ts]: Not sure if this is any clearer but this is that same logic using ternary conditions:
```ts
let output = `EventBus error for ${event}: ${err.name}`;
output +=
  err.description !== null
    ? `: ${err.description}` +
      (err.message !== '' ? ` - ${err.message}` : '')
    : err.message !== ''
    ? `: ${err.message}`
    : '';
```

Comment (CMCDragonkai) [reply src/PolykeyAgent.ts]: One can use the `if` condition at the top and ternary only when I was adding data on.

Actually I just realised we can follow what `src/polykey.ts` does.

```ts
const msg = `${this.constructor.name} error for ${event}`;
if (err instanceof ErrorPolykey) {
  msg += `: ${err.name}: ${err.description}`;
  if (err.message != '') {
    msg += ` - ${err.message}`;
  }
} else {
  msg += `: ${err.name}`;
  if (err.message != '') {
    msg += `: ${err.message}`;
  }
}
this.logger.error(msg);
```

Just use the above.

Comment (emmacasolin) [reply src/PolykeyAgent.ts]: Done

**Comment by emmacasolin** [comment]
With "Replace all use of clearXXX() with destroy methods in tests", since `stop` must be called before `destroy`, and since `start` can't be called after `destroy`, we end up needing to re-create the whole domain any time we want to clear the db if we use `destroy`... is this really better than just using the `clearXXX()` methods? Even just stopping and re-starting with the `fresh` parameter would be simpler

**Comment by CMCDragonkai** [comment]
> With "Replace all use of clearXXX() with destroy methods in tests", since `stop` must be called before `destroy`, and since `start` can't be called after `destroy`, we end up needing to re-create the whole domain any time we want to clear the db if we use `destroy`... is this really better than just using the `clearXXX()` methods? Even just stopping and re-starting with the `fresh` parameter would be simpler

Some domains have appropriate state clearing functions. This is what I mean by reversing side-effects. Like if you create 10 items, there should be a way to delete 10 items.

In the cases where this is not applicable, like in sigchain, then instead we want to model this as destruction of sigchain and recreating it. There shouldn't be a method like `clearSigchain`. And in those cases, you could do `stop` then `start` with `fresh`.

It's really a modelling question, plus state/resource management is already quite complex, so it's the sort of thing where you want to limit the amount of ways people can do things, so that way things are just clearer for modelling and bug fixing later when we have limited surface area to work with.

File: src/status/Status.ts [hunk 10]
```diff
@@ -195,6 +196,16 @@ class Status {
     }
   }
 
+  @ready(new statusErrors.ErrorStatusNotRunning())
+  public async updateNodeId(newNodeId: NodeId): Promise<void> {
```
Comment (CMCDragonkai) [inline src/status/Status.ts]: I don't think we should have a separate method just to do this. It's better to expect that the our event handler just runs `this.writeStatus` directly. And yes, they will need to call `readStatus` beforehand to do so. So this logic should be put into your event handler.

Patching status is complicated by the fact that the SoT is on disk, and we don't have a type-safe way of representing it yet. So we can leave any development of `patchStatus` later.

File: src/keys/types.ts [hunk 11]
```diff
@@ -24,6 +26,12 @@ type CertificatePem = string;
 type CertificatePemChain = string;
 type RecoveryCode = Opaque<'RecoveryCode', string>;
 
+type RootKeyPairChangeData = {
+  nodeId: NodeId;
+  tlsConfig: TLSConfig;
+};
+type RootKeyPairChange = (keyPairData: RootKeyPairChangeData) => Promise<void>;
```
Comment (CMCDragonkai) [inline src/keys/types.ts]: This should have a extra newline in between.

File: src/keys/KeyManager.ts [hunk 12]
```diff
@@ -442,6 +451,15 @@ class KeyManager {
...
     this.rootCert = rootCert;
+    // Update topic about key change
+    const data: RootKeyPairChangeData = {
+      nodeId: this.getNodeId(),
+      tlsConfig: {
+        keyPrivatePem: this.getRootKeyPairPem().privateKey,
+        certChainPem: await this.getRootCertChainPem(),
+      },
+    };
+    await this.rootKeyPairChange(data);
```
Comment (CMCDragonkai) [inline src/keys/KeyManager.ts]: Compared to `resetRootKeyPair`, there should be an expectation that the old expected NodeID or client certificate still works...

Do you have tests included that demonstrate that GRPC clients that are still using the old certificate can still contact the the Polykey agent?

Note that this is supposed to work for agent to agent communication, but also CLI or GUI to agent communication.

The CLI is less of a problem simply because it reads the status each time, and adds the new Node ID to each call.

See the `verifyServerCertificateChain` and `verifyClientCertificateChain` methods in `src/network/utils.ts`.

This may be better done in a later PR to fix this though so we can merge this earlier, since it may be more complicated.

Comment (CMCDragonkai) [reply src/keys/KeyManager.ts]: This was mentioned here https://github.com/MatrixAI/js-polykey/issues/312#issuecomment-1014188218 but wasn't fleshed out, will write more details in #312.

Comment (CMCDragonkai) [reply src/keys/KeyManager.ts]: Wrote it up here: https://github.com/MatrixAI/js-polykey/issues/312#issuecomment-1016137891

File: src/status/Status.ts (hunk 10 above)
Comment (CMCDragonkai) [reply src/status/Status.ts]: The `writeStatus` is currently `protected`, this allows for it work during `start` and `stop`.

So `writeStatus` is not able to be called outside.

Given that patching status only applies when the status is `LIVE`, I think this may mean we can have a function that only patches LIVE statuses.

Also we cannot do 1 read and 1 write. It has to be done within the same lock. So I'll have a new function that's called `updateStatusLive` that can only be used when status is `LIVE`.

Comment (CMCDragonkai) [reply src/status/Status.ts]: I've created an `updateStatusLive` that embeds the logic of `readStatus` and `writeStatus` together and ensures that the whole work is done within a single lock.

Comment (CMCDragonkai) [reply src/status/Status.ts]: A new test called `updating live status` was added in as well to test this function.

Comment (CMCDragonkai) [reply src/status/Status.ts]: Done and squashed into the second commit.

File: src/keys/types.ts (hunk 11 above)
Comment (CMCDragonkai) [reply src/keys/types.ts]: Done and squashed into the second commit.

File: src/keys/KeyManager.ts (hunk 12 above)
Comment (CMCDragonkai) [reply src/keys/KeyManager.ts]: This will need be a new issue @emmacasolin, can't solve in this PR.

**Comment by CMCDragonkai** [comment]
I've merged in until `e09c4d91d45a4e34166edd40bb77ebdac44e75e1`. "Split `tests/client/rpcSessions.test.ts`".

**Comment by CMCDragonkai** [comment]
What about the rest of the commits? What are blocking them?

**Comment by emmacasolin** [comment]
> What about the rest of the commits? What are blocking them?

Most of them still need linting, some are still WIPs. I've realised a couple of failing tests have already slipped into master so I'll need to fix those as well. I don't think this cherry-picking approach is the best since it's so easy to miss things

**Comment by emmacasolin** [comment]
- 587e823381fb0f892d4041b3cec1f94c58b1a1c4 is a fix for failing tests on master and should be fine to cherry-pick
- 71acbff4895299404d21db1f842f09356b24b192 addresses https://github.com/MatrixAI/js-polykey/issues/306 and shouldn't cause any issues if cherry-picked
- 705578effd26fc7d801caf51b78d1ffd0fa46a89 and cd999e5d16a9f027768e003f8197e5f5708a6d8a are lintfixed and passing and should be fine to cherry-pick
- a10a42017d9106504a03cd518b7ae544b5f92d5a is also lintfixed and passing but only splits 3/11 of the identities bin tests (rest are blocked by gestalts)
- 8663d4b63bebcefb343e23948abe3ab535461a4d again, lintfixed and passing but only splits 2 of the agent service tests (rest are blocked by nodes and vaults)
- 7867f5693f13b4baf7112fb4d717e4b1c3638756 is the implementation of the `agent restart` command, but has no tests since I'm not sure if this feature is still needed
- c6747fb90e5371b77913d2d59054742f88d06479 is lintfixed and passing but is very likely to change after gestalts work
- 6a730bc309a7963b7587a5382d27c659b712b36d and 4b0b164b9d1a8607a173b9b0290537dc3054481c are WIPs blocked by gestalts
- 4c087a76caa3b24e0679abae3c1666e759068e61 blocked by nodes
- d70bb4ed9eb54292054be1f6ae5373e66180c25f may cause conflicts since timeouts are being fixed in other PRs as well and many of the affected tests might be changed by vaults/nodes

File: src/keys/KeyManager.ts (hunk 12 above)
Comment (emmacasolin) [reply src/keys/KeyManager.ts]: Created here https://github.com/MatrixAI/js-polykey/issues/317

**Comment by CMCDragonkai** [comment]
> > What about the rest of the commits? What are blocking them?
> 
> Most of them still need linting, some are still WIPs. I've realised a couple of failing tests have already slipped into master so I'll need to fix those as well. I don't think this cherry-picking approach is the best since it's so easy to miss things

Yea I just wanted to get this PR ready to be rebased on top of MatrixAI/Polykey#266 so it can starr working on vault testing.

Some commits can also be cherrypicked into their own branch which can then have tests/lintfixing applied.

Maybe we can do this from now? Instead of cherrypicking directly into master, create another branch for those things like eventbus.

**Comment by CMCDragonkai** [comment]
I've merged up to "Split `tests/client/rpcNotifications.test.ts`". And rebased this MR.

**Comment by CMCDragonkai** [comment]
I think all cherry-picking is done, so any further test splitting should be done when rebased on top of MatrixAI/Polykey#266 or MatrixAI/Polykey#310 depending on which one is ready to merge first.

In the mean time, there are downstream issues that be can be worked on:

* MatrixAI/Polykey#317 - node connection testing like this can be started on grpc first, but then needs to wait for changes coming from MatrixAI/Polykey#310 because there are changes to node connection and connection state tracking in the grpc client
* MatrixAI/Polykey#316 - which came out of this PR's work because you found out that the identities & gestalts work requires more work. You will need to break down the review and come up with smaller issues that have more targeted fixes

It seems that MatrixAI/Polykey#316 is a good place to continue, and you can re-order test splitting here to focus on that, but have a separate PR to come up with proper changes that need to be done for MatrixAI/Polykey#316.

**Comment by CMCDragonkai** [comment]
There are some tests that are related to each other in a multi-step process. For example putting something and then getting it.

These tests in the client service or agent service, should be merged together to test the multistep process.

For example `tests/client/service/keysEncrypt.test.ts` and `tests/client/service/keysDecrypt.test.ts`, can be merged together to `tests/client/service/keysEncryptDecrypt.test.ts` to test encrypting something then decrypting it.

There are other places where this can be done too.

For the CLI tests, because we are using the full agent there. Each test module has access to all the calls, so for example a put test can still call get. This is fine, as we can still have a get test, but they are just biased towards calling and checking the behaviour of get or put. The put test can check for validation behaviour of `get`.

**Comment by CMCDragonkai** [comment]
Once MatrixAI/Polykey#318 is merged and MatrixAI/Polykey#310 rebases on top of that. When @tegefaulkes says that it is ready for review, I think this PR can be rebased on top of MatrixAI/Polykey#310, and you can continue with test splitting relating to nodes.

@emmacasolin says that there are still tests that are failing due to node connection timeout issues. So once @tegefaulkes has those fixed up, you can continue splitting tests here.

**Comment by emmacasolin** [comment]
Rebased on MatrixAI/Polykey#310 - mostly minor changes to the use of node ids in tests. The NotificationsManager seems to have changed significantly though (mostly in the way notifications are sent) so `NotificationsManager.test.ts` has many errors now. It looks like sending is now done using NodeConnectionManager rather than NodeManager, however, `this.nodeConnectionManager` is never set in `NotificationsManager` so I assume this is still being worked on?

Will wait to properly fix up these tests until after NotificationsManager is working.

**Comment by tegefaulkes** [comment]
I'll have a look and fix that.

Just as a note, before the NotificationManager to get the connection and then call `sendNotification`.  two things have changed relating to that. 
1. You interact with the `NodeConnection` through the `NodeConnectionManager` by using `withConnection`
2. Methods in `NodeConnection` such as `SendNotification` has been moved out of the `NodeManager` and re-implemented in the relevant domain using `withConnection`. In this case the functionality was move into `sendNotifcation` in `NotificationManager`.

**Comment by CMCDragonkai** [comment]
Did we discuss the separation of responsibilities between the service tests and the `GRPCClientClient.test.ts` and `GRPCClientAgent.test.ts`?

I think that once we have all the tests separated for the service handlers. The tests for `GRPCClientClient.test.ts` and `GRPCClientAgent.test.ts` should focus solely on connection duties. Which would be based on the work done in MatrixAI/Polykey#310.

Our service handler tests should however use the actual method call in the `GRPCClientClient` and `GRPCClientAgent`, that way we still have coverage over those methods that are using `grpcUtils` promisify/async generator wrappers.

**Comment by emmacasolin** [comment]
Yes, that was discussed at some point. I've already moved the nodes claims test out of `GRPCClientAgent.test.ts` and into its own file so it's mostly just vaults ones left now (which I'll do the same for once MatrixAI/Polykey#266 is merged). A note again that there are still missing tests for a lot of the nodes agent client tests, so there's nothing for me to 'split'. Maybe something to be addressed in MatrixAI/Polykey#310?

**Comment by CMCDragonkai** [comment]
Does MatrixAI/Polykey#310 have any additional tests for the `GRPCClientAgent` @tegefaulkes ?

**Comment by CMCDragonkai** [comment]
@emmacasolin please squash down the recent WIP commits, and then rebase on master.

You'll need to address tests in:

- `tests/notifications`
- `tests/bin/identities`

Due to the left over test failures from https://github.com/MatrixAI/js-polykey/pull/321#issuecomment-1031071710

**Comment by emmacasolin** [comment]
> @emmacasolin please squash down the recent WIP commits, and then rebase on master.
> 
> You'll need to address tests in:
> 
> * `tests/notifications`
> * `tests/bin/identities`
> 
> Due to the left over test failures from [#321 (comment)](https://github.com/MatrixAI/js-polykey/pull/321#issuecomment-1031071710)

This is already rebased on MatrixAI/Polykey#310, so would it be best to hold off rebasing on master until after that is merged?

**Comment by CMCDragonkai** [comment]
With MatrixAI/Polykey#320 merged, it's still left for this to split:

1. `tests/bin/identities/identities.test.ts`
2. `tests/client/rpcGestalts.test.ts`

While doing so, beware of our new policy of using selective imports. I suggest making sure you're doing selective imports for all our types and utilities.

Also where you are doing `import * as utils from '../utils';`, you can change this to `import { ... } from '../utils';`, it's the only place we can do imports for specific functions, everywhere else requires qualification. Also resolve any cyclic imports you see going on according to:

```
     ┌──────────────────┐
     │                  │
     │                  │
Errors────►Types ──┐    │
  │         │      │    │
  │         │      │    │
  ▼         │      │    │
Utils ◄─────┘      │    │
  │                ▼    │
  └─────────► Classes ◄─┘
```

**Comment by joshuakarp** [comment]
FYI @emmacasolin from the [most recent pipeline](https://gitlab.com/MatrixAI/open-source/js-polykey/-/pipelines/470214101) (after MatrixAI/Polykey#320 and MatrixAI/Polykey#310 were merged), we have test failures in:
* `tests/vaults` (presumably fixed in MatrixAI/Polykey#266)
* `tests/bin/identities` (I believe this is already known)
* `tests/client/service/notificationsSend.test.ts` (an empty `NodeGraph` error)

**Comment by emmacasolin** [comment]
> Also where you are doing `import * as utils from '../utils';`, you can change this to `import { ... } from '../utils';`, it's the only place we can do imports for specific functions, everywhere else requires qualification. 

Is `../utils` here referring to a specific file in the codebase or is it referring to any utils that are located in `../utils` relative to the file the import is in?

**Comment by emmacasolin** [comment]
An additional question about selective imports - I'm noticing a shift in the way classes are being imported in the code that came in from the node connection manager PR. For example, imports that used to be done like this:
```ts
import { GestaltGraph } from '@/gestalts';
```
Are now being done like this:
```ts
import GestaltGraph from '@/gestalts/GestaltGraph';
```
Is this something I should also be following in this PR?

**Comment by CMCDragonkai** [comment]
Yea selective imports apply to files now.

The utils I was referring to was only src/utils.

**Comment by CMCDragonkai** [comment]
Are able to separate your commits between changes to selective imports and changes to test splitting. That way we can have commits that about splitting a particular set of tests and commits for changing imports.

Also you had multiple commits for different test splits before right?

**Comment by CMCDragonkai** [comment]
Also since you've moved the validation tests out of MatrixAI/Polykey#326 into here, I'm going to be removing that change from MatrixAI/Polykey#326.

<details>

```ts
import { utils, errors } from '@/validation';
import * as nodesUtils from '@/nodes/utils';

describe('Validation utils', () => {
  describe('parseSeedNodes', () => {
    const nodeIdEncoded1 = 'vrsc24a1er424epq77dtoveo93meij0pc8ig4uvs9jbeld78n9nl0';
    const nodeId1 = nodesUtils.decodeNodeId(nodeIdEncoded1)!;
    const nodeIdEncoded2 = 'vrcacp9vsb4ht25hds6s4lpp2abfaso0mptcfnh499n35vfcn2gkg';
    const nodeId2 = nodesUtils.decodeNodeId(nodeIdEncoded2)!;
    const nodeIdEncoded3 = 'vi3et1hrpv2m2lrplcm7cu913kr45v51cak54vm68anlbvuf83ra0';
    const nodeId3 = nodesUtils.decodeNodeId(nodeIdEncoded3)!;
    const hostname = 'testnet.polykey.io';
    const hostIPv4 = '127.0.0.1';
    const hostIPv6 = '[2001:db8:85a3:8d3:1319:8a2e:370:7348]';
    const port1 = 1314;
    const port2 = 1315;
    const port3 = 1316;
    test('valid seed nodes (using hostname, IPv4, IPv6)', () => {
      const rawSeedNodes =
        `${nodeIdEncoded1}@${hostname}:${port1};` +
        `${nodeIdEncoded2}@${hostIPv4}:${port2};` +
        `${nodeIdEncoded3}@${hostIPv6}:${port3};`;
      const parsed = utils.parseSeedNodes(rawSeedNodes);
      const seeds = parsed[0];
      console.log(seeds);
      expect(seeds[nodeId1]).toStrictEqual({
        host: hostname,
        port: port1,
      });
      expect(seeds[nodeId2]).toStrictEqual({
        host: hostIPv4,
        port: port2,
      });
      expect(seeds[nodeId3]).toStrictEqual({
        host: hostIPv6.replace(/\[|\]/g, ''),
        port: port3,
      });
      expect(parsed[1]).toBeFalsy();
    });
    test('invalid node ID', () => {
      const rawSeedNodes = `INVALIDNODEID@${hostname}:${port1}`;
      expect(() => utils.parseSeedNodes(rawSeedNodes)).toThrow(errors.ErrorParse);
    });
    test('invalid hostname', () => {
      const rawSeedNodes = `${nodeIdEncoded1}@$invalidHost:${port1}`;
      expect(() => utils.parseSeedNodes(rawSeedNodes)).toThrow(errors.ErrorParse);
    });
    test('invalid port', () => {
      const rawSeedNodes = `${nodeIdEncoded1}@${hostname}$:NOTAPORT`;
      // TODO: currently failing here
      expect(() => utils.parseSeedNodes(rawSeedNodes)).toThrow(errors.ErrorParse);
    });
    test('invalid structure', () => {
      const rawSeedNodes = ``
    });
    // TODO: remove - just testing this weird behaviour
    test.only('invalid', () => {
      expect(() => {
        new URL('bad URL');
      }).toThrowError(TypeError)
      // try {
      //   new URL('bad url');
      // } catch (e) {
      //   if (e instanceof TypeError) {
      //     console.log('TypeError')
      //   }
      // }
    });
  });
});
```

</details>

**Comment by CMCDragonkai** [comment]
We should be able to merge this by the end of this week, that should complete the entire test splitting. This PR may also incorporate some additional tests like validation testing or root key pair propagation testing. But we should expect all tests to pass except for vaults to be resolved in MatrixAI/Polykey#266.

**Comment by emmacasolin** [comment]
> Are able to separate your commits between changes to selective imports and changes to test splitting. That way we can have commits that about splitting a particular set of tests and commits for changing imports.
> 
> Also you had multiple commits for different test splits before right?

Yeah they were split previously but I merged everything to make rebasing a little easier. I can split them up again. I think splitting up the 'test splitting' and 'changing imports' commits might be difficult though, since for most of the tests I'll be doing these two things at the same time, as well as making other changes to improve the tests.

**Comment by emmacasolin** [comment]
Just a note that right now, any bin tests that require an authenticated identity cannot use the shared global agent since we can't unauthenticate an identity via the CLI. Once the `pk identities token` commands have been implemented in https://github.com/MatrixAI/js-polykey/issues/334 we will have the ability to put and delete tokens directly via the CLI and so these tests will then be able to switch over to using the global agent.

The affected tests are all of the identities and notifications bin tests.

**Comment by emmacasolin** [comment]
I'm noticing some discrepancies between the stdout of different CLI commands when `json` output is specified. Some commands (e.g. `agent status`) output an object e.g.
```
{
  status: 'LIVE',
  pid: ...,
  nodeId: ...,
  etc...
}
```
Whereas other commands (e.g. `identities claim`) output an array e.g.
```
[ "Claim Id: ...", "Url: ..."]
```

Should there be some sort of standard here? The `keys` commands in particular are adding tabs into their output that no other subcommands are doing (which makes it very difficult to check the stdout during testing). If there should be a standard I would lean towards following the object style that `agent status` uses, as this is the easiest output to write tests for. I can make those changes in this PR if so.

**Comment by CMCDragonkai** [comment]
The `agent status` is using dict or json.

The other output looks weird. Maybe it's an array being passed in? The Json version of list is meant to take an array. But since there are keys there, shouldn't you be using dict?

**Comment by emmacasolin** [comment]
> The `agent status` is using dict or json.
> 
> The other output looks weird. Maybe it's an array being passed in? The Json version of list is meant to take an array. But since there are keys there, shouldn't you be using dict?

In pretty much every command other than `agent status` the output is done similarly to this:
```ts
const output = [`Claim Id: ${claimMessage.getClaimId()}`];
if (claimMessage.getUrl()) {
  output.push(`Url: ${claimMessage.getUrl()}`);
}
process.stdout.write(
  binUtils.outputFormatter({
    type: options.format === 'json' ? 'json' : 'list',
    data: output,
  }),
);
```
Which doesn't seem right to me. Another example from `keys cert`
```ts
process.stdout.write(
  binUtils.outputFormatter({
    type: options.format === 'json' ? 'json' : 'list',
    data: [`Root certificate:\t\t${response.getCert()}`],
  }),
);
```

Should every command instead be constructing the data into an object and outputting it as either json or dict? e.g.
```ts
process.stdout.write(
  binUtils.outputFormatter({
    type: options.format === 'json' ? 'json' : 'dict',
    data: { rootCertificate: response.getCert() },
  }),
);
```

**Comment by CMCDragonkai** [comment]
Yea I can see that being incorrect. The only time when `list` should be used, is when the output of a command is "semantically" a list. Otherwise, use `dict`. So it depends on what the expected output of those commands should be. This can be a new issue.

**Comment by CMCDragonkai** [comment]
It is a case-by-case basis. Some commands have a single string output, and that doesn't even use a output formatter then.

**Comment by emmacasolin** [comment]
> Yea I can see that being incorrect. The only time when `list` should be used, is when the output of a command is "semantically" a list. Otherwise, use `dict`. So it depends on what the expected output of those commands should be. This can be a new issue.

Ok, I'll make a new issue for it. For the time being I might modify the output for some of the keys commands where it would make writing tests significantly easier, but there can be a proper review of every command's output at another time.

**Comment by CMCDragonkai** [comment]
Master now has the `\n` added to all JSON output. So combined with the readline interface, you should be able to operate on each json line by doing a sort of `rlOut.on('line', (line) => JSON.parse(line))`. This should allow you to parse individual lines out, and also do expectations on each.

Or you can accumulate the parsed POJOs into an array, and then do expectations on the whole array.

In the `start.test.ts` we currently do:

```ts
      const rlOut = readline.createInterface(agentProcess.stdout!);
      const recoveryCode = await new Promise<RecoveryCode>(
        (resolve, reject) => {
          rlOut.once('line', resolve);
          rlOut.once('close', reject);
        },
      );
```

You would instead need to do:

```ts
const data = await new Promise<Array<POJO>>(
  (resolve) => {
    const data = [];
    rlOut.on('line', (line) => {
      data.push(JSON.parse(line));
    });
    rlOut.once('close', () => {
      resolve(data);
    });
  },
);
```

Replace the above variable names with appropriate names, and `POJO` should what you're expecting.

This only needs to be done for the when the command outputs a stream of JSON lines.

**Comment by CMCDragonkai** [comment]
Avoid touching `start.test.ts` and `status.test.ts` as that is being changed in MatrixAI/Polykey#326 

The readline interface change should be applicable to `pk identities search` command.

@emmacasolin you can a list any other commands applicable here, but if they are out of the test splitting scope in the PR, we'll leave that till later.

**Comment by emmacasolin** [comment]
I'm running into some weird errors with the keys renew and reset bin tests. The Polykey Agent (which should be the global agent) appears to be stopping too early, but it's difficult to tell from the output:

<details>

```
[nix-shell:~/Projects/js-polykey]$ npm run test keys/renew keys/reset

> @matrixai/polykey@1.0.0 test /home/emma/Projects/js-polykey
> jest "keys/renew" "keys/reset"

Debugger listening on ws://127.0.0.1:39639/b2403d8b-39ce-4837-b076-112f38d8c25b
For help, see: https://nodejs.org/en/docs/inspector
read byte 1

Error activating auto attach, please report to https://aka.ms/js-dbg-issue
Determining test suites to run...
GLOBAL SETUP
Global Data Dir: /tmp/polykey-test-global-6W6c7T
INFO:renew test:Creating PolykeyAgent
INFO:renew test:Setting umask to 077
INFO:renew test:Setting node path to /tmp/polykey-test-global-6W6c7T/agent
INFO:Status:Starting Status
INFO:Status:Writing Status to /tmp/polykey-test-global-6W6c7T/agent/status.json
INFO:Status:Status is STARTING
INFO:Schema:Creating Schema
INFO:Schema:Starting Schema
INFO:Schema:Setting state path to /tmp/polykey-test-global-6W6c7T/agent/state
INFO:Schema:Started Schema
INFO:Schema:Created Schema
INFO:KeyManager:Creating KeyManager
INFO:KeyManager:Setting keys path to /tmp/polykey-test-global-6W6c7T/agent/state/keys
INFO:KeyManager:Starting KeyManager
INFO:KeyManager:Checking /tmp/polykey-test-global-6W6c7T/agent/state/keys/root.pub and /tmp/polykey-test-global-6W6c7T/agent/state/keys/root.key
INFO:KeyManager:Generating root key pair
INFO:KeyManager:Writing /tmp/polykey-test-global-6W6c7T/agent/state/keys/root.pub and /tmp/polykey-test-global-6W6c7T/agent/state/keys/root.key
INFO:KeyManager:Checking /tmp/polykey-test-global-6W6c7T/agent/state/keys/root.crt
INFO:KeyManager:Generating root certificate
INFO:KeyManager:Writing /tmp/polykey-test-global-6W6c7T/agent/state/keys/root.crt
INFO:KeyManager:Checking /tmp/polykey-test-global-6W6c7T/agent/state/keys/db.key
INFO:KeyManager:Generating keys db key
INFO:KeyManager:Writing /tmp/polykey-test-global-6W6c7T/agent/state/keys/db.key
INFO:KeyManager:Checking /tmp/polykey-test-global-6W6c7T/agent/state/keys/vault.key
INFO:KeyManager:Generating keys db key
INFO:KeyManager:Writing /tmp/polykey-test-global-6W6c7T/agent/state/keys/vault.key
INFO:KeyManager:Started KeyManager
INFO:KeyManager:Created KeyManager
INFO:DB:Creating DB
INFO:DB:Starting DB
INFO:DB:Setting DB path to /tmp/polykey-test-global-6W6c7T/agent/state/db
INFO:DB:Started DB
INFO:DB:Created DB
INFO:IdentitiesManager:Creating IdentitiesManager
INFO:IdentitiesManager:Starting IdentitiesManager
INFO:IdentitiesManager:Started IdentitiesManager
INFO:IdentitiesManager:Created IdentitiesManager
INFO:Sigchain:Creating Sigchain
INFO:Sigchain:Starting Sigchain
INFO:Sigchain:Started Sigchain
INFO:Sigchain:Created Sigchain
INFO:ACL:Creating ACL
INFO:ACL:Starting ACL
INFO:ACL:Started ACL
INFO:ACL:Created ACL
INFO:GestaltGraph:Creating GestaltGraph
INFO:GestaltGraph:Starting GestaltGraph
INFO:GestaltGraph:Started GestaltGraph
INFO:GestaltGraph:Created GestaltGraph
INFO:ForwardProxy:Creating Forward Proxy
INFO:ForwardProxy:Created Forward Proxy
INFO:ReverseProxy:Creating Reverse Proxy
INFO:ReverseProxy:Created Reverse Proxy
INFO:NodeGraph:Creating NodeGraph
INFO:NodeGraph:Starting NodeGraph
INFO:NodeGraph:Started NodeGraph
INFO:NodeGraph:Created NodeGraph
INFO:Discovery:Creating Discovery
INFO:Discovery:Starting Discovery
INFO:Discovery:Started Discovery
INFO:Discovery:Created Discovery
INFO:VaultManager:Creating VaultManager
INFO:VaultManager:Created VaultManager
INFO:VaultManager:Starting VaultManager
INFO:DB:Creating DB
INFO:DB:Starting DB
INFO:DB:Setting DB path to /tmp/polykey-test-global-6W6c7T/agent/state/vaults
INFO:DB:Started DB
INFO:DB:Created DB
INFO:VaultManager:Starting EncryptedFS
INFO:VaultManager:Started EncryptedFS
INFO:VaultManager:Started VaultManager
INFO:NotificationsManager:Creating NotificationsManager
INFO:NotificationsManager:Starting NotificationsManager
INFO:NotificationsManager:Started NotificationsManager
INFO:NotificationsManager:Created NotificationsManager
INFO:SessionManager:Creating SessionManager
INFO:SessionManager:Starting SessionManager
INFO:SessionManager:Generating sessions key
INFO:SessionManager:Started SessionManager
INFO:SessionManager:Created SessionManager
INFO:renew test:Starting PolykeyAgent
INFO:GRPCServerClient:Starting GRPCServer on 127.0.0.1:0
INFO:GRPCServerClient:Started GRPCServer on 127.0.0.1:33021
INFO:GRPCServerAgent:Starting GRPCServer on 127.0.0.1:0
INFO:GRPCServerAgent:Started GRPCServer on 127.0.0.1:37995
INFO:ForwardProxy:Starting Forward Proxy from 127.0.0.1:0 to 0.0.0.0:0
INFO:ForwardProxy:Started Forward Proxy from 127.0.0.1:37701 to 0.0.0.0:50134
INFO:ReverseProxy:Starting Reverse Proxy from 0.0.0.0:0 to 127.0.0.1:37995
INFO:ReverseProxy:Started Reverse Proxy from 0.0.0.0:55247 to 127.0.0.1:37995
INFO:NodeConnectionManager:Starting NodeConnectionManager
INFO:NodeConnectionManager:Started NodeConnectionManager
INFO:Status:Finish Status STARTING
INFO:Status:Writing Status to /tmp/polykey-test-global-6W6c7T/agent/status.json
INFO:Status:Status is LIVE
INFO:renew test:Started PolykeyAgent
INFO:renew test:Created PolykeyAgent
 PASS  tests/bin/keys/renew.test.ts (39.22 s)
  renew
    ✓ renews the keypair (5039 ms)

INFO:KeyManager:Resetting root key pair
INFO:KeyManager:Reading /tmp/polykey-test-global-6W6c7T/agent/state/keys/db.key
INFO:KeyManager:Reading /tmp/polykey-test-global-6W6c7T/agent/state/keys/vault.key
INFO:renew test:Stopping PolykeyAgent
INFO:Status:Begin Status STOPPING
INFO:Status:Writing Status to /tmp/polykey-test-global-6W6c7T/agent/status.json
INFO:Status:Status is STOPPING
INFO:SessionManager:Stopping SessionManager
INFO:SessionManager:Stopped SessionManager
INFO:NotificationsManager:Stopping NotificationsManager
INFO:NotificationsManager:Stopped NotificationsManager
INFO:VaultManager:Stopping VaultManager
INFO:VaultManager:Stopping EncryptedFS
INFO:DB:Stopping DB
INFO:DB:Stopped DB
INFO:VaultManager:Stopped EncryptedFS
INFO:VaultManager:Stopped VaultManager
INFO:NodeConnectionManager:Stopping NodeConnectionManager
INFO:NodeConnectionManager:Stopped NodeConnectionManager
INFO:NodeGraph:Stopping NodeGraph
INFO:NodeGraph:Stopped NodeGraph
INFO:Discovery:Stopping Discovery
INFO:Discovery:Stopped Discovery
INFO:ReverseProxy:Stopping Reverse Proxy
INFO:ReverseProxy:Stopped Reverse Proxy
INFO:ForwardProxy:Stopping Forward Proxy Server
INFO:ForwardProxy:Stopped Forward Proxy Server
INFO:GRPCServerAgent:Stopping GRPCServer
INFO:GRPCServerAgent:Stopped GRPCServer
INFO:GRPCServerClient:Stopping GRPCServer
INFO:KeyManager:Performing garbage collection of root certificates
INFO:KeyManager:Writing /tmp/polykey-test-global-6W6c7T/agent/state/keys/root.pub and /tmp/polykey-test-global-6W6c7T/agent/state/keys/root.key
INFO:KeyManager:Writing /tmp/polykey-test-global-6W6c7T/agent/state/keys/root.crt
INFO:KeyManager:Writing /tmp/polykey-test-global-6W6c7T/agent/state/keys/db.key
INFO:KeyManager:Writing /tmp/polykey-test-global-6W6c7T/agent/state/keys/vault.key
INFO:renew test:Propagating root keypair change
INFO:Status:Updating Status LIVE
ERROR:renew test:EventBus error for Symbol(rootKeyPairChange): ErrorStatusLiveUpdate: Failed to update LIVE status info - Status is not LIVE
/home/emma/Projects/js-polykey/src/status/Status.ts:253
                throw new statusErrors.ErrorStatusLiveUpdate(`${this.constructor.name} is not LIVE`);
                      ^

ErrorStatusLiveUpdate: Status is not LIVE
    at Object.updateStatusLive (/home/emma/Projects/js-polykey/src/status/Status.ts:253:23)
    at EventBus.<anonymous> (/home/emma/Projects/js-polykey/src/PolykeyAgent.ts:382:17)
    at EventBus.emitAsync (/home/emma/Projects/js-polykey/src/events/EventBus.ts:21:17)
    at Object.rootKeyPairChange (/home/emma/Projects/js-polykey/src/PolykeyAgent.ts:153:29)
    at Object.resetRootKeyPair (/home/emma/Projects/js-polykey/src/keys/KeyManager.ts:339:9)
    at Object.keysKeyPairReset (/home/emma/Projects/js-polykey/src/client/service/keysKeyPairReset.ts:32:13) {
  description: 'Failed to update LIVE status info',
  exitCode: 64,
  data: {}
}
 FAIL  tests/bin/keys/reset.test.ts (79.366 s)
  reset
    ✕ resets the keypair (20025 ms)

  ● reset › resets the keypair

    : Timeout - Async callback was not invoked within the 20000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 20000 ms timeout specified by jest.setTimeout.Error:

      23 |     await globalAgentClose();
      24 |   });
    > 25 |   test('resets the keypair', async () => {
         |   ^
      26 |     // Get previous keypair and nodeId
      27 |     let { exitCode, stdout } = await testBinUtils.pkStdio(
      28 |       ['keys', 'root', '--private-key', '--format', 'json'],

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (tests/bin/keys/reset.test.ts:25:3)

A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks.
Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        80.217 s, estimated 85 s
Ran all test suites matching /keys\/renew|keys\/reset/i.
GLOBAL TEARDOWN
Destroying Global Data Dir: /tmp/polykey-test-global-6W6c7T
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @matrixai/polykey@1.0.0 test: `jest "keys/renew" "keys/reset"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @matrixai/polykey@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/emma/.npm/_logs/2022-02-18T05_38_10_680Z-debug.log
```

</details>

**Comment by emmacasolin** [comment]
> I'm running into some weird errors with the keys renew and reset bin tests. The Polykey Agent (which should be the global agent) appears to be stopping too early, but it's difficult to tell from the output:

Weirdly the tests are actually passing on the pipeline? So I'm not entirely sure what's happening here

**Comment by CMCDragonkai** [comment]
Was there a regression at some point? Check the commit history as well and see if a previous commits pass without problems. Then compare the code to now.

**Comment by CMCDragonkai** [comment]
This may also be one of those intermittent errors, can you provide a reproducible case? With `npm run test -- ./tests/...`. Also note your debugger is attached as well, does that affect it?

**Comment by emmacasolin** [comment]
> Was there a regression at some point? Check the commit history as well and see if a previous commits pass without problems. Then compare the code to now.

There wasn't a regression - previously these tests were passing when I was not using the global agent, but I recently switched to using the global agent and this is likely the reason why they're failing now.

> This may also be one of those intermittent errors, can you provide a reproducible case? With npm run test -- ./tests/.... Also note your debugger is attached as well, does that affect it?

`npm run test keys/renew keys/reset` seems to be giving the same errors on each execution, so should be reproducible. Detaching the debugger doesn't seem to make a difference.

**Comment by emmacasolin** [comment]
Another strange finding: after removing all of the unnecessary `beforeEach` and `afterEach` blocks from the other keys commands (they were just setting up a `dataDir` that was never used) the `reset` and `renew` tests are now passing? This is even when `tests/bin/keys/renew` and `tests/bin/keys/reset` are the only tests I'm running, so this seemingly insignificant change should have absolutely no effect on these tests. I've changed over to using selective imports for these tests already, however, `tests/utils.ts` still uses index imports so perhaps this is the reason?

**Comment by emmacasolin** [comment]
> Another strange finding: after removing all of the unnecessary `beforeEach` and `afterEach` blocks from the other keys commands (they were just setting up a `dataDir` that was never used) the `reset` and `renew` tests are now passing? This is even when `tests/bin/keys/renew` and `tests/bin/keys/reset` are the only tests I'm running, so this seemingly insignificant change should have absolutely no effect on these tests. I've changed over to using selective imports for these tests already, however, `tests/utils.ts` still uses index imports so perhaps this is the reason?

Removing the index imports from `tests/utils.ts` causes the failures to reappear again. Specifically, changing the line
```ts
import { PolykeyAgent } from '@';
```
to 
```ts
import PolykeyAgent from '@/PolykeyAgent';
```
seems to be the source of the failures.

**Comment by CMCDragonkai** [comment]
As a precaution don't use the global agent for `renew` and `reset` tests because it's affecting alot of different state. So you should be using your own agent for that.

**Comment by CMCDragonkai** [comment]
However I don't think that's the reason for this problem. Comment out the `await globalAgentClose()` in the `afterAll` from `reset.test.ts` or `renew.test.ts`, and just run the test by itself. You should see that the agent does not shutdown.

One thing you want to make clear is whether the command `pk keys renew` or `pk keys reset` **is not** shutting down the agent. Because if it is shutting down the agent, then it's a bug in the source code that needs to be fixed. Do this both commands.

Also make sure you can replicate the problem by doing this:

```ts
npm test -- ./tests/bin/keys/renew.test.ts ./tests/bin/keys/reset.test.ts
```

This ensures that you are not running the `beforeAll`, `afterAll` and nested describes in all the other tests files if you use a directory parameter.

**Comment by emmacasolin** [comment]
> However I don't think that's the reason for this problem. Comment out the `await globalAgentClose()` in the `afterAll` from `reset.test.ts` or `renew.test.ts`, and just run the test by itself. You should see that the agent does not shutdown.
> 
> One thing you want to make clear is whether the command `pk keys renew` or `pk keys reset` **is not** shutting down the agent. Because if it is shutting down the agent, then it's a bug in the source code that needs to be fixed. Do this both commands.
> 
> Also make sure you can replicate the problem by doing this:
> 
> ```ts
> npm test -- ./tests/bin/keys/renew.test.ts ./tests/bin/keys/reset.test.ts
> ```
> 
> This ensures that you are not running the `beforeAll`, `afterAll` and nested describes in all the other tests files if you use a directory parameter.

The problem can be replicated using `npm test -- ./tests/bin/keys/renew.test.ts ./tests/bin/keys/reset.test.ts`. Also, commenting out the `await globalAgentClose()` leads to the agent not shutting down, but also prevents the tests from ever completing. 

Interestingly though, the error is intermittent, and seems to only occur if we have already started renewing/resetting the keypair when one of the tests tries to exit and shut down the global agent. Specifically, if we are reading from the global agent directory, e.g.
```
INFO:KeyManager:Reading /tmp/polykey-test-global-Fu47fO/agent/state/keys/db.key
INFO:KeyManager:Reading /tmp/polykey-test-global-Fu47fO/agent/state/keys/vault.key
```
at the same time as when we call `await globalAgentClose()`, we exit `globalAgentClose` without shutting down the global agent, however, the agent is still being stopped by something
```
INFO:reset test:Stopping PolykeyAgent
```

I'm going to switch to using separate agents for the `renew` and `reset` commands due to the potential for these operations to have unwanted side-effects on the global agent, however there seems to be some sort of weird bug here that should be looked into at some point.

**Comment by CMCDragonkai** [comment]
That `Stopping PolykeyAgent` message can only come from `PolykeyAgent.stop` method. So we should trace who is calling that method. But again, this can go into a new issue to address afterwards.

File: src/PolykeyAgent.ts [hunk 13]
```diff
@@ -712,6 +712,25 @@ class PolykeyAgent {
     this.logger.info(`Destroyed ${this.constructor.name}`);
   }
 
+  public async restart({
```
Comment (CMCDragonkai) [inline src/PolykeyAgent.ts]: Are you using this method anywhere in the tests? This is best separated into another PR.

**Comment by emmacasolin** [comment]
All of the test splitting work is done here. All that's left is fixing up any remaining index imports in any of the split tests and debugging any remaining test failures (there seems to be some intermittent failures on the pipeline across `tests/agent/service`, `tests/bin`, `tests/bin/identities`, `tests/client/service`, `tests/notifications`, and `tests/validation`).

File: src/PolykeyAgent.ts (hunk 13 above)
Comment (CMCDragonkai) [reply src/PolykeyAgent.ts]: Would include `src/bin/agent/CommandAgent.ts` and `src/bin/agent/CommandRestart.ts`

Comment (CMCDragonkai) [reply src/PolykeyAgent.ts]: And `src/client/service/agentRestart.ts`.

**Comment by emmacasolin** [comment]
I've debugged all of the tests except for the vaults tests, as well as a tricky error I'm getting from `tests/bin/identities/discoverGet.test.ts`. It's an intermittent error that seems to occur completely randomly - it's a `PromiseRejectionHandledWarning` that is coming from when we `await this.discoveryProcess;` to exit the discovery queue when we call `stop` in `Discovery.ts`.

If we catch the error that's being thrown there and log it out, we can see that it's an `ErrorNodeConnectionDestroyed` error, which is coming from trying to call `getExpectedPublicKey()` inside `NodeConnection.ts`. I thought maybe there was an issue with the order of stopping inside the `PolykeyAgent` that was causing the connection to be destroyed before discovery - `NodeConnectionManager` and `NodeGraph` were indeed being stopped before `Discovery`, however even after fixing up this order the error still persists.

The affected tests still pass even when this error occurs, the only problem is that the test never exits so we get a timeout on the pipeline. I still haven't been able to pin down the reason for why the error occurs only some of the time, or what exactly is causing it, however I'm wondering if potentially it has something to do with the `Forward Error: ErrorConnectionEndTimeout` that seems to occur in all of the tests that incorporate the nodes domain. It's the same warning I talked about here https://github.com/MatrixAI/js-polykey/pull/326#issuecomment-1046462357 and it seems to be popping up in quite a lot of places.

**Comment by emmacasolin** [comment]
> That `Stopping PolykeyAgent` message can only come from `PolykeyAgent.stop` method. So we should trace who is calling that method. But again, this can go into a new issue to address afterwards.

Issue created for this here: https://github.com/MatrixAI/js-polykey/issues/347

**Comment by CMCDragonkai** [comment]
> I've debugged all of the tests except for the vaults tests, as well as a tricky error I'm getting from `tests/bin/identities/discoverGet.test.ts`. It's an intermittent error that seems to occur completely randomly - it's a `PromiseRejectionHandledWarning` that is coming from when we `await this.discoveryProcess;` to exit the discovery queue when we call `stop` in `Discovery.ts`.
> 
> If we catch the error that's being thrown there and log it out, we can see that it's an `ErrorNodeConnectionDestroyed` error, which is coming from trying to call `getExpectedPublicKey()` inside `NodeConnection.ts`. I thought maybe there was an issue with the order of stopping inside the `PolykeyAgent` that was causing the connection to be destroyed before discovery - `NodeConnectionManager` and `NodeGraph` were indeed being stopped before `Discovery`, however even after fixing up this order the error still persists.
> 
> The affected tests still pass even when this error occurs, the only problem is that the test never exits so we get a timeout on the pipeline. I still haven't been able to pin down the reason for why the error occurs only some of the time, or what exactly is causing it, however I'm wondering if potentially it has something to do with the `Forward Error: ErrorConnectionEndTimeout` that seems to occur in all of the tests that incorporate the nodes domain. It's the same warning I talked about here https://github.com/MatrixAI/js-polykey/pull/326#issuecomment-1046462357 and it seems to be popping up in quite a lot of places.

Can you replicate this within the Discovery module and without the bin executable? You may need to ablate to the minimum reproducible case.

**Comment by tegefaulkes** [comment]
There are two ways the `NodeConnection` can be destroyed. normally by calling `nodeConnection.destroy()` but it will also be destroyed in the case that the underlying connection failed. Is it possible you are destroying the connection from the server side before discovery completes?

**Comment by tegefaulkes** [comment]
Found the problem. The `ErrorNodeConnectionDestroyed` is caused because we are stopping the remote nodes before stopping the agent doing the discovery. If you stop `pkAgent` before `nodeA` and `nodeB` then we don't get the error. When you stop the remote nodes first any active connection to the `pkAgent` is closed. This is seen by the `GRPCClientAgent`'s channel watcher which destroys the client including the `NodeConnection`. This is why we're getting the `ErrorNodeConnectionDestroyed` error.

**Comment by emmacasolin** [comment]
> Found the problem. The `ErrorNodeConnectionDestroyed` is caused because we are stopping the remote nodes before stopping the agent doing the discovery. If you stop `pkAgent` before `nodeA` and `nodeB` then we don't get the error. When you stop the remote nodes first any active connection to the `pkAgent` is closed. This is seen by the `GRPCClientAgent`'s channel watcher which destroys the client including the `NodeConnection`. This is why we're getting the `ErrorNodeConnectionDestroyed` error.

One of the steps of the discovery process is to request the chain data of the node we're discovering in order to add its linked nodes/identities to the discovery queue. This process is done inside a `withConnF()`, so if the node we're contacting goes offline while we're in the middle of this process it will destroy the connection and throw the error. The problem is that we're not catching/handling this error in the discovery process. Would the better solution here be to put a catch handler around `vertexChainData = await this.nodeManager.requestChainData(nodeId);` inside the discovery process and skip discovering a vertex if this error occurs? Or should `nodeManager.requestChainData()` be handling this error instead and returning an empty `ChainData` object?

In either case, once https://github.com/MatrixAI/js-polykey/issues/328 has been implemented both an offline node and a node with no linked nodes/vertices would be added back into the discovery queue at some point. The only difference being perhaps an offline node should have a higher priority for being added back into the queue (https://github.com/MatrixAI/js-polykey/issues/329)? This would be the only reason for needing to differenciate between these two cases (and thus requiring us to catch the error on the discovery side rather than just receive back an empty `ChainData`).

**Comment by tegefaulkes** [comment]
I think Discovery should be handling the exception. It gives better context in the code when a failure does happen. On that note I think that the `nodeConnectionManager.withConnF` and `nodeConnectionManager.withConnG` should re-throw the connection errors as a general `ErrorConnectionFailed`. it might've provided better context when debugging this kind of problem.

**Comment by CMCDragonkai** [comment]
> > Found the problem. The `ErrorNodeConnectionDestroyed` is caused because we are stopping the remote nodes before stopping the agent doing the discovery. If you stop `pkAgent` before `nodeA` and `nodeB` then we don't get the error. When you stop the remote nodes first any active connection to the `pkAgent` is closed. This is seen by the `GRPCClientAgent`'s channel watcher which destroys the client including the `NodeConnection`. This is why we're getting the `ErrorNodeConnectionDestroyed` error.
> 
> One of the steps of the discovery process is to request the chain data of the node we're discovering in order to add its linked nodes/identities to the discovery queue. This process is done inside a `withConnF()`, so if the node we're contacting goes offline while we're in the middle of this process it will destroy the connection and throw the error. The problem is that we're not catching/handling this error in the discovery process. Would the better solution here be to put a catch handler around `vertexChainData = await this.nodeManager.requestChainData(nodeId);` inside the discovery process and skip discovering a vertex if this error occurs? Or should `nodeManager.requestChainData()` be handling this error instead and returning an empty `ChainData` object?
> 
> In either case, once MatrixAI/Polykey#328 has been implemented both an offline node and a node with no linked nodes/vertices would be added back into the discovery queue at some point. The only difference being perhaps an offline node should have a higher priority for being added back into the queue (#329)? This would be the only reason for needing to differenciate between these two cases (and thus requiring us to catch the error on the discovery side rather than just receive back an empty `ChainData`).

1. Any classes that perform calls to other agents by using `NodeConnectionManager` needs to be ready deal with connection failures, which can be caused by remote agents shutting down early.
2. `NodeManager` does perform calls to other agents, specifically the `requestChainData` call.
3. In this particular case, the fact that the connection has failed, should mean that `requestChainData` should "rethrow" that exception upwards. It cannot do anything here as we do not want to apply retry policies within low level methods like this. Therefore it indeed **should not** be returning an empty chain data. This is an exceptional condition.
4. The `Discovery` is calling `NodeManager` here, and once it catches that exception it should handle this by dequeuing the node it's trying to discover and reset its TTL so it can be put back into the queue. The `Discovery` **can** handle the error here, because it's meant to run forever and be forgiving of nodes that are offline or have been shutdown for variety of reasons.
5. This is an edge case that wasn't covered in the initial spec. Please beware that when dealing with anything over the network you **must** cover all possible edge cases that come from network failure.

**Comment by CMCDragonkai** [comment]
> I think Discovery should be handling the exception. It gives better context in the code when a failure does happen. On that note I think that the `nodeConnectionManager.withConnF` and `nodeConnectionManager.withConnG` should re-throw the connection errors as a general `ErrorConnectionFailed`. it might've provided better context when debugging this kind of problem.

Actually in this case `ErrorNodeConnectionDestroyed` is an appropriate exception. It can only be further disambiguated by creating a second variant that indicates that it was destroyed by forces other than directly calling `destroy`. However this is complicated and we can leave it for now. This is just missing specified behaviour handling network failures for `Discovery` module.

**Comment by CMCDragonkai** [comment]
Regarding the revisiting policies. Actually if something is offline, it's likely to continue being offline. While something that is online is likely to continue being online. So we would use exponential backoff for any kind of revisiting for offline nodes (or nodes where there are connection failures). Same with online nodes that don't change all that much. We can tune this in production as we see fit.

**Comment by emmacasolin** [comment]
> 1. Any classes that perform calls to other agents by using `NodeConnectionManager` needs to be ready deal with connection failures, which can be caused by remote agents shutting down early.
> 2. `NodeManager` does perform calls to other agents, specifically the `requestChainData` call.
> 3. In this particular case, the fact that the connection has failed, should mean that `requestChainData` should "rethrow" that exception upwards. It cannot do anything here as we do not want to apply retry policies within low level methods like this. Therefore it indeed **should not** be returning an empty chain data. This is an exceptional condition.
> 4. The `Discovery` is calling `NodeManager` here, and once it catches that exception it should handle this by dequeuing the node it's trying to discover and reset its TTL so it can be put back into the queue. The `Discovery` **can** handle the error here, because it's meant to run forever and be forgiving of nodes that are offline or have been shutdown for variety of reasons.
> 5. This is an edge case that wasn't covered in the initial spec. Please beware that when dealing with anything over the network you **must** cover all possible edge cases that come from network failure.

I've added a catch handler for `ErrorNodeConnectionDestroyed`, however after doing so I'm now seeing a large number of errors appearing in the logger output:
```
WARN:ConnectionForward 0.0.0.0:50690:Forward Error: ErrorConnectionEndTimeout
ERROR:ForwardProxy:Failed CONNECT to 0.0.0.0:39365 - ErrorConnectionStart: UTP_ECONNRESET
ERROR:grpc:Failed to connect to 0.0.0.0:39365/?nodeId=vdl79qbko2jm7ajhs081d1quk50scbk61apkdorhj9i6mdu425j9g through proxy 127.0.0.1:33071 with status 502
ERROR:ForwardProxy:Failed CONNECT to 0.0.0.0:39365 - ErrorConnectionStart: UTP_ECONNRESET
ERROR:grpc:Failed to connect to 0.0.0.0:39365/?nodeId=vdl79qbko2jm7ajhs081d1quk50scbk61apkdorhj9i6mdu425j9g through proxy 127.0.0.1:33071 with status 502
ERROR:ForwardProxy:Failed CONNECT to 0.0.0.0:39365 - ErrorConnectionStart: UTP_ECONNRESET
ERROR:grpc:Failed to connect to 0.0.0.0:39365/?nodeId=vdl79qbko2jm7ajhs081d1quk50scbk61apkdorhj9i6mdu425j9g through proxy 127.0.0.1:33071 with status 502
ERROR:ForwardProxy:Failed CONNECT to 0.0.0.0:39365 - ErrorConnectionStart: UTP_ECONNRESET
ERROR:grpc:Failed to connect to 0.0.0.0:39365/?nodeId=vdl79qbko2jm7ajhs081d1quk50scbk61apkdorhj9i6mdu425j9g through proxy 127.0.0.1:33071 with status 502
ERROR:ForwardProxy:Failed CONNECT to 0.0.0.0:39365 - ErrorConnectionStart: UTP_ECONNRESET
ERROR:grpc:Failed to connect to 0.0.0.0:39365/?nodeId=vdl79qbko2jm7ajhs081d1quk50scbk61apkdorhj9i6mdu425j9g through proxy 127.0.0.1:33071 with status 502
ERROR:ForwardProxy:Failed CONNECT to 0.0.0.0:39365 - ErrorConnectionStart: UTP_ECONNRESET
ERROR:grpc:Failed to connect to 0.0.0.0:39365/?nodeId=vdl79qbko2jm7ajhs081d1quk50scbk61apkdorhj9i6mdu425j9g through proxy 127.0.0.1:33071 with status 502
```
Along with this error coming from when we try to request chain data:
```
"ErrorNodeConnectionTimeout: 
        at Function.createNodeConnection (/home/emma/Projects/js-polykey/src/nodes/NodeConnection.ts:110:23)
        at Object.establishNodeConnection (/home/emma/Projects/js-polykey/src/nodes/NodeConnectionManager.ts:241:28)
        at /home/emma/Projects/js-polykey/src/nodes/NodeConnectionManager.ts:191:24
        at RWLock.withWrite (/home/emma/Projects/js-polykey/src/utils/locks.ts:34:20)
        at Object.createConnection (/home/emma/Projects/js-polykey/src/nodes/NodeConnectionManager.ts:183:20)
        at /home/emma/Projects/js-polykey/src/nodes/NodeConnectionManager.ts:99:33
        at withF (/home/emma/Projects/js-polykey/src/utils/context.ts:12:41)
        at Object.withConnF (/home/emma/Projects/js-polykey/src/nodes/NodeConnectionManager.ts:123:20)
        at NodeManager.requestChainData (/home/emma/Projects/js-polykey/src/nodes/NodeManager.ts:130:36)
        at Object.setupDiscoveryQueue (/home/emma/Projects/js-polykey/src/discovery/Discovery.ts:168:51) {
      description: 'Polykey error',
      exitCode: 69,
      data: {}
    }"
```

I added `ErrorNodeConnectionTimeout` to the catch handler, which did not get rid of the logger errors but did lead to the test actually completing rather than timing out like before.

Still trying to work out where these logger errors are coming from, but while I was revisiting the discovery algorithm I noticed that there seems to be quite a lot of repetition. Now might not be the time, but I think there is probably room for simplifying the algorithm such that it decreases the repetition, which I think would cut down on the logger errors that seem to be being re-emitted for the same attempted action.

**Comment by tegefaulkes** [comment]
Looks like it keeps attempting to connect and failing. Seems like you either keep adding the node back to the queue or you're not properly removing it? If you fail to connect to a node shouldn't you wait a while before trying to connect again?

**Comment by emmacasolin** [comment]
> Looks like it keeps attempting to connect and failing. Seems like you either keep adding the node back to the queue or you're not properly removing it? If you fail to connect to a node shouldn't you wait a while before trying to connect again?

If the node is the node we're currently discovering, then yes it gets removed from the queue.

The problem is that during discovery we also need to contact the linked nodes in order to get their chain data, since we can't link two nodes in the gestalt graph unless we have the chain data of both nodes (this is the repetition I mentioned, since the linked node will also be added to the discovery queue where we'll need to request its chain data a second time). In this case, the linked node (that we're contacting) might not be in the queue yet. Currently, we're checking if the linked node is in our set of "visited vertices" and only adding it into the queue if we haven't already discovered it. We're not checking if it's already in the queue though, so I can add in a check for that.

**Comment by CMCDragonkai** [comment]
This log messages only happen in the background:

```
WARN:ConnectionForward 0.0.0.0:50690:Forward Error: ErrorConnectionEndTimeout
ERROR:ForwardProxy:Failed CONNECT to 0.0.0.0:39365 - ErrorConnectionStart: UTP_ECONNRESET
ERROR:grpc:Failed to connect to 0.0.0.0:39365/?nodeId=vdl79qbko2jm7ajhs081d1quk50scbk61apkdorhj9i6mdu425j9g through proxy 127.0.0.1:33071 with status 502
```

The `ERROR:grpc` occurs whenever something triggers the underlying GRPC client to connect to the proxy and that there's a failure from the other side. 502 means bad gateway, I put 502 code into the `ForwardProxy` to indicate this.

So it's ultimately connected to the `ERROR:ForwardProxy:Failed CONNECT to 0.0.0.0:39365 - ErrorConnectionStart: UTP_ECONNRESET`, they are always together.

And that means a connection request from forward proxy failed because the UTP connection has been reset.

Perhaps something is retrying the connection request? Where can you reproduce it?

**Comment by CMCDragonkai** [comment]
@emmacasolin seems like having a uniqueness constraint on the discovery queue DB would be helpful. This can also be achieved by our indexing issue on js-db.

**Comment by CMCDragonkai** [comment]
BTW this seems wrong.

```
0.0.0.0:39365
```

You cannot "connect to" `0.0.0.0`. It's possible your IP host is incorrect. That address is only available to be bound to and listened from.

**Comment by emmacasolin** [comment]
> This log messages only happen in the background:
> 
> ```
> WARN:ConnectionForward 0.0.0.0:50690:Forward Error: ErrorConnectionEndTimeout
> ERROR:ForwardProxy:Failed CONNECT to 0.0.0.0:39365 - ErrorConnectionStart: UTP_ECONNRESET
> ERROR:grpc:Failed to connect to 0.0.0.0:39365/?nodeId=vdl79qbko2jm7ajhs081d1quk50scbk61apkdorhj9i6mdu425j9g through proxy 127.0.0.1:33071 with status 502
> ```
> 
> The `ERROR:grpc` occurs whenever something triggers the underlying GRPC client to connect to the proxy and that there's a failure from the other side. 502 means bad gateway, I put 502 code into the `ForwardProxy` to indicate this.
> 
> So it's ultimately connected to the `ERROR:ForwardProxy:Failed CONNECT to 0.0.0.0:39365 - ErrorConnectionStart: UTP_ECONNRESET`, they are always together.
> 
> And that means a connection request from forward proxy failed because the UTP connection has been reset.
> 
> Perhaps something is retrying the connection request? Where can you reproduce it?

> @emmacasolin seems like having a uniqueness constraint on the discovery queue DB would be helpful. This can also be achieved by our indexing issue on js-db.

I think the retrying was coming from the linked nodes being added back into the discovery queue multiple times, which I've now fixed by checking if a vertex is already in the queue before pushing it (inside the `pushKeyToDiscoveryQueue()` method). But once we've handled the indexing issue then this check can be removed.

After making this change all of the errors from before are gone, however I'm still occasionally getting these errors:
```
  console.error
    ErrorGRPCClientCall: 14 UNAVAILABLE: Connection dropped
        at toError (/home/emma/Projects/js-polykey/src/grpc/utils/utils.ts:190:16)
        at Object.callback (/home/emma/Projects/js-polykey/src/grpc/utils/utils.ts:219:17)
        at Object.onReceiveStatus (/home/emma/Projects/js-polykey/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at /home/emma/Projects/js-polykey/node_modules/@grpc/grpc-js/src/call-stream.ts:170:27
        at Object.onReceiveStatus (/home/emma/Projects/js-polykey/src/grpc/utils/FlowCountInterceptor.ts:57:13)
        at InterceptingListenerImpl.onReceiveStatus (/home/emma/Projects/js-polykey/node_modules/@grpc/grpc-js/src/call-stream.ts:166:19)
        at Object.onReceiveStatus (/home/emma/Projects/js-polykey/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/home/emma/Projects/js-polykey/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /home/emma/Projects/js-polykey/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (internal/process/task_queues.js:77:11)

      at process.uncaught (node_modules/jest-jasmine2/build/jasmine/Env.js:249:21)

WARN:ConnectionReverse 127.0.0.1:46442:Server Error: ErrorConnectionEndTimeout
(node:344161) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
    at handledRejection (internal/process/promises.js:140:23)
    at promiseRejectHandler (internal/process/promises.js:102:7)
    at Object.stop (/home/emma/Projects/js-polykey/src/discovery/Discovery.ts:166:16)
    at Object.stop (/home/emma/Projects/js-polykey/node_modules/@matrixai/async-init/src/CreateDestroyStartStop.ts:130:22)
    at Object.stop (/home/emma/Projects/js-polykey/src/PolykeyAgent.ts:675:5)
    at Object.stop (/home/emma/Projects/js-polykey/node_modules/@matrixai/async-init/src/CreateDestroyStartStop.ts:130:22)
    at Object.<anonymous> (/home/emma/Projects/js-polykey/tests/bin/identities/discoverGet.test.ts:107:5)
```

I'm not sure if this is still related to `requestChainData` or if this is something else.

**Comment by emmacasolin** [comment]
> BTW this seems wrong.
> 
> ```
> 0.0.0.0:39365
> ```
> 
> You cannot "connect to" `0.0.0.0`. It's possible your IP host is incorrect. That address is only available to be bound to and listened from.

This output is from a bin test where I'm not manually setting any of the values for hosts/ports - is it perhaps taking a default value from somewhere?

**Comment by CMCDragonkai** [comment]
Can you start `console.log` where those values are propagated from. Because it should not be saying `0.0.0.0`. We in fact have a test for this asserting that using `0.0.0.0` should result in an exception.

**Comment by CMCDragonkai** [comment]
BTW, any mention of `console.error` is incorrect too. Did you make sure to set the proper stream handler in the logger when used in tests.

```
  console.error
    ErrorGRPCClientCall: 14 UNAVAILABLE: Connection dropped
        at toError (/home/emma/Projects/js-polykey/src/grpc/utils/utils.ts:190:16)
        at Object.callback (/home/emma/Projects/js-polykey/src/grpc/utils/utils.ts:219:17)
        at Object.onReceiveStatus (/home/emma/Projects/js-polykey/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at /home/emma/Projects/js-polykey/node_modules/@grpc/grpc-js/src/call-stream.ts:170:27
        at Object.onReceiveStatus (/home/emma/Projects/js-polykey/src/grpc/utils/FlowCountInterceptor.ts:57:13)
        at InterceptingListenerImpl.onReceiveStatus (/home/emma/Projects/js-polykey/node_modules/@grpc/grpc-js/src/call-stream.ts:166:19)
        at Object.onReceiveStatus (/home/emma/Projects/js-polykey/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/home/emma/Projects/js-polykey/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /home/emma/Projects/js-polykey/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (internal/process/task_queues.js:77:11)

      at process.uncaught (node_modules/jest-jasmine2/build/jasmine/Env.js:249:21)
```

**Comment by CMCDragonkai** [comment]
@tegefaulkes shouldn't there be proper descriptions for `ErrorNodeConnectionTimeout`?

```
"ErrorNodeConnectionTimeout: 
        at Function.createNodeConnection (/home/emma/Projects/js-polykey/src/nodes/NodeConnection.ts:110:23)
        at Object.establishNodeConnection (/home/emma/Projects/js-polykey/src/nodes/NodeConnectionManager.ts:241:28)
        at /home/emma/Projects/js-polykey/src/nodes/NodeConnectionManager.ts:191:24
        at RWLock.withWrite (/home/emma/Projects/js-polykey/src/utils/locks.ts:34:20)
        at Object.createConnection (/home/emma/Projects/js-polykey/src/nodes/NodeConnectionManager.ts:183:20)
        at /home/emma/Projects/js-polykey/src/nodes/NodeConnectionManager.ts:99:33
        at withF (/home/emma/Projects/js-polykey/src/utils/context.ts:12:41)
        at Object.withConnF (/home/emma/Projects/js-polykey/src/nodes/NodeConnectionManager.ts:123:20)
        at NodeManager.requestChainData (/home/emma/Projects/js-polykey/src/nodes/NodeManager.ts:130:36)
        at Object.setupDiscoveryQueue (/home/emma/Projects/js-polykey/src/discovery/Discovery.ts:168:51) {
      description: 'Polykey error',
      exitCode: 69,
      data: {}
    }"
```

And how is this related to:

```
ErrorConnectionTimeout
ErrorConnectionEndTimeout
ErrorConnectionStartTimeout
ErrorConnectionComposeTimeout
```

All of these timeouts could occur during the start of the connection and subsequently while the connection is in operation.

**Comment by emmacasolin** [comment]
> Can you start `console.log` where those values are propagated from. Because it should not be saying `0.0.0.0`. We in fact have a test for this asserting that using `0.0.0.0` should result in an exception.

Yeah I can do that. These errors aren't popping up anymore after fixing the issue with doubles in the queue:
```
ERROR:ForwardProxy:Failed CONNECT to 0.0.0.0:39365 - ErrorConnectionStart: UTP_ECONNRESET
ERROR:grpc:Failed to connect to 0.0.0.0:39365/?nodeId=vdl79qbko2jm7ajhs081d1quk50scbk61apkdorhj9i6mdu425j9g through proxy 127.0.0.1:33071 with status 502
```

However this one still is:
```
WARN:ConnectionForward 0.0.0.0:35724:Client Error: ErrorConnectionEndTimeout
```

Is `0.0.0.0` incorrect here too?

**Comment by CMCDragonkai** [comment]
Yes, any connection **to** `0.0.0.0` is wrong.

**Comment by emmacasolin** [comment]
> BTW, any mention of `console.error` is incorrect too. Did you make sure to set the proper stream handler in the logger when used in tests.
> 
> ```
>   console.error
>     ErrorGRPCClientCall: 14 UNAVAILABLE: Connection dropped
>         at toError (/home/emma/Projects/js-polykey/src/grpc/utils/utils.ts:190:16)
>         at Object.callback (/home/emma/Projects/js-polykey/src/grpc/utils/utils.ts:219:17)
>         at Object.onReceiveStatus (/home/emma/Projects/js-polykey/node_modules/@grpc/grpc-js/src/client.ts:338:26)
>         at /home/emma/Projects/js-polykey/node_modules/@grpc/grpc-js/src/call-stream.ts:170:27
>         at Object.onReceiveStatus (/home/emma/Projects/js-polykey/src/grpc/utils/FlowCountInterceptor.ts:57:13)
>         at InterceptingListenerImpl.onReceiveStatus (/home/emma/Projects/js-polykey/node_modules/@grpc/grpc-js/src/call-stream.ts:166:19)
>         at Object.onReceiveStatus (/home/emma/Projects/js-polykey/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
>         at Object.onReceiveStatus (/home/emma/Projects/js-polykey/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
>         at /home/emma/Projects/js-polykey/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
>         at processTicksAndRejections (internal/process/task_queues.js:77:11)
> 
>       at process.uncaught (node_modules/jest-jasmine2/build/jasmine/Env.js:249:21)
> ```

I'm setting up the logger like this in all the tests:
```ts
import Logger, { LogLevel, StreamHandler } from '@matrixai/logger';

const logger = new Logger('discover/get test', LogLevel.WARN, [
  new StreamHandler(),
]);
```

**Comment by CMCDragonkai** [comment]
But `console.error` should not appear. That means one the log messages is routing to the default console handler. You can see this occur by applying the debugger and stepping through to the logger. But fix one error at a time to avoid interference.

**Comment by emmacasolin** [comment]
I thought that the errors had been resolved after the fix for doubles in the discovery queue was added, however it turns out that wasn't the case. Here is a complete output for a run of the test where these errors are appearing, with a `console.log` to show when we start discovering the next vertex in the discovery queue each time:

<details>

```
INFO:discover/get test:Creating PolykeyAgent
INFO:discover/get test:Setting umask to 077
INFO:discover/get test:Setting node path to /tmp/polykey-test-vgrfqL/polykey
INFO:Status:Starting Status
INFO:Status:Writing Status to /tmp/polykey-test-vgrfqL/polykey/status.json
INFO:Status:Status is STARTING
INFO:Schema:Creating Schema
INFO:Schema:Starting Schema
INFO:Schema:Setting state path to /tmp/polykey-test-vgrfqL/polykey/state
INFO:Schema:Started Schema
INFO:Schema:Created Schema
INFO:KeyManager:Creating KeyManager
INFO:KeyManager:Setting keys path to /tmp/polykey-test-vgrfqL/polykey/state/keys
INFO:KeyManager:Starting KeyManager
INFO:KeyManager:Checking /tmp/polykey-test-vgrfqL/polykey/state/keys/root.pub and /tmp/polykey-test-vgrfqL/polykey/state/keys/root.key
INFO:KeyManager:Generating root key pair
INFO:KeyManager:Writing /tmp/polykey-test-vgrfqL/polykey/state/keys/root.pub and /tmp/polykey-test-vgrfqL/polykey/state/keys/root.key
INFO:KeyManager:Checking /tmp/polykey-test-vgrfqL/polykey/state/keys/root.crt
INFO:KeyManager:Generating root certificate
INFO:KeyManager:Writing /tmp/polykey-test-vgrfqL/polykey/state/keys/root.crt
INFO:KeyManager:Checking /tmp/polykey-test-vgrfqL/polykey/state/keys/db.key
INFO:KeyManager:Generating keys db key
INFO:KeyManager:Writing /tmp/polykey-test-vgrfqL/polykey/state/keys/db.key
INFO:KeyManager:Checking /tmp/polykey-test-vgrfqL/polykey/state/keys/vault.key
INFO:KeyManager:Generating keys db key
INFO:KeyManager:Writing /tmp/polykey-test-vgrfqL/polykey/state/keys/vault.key
INFO:KeyManager:Started KeyManager
INFO:KeyManager:Created KeyManager
INFO:DB:Creating DB
INFO:DB:Starting DB
INFO:DB:Setting DB path to /tmp/polykey-test-vgrfqL/polykey/state/db
INFO:DB:Started DB
INFO:DB:Created DB
INFO:IdentitiesManager:Creating IdentitiesManager
INFO:IdentitiesManager:Starting IdentitiesManager
INFO:IdentitiesManager:Started IdentitiesManager
INFO:IdentitiesManager:Created IdentitiesManager
INFO:Sigchain:Creating Sigchain
INFO:Sigchain:Starting Sigchain
INFO:Sigchain:Started Sigchain
INFO:Sigchain:Created Sigchain
INFO:ACL:Creating ACL
INFO:ACL:Starting ACL
INFO:ACL:Started ACL
INFO:ACL:Created ACL
INFO:GestaltGraph:Creating GestaltGraph
INFO:GestaltGraph:Starting GestaltGraph
INFO:GestaltGraph:Started GestaltGraph
INFO:GestaltGraph:Created GestaltGraph
INFO:ForwardProxy:Creating Forward Proxy
INFO:ForwardProxy:Created Forward Proxy
INFO:ReverseProxy:Creating Reverse Proxy
INFO:ReverseProxy:Created Reverse Proxy
INFO:NodeGraph:Creating NodeGraph
INFO:NodeGraph:Starting NodeGraph
INFO:NodeGraph:Started NodeGraph
INFO:NodeGraph:Created NodeGraph
INFO:Discovery:Creating Discovery
INFO:Discovery:Starting Discovery
INFO:Discovery:Started Discovery
INFO:Discovery:Created Discovery
INFO:VaultManager:Creating VaultManager
INFO:VaultManager:Created VaultManager
INFO:VaultManager:Starting VaultManager
INFO:DB:Creating DB
INFO:DB:Starting DB
INFO:DB:Setting DB path to /tmp/polykey-test-vgrfqL/polykey/state/vaults
INFO:DB:Started DB
INFO:DB:Created DB
INFO:VaultManager:Starting EncryptedFS
INFO:VaultManager:Started EncryptedFS
INFO:VaultManager:Started VaultManager
INFO:NotificationsManager:Creating NotificationsManager
INFO:NotificationsManager:Starting NotificationsManager
INFO:NotificationsManager:Started NotificationsManager
INFO:NotificationsManager:Created NotificationsManager
INFO:SessionManager:Creating SessionManager
INFO:SessionManager:Starting SessionManager
INFO:SessionManager:Generating sessions key
INFO:SessionManager:Started SessionManager
INFO:SessionManager:Created SessionManager
INFO:discover/get test:Starting PolykeyAgent
INFO:GRPCServerClient:Starting GRPCServer on 127.0.0.1:0
INFO:GRPCServerClient:Started GRPCServer on 127.0.0.1:36331
INFO:GRPCServerAgent:Starting GRPCServer on 127.0.0.1:0
INFO:GRPCServerAgent:Started GRPCServer on 127.0.0.1:34049
INFO:ForwardProxy:Starting Forward Proxy from 127.0.0.1:0 to 0.0.0.0:0
INFO:ForwardProxy:Started Forward Proxy from 127.0.0.1:35533 to 0.0.0.0:44308
INFO:ReverseProxy:Starting Reverse Proxy from 0.0.0.0:0 to 127.0.0.1:34049
INFO:ReverseProxy:Started Reverse Proxy from 0.0.0.0:46842 to 127.0.0.1:34049
INFO:NodeConnectionManager:Starting NodeConnectionManager
INFO:NodeConnectionManager:Started NodeConnectionManager
INFO:Status:Finish Status STARTING
INFO:Status:Writing Status to /tmp/polykey-test-vgrfqL/polykey/status.json
INFO:Status:Status is LIVE
INFO:discover/get test:Started PolykeyAgent
INFO:discover/get test:Created PolykeyAgent
INFO:discover/get test:Creating PolykeyAgent
INFO:discover/get test:Setting umask to 077
INFO:discover/get test:Setting node path to /tmp/polykey-test-vgrfqL/nodeA
INFO:Status:Starting Status
INFO:Status:Writing Status to /tmp/polykey-test-vgrfqL/nodeA/status.json
INFO:Status:Status is STARTING
INFO:Schema:Creating Schema
INFO:Schema:Starting Schema
INFO:Schema:Setting state path to /tmp/polykey-test-vgrfqL/nodeA/state
INFO:Schema:Started Schema
INFO:Schema:Created Schema
INFO:KeyManager:Creating KeyManager
INFO:KeyManager:Setting keys path to /tmp/polykey-test-vgrfqL/nodeA/state/keys
INFO:KeyManager:Starting KeyManager
INFO:KeyManager:Checking /tmp/polykey-test-vgrfqL/nodeA/state/keys/root.pub and /tmp/polykey-test-vgrfqL/nodeA/state/keys/root.key
INFO:KeyManager:Generating root key pair
INFO:KeyManager:Writing /tmp/polykey-test-vgrfqL/nodeA/state/keys/root.pub and /tmp/polykey-test-vgrfqL/nodeA/state/keys/root.key
INFO:KeyManager:Checking /tmp/polykey-test-vgrfqL/nodeA/state/keys/root.crt
INFO:KeyManager:Generating root certificate
INFO:KeyManager:Writing /tmp/polykey-test-vgrfqL/nodeA/state/keys/root.crt
INFO:KeyManager:Checking /tmp/polykey-test-vgrfqL/nodeA/state/keys/db.key
INFO:KeyManager:Generating keys db key
INFO:KeyManager:Writing /tmp/polykey-test-vgrfqL/nodeA/state/keys/db.key
INFO:KeyManager:Checking /tmp/polykey-test-vgrfqL/nodeA/state/keys/vault.key
INFO:KeyManager:Generating keys db key
INFO:KeyManager:Writing /tmp/polykey-test-vgrfqL/nodeA/state/keys/vault.key
INFO:KeyManager:Started KeyManager
INFO:KeyManager:Created KeyManager
INFO:DB:Creating DB
INFO:DB:Starting DB
INFO:DB:Setting DB path to /tmp/polykey-test-vgrfqL/nodeA/state/db
INFO:DB:Started DB
INFO:DB:Created DB
INFO:IdentitiesManager:Creating IdentitiesManager
INFO:IdentitiesManager:Starting IdentitiesManager
INFO:IdentitiesManager:Started IdentitiesManager
INFO:IdentitiesManager:Created IdentitiesManager
INFO:Sigchain:Creating Sigchain
INFO:Sigchain:Starting Sigchain
INFO:Sigchain:Started Sigchain
INFO:Sigchain:Created Sigchain
INFO:ACL:Creating ACL
INFO:ACL:Starting ACL
INFO:ACL:Started ACL
INFO:ACL:Created ACL
INFO:GestaltGraph:Creating GestaltGraph
INFO:GestaltGraph:Starting GestaltGraph
INFO:GestaltGraph:Started GestaltGraph
INFO:GestaltGraph:Created GestaltGraph
INFO:ForwardProxy:Creating Forward Proxy
INFO:ForwardProxy:Created Forward Proxy
INFO:ReverseProxy:Creating Reverse Proxy
INFO:ReverseProxy:Created Reverse Proxy
INFO:NodeGraph:Creating NodeGraph
INFO:NodeGraph:Starting NodeGraph
INFO:NodeGraph:Started NodeGraph
INFO:NodeGraph:Created NodeGraph
INFO:Discovery:Creating Discovery
INFO:Discovery:Starting Discovery
INFO:Discovery:Started Discovery
INFO:Discovery:Created Discovery
INFO:VaultManager:Creating VaultManager
INFO:VaultManager:Created VaultManager
INFO:VaultManager:Starting VaultManager
INFO:DB:Creating DB
INFO:DB:Starting DB
INFO:DB:Setting DB path to /tmp/polykey-test-vgrfqL/nodeA/state/vaults
INFO:DB:Started DB
INFO:DB:Created DB
INFO:VaultManager:Starting EncryptedFS
INFO:VaultManager:Started EncryptedFS
INFO:VaultManager:Started VaultManager
INFO:NotificationsManager:Creating NotificationsManager
INFO:NotificationsManager:Starting NotificationsManager
INFO:NotificationsManager:Started NotificationsManager
INFO:NotificationsManager:Created NotificationsManager
INFO:SessionManager:Creating SessionManager
INFO:SessionManager:Starting SessionManager
INFO:SessionManager:Generating sessions key
INFO:SessionManager:Started SessionManager
INFO:SessionManager:Created SessionManager
INFO:discover/get test:Starting PolykeyAgent
INFO:GRPCServerClient:Starting GRPCServer on 127.0.0.1:0
INFO:GRPCServerClient:Started GRPCServer on 127.0.0.1:35829
INFO:GRPCServerAgent:Starting GRPCServer on 127.0.0.1:0
INFO:GRPCServerAgent:Started GRPCServer on 127.0.0.1:38717
INFO:ForwardProxy:Starting Forward Proxy from 127.0.0.1:0 to 0.0.0.0:0
INFO:ForwardProxy:Started Forward Proxy from 127.0.0.1:43525 to 0.0.0.0:48658
INFO:ReverseProxy:Starting Reverse Proxy from 0.0.0.0:0 to 127.0.0.1:38717
INFO:ReverseProxy:Started Reverse Proxy from 0.0.0.0:42167 to 127.0.0.1:38717
INFO:NodeConnectionManager:Starting NodeConnectionManager
INFO:NodeConnectionManager:Started NodeConnectionManager
INFO:Status:Finish Status STARTING
INFO:Status:Writing Status to /tmp/polykey-test-vgrfqL/nodeA/status.json
INFO:Status:Status is LIVE
INFO:discover/get test:Started PolykeyAgent
INFO:discover/get test:Created PolykeyAgent
INFO:discover/get test:Creating PolykeyAgent
INFO:discover/get test:Setting umask to 077
INFO:discover/get test:Setting node path to /tmp/polykey-test-vgrfqL/nodeB
INFO:Status:Starting Status
INFO:Status:Writing Status to /tmp/polykey-test-vgrfqL/nodeB/status.json
INFO:Status:Status is STARTING
INFO:Schema:Creating Schema
INFO:Schema:Starting Schema
INFO:Schema:Setting state path to /tmp/polykey-test-vgrfqL/nodeB/state
INFO:Schema:Started Schema
INFO:Schema:Created Schema
INFO:KeyManager:Creating KeyManager
INFO:KeyManager:Setting keys path to /tmp/polykey-test-vgrfqL/nodeB/state/keys
INFO:KeyManager:Starting KeyManager
INFO:KeyManager:Checking /tmp/polykey-test-vgrfqL/nodeB/state/keys/root.pub and /tmp/polykey-test-vgrfqL/nodeB/state/keys/root.key
INFO:KeyManager:Generating root key pair
INFO:KeyManager:Writing /tmp/polykey-test-vgrfqL/nodeB/state/keys/root.pub and /tmp/polykey-test-vgrfqL/nodeB/state/keys/root.key
INFO:KeyManager:Checking /tmp/polykey-test-vgrfqL/nodeB/state/keys/root.crt
INFO:KeyManager:Generating root certificate
INFO:KeyManager:Writing /tmp/polykey-test-vgrfqL/nodeB/state/keys/root.crt
INFO:KeyManager:Checking /tmp/polykey-test-vgrfqL/nodeB/state/keys/db.key
INFO:KeyManager:Generating keys db key
INFO:KeyManager:Writing /tmp/polykey-test-vgrfqL/nodeB/state/keys/db.key
INFO:KeyManager:Checking /tmp/polykey-test-vgrfqL/nodeB/state/keys/vault.key
INFO:KeyManager:Generating keys db key
INFO:KeyManager:Writing /tmp/polykey-test-vgrfqL/nodeB/state/keys/vault.key
INFO:KeyManager:Started KeyManager
INFO:KeyManager:Created KeyManager
INFO:DB:Creating DB
INFO:DB:Starting DB
INFO:DB:Setting DB path to /tmp/polykey-test-vgrfqL/nodeB/state/db
INFO:DB:Started DB
INFO:DB:Created DB
INFO:IdentitiesManager:Creating IdentitiesManager
INFO:IdentitiesManager:Starting IdentitiesManager
INFO:IdentitiesManager:Started IdentitiesManager
INFO:IdentitiesManager:Created IdentitiesManager
INFO:Sigchain:Creating Sigchain
INFO:Sigchain:Starting Sigchain
INFO:Sigchain:Started Sigchain
INFO:Sigchain:Created Sigchain
INFO:ACL:Creating ACL
INFO:ACL:Starting ACL
INFO:ACL:Started ACL
INFO:ACL:Created ACL
INFO:GestaltGraph:Creating GestaltGraph
INFO:GestaltGraph:Starting GestaltGraph
INFO:GestaltGraph:Started GestaltGraph
INFO:GestaltGraph:Created GestaltGraph
INFO:ForwardProxy:Creating Forward Proxy
INFO:ForwardProxy:Created Forward Proxy
INFO:ReverseProxy:Creating Reverse Proxy
INFO:ReverseProxy:Created Reverse Proxy
INFO:NodeGraph:Creating NodeGraph
INFO:NodeGraph:Starting NodeGraph
INFO:NodeGraph:Started NodeGraph
INFO:NodeGraph:Created NodeGraph
INFO:Discovery:Creating Discovery
INFO:Discovery:Starting Discovery
INFO:Discovery:Started Discovery
INFO:Discovery:Created Discovery
INFO:VaultManager:Creating VaultManager
INFO:VaultManager:Created VaultManager
INFO:VaultManager:Starting VaultManager
INFO:DB:Creating DB
INFO:DB:Starting DB
INFO:DB:Setting DB path to /tmp/polykey-test-vgrfqL/nodeB/state/vaults
INFO:DB:Started DB
INFO:DB:Created DB
INFO:VaultManager:Starting EncryptedFS
INFO:VaultManager:Started EncryptedFS
INFO:VaultManager:Started VaultManager
INFO:NotificationsManager:Creating NotificationsManager
INFO:NotificationsManager:Starting NotificationsManager
INFO:NotificationsManager:Started NotificationsManager
INFO:NotificationsManager:Created NotificationsManager
INFO:SessionManager:Creating SessionManager
INFO:SessionManager:Starting SessionManager
INFO:SessionManager:Generating sessions key
INFO:SessionManager:Started SessionManager
INFO:SessionManager:Created SessionManager
INFO:discover/get test:Starting PolykeyAgent
INFO:GRPCServerClient:Starting GRPCServer on 127.0.0.1:0
INFO:GRPCServerClient:Started GRPCServer on 127.0.0.1:39099
INFO:GRPCServerAgent:Starting GRPCServer on 127.0.0.1:0
INFO:GRPCServerAgent:Started GRPCServer on 127.0.0.1:41355
INFO:ForwardProxy:Starting Forward Proxy from 127.0.0.1:0 to 0.0.0.0:0
INFO:ForwardProxy:Started Forward Proxy from 127.0.0.1:35481 to 0.0.0.0:53365
INFO:ReverseProxy:Starting Reverse Proxy from 0.0.0.0:0 to 127.0.0.1:41355
INFO:ReverseProxy:Started Reverse Proxy from 0.0.0.0:56375 to 127.0.0.1:41355
INFO:NodeConnectionManager:Starting NodeConnectionManager
INFO:NodeConnectionManager:Started NodeConnectionManager
INFO:Status:Finish Status STARTING
INFO:Status:Writing Status to /tmp/polykey-test-vgrfqL/nodeB/status.json
INFO:Status:Status is LIVE
INFO:discover/get test:Started PolykeyAgent
INFO:discover/get test:Created PolykeyAgent
INFO:NodeConnectionManager:Creating connection to vhru3cd29ktp51ee74cauqpqncm8546pnagumvgr98pmc3mud915g
INFO:NodeConnectionManager:no existing entry: creating connection to vhru3cd29ktp51ee74cauqpqncm8546pnagumvgr98pmc3mud915g
INFO:0.0.0.0:56375:Creating NodeConnection
INFO:clientFactory:Creating GRPCClientAgent connecting to 0.0.0.0:56375
INFO:ForwardProxy:Handling CONNECT to 0.0.0.0:56375
INFO:ConnectionForward 0.0.0.0:56375:Starting Connection Forward
INFO:ReverseProxy:Handling connection from 127.0.0.1:48658
INFO:ConnectionReverse 127.0.0.1:48658:Starting Connection Reverse
INFO:ConnectionReverse 127.0.0.1:48658:Started Connection Reverse
INFO:ConnectionReverse 127.0.0.1:48658:Composing Connection Reverse
INFO:ConnectionForward 0.0.0.0:56375:Started Connection Forward
INFO:ConnectionForward 0.0.0.0:56375:Composing Connection Forward
INFO:ConnectionForward 0.0.0.0:56375:Composed Connection Forward
INFO:ForwardProxy:Handled CONNECT to 0.0.0.0:56375
INFO:clientFactory:Created GRPCClientAgent connecting to 0.0.0.0:56375
INFO:0.0.0.0:56375:Created NodeConnection
INFO:ConnectionReverse 127.0.0.1:48658:Composed Connection Reverse
INFO:ReverseProxy:Handled connection from 127.0.0.1:48658
INFO:NodeConnectionManager:Creating connection to vb6eqvrbadb500srcff1k5q1o3kkhtcnabusku2pec4sntkdk95kg
INFO:NodeConnectionManager:no existing entry: creating connection to vb6eqvrbadb500srcff1k5q1o3kkhtcnabusku2pec4sntkdk95kg
INFO:0.0.0.0:42167:Creating NodeConnection
INFO:clientFactory:Creating GRPCClientAgent connecting to 0.0.0.0:42167
INFO:ForwardProxy:Handling CONNECT to 0.0.0.0:42167
INFO:ConnectionForward 0.0.0.0:42167:Starting Connection Forward
INFO:ReverseProxy:Handling connection from 127.0.0.1:53365
INFO:ConnectionReverse 127.0.0.1:53365:Starting Connection Reverse
INFO:ConnectionReverse 127.0.0.1:53365:Started Connection Reverse
INFO:ConnectionReverse 127.0.0.1:53365:Composing Connection Reverse
INFO:ConnectionForward 0.0.0.0:42167:Started Connection Forward
INFO:ConnectionForward 0.0.0.0:42167:Composing Connection Forward
INFO:ConnectionForward 0.0.0.0:42167:Composed Connection Forward
INFO:ForwardProxy:Handled CONNECT to 0.0.0.0:42167
INFO:clientFactory:Created GRPCClientAgent connecting to 0.0.0.0:42167
INFO:0.0.0.0:42167:Created NodeConnection
INFO:ConnectionReverse 127.0.0.1:53365:Composed Connection Reverse
INFO:ReverseProxy:Handled connection from 127.0.0.1:53365
INFO:0.0.0.0:42167:Creating NodeConnection
INFO:clientFactory:Creating GRPCClientAgent connecting to 0.0.0.0:42167
INFO:ForwardProxy:Handling CONNECT to 0.0.0.0:42167
INFO:ConnectionForward 0.0.0.0:42167:Starting Connection Forward
INFO:ReverseProxy:Handling connection from 127.0.0.1:44308
INFO:ConnectionReverse 127.0.0.1:44308:Starting Connection Reverse
INFO:ConnectionReverse 127.0.0.1:44308:Started Connection Reverse
INFO:ConnectionReverse 127.0.0.1:44308:Composing Connection Reverse
INFO:ConnectionForward 0.0.0.0:42167:Started Connection Forward
INFO:ConnectionForward 0.0.0.0:42167:Composing Connection Forward
INFO:ConnectionForward 0.0.0.0:42167:Composed Connection Forward
INFO:ForwardProxy:Handled CONNECT to 0.0.0.0:42167
INFO:clientFactory:Created GRPCClientAgent connecting to 0.0.0.0:42167
INFO:0.0.0.0:42167:Created NodeConnection
INFO:ConnectionReverse 127.0.0.1:44308:Composed Connection Reverse
INFO:ReverseProxy:Handled connection from 127.0.0.1:44308
INFO:NodeConnectionManager:Creating connection to vhru3cd29ktp51ee74cauqpqncm8546pnagumvgr98pmc3mud915g
INFO:NodeConnectionManager:no existing entry: creating connection to vhru3cd29ktp51ee74cauqpqncm8546pnagumvgr98pmc3mud915g
INFO:NodeConnectionManager:Creating connection to vb6eqvrbadb500srcff1k5q1o3kkhtcnabusku2pec4sntkdk95kg
INFO:NodeConnectionManager:Creating connection to vb6eqvrbadb500srcff1k5q1o3kkhtcnabusku2pec4sntkdk95kg
INFO:0.0.0.0:56375:Creating NodeConnection
INFO:clientFactory:Creating GRPCClientAgent connecting to 0.0.0.0:56375
INFO:ForwardProxy:Handling CONNECT to 0.0.0.0:56375
INFO:ConnectionForward 0.0.0.0:56375:Starting Connection Forward
INFO:ReverseProxy:Handling connection from 127.0.0.1:44308
INFO:ConnectionReverse 127.0.0.1:44308:Starting Connection Reverse
INFO:ConnectionReverse 127.0.0.1:44308:Started Connection Reverse
INFO:ConnectionReverse 127.0.0.1:44308:Composing Connection Reverse
INFO:ConnectionForward 0.0.0.0:56375:Started Connection Forward
INFO:ConnectionForward 0.0.0.0:56375:Composing Connection Forward
INFO:ConnectionForward 0.0.0.0:56375:Composed Connection Forward
INFO:ForwardProxy:Handled CONNECT to 0.0.0.0:56375
INFO:clientFactory:Created GRPCClientAgent connecting to 0.0.0.0:56375
INFO:0.0.0.0:56375:Created NodeConnection
INFO:NodeConnectionManager:Creating connection to vhru3cd29ktp51ee74cauqpqncm8546pnagumvgr98pmc3mud915g
INFO:ConnectionReverse 127.0.0.1:44308:Composed Connection Reverse
INFO:ReverseProxy:Handled connection from 127.0.0.1:44308
INFO:NodeConnectionManager:Creating connection to vb6eqvrbadb500srcff1k5q1o3kkhtcnabusku2pec4sntkdk95kg
INFO:NodeConnectionManager:Creating connection to vb6eqvrbadb500srcff1k5q1o3kkhtcnabusku2pec4sntkdk95kg
INFO:NodeConnectionManager:Creating connection to vhru3cd29ktp51ee74cauqpqncm8546pnagumvgr98pmc3mud915g
  console.log
    discovering {"nodeId":"vhru3cd29ktp51ee74cauqpqncm8546pnagumvgr98pmc3mud915g","type":"node"}

      at Object.setupDiscoveryQueue (src/discovery/Discovery.ts:218:19)

INFO:discover/get test:Stopping PolykeyAgent
INFO:Status:Begin Status STOPPING
INFO:Status:Writing Status to /tmp/polykey-test-vgrfqL/nodeB/status.json
INFO:Status:Status is STOPPING
INFO:SessionManager:Stopping SessionManager
INFO:SessionManager:Stopped SessionManager
INFO:NotificationsManager:Stopping NotificationsManager
INFO:NotificationsManager:Stopped NotificationsManager
INFO:VaultManager:Stopping VaultManager
INFO:VaultManager:Stopping EncryptedFS
INFO:DB:Stopping DB
INFO:DB:Stopped DB
INFO:VaultManager:Stopped EncryptedFS
INFO:VaultManager:Stopped VaultManager
INFO:Discovery:Stopping Discovery
INFO:Discovery:Stopped Discovery
INFO:NodeConnectionManager:Stopping NodeConnectionManager
INFO:0.0.0.0:42167:Destroying NodeConnection
INFO:clientFactory:Destroying GRPCClientAgent connected to 0.0.0.0:42167
INFO:clientFactory:Destroyed GRPCClientAgent connected to 0.0.0.0:42167
INFO:0.0.0.0:42167:Destroyed NodeConnection
INFO:NodeConnectionManager:Stopped NodeConnectionManager
INFO:NodeGraph:Stopping NodeGraph
INFO:NodeGraph:Stopped NodeGraph
INFO:ReverseProxy:Stopping Reverse Proxy
INFO:ConnectionReverse 127.0.0.1:48658:Stopping Connection Reverse
INFO:ConnectionReverse 127.0.0.1:44308:Stopping Connection Reverse
INFO:ConnectionForward 0.0.0.0:56375:Stopping Connection Forward
INFO:ConnectionForward 0.0.0.0:56375:Stopping Connection Forward
INFO:ConnectionForward 0.0.0.0:42167:Stopping Connection Forward
INFO:NodeConnectionManager:Creating connection to vb6eqvrbadb500srcff1k5q1o3kkhtcnabusku2pec4sntkdk95kg
INFO:NodeConnectionManager:Creating connection to vb6eqvrbadb500srcff1k5q1o3kkhtcnabusku2pec4sntkdk95kg
INFO:ConnectionReverse 127.0.0.1:48658:Stopped Connection Reverse
INFO:ConnectionReverse 127.0.0.1:44308:Stopped Connection Reverse
INFO:ReverseProxy:Stopped Reverse Proxy
INFO:ForwardProxy:Stopping Forward Proxy Server
INFO:ConnectionReverse 127.0.0.1:53365:Stopping Connection Reverse
INFO:clientFactory:Destroying GRPCClientAgent connected to 0.0.0.0:56375
INFO:0.0.0.0:56375:Destroying NodeConnection
INFO:0.0.0.0:56375:Destroyed NodeConnection
INFO:clientFactory:Destroyed GRPCClientAgent connected to 0.0.0.0:56375
INFO:clientFactory:Destroying GRPCClientAgent connected to 0.0.0.0:56375
INFO:0.0.0.0:56375:Destroying NodeConnection
INFO:0.0.0.0:56375:Destroyed NodeConnection
INFO:clientFactory:Destroyed GRPCClientAgent connected to 0.0.0.0:56375
INFO:ConnectionReverse 127.0.0.1:53365:Stopped Connection Reverse
INFO:ConnectionForward 0.0.0.0:56375:Stopped Connection Forward
INFO:ConnectionForward 0.0.0.0:56375:Stopped Connection Forward
INFO:NodeConnectionManager:Creating connection to vhru3cd29ktp51ee74cauqpqncm8546pnagumvgr98pmc3mud915g
INFO:NodeConnectionManager:Creating connection to vb6eqvrbadb500srcff1k5q1o3kkhtcnabusku2pec4sntkdk95kg
INFO:NodeConnectionManager:Creating connection to vhru3cd29ktp51ee74cauqpqncm8546pnagumvgr98pmc3mud915g
INFO:NodeConnectionManager:existing lock: creating connection to vhru3cd29ktp51ee74cauqpqncm8546pnagumvgr98pmc3mud915g
INFO:0.0.0.0:56375:Creating NodeConnection
INFO:clientFactory:Creating GRPCClientAgent connecting to 0.0.0.0:56375
  console.log
    discovering {"nodeId":"vb6eqvrbadb500srcff1k5q1o3kkhtcnabusku2pec4sntkdk95kg","type":"node"}

      at Object.setupDiscoveryQueue (src/discovery/Discovery.ts:218:19)

INFO:ForwardProxy:Handling CONNECT to 0.0.0.0:56375
INFO:ConnectionForward 0.0.0.0:56375:Starting Connection Forward
WARN:ConnectionForward 0.0.0.0:42167:Forward Error: ErrorConnectionEndTimeout
INFO:ConnectionForward 0.0.0.0:42167:Stopped Connection Forward
INFO:ForwardProxy:Stopped Forward Proxy Server
INFO:GRPCServerAgent:Stopping GRPCServer
INFO:GRPCServerAgent:Stopped GRPCServer
INFO:GRPCServerClient:Stopping GRPCServer
INFO:GRPCServerClient:Stopped GRPCServer
INFO:GestaltGraph:Stopping GestaltGraph
INFO:GestaltGraph:Stopped GestaltGraph
INFO:ACL:Stopping ACL
INFO:ACL:Stopped ACL
INFO:Sigchain:Stopping Sigchain
INFO:Sigchain:Stopped Sigchain
INFO:IdentitiesManager:Stopping IdentitiesManager
INFO:IdentitiesManager:Stopped IdentitiesManager
INFO:DB:Stopping DB
INFO:DB:Stopped DB
INFO:KeyManager:Stopping KeyManager
INFO:KeyManager:Stopped KeyManager
INFO:Schema:Stopping Schema
INFO:Schema:Stopped Schema
INFO:Status:Stopping Status
INFO:Status:Writing Status to /tmp/polykey-test-vgrfqL/nodeB/status.json
INFO:Status:Status is DEAD
INFO:discover/get test:Stopped PolykeyAgent
INFO:discover/get test:Stopping PolykeyAgent
INFO:Status:Begin Status STOPPING
INFO:Status:Writing Status to /tmp/polykey-test-vgrfqL/nodeA/status.json
INFO:Status:Status is STOPPING
INFO:SessionManager:Stopping SessionManager
INFO:SessionManager:Stopped SessionManager
INFO:NotificationsManager:Stopping NotificationsManager
INFO:NotificationsManager:Stopped NotificationsManager
INFO:VaultManager:Stopping VaultManager
INFO:VaultManager:Stopping EncryptedFS
INFO:DB:Stopping DB
INFO:DB:Stopped DB
INFO:VaultManager:Stopped EncryptedFS
INFO:VaultManager:Stopped VaultManager
INFO:Discovery:Stopping Discovery
INFO:Discovery:Stopped Discovery
INFO:NodeConnectionManager:Stopping NodeConnectionManager
INFO:NodeConnectionManager:Stopped NodeConnectionManager
INFO:NodeGraph:Stopping NodeGraph
INFO:NodeGraph:Stopped NodeGraph
INFO:ReverseProxy:Stopping Reverse Proxy
INFO:ConnectionReverse 127.0.0.1:44308:Stopping Connection Reverse
INFO:ConnectionForward 0.0.0.0:42167:Stopping Connection Forward
INFO:ConnectionReverse 127.0.0.1:44308:Stopped Connection Reverse
INFO:ReverseProxy:Stopped Reverse Proxy
INFO:ForwardProxy:Stopping Forward Proxy Server
INFO:ForwardProxy:Stopped Forward Proxy Server
INFO:GRPCServerAgent:Stopping GRPCServer
INFO:GRPCServerAgent:Stopped GRPCServer
INFO:GRPCServerClient:Stopping GRPCServer
INFO:GRPCServerClient:Stopped GRPCServer
INFO:GestaltGraph:Stopping GestaltGraph
INFO:GestaltGraph:Stopped GestaltGraph
INFO:ACL:Stopping ACL
INFO:ACL:Stopped ACL
INFO:Sigchain:Stopping Sigchain
INFO:Sigchain:Stopped Sigchain
INFO:IdentitiesManager:Stopping IdentitiesManager
INFO:IdentitiesManager:Stopped IdentitiesManager
INFO:DB:Stopping DB
INFO:clientFactory:Destroying GRPCClientAgent connected to 0.0.0.0:42167
INFO:0.0.0.0:42167:Destroying NodeConnection
INFO:0.0.0.0:42167:Destroyed NodeConnection
INFO:clientFactory:Destroyed GRPCClientAgent connected to 0.0.0.0:42167
INFO:ConnectionForward 0.0.0.0:42167:Stopped Connection Forward
INFO:DB:Stopped DB
INFO:KeyManager:Stopping KeyManager
INFO:KeyManager:Stopped KeyManager
INFO:Schema:Stopping Schema
INFO:Schema:Stopped Schema
INFO:Status:Stopping Status
INFO:Status:Writing Status to /tmp/polykey-test-vgrfqL/nodeA/status.json
INFO:Status:Status is DEAD
INFO:discover/get test:Stopped PolykeyAgent
INFO:discover/get test:Stopping PolykeyAgent
INFO:Status:Begin Status STOPPING
INFO:Status:Writing Status to /tmp/polykey-test-vgrfqL/polykey/status.json
INFO:Status:Status is STOPPING
INFO:SessionManager:Stopping SessionManager
INFO:SessionManager:Stopped SessionManager
INFO:NotificationsManager:Stopping NotificationsManager
INFO:NotificationsManager:Stopped NotificationsManager
INFO:VaultManager:Stopping VaultManager
INFO:VaultManager:Stopping EncryptedFS
INFO:DB:Stopping DB
INFO:DB:Stopped DB
INFO:VaultManager:Stopped EncryptedFS
INFO:VaultManager:Stopped VaultManager
INFO:Discovery:Stopping Discovery
ERROR:ForwardProxy:Failed CONNECT to 0.0.0.0:56375 - ErrorConnectionStart: UTP_ECONNRESET
ERROR:grpc:Failed to connect to 0.0.0.0:56375/?nodeId=vhru3cd29ktp51ee74cauqpqncm8546pnagumvgr98pmc3mud915g through proxy 127.0.0.1:35533 with status 502
INFO:ForwardProxy:Handling CONNECT to 0.0.0.0:56375
INFO:ConnectionForward 0.0.0.0:56375:Starting Connection Forward
ERROR:ForwardProxy:Failed CONNECT to 0.0.0.0:56375 - ErrorConnectionStart: UTP_ECONNRESET
ERROR:grpc:Failed to connect to 0.0.0.0:56375/?nodeId=vhru3cd29ktp51ee74cauqpqncm8546pnagumvgr98pmc3mud915g through proxy 127.0.0.1:35533 with status 502
INFO:ForwardProxy:Handling CONNECT to 0.0.0.0:56375
INFO:ConnectionForward 0.0.0.0:56375:Starting Connection Forward
ERROR:ForwardProxy:Failed CONNECT to 0.0.0.0:56375 - ErrorConnectionStart: UTP_ECONNRESET
ERROR:grpc:Failed to connect to 0.0.0.0:56375/?nodeId=vhru3cd29ktp51ee74cauqpqncm8546pnagumvgr98pmc3mud915g through proxy 127.0.0.1:35533 with status 502
INFO:ForwardProxy:Handling CONNECT to 0.0.0.0:56375
INFO:ConnectionForward 0.0.0.0:56375:Starting Connection Forward
ERROR:ForwardProxy:Failed CONNECT to 0.0.0.0:56375 - ErrorConnectionStart: UTP_ECONNRESET
ERROR:grpc:Failed to connect to 0.0.0.0:56375/?nodeId=vhru3cd29ktp51ee74cauqpqncm8546pnagumvgr98pmc3mud915g through proxy 127.0.0.1:35533 with status 502
INFO:ForwardProxy:Handling CONNECT to 0.0.0.0:56375
INFO:ConnectionForward 0.0.0.0:56375:Starting Connection Forward
ERROR:ForwardProxy:Failed CONNECT to 0.0.0.0:56375 - ErrorConnectionStart: UTP_ECONNRESET
ERROR:grpc:Failed to connect to 0.0.0.0:56375/?nodeId=vhru3cd29ktp51ee74cauqpqncm8546pnagumvgr98pmc3mud915g through proxy 127.0.0.1:35533 with status 502
INFO:ForwardProxy:Handling CONNECT to 0.0.0.0:56375
INFO:ConnectionForward 0.0.0.0:56375:Starting Connection Forward
 PASS  tests/bin/identities/discoverGet.test.ts (58.742 s)
  discover/get
    ✓ discovers and gets gestalt by node (2559 ms)
    ○ skipped discovers and gets gestalt by identity
    ○ skipped should fail on invalid inputs

Test Suites: 1 passed, 1 total
Tests:       2 skipped, 1 passed, 3 total
Snapshots:   0 total
Time:        58.772 s
Ran all test suites matching /identities\/discover/i.
GLOBAL TEARDOWN
Destroying Global Data Dir: /tmp/polykey-test-global-vejNIN
INFO:0.0.0.0:56375:Destroying NodeConnection
INFO:0.0.0.0:56375:Destroyed NodeConnection
INFO:Discovery:Stopped Discovery
INFO:NodeConnectionManager:Stopping NodeConnectionManager
INFO:NodeConnectionManager:Stopped NodeConnectionManager
INFO:NodeGraph:Stopping NodeGraph
INFO:NodeGraph:Stopped NodeGraph
INFO:ReverseProxy:Stopping Reverse Proxy
INFO:ReverseProxy:Stopped Reverse Proxy
INFO:ForwardProxy:Stopping Forward Proxy Server
ERROR:ForwardProxy:Failed CONNECT to 0.0.0.0:56375 - ErrorConnectionStart: UTP_ECONNRESET
INFO:ForwardProxy:Stopped Forward Proxy Server
INFO:GRPCServerAgent:Stopping GRPCServer
INFO:GRPCServerAgent:Stopped GRPCServer
INFO:GRPCServerClient:Stopping GRPCServer
INFO:GRPCServerClient:Stopped GRPCServer
INFO:GestaltGraph:Stopping GestaltGraph
INFO:GestaltGraph:Stopped GestaltGraph
INFO:ACL:Stopping ACL
INFO:ACL:Stopped ACL
INFO:Sigchain:Stopping Sigchain
INFO:Sigchain:Stopped Sigchain
INFO:IdentitiesManager:Stopping IdentitiesManager
INFO:IdentitiesManager:Stopped IdentitiesManager
INFO:DB:Stopping DB
ERROR:grpc:Failed to connect to 0.0.0.0:56375/?nodeId=vhru3cd29ktp51ee74cauqpqncm8546pnagumvgr98pmc3mud915g through proxy 127.0.0.1:35533 with status 502
INFO:DB:Stopped DB
INFO:KeyManager:Stopping KeyManager
INFO:KeyManager:Stopped KeyManager
INFO:Schema:Stopping Schema
INFO:Schema:Stopped Schema
INFO:Status:Stopping Status
INFO:Status:Writing Status to /tmp/polykey-test-vgrfqL/polykey/status.json
INFO:Status:Status is DEAD
INFO:discover/get test:Stopped PolykeyAgent
```

</details>

The errors start when we try to stop the discovery domain, however we're not iterating through the queue at this point.

Additionally, it looks like the `0.0.0.0`s are coming from the setting of the ingress and egress hosts, which both default to that value.

**Comment by CMCDragonkai** [comment]
If you are contacting the local reverse proxy, even if you are binding to `0.0.0.0`, the connecting code must use `127.0.0.1`.

**Comment by CMCDragonkai** [comment]
1. Any agent being started for testing should be bound to `127.0.0.1`
2. Don't use any default network config in the tests, all network configuration must be explicit to avoid tests being broken by future config changes.
3. This goes for the global agent as well.
4. Agent network configuration is in `PolykeyAgent.start()` method.
5. On the client side, you can then target `127.0.0.1` either by setting `--client-host` or via the `--seed-nodes`
6. We might need to put in checks for `0.0.0.0` being incorrect earlier in whenever it's being used for connecting to another agent or from client to agent. It's a special wildcard address only valid for binding. Right now the network domain throws error if this is used when passing through the network. But this is something we can add to validation, however only when it is intended to be the target. Remember `--client-host` for `pk agent start` is not the target, but for other commands they are the target. This is something to be considered later.

**Comment by CMCDragonkai** [comment]
The `tests/utils.ts` should also be converted to using selective imports too.

**Comment by emmacasolin** [comment]
> 1. Any agent being started for testing should be bound to `127.0.0.1`
> 2. Don't use any default network config in the tests, all network configuration must be explicit to avoid tests being broken by future config changes.
> 3. This goes for the global agent as well.
> 4. Agent network configuration is in `PolykeyAgent.start()` method.
> 5. On the client side, you can then target `127.0.0.1` either by setting `--client-host` or via the `--seed-nodes`
> 6. We might need to put in checks for `0.0.0.0` being incorrect earlier in whenever it's being used for connecting to another agent or from client to agent. It's a special wildcard address only valid for binding. Right now the network domain throws error if this is used when passing through the network. But this is something we can add to validation, however only when it is intended to be the target. Remember `--client-host` for `pk agent start` is not the target, but for other commands they are the target. This is something to be considered later.

So is `clientHost` the only field of the `networkConfig` that needs to be set in tests? Or should they all have explicitly set values? And if so what should those values be?

**Comment by tegefaulkes** [comment]
Only the hosts. It's fine to have defaults for for port binds the port to a random number. we can easily get that when needed by using a relevant `getPort()` function EG. `fwdProxy.getEgressPort()` returns the port number it was actually bound to. The hosts are a special case since we can't get the actual host the port is listening on. so for example `fwdProxy.getEgressHost()` just returns what was set and not what it is actually listening on.

**Comment by CMCDragonkai** [comment]
Yea all `Xhost` needs to be set explicitly.

**Comment by emmacasolin** [comment]
The tests that setup an agent are now using this networkConfig:
```ts
networkConfig: {
  proxyHost: '127.0.0.1' as Host,
  egressHost: '127.0.0.1' as Host,
  ingressHost: '127.0.0.1' as Host,
  agentHost: '127.0.0.1' as Host,
  clientHost: '127.0.0.1' as Host,
},
```

We're no longer binding to `0.0.0.0` anywhere in the failing discovery test, however the same errors and warnings are still being displayed as before. Most of the errors seem to pop up when we try to stop the discovery domain.

**Comment by CMCDragonkai** [comment]
The `GRPCClient` when it executes `await waitForReady` will attempt to reconnect over and over until the `timeout` is expired. This is done by the upstream GRPC library. So if it is going over the proxy, it will attempt to connect over and over.

Before you stop the discovery domain, you want to ensure that all `NodeConnection`s which wraps `GRPCClient`, is actually destroying/cancelling their clients.

**Comment by CMCDragonkai** [comment]
What may be happening here is something like this:

```
                      ┌─────┐        ┌─────┐
                      │ N 1 │        │ N 2 │
                      └──┬──┘        └──┬──┘
  Discovery Queue        │              │
┌────────────────┐       │              │
│ T4  T3  T2  T1 ├─────► T1      PolykeyAgent.stop()
└────────────────┘       │              │
                         │              │
                         │              X
                   Discovery.stop()
                         │
                         │
                         │
                         T1 ───────────►
                         │      GRPCClient.createClient()
                         │          Retries for 20s
                         │
               ErrorNodeConnectionTimeout
                         │
                         │
                         │
             NodeConnectionManager.stop()
                         │
                         │
                         │
                  PolykeyAgent.stop()
```

1. When stopping the `Discovery`, you're still awaiting for the current task `T1` to finish.
2. We don't have the ability to abort currently asynchronous side-effectful tasks which is scheduled in MatrixAI/Polykey#297 
3. So you have to wait for this task to finish anyway
4. The task itself involves establishing a node connection to the remote agent `N 2`
5. `N 2` has already been shutdown and is no longer running
6. Therefore the connection timeout which is passed from `NodeConnectionManager` to `NodeConnection` to `GRPCClientAgent` to `GRPCClient` is what is going to determine how long to wait for connection readiness
7. The default timeout is set to 20s for `NodeConnectionManager`
8. You'll see retried attempts to connect through the proxy, now using `127.0.0.1` as the address which is correct
9. Then the `ErrorGRPCClientTimeout` should be thrown, which is then rethrown as `ErrorNodeConnectionTimeout`
10. You should get this exception on `withConnF` in `Discovery`

This is good exercise as this essentially is testing what happens when the remote node is shutdown first. And is what is going to happen if you fail to connect anyway. To have a happy case test, all you need to do is move the `N 2` shutdown to after you finish what you're doing with `N 1`. Then you shouldn't see any error log messages from the proxies.

However, we should still have a test case for this, as this is the expected behaviour when the remote agent is shutdown first.

Some things we should change here:

1. In our `Discovery`, the default timeout shouldn't be 20s, that's too long. You want to modify this timeout. The `withConnF` should be able to override this timeout, even if the class default is `20s`.
2. We need MatrixAI/Polykey#297 so we can actually stop the `T1` when we stop the discovery instead of waiting for it to finish. @emmacasolin make sure that if T1 finishes even after stopping, that `T1` is removed from the DB, so you don't redo the work.
3. We need MatrixAI/Polykey#304 so we can have a clearer error trace, so you can more easily see how the exceptions form
4. The discovery must log every exception that occurs even if it recovers from it similar to how network proxies report the exceptions.

**Comment by CMCDragonkai** [comment]
> The tests that setup an agent are now using this networkConfig:
> 
> ```ts
> networkConfig: {
>   proxyHost: '127.0.0.1' as Host,
>   egressHost: '127.0.0.1' as Host,
>   ingressHost: '127.0.0.1' as Host,
>   agentHost: '127.0.0.1' as Host,
>   clientHost: '127.0.0.1' as Host,
> },
> ```
> 
> We're no longer binding to `0.0.0.0` anywhere in the failing discovery test, however the same errors and warnings are still being displayed as before. Most of the errors seem to pop up when we try to stop the discovery domain.

Do this for the global agent as well too, and remember clients must then use `127.0.0.1` too.

**Comment by CMCDragonkai** [comment]
@emmacasolin

> 1. In our Discovery, the default timeout shouldn't be 20s, that's too long. You want to modify this timeout. The withConnF should be able to override this timeout, even if the class default is 20s.

Can you create a new issue for this as well later.

**Comment by CMCDragonkai** [comment]
If all the top issues are resolved, proceed to:

1. Squashing all the WIP commits into semantic commits
2. Create new issues for remaining work like `Discovery` controlling timeouts, and any additional testing you think would be suitable
3. Tick off the final items
4. Merge!

**Comment by CMCDragonkai** [comment]
For good practice you should change where `pk agent start` is used with `pkSpawn` or otherwise to also have `'--client-host', '127.0.0.1', '--ingress-host', '127.0.0.1'`. This mostly occurs in `tests/bin/agent/start.tes.ts` and `tests/bin/agent/status.test.ts` but a few other places might have this as well. We don't need to change the egress host because it's not a configurable parameter and it is for sending out, so it won't receive random internet packets anyway.

**Comment by CMCDragonkai** [comment]
Remember the port of `0` means "any" port. While a host of `0.0.0.0` means "all" addresses. This means when you are later contacting the polykey agent, you don't want to use the initial parameters you passed in, because they could be wildcards. You want to know either:

1. For port - get it from the instance by doing `getPort()` or `.port` (in GRPCServer, this should be changed)
2. For host - explicitly set it to `127.0.0.1`, don't get it from the parameter, nor property of the class instance

**Comment by CMCDragonkai** [comment]
To make our host and port acquisition consistent, can you change `GRPCServer.host` and `GRPCServer.port` getters to methods:

```ts
  /**
   * Gets the host
   * Wildcard host `0.0.0.0` or `::` is not resolved
   */
  @ready(new grpcErrors.ErrorGRPCServerNotRunning())
  getHost(): Host {
    return this.host;
  }

  /**
   * Gets the resolved port
   * Use the resolved port for connections
   */
  @ready(new grpcErrors.ErrorGRPCServerNotRunning())
  getPort(): Port {
    return this.port;
  }
```

Note that these methods only ever occur on the server side of programs, never client side, compare with `GRPCClient`.

Beware of find replace all, with `grpcServerAgent.X` and `grpcServerClient.X`.

File: tests/bin/identities/allowPermissionsDisallow.test.ts [hunk 14]
```diff
@@ -0,0 +1,417 @@
...
+import { poll, sysexits } from '@/utils';
+import * as nodesUtils from '@/nodes/utils';
+import * as keysUtils from '@/keys/utils';
+import * as claimsUtils from '@/claims/utils';
+import * as identitiesUtils from '@/identities/utils';
+import * as testBinUtils from '../utils';
+import * as testUtils from '../../utils';
+import TestProvider from '../../identities/TestProvider';
+
+describe('allow/permissions/disallow', () => {
```
Comment (CMCDragonkai) [inline tests/bin/identities/allowPermissionsDisallow.test.ts]: This should be `allow/disallow/permissions`. And you want to focus on testing `allow` then `disallow` as exact opposites, and `permissions` command comes after both. Like allow 3, then disallow 2 and then permissions.

File: tests/validation/utils.nodes.test.ts [hunk 15]
```diff
@@ -0,0 +1,60 @@
...
+      validationErrors.ErrorParse,
+    );
+  });
+  test('parseSeedNodes - invalid hostname', () => {
+    const rawSeedNodes = `${nodeIdEncoded1}@$invalidHost:${port1}`;
+    expect(() => validationUtils.parseSeedNodes(rawSeedNodes)).toThrow(
+      validationErrors.ErrorParse,
+    );
+  });
+  test.skip('parseSeedNodes - invalid port', () => {
```
Comment (CMCDragonkai) [inline tests/validation/utils.nodes.test.ts]: Change this to `test.todo` with only the string.

File: tests/validation/utils.nodes.test.ts [hunk 16]
```diff
@@ -0,0 +1,60 @@
...
+    const rawSeedNodes = `${nodeIdEncoded1}@${hostname}$:NOTAPORT`;
+    // TODO: currently failing here
+    expect(() => validationUtils.parseSeedNodes(rawSeedNodes)).toThrow(
+      validationErrors.ErrorParse,
+    );
+  });
+  test('parseSeedNodes - invalid structure', () => {
```
Comment (CMCDragonkai) [inline tests/validation/utils.nodes.test.ts]: Change this to `test.todo` with only the string.

**Comment by CMCDragonkai** [comment]
For the agent restart commit, move it to the very end (recent commit), makes it easier to split out into another PR and keeping with the PR merge order.

File: tests/validation/utils.nodes.test.ts (hunk 16 above)
Comment (emmacasolin) [reply tests/validation/utils.nodes.test.ts]: Done

File: tests/validation/utils.nodes.test.ts (hunk 15 above)
Comment (emmacasolin) [reply tests/validation/utils.nodes.test.ts]: Done

File: tests/bin/identities/allowPermissionsDisallow.test.ts (hunk 14 above)
Comment (emmacasolin) [reply tests/bin/identities/allowPermissionsDisallow.test.ts]: Fixed up the order for this, as well as for trust/untrust/list (gestalts), set/unset/get (gestalt actions), and put/delete/get (tokens).

**Comment by emmacasolin** [comment]
The remaining instances of `0.0.0.0` appearing in test outputs are the following tests. The ports are likely random for the most part, however I included them to show how many occurances there were for the same port in each test.

`tests/nodes/NodeConnectionManager.general.test.ts`
- `WARN:ConnectionForward 0.0.0.0:58343:Forward Error: ErrorConnectionEndTimeout` (x2)
- `WARN:ConnectionForward 0.0.0.0:43971:Forward Error: ErrorConnectionEndTimeout` (x2)

`tests/nodes/NodeConnectionManager.lifecycle.test.ts`
- `WARN:ConnectionForward 0.0.0.0:46710:Forward Error: ErrorConnectionEndTimeout` (x7)
- `WARN:ConnectionForward 0.0.0.0:56352:Forward Error: ErrorConnectionEndTimeout` (x1)

`tests/nodes/NodeConnectionManager.seednodes.test.ts`
- `WARN:ConnectionForward 0.0.0.0:51387:Forward Error: ErrorConnectionEndTimeout` (x2)

`tests/nodes/NodeConnectionManager.termination.test.ts`
- `WARN:ConnectionForward 0.0.0.0:46311:Forward Error: ErrorConnectionEndTimeout` (x1)
- `WARN:ConnectionForward 0.0.0.0:52191:Forward Error: ErrorConnectionEndTimeout` (x1)
- `WARN:ConnectionForward 0.0.0.0:39933:Forward Error: ErrorConnectionEndTimeout` (x1)
- `WARN:ConnectionForward 0.0.0.0:33209:Forward Error: ErrorConnectionEndTimeout` (x1)
- `WARN:ConnectionForward 0.0.0.0:54328:Forward Error: ErrorConnectionEndTimeout` (x1)
- `WARN:ConnectionForward 0.0.0.0:55269:Forward Error: ErrorConnectionEndTimeout` (x1)
- `WARN:ConnectionForward 0.0.0.0:52081:Forward Error: ErrorConnectionEndTimeout` (x1)
- `WARN:ConnectionForward 0.0.0.0:44664:Forward Error: ErrorConnectionEndTimeout` (x1)

`tests/nodes/NodeConnectionManager.termination.test.ts`
- `WARN:ConnectionForward 0.0.0.0:59681:Forward Error: ErrorConnectionEndTimeout` (x3)

While all of these warnings are for the same error, there are other occurances of the same warning where the host takes the correct value of `127.0.0.1`, for example `WARN:ConnectionForward 127.0.0.1:37133:Forward Error: ErrorConnectionEndTimeout` which comes from `tests/nodes/NodeConnection.test.ts`.

**Comment by CMCDragonkai** [comment]
I've checked the final `npm run build`. Proceeding to merge.

The final nodes related issues above will be addressed in MatrixAI/Polykey#326.
