### PR TITLE
Fixing the `pk identities claim` command to augment DIs

### LINKED ISSUE #267: The `pk identities claim` command should perform augmentation
### Specification

We need to provide support for the creation of claims between a node and digital identity in a gestalt. 

> An issue with the `identities claim` CLI command - it doesn't actually perform the augmentation. At the moment, all this command does is call `await gestaltGraph.linkNodeAndIdentity(nodeInfo, identityInfo)`. Looking at `GestaltGraph.ts`, all this function does is update (or create if none exist) the ACL permissions for the node's gestalt.
> 
> In order to actually perform an identity claim/augmentation there are two more steps we need to add.
> 
> ### 1. Create a claim on the node's sigchain
> To do this, we need to construct a `ClaimLinkIdentity` object, which is just
> ```typescript
> type ClaimLinkIdentity = {
>   type: 'identity';
>   node: NodeId; // can get using nodeManager.getNodeId() since node manager is already injected into identities RPC
>   provider: ProviderId; // provided in call request already
>   identity: IdentityId; // provided in call request already
> };
> ```
> Next we would just need to call `sigchain.addClaim()`, passing this function the `ClaimLinkIdentity` object we created (unless there's a better way to do this?). Only thing is that the sigchain is not currently being injected into the identities RPC so that would need to be added.
> 
> ### 2. Publish the claim on the DI
> Once we've made a claim we just need to publish it on the provider as well. This stage requires the provider to be authenticated so it would be a good idea to check that before we even update ACL permissions/generate the claim on the sigchain (whichever comes first). We can get the provider from Identities Manager using the provided `ProviderId` we already have (`identities.getProvider`). After that we just need to call the `publishClaim()` method on the provider, passing it the claim we made on the Sigchain. Only problem here is that `sigchain.addClaim()` doesn't return the claim it generates, so we'll have to search the sigchain for the one we're looking for. This might be a little challenging unless we can assume that the most recent identity claim is the one we want.
> 
> Once we've got the claim we also need to decode it (using `decodeClaim` from claims utils) before we can publish it.
> 
> That's about all that needs to be done here, unless we also want to return something to the caller (e.g. the claim id and url that gets returned by `publishClaim()`) since right now that grpc call responds with an `EmptyMessage`.

### Additional context

- original comment by @emmacasolin regarding this in the `vaultsrefactoring` MR: https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/184#note_687311752
- issue for node -> node claims: #213 

### Tasks

1. Create and add the identity claim on the node's sigchain
2. Publish the claim on the digital identity provider

### PR DESCRIPTION
**Pull request by emmacasolin**
### Description
Currently the `pk-identities claim` command does not perform a DI augmentation. `src/client/rpcIdentities.ts` and `src/bin/identities/claim.ts` will need to be rewritten to address this.

### Issues Fixed
* Fixes #267 

### Tasks
1. [x] Check that the provider is auhenticated
1. [x] Create an identity claim on the claiming node's sigchain
   - [x] Inject the sigchain into identities rpc
   - [x] Construct `ClaimLinkIdentity` object
   - [x] Call `sigchain.addClaim()` to add the claim
2. [x] Publish the claim on the DI
   - [x] Find a way to get the newly added claim from the sigchain
   - [x] Decode the claim
   - [x] Get the provider from identity manager
   - [x] Call the `publishClaim()` method on the provider
3. [x] Return info to the caller (e.g. claimId and/or claim url)
4. [x] Write tests for augmentation
   - [x] CLI command
   - [x] rpc
5. [x] Replace identities exceptions with client service exceptions https://github.com/MatrixAI/js-polykey/pull/278#issuecomment-979728048

### Final checklist
* [x] Domain specific tests
* [x] Lint fixed
* [x] Squash and rebased
* [ ] Sanity check the final build

### CODE REVIEW

**Comment by emmacasolin** [comment]
Is there a reason why `ProviderMessage` uses the parameter `message` rather than `identityId`? Because it seems like everywhere that uses it assumes it's an identity id:
```proto
message ProviderMessage {
  string provider_id = 1;
  string message = 2;
}
```

**Comment by CMCDragonkai** [comment]
Not sure. Who wrote this?

On 29 October 2021 10:27:06 am AEDT, emmacasolin ***@***.***> wrote:
>Is there a reason why `ProviderMessage` uses the parameter `message` rather than `identityId`? Because it seems like everywhere that uses it assumes it's an identity id:
>```proto
>message ProviderMessage {
>  string provider_id = 1;
>  string message = 2;
>}
>```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MatrixAI/js-polykey/pull/278#issuecomment-954296440
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by emmacasolin** [comment]
> Not sure. Who wrote this?

Looks like it just hasn't been changed since it was first added months ago. I'll change it to `identityId` for clarity.

**Comment by emmacasolin** [comment]
Since `sigchain.addClaim()` doesn't return the generated claim I'm getting the newly created identity claim by doing
```ts
await sigchain.addClaim(claimData);
const claimId = await sigchain.getLatestClaimId();
const claimEncoded = await sigchain.getClaim(claimId!);
const claimDecoded = claimsUtils.decodeClaim(claimEncoded);
```
Although this assumes that the most recent claim on the sigchain is the one we just created (i.e. no other claims will be generated by other processes in between `addClaim` and `getLatestClaim`) - is it ok to make this assumption?

**Comment by emmacasolin** [comment]
I was running into issues with importing the sigchain into rpc identities where I was getting an undefined error after trying to run a function from the sigchain domain. To get around this I've created a function called `claimIdentity()` in NodeManager to do the creation of the claim, adding it onto the sigchain, and returning the encoded claim which seems to be working and is probably better design anyway over having all of the logic in `rpcIdentities.ts`. 

The augmentation process now seems to work in a simple test in `clientService.test.ts`, although there are still a few bugs that need to be ironed out, as well as tests in `bin/identities.test.ts` that need to be done, so this will probably be finished sometime on Monday.

**Comment by CMCDragonkai** [comment]
@tegefaulkes is changing the proto schema in #279, so this may need to be updated on that.

**Comment by emmacasolin** [comment]
I'm having some issues with the identities bin tests where the `identities claim` test is interfering with the `identities discover` (by node) test later on, causing it to fail with `Error: 2 UNKNOWN: Unknown Error`. I'm assuming it's from some sort of state that isn't getting cleaned up, since skipping the claims test causes everything else to pass, however I'm having trouble working out what it is. At the moment I'm clearing the sigchain, claimed identities on the provider, registered providers, the node graph, and the gestalt graph:
```ts
await polykeyAgent.sigchain.clearDB();
await testProvider.delToken(testToken.identityId);
await polykeyAgent.nodes.clearDB();
await polykeyAgent.gestalts.clearDB();
await polykeyAgent.identities.delToken(testToken.providerId, testToken.identityId);
```
However none of these have solved the problem. Not sure what else it could possibly be...

**Comment by CMCDragonkai** [comment]
When prototyping, don't use the tests. Create it from scratch using a 
`test.ts`. Then you can port it over when everything works/makes sense.

**Comment by tegefaulkes** [comment]
It's useful to know exactly what the error is. You'll want to find the RPC function throwing the error and add a `console.error(err)` in the catch block for it. That should give you some more information to work with.

**Comment by emmacasolin** [comment]
Rebased

**Comment by joshuakarp** [comment]
> Since `sigchain.addClaim()` doesn't return the generated claim I'm getting the newly created identity claim by doing
> 
> ```ts
> await sigchain.addClaim(claimData);
> const claimId = await sigchain.getLatestClaimId();
> const claimEncoded = await sigchain.getClaim(claimId!);
> const claimDecoded = claimsUtils.decodeClaim(claimEncoded);
> ```
> 
> Although this assumes that the most recent claim on the sigchain is the one we just created (i.e. no other claims will be generated by other processes in between `addClaim` and `getLatestClaim`) - is it ok to make this assumption?

My bad in only seeing this now.

It should be fine to actually make `addClaim` return the created claim, so we don't have to do this. Alternatively, you should acquire the sigchain's lock and perform this in a transaction instead to ensure it's a safe operation.

**Comment by joshuakarp** [comment]
From our sprint meeting yesterday, I believe there'll also be some testing fixes to be done after the CLI MR on Gitlab is merged and we rebase on those changes.

**Comment by CMCDragonkai** [comment]
The errors for `rpcIdentities` should be using domain-specific errors or client service errors.

```
client/rpcIdentities.ts
164:          throw Error(
203:        if (provider == null) throw Error(`Invalid provider: ${providerId}`);
208:        } else throw Error(`No identities found for provider: ${providerId}`);
```

**Comment by CMCDragonkai** [comment]
We shouldn't be throwing generic errors anywhere, it should always be attached to the error hierarchy somewhere. So the 2 choices are client service errors or domain specific errors. If the identities domain is returning undefined, then the exception should in client service. We will later review the entire system of how to do this. There's general exceptions for something not existing in HTTP like `404`. We can do something similar in this case.

Or we can propagate "undefined", which means one has to have a representation of `undefined` in protobuf. Details here: https://stackoverflow.com/a/64970700/582917

This has to be done in the #249 where we review how the API used in a larger scope.

**Comment by joshuakarp** [comment]
@emmacasolin can you provide an update on the status of this PR when you're back in? 

It will also need to be rebased on master before merging.

**Comment by emmacasolin** [comment]
> @emmacasolin can you provide an update on the status of this PR when you're back in?
> 
> It will also need to be rebased on master before merging.

Will need to fix up the command to match the new cli style + double check tests but other than that this is done. Will probably be finished off today.

**Comment by emmacasolin** [comment]
This has been rebased on master

**Comment by emmacasolin** [comment]
There's a lot of uncleared state in the identities bin tests, primarily once an identity is authenticated in any test it remains authenticated in future tests. So far I haven't been able to find a way to clear this between tests without destroying and recreating the entire `IdentitiesManager`, but will keep working on it. There are other things that are cleared at the end of individual tests rather than in before/after each blocks, so will try to clean this up too.

**Comment by emmacasolin** [comment]
Still having an issue with a successful identity claim causing an error in "Should start discovery by node" in `tests/bin/identities.test.ts`. The error is "Error: key should be a string or a buffer" and it's thrown inside the `gestaltsDiscoveryByNode` rpc. I haven't yet narrowed down exactly where it's being thrown, but I have a hunch it might be a jose error. Will continue looking into it tomorrow.

**Comment by joshuakarp** [comment]
Not sure if you've pushed your version, but that test seems to be passing on its own on my end:

<details>

```
 PASS  tests/bin/identities.test.ts (21.953 s)
  CLI Identities
    commandAllowGestalts
      ○ skipped Should allow permissions on node.
      ○ skipped Should allow permissions on Identity.
      ○ skipped Should fail on invalid inputs.
    commandDisallowGestalts
      ○ skipped Should disallow permissions on Node.
      ○ skipped Should disallow permissions on Identity.
      ○ skipped Should fail on invalid inputs.
    commandPermissionsGestalts
      ○ skipped Should get permissions on Node.
      ○ skipped Should get permissions on Identity.
    commandTrustGestalts
      ○ skipped Should set trust on Node.
      ○ skipped Should set trust on Identity.
      ○ skipped Should fail on invalid inputs.
    commandUntrustGestalts
      ○ skipped Should unset trust on Node.
      ○ skipped Should unset trust on Identity.
      ○ skipped Should fail on invalid inputs.
    commandClaimIdentity
      ○ skipped Should claim an identity.
      ○ skipped Should fail for unauthenticated identities.
    commandAuthenticateProvider
      ○ skipped Should authenticate an identity with a provider.
    commandGetGestalts
      ○ skipped Should list gestalt by Node
      ○ skipped Should list gestalt by Identity
    commandListGestalts
      ○ skipped Should list gestalts with permissions.
    commandSearchIdentities
      ○ skipped Should find a connected identity.
    commandDiscoverGestalts
      ✓ Should start discovery by Node (1136 ms)
      ○ skipped Should start discovery by Identity

Test Suites: 1 passed, 1 total
Tests:       22 skipped, 1 passed, 23 total
Snapshots:   0 total
Time:        22.013 s, estimated 27 s
Ran all test suites matching /tests\/bin\/identities.test.ts/i.
GLOBAL TEARDOWN
```

</details>

Seems like there's some interference between tests though when ran together:

<details>

```
 FAIL  tests/bin/identities.test.ts (28.247 s)
  CLI Identities
    commandAllowGestalts
      ✓ Should allow permissions on node. (228 ms)
      ✓ Should allow permissions on Identity. (164 ms)
      ✓ Should fail on invalid inputs. (135 ms)
    commandDisallowGestalts
      ✓ Should disallow permissions on Node. (73 ms)
      ✓ Should disallow permissions on Identity. (72 ms)
      ✓ Should fail on invalid inputs. (114 ms)
    commandPermissionsGestalts
      ✓ Should get permissions on Node. (72 ms)
      ✓ Should get permissions on Identity. (66 ms)
    commandTrustGestalts
      ✓ Should set trust on Node. (64 ms)
      ✓ Should set trust on Identity. (77 ms)
      ✓ Should fail on invalid inputs. (85 ms)
    commandUntrustGestalts
      ✓ Should unset trust on Node. (70 ms)
      ✓ Should unset trust on Identity. (60 ms)
      ✓ Should fail on invalid inputs. (85 ms)
    commandClaimIdentity
      ✓ Should claim an identity. (76 ms)
      ✕ Should fail for unauthenticated identities. (78 ms)
    commandAuthenticateProvider
      ✓ Should authenticate an identity with a provider. (52 ms)
    commandGetGestalts
      ✓ Should list gestalt by Node (74 ms)
      ✓ Should list gestalt by Identity (67 ms)
    commandListGestalts
      ✓ Should list gestalts with permissions. (198 ms)
    commandSearchIdentities
      ✓ Should find a connected identity. (55 ms)
    commandDiscoverGestalts
      ✕ Should start discovery by Node (1290 ms)
      ✓ Should start discovery by Identity (969 ms)

  ● CLI Identities › commandClaimIdentity › Should fail for unauthenticated identities.

    expect(received).toBeFalsy()

    Received: true

      575 |       ];
      576 |       const result = await testUtils.pkStdio(commands, {}, dataDir);
    > 577 |       expect(result.exitCode === 0).toBeFalsy(); // Fails..
          |                                     ^
      578 |     });
      579 |   });
      580 |   describe('commandAuthenticateProvider', () => {

      at Object.<anonymous> (tests/bin/identities.test.ts:577:37)

  ● CLI Identities › commandDiscoverGestalts › Should start discovery by Node

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 1

      754 |       ];
      755 |       const result = await testUtils.pkStdio(commands, {}, dataDir);
    > 756 |       expect(result.exitCode).toBe(0);
          |                               ^
      757 |
      758 |       // We expect to find a gestalt now.
      759 |       const gestalt = await polykeyAgent.gestaltGraph.getGestalts();

      at Object.<anonymous> (tests/bin/identities.test.ts:756:31)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 21 passed, 23 total
Snapshots:   0 total
Time:        28.313 s
Ran all test suites matching /tests\/bin\/identities.test.ts/i.
GLOBAL TEARDOWN
npm ERR! Test failed.  See above for more details.

```

</details>

**Comment by emmacasolin** [comment]
I haven’t pushed up my most recent changes but the “Should fail for unauthenticated identities” test is now passing on my end (there was interference from the test above it where the authentication wasn’t being undone - this is now being cleared in the afterEach block). I haven’t been able to fix the discovery failure yet but it’s the first claims test which is creating the interference causing it.
________________________________

**Comment by emmacasolin** [comment]
I've found the source of the error, however I don't know enough about the nodes domain to work out why it's occurring or how to fix it. What's happening is that when the node graph is being set up in the discover by node test (using `setNodeOps()`, at some point when it's calculating the bucket index it receives `undefined`. Undefined is returned by `getBucketIndex()` when the index (before being packed as a lexicographic integer and returned) is calculated as -1, which occurs when source node and target node for `calculateBucketIndex()` are the same. This error occurs even if I clear the node graph between tests so I don't know why claiming an identity would be causing this issue?

**Comment by joshuakarp** [comment]
Have you pushed up your most recent changes? I can take a look.

**Comment by emmacasolin** [comment]
> Have you pushed up your most recent changes? I can take a look.

Yep, everything's pushed up except some console logs for debugging

**Comment by joshuakarp** [comment]
This is unrelated to this particular problem, but I've realised that the node claims setup for these tests is slightly incorrect:

```ts
      // Adding sigchain details.
      const claimBtoC: ClaimLinkNode = {
        type: 'node',
        node1: nodeB.nodeManager.getNodeId(),
        node2: nodeC.nodeManager.getNodeId(),
      };
      const claimCtoB: ClaimLinkNode = {
        type: 'node',
        node1: nodeC.nodeManager.getNodeId(),
        node2: nodeB.nodeManager.getNodeId(),
      };
      await nodeB.sigchain.addClaim(claimBtoC);
      await nodeB.sigchain.addClaim(claimCtoB);
      await nodeC.sigchain.addClaim(claimCtoB);
      await nodeC.sigchain.addClaim(claimBtoC);
```

A cryptolink between `B` and `C` here should be represented by a **single** claim on each node's sigchain (that's been signed by both `B` and `C`). That is, `B` will have a single claim signed by both itself and `C`, and `C` will have a single claim signed by both itself and `B`.

But here, we're adding 2 claims. This is incorrect. I don't think this is the cause of the error, but it will also need to be resolved at some stage. From the git blame, it seems like this was added prior to the refactoring of node claims though, so just something that's been missed. I'll make a separate issue for this.

**Comment by joshuakarp** [comment]
We have a setup like this:

```
┌─────────────────────────────────────┐
│                                     │
│   ┌─────┐     ┌─────┐     ┌─────┐   │
│   │     │     │     │     │     │   │
│   │  i  ├─────┤  B  ├─────┤  C  │   │
│   │     │     │     │     │     │   │
│   └─────┘     └─────┘     └─────┘   │
│                                     │
└─────────────────────────────────────┘

                ┌─────┐
                │     │
                │  A  │
                │     │
                └─────┘
```

where the lines indicate cryptolinks between the nodes `B` and `C`, and the identity `i`. The outer square represents the gestalt. `A` is the `PolykeyAgent` instance that we are.

If I change these to arrows, to represent knowledge of the other node in their `NodeGraph`, we get the following:

```
┌─────────────────────────────────────┐
│                                     │
│   ┌─────┐     ┌─────┐     ┌─────┐   │
│   │     │     │     ◄─────┤     │   │
│   │  i  │     │  B  │     │  C  │   │
│   │     │     │     ├─────►     │   │
│   └─────┘     └─▲─┬─┘     └─────┘   │
│                 │ │                 │
└─────────────────┼─┼─────────────────┘
                  │ │
                ┌─┴─▼─┐
                │     │
                │  A  │
                │     │
                └─────┘
```

that is, `A` has an arrow pointing to `B`, so has it in its `NodeGraph`. Similarly, `B` has an arrow pointing to `A` and `C`, so has entries for both these nodes in its `NodeGraph`.

Potentially `B` is returning the info of `A` back to itself (`A`), and so it tries to add itself to its `NodeGraph`. I thought I'd fixed this a while ago, but I'll take a deeper look.

**Comment by emmacasolin** [comment]
It could actually be an issue with the identity -> I'm able to clear an identity claim on the node's side through IdentitiesManager in between tests, however there isn't a way to clear the claim from the identity that I've found. I'll see if I can find a way to do this because I have a feeling this might be the issue.

**Comment by joshuakarp** [comment]
Okay, possibly. I'm not too sure how that would invoke a `setNodeOps` operation though?

It's definitely the `polykeyAgent` (`A` in the diagram) trying to add itself to its own `NodeGraph` - I've verified that with some logger outputs.

**Comment by emmacasolin** [comment]
Not clearing the claims on the identity side was in fact the problem! I think nodeops was being invoked when discoverGestalt() attempts to rebuild the gestalt during discovery, but it was receiving incorrect data from the uncleared identity. There wasn't an existing method to remove cryptolinks from the Test Provider used in tests (I don't think there's one for real providers either) so I added a method in TestProvider.ts that just resets the links field to the default set during contruction. Not sure if there's a better way to do this but since it's just a class used for testing I'm assuming it's ok? Calling this method in between tests removes the error so all identities bin tests are now passing!

**Comment by joshuakarp** [comment]
Great. That's interesting, but does make sense.

And yeah, that's completely fine given that it's just a `TestProvider` - it's purely there to make our lives easy for testing, so that seems sufficient to me.

**Comment by joshuakarp** [comment]
There seems to be 1 too many commits on here from the rebase https://github.com/MatrixAI/js-polykey/pull/278/commits. This should only have 1 "Unattended `pk bootstrap` and `pk agent start`", with a list of items 1-9 (there's an extra commit with a list of 1-8).

**Comment by emmacasolin** [comment]
The commit with 1-8 seems to be a mistake -> the added files I don't think should be there. That commit can probably be reverted?

**Comment by joshuakarp** [comment]
You can most likely just do `git rebase -i <some commit before>` and then `drop` the extra commit - then you won't have a revert commit either.

if you need to do another rebase on the BIP39 PR too, you should `drop` the previous BIP39 commit you have. Actually, same goes for when you rebase on master after the BIP39 PR is merged - I believe you should be dropping the BIP39 commit that you've currently got here in favour of the merged BIP39 commit on master.

**Comment by emmacasolin** [comment]
Note that we'll need to look into mocking the Identities Manager for testing this PR due to the inteference between claims tests and discovery tests. This comment describes the fix I made for the problem I was encountering: https://github.com/MatrixAI/js-polykey/pull/278#issuecomment-985230957

**Comment by joshuakarp** [comment]
As another quick note on this, from our discussion today, for usage of the global `pkAgent`:
* all state added to the global agent in a particular test should be explicitly removed at the end of the test. 
   - this requires having a corresponding "undo" CLI command to remove the state (e.g. for a `pk nodes add`, a corresponding `pk nodes delete`). Given that we don't have access to the internals of PK, this undo command is necessary
   - note that this has complications for some domains where we shouldn't have publicly available undo commands (such as the sigchain) - for these circumstances, the simplest solution for now is to just create your own separate agent process (i.e. use `pkStdio` with `pk agent start` instead of using `pkAgent`) to have a clean state for the test (assuming that the side-effects imposed on the sigchain, or any other domain, would impact the result of a later test)

**Comment by CMCDragonkai** [comment]
Needs big rebase on master. First squash both of these commits. You're going to have a lot of merge conflicts. To resolve, use `git checkout --ours ./..` on files/directories that are not meant to be addressed by this PR. Then do `git add` on them. Observe that `git status` doesn't show these changes up.

**Comment by CMCDragonkai** [comment]
Tomorrow wednesday @emmacasolin you'll need to try doing this. It may be complicated, but first write down here in this comment what files are actually meant to be changed by this PR (it will help us next). Then:

1. Squash this down to 1 commit
2. Rebase on master
3. Using `git checkout --ours` to select master versions of files/directories this PR doesn't affect
4. Use vs code to reconcile other merge conflicts
5. Check that all code is correct, run tests
6. Push up rebased commit
7. Lint fix this
8. Test this
9. Then ask @joshuakarp to review and merge

**Comment by emmacasolin** [comment]
### Files intended to be changed in this PR:

`identities claim` cli command
- `src/bin/identities/CommandClaim.ts`
- `src/client/rpcIdentities.ts`
- `src/client/GRPCClientClient.ts`
- `src/client/clientService.ts`
- `src/PolykeyAgent.ts`
- `tests/client/utils.ts`

`Provider` message better name for `message` field (now `identityId`)
- `src/proto/schemas/polykey/v1/identities/identities.proto`
- `src/proto/schemas/polykey/v1/client_service.proto`
- `src/proto/js/polykey/v1/identities/identities_pb.d.ts`
- `src/proto/js/polykey/v1/identities/identities_pb.js`
- `src/proto/js/polykey/v1/client_service_grpc_pb.d.ts`
- `src/proto/js/polykey/v1/client_service_grpc_pb.js`
- `src/bin/identities/CommandAllow.ts`
- `src/bin/identities/CommandAuthenticate.ts`
- `src/bin/identities/CommandDisallow.ts`
- `src/bin/identities/CommandDiscover.ts`
- `src/bin/identities/CommandGet.ts`
- `src/bin/identities/CommandPermissions.ts`
- `src/bin/identities/CommandSearch.ts`
- `src/bin/identities/CommandTrust.ts`
- `src/bin/identities/CommandUntrust.ts`
- `src/client/rpcGestalts.ts`
- `tests/client/rpcGestalts.test.ts`

Sigchain returns newly created claim
- `src/sigchain/Sigchain.ts`

"Reset" option added to Test Provider to clear changes between tests
- `tests/identities/TestProvider.ts`

Replacing indentities exceptions with domain/client specific exceptions
- `src/client/errors.ts`

Tests
- `tests/bin/identities.test.ts`
- `tests/client/rpcIdentities.test.ts`

File: tests/identities/TestProvider.ts [hunk 1]
```diff
@@ -82,6 +82,28 @@ class TestProvider extends Provider {
     };
   }
 
+  public resetLinks() {
```
Comment (CMCDragonkai) [inline tests/identities/TestProvider.ts]: What does this function do?

File: src/client/clientService.ts [hunk 2]
```diff
@@ -93,7 +96,7 @@ function createClientService({
     }),
     ...createIdentitiesRPC({
       identitiesManager,
-      gestaltGraph,
+      sigchain,
```
Comment (CMCDragonkai) [inline src/client/clientService.ts:99]: Was surprised that `sigchain` wasn't part of the client service yet. That seems like a big oversight.

File: tests/identities/TestProvider.ts (hunk 1 above)
Comment (emmacasolin) [reply tests/identities/TestProvider.ts]: It removes all claims from the test provider, since these were affecting later tests. Addressed in this comment https://github.com/MatrixAI/js-polykey/pull/278#issuecomment-985230957

File: src/client/errors.ts [hunk 3]
```diff
@@ -26,11 +26,17 @@ class ErrorClientInvalidNode extends ErrorClient {
   exitCode: number = 70;
 }
 
+class ErrorClientInvalidProvider extends ErrorClient {
```
Comment (CMCDragonkai) [inline src/client/errors.ts:25]: What is this exception for? In our `IdentitiesManager` we return `undefined` when we cannot provide a given provider. Unless we have a call that expects a provider to exist, we can propagate this value-error via GRPC in a empty message sort of value. That is if this is used to fetch a provider, you would return undefined/null instead of throwing an error. The caller must then check if it actually got the data or not.

In grpc I'm pretty we have optional message properties.

Comment (CMCDragonkai) [reply src/client/errors.ts:25]: Same goes for all other kinds of GRPC calls that fetch things. You don't use an exception to indicate that it doesn't exist. You use an undefined/null value instead.

Now when do you use such an exception, you do use it when there will be a call that takes a provider id or whatever id and you intend to do something with that id. Then in that case, an exception can be thrown. But make sure that such exceptions are isolated to those calls, and not calls that simply fetch a resource.

File: src/client/clientService.ts (hunk 2 above)
Comment (emmacasolin) [reply src/client/clientService.ts:99]: I think it was part of the client service at some point but was later removed? I don't remember what it was previously used for though.

File: tests/bin/identities.test.ts [hunk 4]
```diff
@@ -135,7 +135,7 @@ describe('CLI Identities', () => {
     keynode.id = polykeyAgent.nodeManager.getNodeId();
 
     testProvider = new TestProvider();
-    await polykeyAgent.identitiesManager.registerProvider(testProvider);
+    polykeyAgent.identitiesManager.registerProvider(testProvider);
```
Comment (CMCDragonkai) [inline tests/bin/identities.test.ts:128]: This can indeed be done. But I was actually thinking that you do this before `PolykeyAgent.createPolykeyAgent` but dependency injecting the `identitiesManager`. 

But due to the complexity of setting up the `identitiesManager` prior, I guess this can do for now.

Comment (CMCDragonkai) [reply tests/bin/identities.test.ts:128]: Actually maybe we should do this for the global agent instead? We can't use any of the existing real providers anyway.

File: tests/identities/TestProvider.ts (hunk 1 above)
Comment (CMCDragonkai) [reply tests/identities/TestProvider.ts]: It's not part of the original provider standard, and it seems special cased. This seems like something that should be done in the test function itself, not embedded in `TestProvider`.

File: src/bin/identities/CommandSearch.ts [hunk 5]
```diff
@@ -54,15 +54,21 @@ class CommandSearch extends CommandPolykey {
...
+        let output;
+        if (res.getIdentityId()) {
+          output = [
+            parsers.formatIdentityString(
+              res.getProviderId() as ProviderId,
+              res.getIdentityId() as IdentityId,
+            ),
+          ];
+        } else {
+          output = [`No identities found for provider ${providerId}`];
```
Comment (CMCDragonkai) [inline src/bin/identities/CommandSearch.ts]: You want to do 2 things here:

1. Indicate the sentinel value by simply an empty list. `[]`
2. Additionally write a logger message with `this.logger.info('...');` regarding that no identities were found

Do not write a human readable message in the list item that ism eant to be reserved for the identity string.

File: src/client/errors.ts (hunk 3 above)
Comment (emmacasolin) [reply src/client/errors.ts:25]: It's for when the user passes in an invalid provider as the argument for a CLI call, so it's more of a client-side error. Since the command can't continue if the provided input is incorrect we need to throw an error.

File: src/bin/identities/CommandSearch.ts [hunk 6]
```diff
@@ -54,15 +54,21 @@ class CommandSearch extends CommandPolykey {
             pkClient.grpcClient.identitiesInfoGet(providerMessage, auth),
           meta,
         );
+        let output;
+        if (res.getIdentityId()) {
+          output = [
+            parsers.formatIdentityString(
```
Comment (CMCDragonkai) [inline src/bin/identities/CommandSearch.ts]: Can you remove this function and replace it with the actual implementation:

```
`${providerId}:${identityId}`
```

This is a premature abstraction.

These places need to be changed:

```
»» ~/Projects/js-polykey/src
 ♖ ag 'formatIdentityString'              (qa-testing) pts/2 10:28:26
bin/identities/CommandGet.ts
92:              parsers.formatIdentityString(

bin/identities/CommandSearch.ts
61:              parsers.formatIdentityString(

bin/identities/CommandList.ts
101:                parsers.formatIdentityString(

bin/utils/parsers.ts
59:function formatIdentityString(
65:export { parseNumber, parseSecretPath, parseGestaltId, formatIdentityString };
```

File: src/client/errors.ts (hunk 3 above)
Comment (CMCDragonkai) [reply src/client/errors.ts:25]: Yea but you must differentiate between these commands:

1. Commands that get a resource based on the ID. The response is not an error, simply an undefined/null.
2. Commands that do something to a resource based on the ID. The response is an error because the ID doesn't exist.
3. Commands that get a collection of resources based on an ID. The response is not an error, simply an empty collection value like `[]`.

Special case:

4. Commands that get a resource B that depends on resource A that is indexed by the ID. In this case it could be either. But I usually default on returning undefined because the transitive lookup failed.

Comment (CMCDragonkai) [reply src/client/errors.ts:25]: I should clarify the above. The above depends on API context.

In case 1, you usually have a `404` to represent a client error when a resource is missing in HTTP. But in RPC and functional calls, this should be translated to a `Maybe` type which results in either a value or a sentinel value representing emptiness like `null` or `undefined.

If you're in a CLI environment, you should probably throw an error here with an exit code. You don't want to just return nothing with exit code 0. EXCEPT when the command is meant to return a series of data. In such a case, a succesful exit code with 0 results is sufficient.

So for example:

```sh
# imagine we are in the terminal
get-one-thing <id>
# it should be exit code > 0 because the id doesn't exsit

get-many-things/search-for-things <id>
# it should be exit code 0 with no results because it is successfully getting you 0 results
```

This also applies to network APIs.

File: src/client/clientService.ts (hunk 2 above)
Comment (joshuakarp) [reply src/client/clientService.ts:99]: This is an interesting point. I couldn't quite remember why `sigchain` wasn't already there (even for node claims which are already implemented). Looking back, it's because the sigchain is injected into the `NodeManager`, and it makes a call through `NodeManager` to perform the claiming process (i.e. `NodeManager.claimNode`). This call requires a `NodeConnection`, hence the current requirements on `NodeManager`.

File: src/client/errors.ts (hunk 3 above)
Comment (CMCDragonkai) [reply src/client/errors.ts:25]: Ok I have written up a guideline here: https://github.com/MatrixAI/js-polykey/wiki/API-Design. Let me know if that helps.

File: tests/identities/TestProvider.ts (hunk 1 above)
Comment (emmacasolin) [reply tests/identities/TestProvider.ts]: Looking back on this function again it's actually resetting the cryptolinks back to the default created during contruction rather than deleting all of them, so there still needs to be some way of keeping track of this default. There's also no existing way of directly accessing or editing the links stored on the test provider from outside of it, since the field is protected and there are no getters or setters, so this would need to change. I think keeping it the way it is is the simplest option, especially considering that the test provider is implemented very differently from a normal provider anyway and already has an extra function `overrideLinks()` that isn't part of the original provider standard and is purely there to make testing easier.

Comment (CMCDragonkai) [reply tests/identities/TestProvider.ts:85]: So can this be done in the tests themselves? It's not really part of the domain model of `TestProvider` right?

Comment (CMCDragonkai) [reply tests/identities/TestProvider.ts]: I didn't add `overrideLinks` into this class.

It was added in here: https://github.com/MatrixAI/js-polykey/commit/c2dfe01c281fef8adcee8de17263363c733ea800.

I don't think that had a full deep review, and I suspect that this is the wrong place to do it.

If you must, you can also make the links public so you can mutate them in the tests.

Comment (joshuakarp) [reply tests/identities/TestProvider.ts]: Could you also just do a `ts-ignore` to access and mutate the links on a test-by-test basis? Or bad practice?

Comment (CMCDragonkai) [reply tests/identities/TestProvider.ts]: Like the concept of `links` itself is specific to `TestProvider`. So you can just make that public if you need to modify those links.

I would also suggest just creating a new `IdentityProvider` instance when you want to change a "default state"... but I guess during testing this can be cost prohibitive.

Comment (CMCDragonkai) [reply tests/identities/TestProvider.ts]: This is what I wrote originally:

```ts
  protected linkIdCounter: number = 0;
  protected users: Record<IdentityId, POJO>;
  protected links: Record<LinkId, string>;
  protected userLinks: Record<IdentityId, Array<LinkId>>;
  protected userTokens: Record<string, IdentityId>;

  public constructor() {
    super();
    this.users = {
      test_user: {
        email: 'test_user@test.com',
      },
      test_user2: {
        email: 'test_user2@test.com',
      },
    };
    this.links = {
      test_link: JSON.stringify({
        type: 'identity',
        node: 'nodeid' as NodeId,
        provider: this.id,
        identity: 'test_link' as IdentityId,
        timestamp: 1618650105,
        signature: 'somesignature',
      }),
    };
    this.userLinks = {
      test_user: ['test_link'],
    };
    this.userTokens = {
      abc123: 'test_user' as IdentityId,
    };
  }
```

The `links` property was only there to enable the `TestProvider` to seed it with some initial state.

If you want to do this properly, just make the `links` property public, and mutate it as you are testing it.

You could even change the `constructor` of `TestProvider` so that tests can seed the relevant state that you want.

But arbitrary methods inside the `TestProvider` is not the right place to do link state mutation. They don't correspond to any test, and it's difficult to know why these methods exist at all when looking at this code 6 months later.

Comment (emmacasolin) [reply tests/identities/TestProvider.ts]: Ok, I'll remove the two link-mutating metods and make the `links` property public.

File: src/bin/identities/CommandSearch.ts (hunk 6 above)
Comment (emmacasolin) [reply src/bin/identities/CommandSearch.ts]: Done

File: tests/identities/TestProvider.ts (hunk 1 above)
Comment (emmacasolin) [reply tests/identities/TestProvider.ts]: This has been fixed

File: src/client/errors.ts (hunk 3 above)
Comment (emmacasolin) [reply src/client/errors.ts:25]: The client errors that were previously being used (`ErrorClientInvalidNode` and `ErrorClientInvalidProvider`) have been removed from everywhere except for two places:
- `identitiesClaim` - we need to throw an error if the provider is invalid before we generate the claim on our sigchain, because once we do that we can't remove it, and if the provider is invalid we won't be able to publish the claim on the identity
- `identitiesInfoGetConnected` - this rpc doesn't have a corresponding bin command so I wasn't sure what its purpose was. Should this even exist?

File: src/bin/identities/CommandSearch.ts (hunk 5 above)
Comment (emmacasolin) [reply src/bin/identities/CommandSearch.ts]: Done

File: src/client/errors.ts (hunk 3 above)
Comment (CMCDragonkai) [reply src/client/errors.ts:25]: Seems right for `identitiesClaim`, that's one of the cases where you are doing something to a resource with the expectation that the ID is valid.

`identitiesInfoGetConnected` - Does this get a transitive resource? This is the ambiguous one. Sometimes we would say that the ID isn't valid, so you have no connections. But I think in this case, we would want to differentiate the fact that the identity doesn't actually exist, vs the identity exist, but empty list of connections. Therefore it should throw an error.

File: src/bin/identities/CommandAuthenticate.ts [hunk 7]
```diff
@@ -45,32 +45,21 @@ class CommandAuthenticate extends CommandPolykey {
...
-          }),
-        );
+        providerMessage.setIdentityId(identityId);
+        await binUtils.retryAuthentication(async (auth) => {
+          const stream = pkClient.grpcClient.identitiesAuthenticate(
+            providerMessage,
+            auth,
+          );
+          const codeMessage = (await stream.next()).value;
+          process.stdout.write(
```
Comment (CMCDragonkai) [inline src/bin/identities/CommandAuthenticate.ts]: Do this outside of the lambda. Take the result from `retryAuthentication` and do this.

File: src/bin/identities/CommandAuthenticate.ts [hunk 8]
```diff
@@ -45,32 +45,21 @@ class CommandAuthenticate extends CommandPolykey {
...
-            ],
-          }),
-        );
+        providerMessage.setIdentityId(identityId);
+        await binUtils.retryAuthentication(async (auth) => {
+          const stream = pkClient.grpcClient.identitiesAuthenticate(
+            providerMessage,
+            auth,
+          );
+          const codeMessage = (await stream.next()).value;
```
Comment (CMCDragonkai) [inline src/bin/identities/CommandAuthenticate.ts]: Are you supposed to take 1 value from the stream? Why is it stream at all then?

File: src/bin/identities/CommandAuthenticate.ts (hunk 7 above)
Comment (CMCDragonkai) [reply src/bin/identities/CommandAuthenticate.ts]: The `retryAuthentication` should give back the stream. Then use the stream outside of `retryAuthentication`. We only retry upon establishing the stream.

File: src/bin/identities/CommandList.ts [hunk 9]
```diff
@@ -90,25 +89,18 @@ class CommandList extends CommandPolykey {
...
             for (const identity of gestalt.identities) {
-              output.push(
-                parsers.formatIdentityString(
-                  identity.providerId,
-                  identity.identityId,
-                ),
-              );
+              output.push(`${identity.providerId}:${identity.identityId}`);
             }
             output.push('');
```
Comment (CMCDragonkai) [inline src/bin/identities/CommandList.ts:100]: I can see there's some problems with these where the `retryAuthentication` should just return the stream.

I think this can be addressed in a later PR then. We would move most of that logic our of `retryAuthentication`.

File: tests/identities/TestProvider.ts [hunk 10]
```diff
@@ -7,17 +7,15 @@ import type {
...
 
 class TestProvider extends Provider {
   public readonly id = 'test-provider' as ProviderId;
 
-  protected linkIdCounter: number = 0;
+  public linkIdCounter: number = 0;
   protected users: Record<IdentityId | string, POJO>; // FIXME: the string union on VaultId is to prevent some false errors.
-  protected links: Record<IdentityClaimId | string, string>; // FIXME: the string union on VaultId is to prevent some false errors.
+  public links: Record<IdentityClaimId | string, string>; // FIXME: the string union on VaultId is to prevent some false errors.
   protected userLinks: Record<
```
Comment (CMCDragonkai) [inline tests/identities/TestProvider.ts:20]: Why not make `userLinks` and `userTokens` also public so they can be later mutated too.

File: src/bin/identities/CommandAuthenticate.ts (hunk 8 above)
Comment (CMCDragonkai) [reply src/bin/identities/CommandAuthenticate.ts]: DW about this. This is because I think alot of CLI calls are bundling too much logic within the `retryAuthentication` lambda. It should only be done on the initial call. All stream related work then happens outside and afterwards.

Comment (CMCDragonkai) [reply src/bin/identities/CommandAuthenticate.ts]: This would need to be resolved in a later PR. New issue for this.

Comment (emmacasolin) [reply src/bin/identities/CommandAuthenticate.ts]: Previously it was returning the identity id as the second value, which seemed to be unecessary considering it's a parameter for the command. I kept it as a stream after doing that since the authenticate function on the provider is itself a stream so I wasn't sure if it would still work as a unary call.

File: tests/identities/TestProvider.ts (hunk 10 above)
Comment (emmacasolin) [reply tests/identities/TestProvider.ts:20]: `userTokens` and `userLinks` are both very hard-coded into some of the functions in the test provider, and changing them can break the entire thing. I think it's safer to leave as is but I can make them public if you'd prefer

File: src/client/errors.ts (hunk 3 above)
Comment (emmacasolin) [reply src/client/errors.ts:25]: The thing with `identitiesInfoGetConnected` is that it isn't used anywhere in the CLI. There's a test for it in `rpcIdentities.test.ts` but other than that it's not used anywhere in the codebase.

File: src/bin/identities/CommandAuthenticate.ts (hunk 8 above)
Comment (emmacasolin) [reply src/bin/identities/CommandAuthenticate.ts]: `identities authenticate` is now a unary call. Still works as expected with all tests passing.

File: src/bin/identities/CommandAuthenticate.ts (hunk 7 above)
Comment (emmacasolin) [reply src/bin/identities/CommandAuthenticate.ts]: Done

File: src/client/rpcIdentities.ts [hunk 11]
```diff
@@ -26,17 +26,16 @@ const createIdentitiesRPC = ({
 }) => {
   return {
     identitiesAuthenticate: async (
```
Comment (CMCDragonkai) [inline src/client/rpcIdentities.ts:27]: I forgot how this call is supposed to work. Are we expecting a back and forth protocol between the CLI user and the agent? Or are you saying that the user provides the token upon calling authenticate?

I thought that the provider has to start the operation, and then give you a URL that you have to go to, and then the user has to copy that URL back into the CLI. That's why the `authenticate` is an async generator as it represents this particular flow of interaction. Therefore you would need a duplex stream right?

Comment (CMCDragonkai) [reply src/client/rpcIdentities.ts:27]: I believe the authenticate call needs to be a duplex stream. For `TestProvider` it doesn't matter. But for `GitHubProvider` it does matter and all real providers will need to be an "interaction". This will need to convert the duplex stream to using the `prompts` library to prompt the user for more input.

Comment (joshuakarp) [reply src/client/rpcIdentities.ts:27]: I need to refresh my memory of how the authentication process actually works for our actual providers (i.e. not the `TestProvider`). Going to write a test.ts and re-augment my GitHub to map out the process that will be required for the stream.

The current test in `rpcIdentities.test.ts` assumes the easiest case of the `TestProvider`, where no back and forth is required:

```ts
  test('should authenticate an identity', async () => {
    const identitiesAuthenticate =
      grpcUtils.promisifyUnaryCall<identitiesPB.Token>(
        client,
        client.identitiesAuthenticate,
      );

    const providerMessage = new identitiesPB.Provider();
    providerMessage.setProviderId(testToken.providerId);
    providerMessage.setIdentityId(testToken.identityId);

    const codeMessage = await identitiesAuthenticate(
      providerMessage,
      callCredentials,
    );
    expect(codeMessage.getToken()).toContain('randomtestcode');
    expect(
      await polykeyAgent.identitiesManager.getToken(
        testToken.providerId,
        testToken.identityId,
      ),
    ).toEqual(testToken.tokenData);
    await polykeyAgent.identitiesManager.delToken(
      testToken.providerId,
      testToken.identityId,
    );
  });
```

and `TestProvider.authenticate` is the following:

```ts
  public async *authenticate(): AsyncGenerator<string | undefined, IdentityId> {
    const code = 'randomtestcode';
    yield code;
    // Always gives back the abc123 token
    const tokenData = { accessToken: 'abc123' };
    const identityId = await this.getIdentityId(tokenData);
    await this.putToken(identityId, tokenData);
    return identityId;
  }
```

Comment (joshuakarp) [reply src/client/rpcIdentities.ts:27]: So our `authenticate` function has the following flow:
1. We perform a request to GitHub (or some provider)
2. This produces a usercode, which is yielded to the user.
3. The user manually inputs this usercode into the opened GitHub URL
4. `authenticate` performs the remainder of the authentication. It polls on this authentication request, waiting for the usercode to be manually entered
5. After it's been entered, it finally returns the token data/identity ID

Comment (joshuakarp) [reply src/client/rpcIdentities.ts:27]: I actually don't think there's an issue with this? I've recorded myself performing a GitHub authentication with the current `authenticate` CLI command. Is this not what you expect @CMCDragonkai?

https://user-images.githubusercontent.com/49772421/146286560-f7d08772-dfd9-4832-b28f-665f66fcdf71.mp4

Comment (CMCDragonkai) [reply src/client/rpcIdentities.ts:27]: If this is a unary call how do you get the user code to the user?

Comment (CMCDragonkai) [reply src/client/rpcIdentities.ts:27]: I mean the URL?

Comment (CMCDragonkai) [reply src/client/rpcIdentities.ts:27]: Remember the agent has to tell the user to visit a URL. If the client is on a different host. They would need a URL to access. The CLI client can auto open a browser. But if it fails to do so, the url should be printed out to STDOUT and then prompt for the code?

Comment (CMCDragonkai) [reply src/client/rpcIdentities.ts:27]: I just watched the video. There are several things we need to change there:

1. The opening the browser to the authentication URL should be done on the `CommandAuthenticate.ts` which means it can execute on the client side even if the PK agent exists on a different host. The video shows this being executed by the server side which is not a good idea.
2. The automatic opening of the browser may fail because it relies on the platform specifics which may not work. This means the target URL should be displayed on the CLI side, and if the browser fails to run, it will just display the URL for the user to visit directly.
3. The user code is provided to the user to enter into the website being opened up. The message should be "Enter this Code: ". Sort of a key-value structure for the STDOUT.
4. The entire CLI call should probably only terminate when the entire authentication process is done. This ensures one can cancel the entire process if need be.

In order to solve 1./2. the `authenticate` may need to change a bit. Right now it directly calls `browser()` which means this executes on the agent side. This would be something that the CLI command would instead execute.

On the agent side, it can continue pinging the `https://github.com/login/oauth/access_token` until it acquires the token. And if it succeeds it puts that token against the identity ID.

So here's what I propose:

1. The `authenticate` process yields 2 things: the user code and the URL you're supposed to go to on your browser.
2. The GRPC handler provides 2 things in its stream. It's important to be a stream, because the last message in the stream SHOULD be the identity id.
3. The stream should a **server stream**. So you know when the authentication process has successfully completed. This allows us to communicate the agent to cancel this operation if we need to.
4. The `CommandAuthenticate.ts` takes the URL and the user code (which may be optional). For example: `public async *authenticate(timeout: number = 120000): AsyncGenerator<string | undefined, IdentityId>;` is the signature for `authenticate`. What this means that the `string | undefined` was originally for the user code. Some providers may not do this at all. Instead we need change this to `AsyncGenerator<{url: string; code?: string}, IdentityId>`. Note that the `IdentityId` is what is returned at the end.
5. The `CommandAuthenticate` uses the `browser` function to try and launch the `url`. Whether this fails or not, it will show the url on the STDOUT as well. If it does fail, a STDERR message should be provided to tell the user to try and visit the URL. The code is optional because some providers don't do this. But if it does exist, it should be some like `Enter this Code: ...`.
6. At this point, the `CommandAuthenticate` will just `await` on the stream to be finished and acquire the `IdentityId`. While this is happening, in the agent, it's polling the authentication URL to see if the authentication process has been completed. If it completes, it will then return the identity id, and this will close the stream. The `CommandAuthenticate` can then output the authenticated ID in its STDOUT.
7. This means that the CLI execution only finishes when authentication process completes.

There are some exceptions:

1. If the timeout times out, the agent actually throws the exception, this exception is thrown to the stream which should be done in the handler, it is propagated to the client. The client then outputs the error and exits the process.
2. If the authentication fails, as in the user didn't provide the right user code or if the authentication was rejected, then an exception will be propagated to the client as well.
3. The client side may cancel/close the request. That would mean the client side tries to close the stream. If the client side closes the stream. The server side should handle this and stop what it is doing. This can be done by throwing an exception into `AsyncGenerator`. It would be `new ErrorProviderAuthentication()`. But note that the poll loop will have to timeout: https://github.com/MatrixAI/js-polykey/issues/297#issuecomment-995363066

Comment (CMCDragonkai) [reply src/client/rpcIdentities.ts:27]: So try this instead:

```
AsyncGenerator<{ url: string; [key: string]: string; }, IdentityId>
```

This allows arbitrary data which may be useful for future providers. Any of this data would be printed out on the CLI for the user to use to authenticate.

Then on the GRPC protobuf, you would need an a message with arbitrary number of data. This could be a map. There's always the JSON encode. You could try using the `Struct` or directly with `map`.

Comment (CMCDragonkai) [reply src/client/rpcIdentities.ts:27]: On the CLI side, you can use the output formatter for an arbitrary dictionary to display.

Comment (joshuakarp) [reply src/client/rpcIdentities.ts:27]: Given that we're using `[key: string]: string;` in `AsyncGenerator<{ url: string; [key: string]: string; }, IdentityId>`, we can enforce this at the proto level too.

i.e. instead of using the `Struct` type (that supports `Value`s of any type), we can just use a `map<string, string>` for the extra data.

Comment (joshuakarp) [reply src/client/rpcIdentities.ts:27]: Remaining TODOs for this:
- [x] - add required protobuf messages
- [x] - adjust corresponding GRPC calls/signatures
- `GithubProvider`:
   * [x] - adjust async generator return types
   * [x] - remove `browser` call
- `rpcIdentities.identitiesAuthenticate`
   * [x] - change to using the stream
   * [x] - add support for arbitrary data with `[key: string]: string` 
   * [x] - adjust flow to utilise the generator and corresponding calls to stream
   * [x] - remove callbacks
   * [x] - add exception handling (and propagate to stream closures)
- `CommandAuthenticate`:
   * [x] - add `browser` call here
   * [x] - adjust output to display URL, user code (where necessary) and appropriate messaging
   * [x] - change to using the stream

**Comment by CMCDragonkai** [comment]
The map used in protobuf is not a ES6 map. It's google-protobuf library's own map. The documentation is here:

* https://github.com/protocolbuffers/protobuf/blob/master/js/map.js

To convert it to a POJO:

```ts
// this is the closest way to do it, the X is whatever the field name is
Object.fromEntries(message.getXMap().entries());
```

**Comment by CMCDragonkai** [comment]
The provider authentication is working now. Naming of the protobuf messages came from https://datatracker.ietf.org/doc/html/rfc6749.

However there is one problem.

We have not dealt with stream cancellation from the client side.

If the client side cancels the stream, the server does not listen for this event. Therefore subsequent write calls just hang forever. And server does not have deadlines, so it's just hanging forever.

For example in the `identitiesAuthenticate` handler:

At the end where it tries to:

```ts
        await genWritable.next(authProcess);
        await genWritable.next(null);
```

The first call to write may never return and finish if the client has already cancelled the stream that `genWritable` is trying to write.

This is because in our grpc utilities, we have not been listening for any kind of cancellation event. But more over we don't even have a server-side deadline system.

There should 3 potential events that we will need to address in a later PR targetting #249 and #243 and #297:

1. Deadline exceeded from client
2. Client cancellation
3. Timeout on server side when handling ANY stream/call - this is the last resort, if it reaches here, it means the client is so slow, the server just aborts whatever it is doing

File: src/client/rpcIdentities.ts (hunk 11 above)
Comment (CMCDragonkai) [reply src/client/rpcIdentities.ts:27]: It's working for now, so this can be resolved.

**Comment by CMCDragonkai** [comment]
@joshuakarp You need to update the `TestProvider` to do the same as `GitHubProvider` just as a dummy.

Unsuccessful cases in `TestProvider` is not testable yet. We'll have to address how to make our `TestProvider` more dynamic later.

**Comment by CMCDragonkai** [comment]
After verifying all tests, lint, squash, and prepare to merge.

**Comment by joshuakarp** [comment]
Running tests:

* tests/bin: `list secrets` failed in `secret.test.ts` with a timeout error, but all others passed. The test passes when run on its own in both this branch and master. ~~Also, because we've moved the `browser` call to `CommandAuthenticate` now, it does open a browser to `test.com` (the url used to "authenticate"). Will look into mocking this.~~ this is now being correctly mocked as an empty function

<details>

```
~/Documents/Projects/js-polykey(identities-augment) » npm test -- tests/bin

> @matrixai/polykey@1.0.0 test /home/josh/Documents/Projects/js-polykey
> jest "tests/bin"

Determining test suites to run...
GLOBAL SETUP
Creating global.keyPairDir: /tmp/polykey-test-keypair
Creating global.binAgentDir: /tmp/polykey-test-bin
 PASS  tests/bin/identities.test.ts (47.781 s)
  CLI Identities
    commandAllowGestalts
      ✓ Should allow permissions on node. (435 ms)
      ✓ Should allow permissions on Identity. (829 ms)
      ✓ Should fail on invalid inputs. (371 ms)
    commandDisallowGestalts
      ✓ Should disallow permissions on Node. (141 ms)
      ✓ Should disallow permissions on Identity. (247 ms)
      ✓ Should fail on invalid inputs. (356 ms)
    commandPermissionsGestalts
      ✓ Should get permissions on Node. (183 ms)
      ✓ Should get permissions on Identity. (228 ms)
    commandTrustGestalts
      ✓ Should set trust on Node. (144 ms)
      ✓ Should set trust on Identity. (107 ms)
      ✓ Should fail on invalid inputs. (190 ms)
    commandUntrustGestalts
      ✓ Should unset trust on Node. (153 ms)
      ✓ Should unset trust on Identity. (122 ms)
      ✓ Should fail on invalid inputs. (296 ms)
    commandClaimIdentity
      ✓ Should claim an identity. (194 ms)
      ✓ Should fail for unauthenticated identities. (99 ms)
    commandAuthenticateProvider
      ✓ Should authenticate an identity with a provider. (259 ms)
    commandGetGestalts
      ✓ Should list gestalt by Node (160 ms)
      ✓ Should list gestalt by Identity (122 ms)
    commandListGestalts
      ✓ Should list gestalts with permissions. (567 ms)
    commandSearchIdentities
      ✓ Should find a connected identity. (141 ms)
    commandDiscoverGestalts
      ✓ Should start discovery by Node (3569 ms)
      ✓ Should start discovery by Identity (1896 ms)

 PASS  tests/bin/notifications.test.ts (48.022 s)
  CLI Notifications
    commandSendNotification
      ✓ Should send notification with permission. (970 ms)
      ✓ Should send notification without permission. (145 ms)
    commandReadNotifications
      ✓ Should read all notifications. (699 ms)
      ✓ Should read all unread notifications. (734 ms)
      ✓ Should read a fixed number of notifications. (510 ms)
      ✓ Should read notifications in reverse order. (605 ms)
      ✓ Should read no notifications. (74 ms)
      ✓ Should read all types of notifications. (360 ms)
    commandClearNotifications
      ✓ Should remove all notifications. (539 ms)

 PASS  tests/bin/utils.retryAuth.test.ts
  bin/utils retryAuthentication
    ✓ no retry on success (6 ms)
    ✓ no retry on generic error (5 ms)
    ✓ no retry on unattended call with PK_TOKEN and PK_PASSWORD (4 ms)
    ✓ no retry on unattended call with PK_TOKEN (2 ms)
    ✓ no retry on unattended call with PK_PASSWORD (2 ms)
    ✓ retry once on clientErrors.ErrorClientAuthMissing (5 ms)
    ✓ retry 2 times on clientErrors.ErrorClientAuthDenied (4 ms)
    ✓ retry 2+ times on clientErrors.ErrorClientAuthDenied until generic error (5 ms)

 PASS  tests/bin/keys.test.ts (70.175 s)
  CLI keys
    commandCertChain
      ✓ should get the certificate chain (2294 ms)
    commandGetCert
      ✓ should get the certificate (2192 ms)
    commandGetRootKeypair
      ✓ should get the root keypair (2007 ms)
    commandEncryptKeys
      ✓ should encrypt data (2000 ms)
    commandDecryptKeys
      ✓ should decrypt data (2688 ms)
    commandSignKeys
      ✓ should sign a file (2542 ms)
    commandVerifyKeys
      ✓ should verify a file (2092 ms)
    commandRenewKeypair
      ✓ should renew the keypair (12833 ms)
    commandResetKeyPair
      ✓ should reset the keypair (13023 ms)
    commandChangePassword
      ✓ should change the root password (9215 ms)

 FAIL  tests/bin/secret.test.ts (118.294 s)
  CLI secrets
    commandCreateSecret
      ✓ should create secrets (7781 ms)
    commandDeleteSecret
      ✓ should delete secrets (8335 ms)
    commandGetSecret
      ✓ should retrieve secrets (7466 ms)
    commandListSecrets
      ✕ should list secrets (20001 ms)
    commandNewDir
      ✓ should make a directory (14141 ms)
    commandRenameSecret
      ✓ should rename secrets (9193 ms)
    commandUpdateSecret
      ✓ should update secrets (8218 ms)
    commandNewDirSecret
      ✓ should add a directory of secrets (7552 ms)

  ● CLI secrets › commandListSecrets › should list secrets

    : Timeout - Async callback was not invoked within the 20000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 20000 ms timeout specified by jest.setTimeout.Error:

      125 |   });
      126 |   describe('commandListSecrets', () => {
    > 127 |     test('should list secrets', async () => {
          |     ^
      128 |       const vaultName = 'Vault4' as VaultName;
      129 |       const vault = await polykeyAgent.vaultManager.createVault(vaultName);
      130 |

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (tests/bin/secret.test.ts:127:5)

 PASS  tests/bin/bootstrap.test.ts (126.648 s)
  bootstrap
    ✓ bootstraps node state (28392 ms)
    ✓ bootstrapping occupied node state (19497 ms)
    ✓ concurrent bootstrapping are coalesced (16818 ms)
    ✓ bootstrap when interrupted, requires fresh on next bootstrap (38287 ms)

 PASS  tests/bin/vaults.test.ts (133.889 s)
  CLI vaults
    commandListVaults
      ✓ should list all vaults (6139 ms)
    commandCreateVaults
      ✓ should create vaults (4362 ms)
    commandRenameVault
      ✓ should rename vault (1467 ms)
      ✓ should fail to rename non-existent vault (1796 ms)
    commandDeleteVault
      ✓ should delete vault (4765 ms)
    commandVaultStats
      ○ skipped should return the stats of a vault
    commandSetPermsVault
      ○ skipped should share a vault
    commandUnsetPermsVault
      ○ skipped should un-share a vault
    commandVaultPermissions
      ○ skipped should get permissions of a vault
    commandPullVault
      ○ skipped should clone a vault
      ○ skipped should pull a vault
    commandScanVault
      ○ skipped should scan a node for vaults
    commandVaultVersion
      ✓ should switch the version of a vault (12992 ms)
      ✓ should switch the version of a vault to the latest version (14156 ms)
      ✓ should handle invalid version IDs (2573 ms)
      ✓ should throw an error if the vault is not found (80 ms)
    commandVaultLog
      ✓ Should get all commits (16188 ms)
      ✓ should get a part of the log (16842 ms)
      ✓ should get a specific commit (16439 ms)
      ✎ todo test formatting of the output

 PASS  tests/bin/agent/stop.test.ts (88.189 s)
  stop
    ✓ stop LIVE agent (25933 ms)
    ✓ stopping is idempotent during concurrent calls and STOPPING or DEAD status (23710 ms)
    ✓ stopping starting agent results in error (15791 ms)
    ✓ stopping while unauthenticated does not stop (21305 ms)

 PASS  tests/bin/sessions.test.ts (25.103 s)
  CLI Sessions
    ✓ serial commands refresh the session token (2953 ms)
    ✓ unattended commands with invalid authentication should fail (1594 ms)
    ✓ prompt for password to authenticate attended commands (744 ms)
    ✓ re-prompts for password if unable to authenticate command (1356 ms)

 PASS  tests/bin/utils.test.ts
  bin/utils
    ✓ list in human and json format (1 ms)
    ✓ table in human and in json format
    ✓ dict in human and in json format (1 ms)

 PASS  tests/bin/polykey.test.ts
  polykey
    ✓ default help display (35 ms)

 PASS  tests/bin/agent/lockall.test.ts (21.15 s)
  lockall
    ✓ lockall deletes the session token (672 ms)
    ✓ lockall ensures reauthentication is required (1297 ms)
    ✓ lockall causes old session tokens to fail (1307 ms)

 PASS  tests/bin/agent/lock.test.ts (16.759 s)
  lock
    ✓ lock deletes the session token (643 ms)
    ✓ lock ensures reauthentication is required (1343 ms)

 PASS  tests/bin/agent/unlock.test.ts (11.912 s)
  unlock
    ✓ unlock acquires session token (934 ms)

 PASS  tests/bin/agent/status.test.ts (40.457 s)
  status
    ✓ status on STARTING, STOPPING, DEAD agent (13277 ms)
    ✓ status on missing agent (12 ms)
    status with global agent
      ✓ status on LIVE agent (883 ms)
      ✓ status on remote LIVE agent (992 ms)

 PASS  tests/bin/agent/start.test.ts (165.511 s)
  start
    ✓ start in foreground (16997 ms)
    ✓ start in background (15847 ms)
    ✓ concurrent starts are coalesced (8998 ms)
    ✓ concurrent bootstrap is coalesced (7359 ms)
    ✓ start with existing state (19499 ms)
    ✓ start when interrupted, requires fresh on next start (26731 ms)
    ✓ start from recovery code (42197 ms)
    ✓ start with network configuration (5788 ms)

 PASS  tests/bin/nodes.test.ts (175.838 s)
  CLI Nodes
    commandClaimNode
      ✓ Should send a gestalt invite (775 ms)
      ✓ Should send a gestalt invite (force invite) (841 ms)
      ✓ Should claim remote node (380 ms)
    commandPingNode
      ✓ Should return failure when pinging an offline node (43250 ms)
      ✓ Should return failure if can't find the node (41621 ms)
      ✓ Should return success when pinging a live node (228 ms)
    commandFindNode
      ✓ Should find an online node (197 ms)
      ✓ Should find an offline node (146 ms)
      ✓ Should fail to find an unknown node (40921 ms)
    commandAddNode
      ✓ Should add the node (36 ms)
      ✓ Should fail to add the node (invalid node ID) (25 ms)
      ✓ Should fail to add the node (invalid IP address) (30 ms)

Test Suites: 1 failed, 16 passed, 17 total
Tests:       1 failed, 7 skipped, 1 todo, 115 passed, 124 total
Snapshots:   0 total
Time:        176.138 s
Ran all test suites matching /tests\/bin/i.
GLOBAL TEARDOWN
Destroying global.keyPairDir: /tmp/polykey-test-keypair
Destroying global.binAgentDir: /tmp/polykey-test-bin
npm ERR! Test failed.  See above for more details.

```

</details>

* running these bin tests a second time produced different timeout errors, so I'm not too worried:

<details>

```
~/Documents/Projects/js-polykey(identities-augment) » npm test -- tests/bin/         

> @matrixai/polykey@1.0.0 test /home/josh/Documents/Projects/js-polykey
> jest "tests/bin/"

Determining test suites to run...
GLOBAL SETUP
Creating global.keyPairDir: /tmp/polykey-test-keypair
Creating global.binAgentDir: /tmp/polykey-test-bin
 PASS  tests/bin/notifications.test.ts (31.534 s)
  CLI Notifications
    commandSendNotification
      ✓ Should send notification with permission. (1725 ms)
      ✓ Should send notification without permission. (228 ms)
    commandReadNotifications
      ✓ Should read all notifications. (1010 ms)
      ✓ Should read all unread notifications. (963 ms)
      ✓ Should read a fixed number of notifications. (558 ms)
      ✓ Should read notifications in reverse order. (693 ms)
      ✓ Should read no notifications. (57 ms)
      ✓ Should read all types of notifications. (398 ms)
    commandClearNotifications
      ✓ Should remove all notifications. (708 ms)

 PASS  tests/bin/identities.test.ts (35.234 s)
  CLI Identities
    commandAllowGestalts
      ✓ Should allow permissions on node. (282 ms)
      ✓ Should allow permissions on Identity. (428 ms)
      ✓ Should fail on invalid inputs. (335 ms)
    commandDisallowGestalts
      ✓ Should disallow permissions on Node. (143 ms)
      ✓ Should disallow permissions on Identity. (158 ms)
      ✓ Should fail on invalid inputs. (298 ms)
    commandPermissionsGestalts
      ✓ Should get permissions on Node. (151 ms)
      ✓ Should get permissions on Identity. (164 ms)
    commandTrustGestalts
      ✓ Should set trust on Node. (155 ms)
      ✓ Should set trust on Identity. (151 ms)
      ✓ Should fail on invalid inputs. (212 ms)
    commandUntrustGestalts
      ✓ Should unset trust on Node. (154 ms)
      ✓ Should unset trust on Identity. (149 ms)
      ✓ Should fail on invalid inputs. (213 ms)
    commandClaimIdentity
      ✓ Should claim an identity. (182 ms)
      ✓ Should fail for unauthenticated identities. (122 ms)
    commandAuthenticateProvider
      ✓ Should authenticate an identity with a provider. (228 ms)
    commandGetGestalts
      ✓ Should list gestalt by Node (147 ms)
      ✓ Should list gestalt by Identity (143 ms)
    commandListGestalts
      ✓ Should list gestalts with permissions. (506 ms)
    commandSearchIdentities
      ✓ Should find a connected identity. (151 ms)
    commandDiscoverGestalts
      ✓ Should start discovery by Node (4458 ms)
      ✓ Should start discovery by Identity (1667 ms)

 PASS  tests/bin/keys.test.ts (69.485 s)
  CLI keys
    commandCertChain
      ✓ should get the certificate chain (2847 ms)
    commandGetCert
      ✓ should get the certificate (2310 ms)
    commandGetRootKeypair
      ✓ should get the root keypair (2340 ms)
    commandEncryptKeys
      ✓ should encrypt data (3058 ms)
    commandDecryptKeys
      ✓ should decrypt data (3153 ms)
    commandSignKeys
      ✓ should sign a file (2535 ms)
    commandVerifyKeys
      ✓ should verify a file (2511 ms)
    commandRenewKeypair
      ✓ should renew the keypair (13849 ms)
    commandResetKeyPair
      ✓ should reset the keypair (15456 ms)
    commandChangePassword
      ✓ should change the root password (9467 ms)

 PASS  tests/bin/agent/stop.test.ts (112.971 s)
  stop
    ✓ stop LIVE agent (31994 ms)
    ✓ stopping is idempotent during concurrent calls and STOPPING or DEAD status (28428 ms)
    ✓ stopping starting agent results in error (12746 ms)
    ✓ stopping while unauthenticated does not stop (37801 ms)

 PASS  tests/bin/agent/status.test.ts (49.267 s)
  status
    ✓ status on STARTING, STOPPING, DEAD agent (13816 ms)
    ✓ status on missing agent (19 ms)
    status with global agent
      ✓ status on LIVE agent (1881 ms)
      ✓ status on remote LIVE agent (1411 ms)

 PASS  tests/bin/sessions.test.ts (16.781 s)
  CLI Sessions
    ✓ serial commands refresh the session token (4572 ms)
    ✓ unattended commands with invalid authentication should fail (3200 ms)
    ✓ prompt for password to authenticate attended commands (1564 ms)
    ✓ re-prompts for password if unable to authenticate command (2783 ms)

 FAIL  tests/bin/vaults.test.ts (131.302 s)
  CLI vaults
    commandListVaults
      ✓ should list all vaults (9252 ms)
    commandCreateVaults
      ✓ should create vaults (7167 ms)
    commandRenameVault
      ✓ should rename vault (2493 ms)
      ✓ should fail to rename non-existent vault (2312 ms)
    commandDeleteVault
      ✓ should delete vault (2749 ms)
    commandVaultStats
      ○ skipped should return the stats of a vault
    commandSetPermsVault
      ○ skipped should share a vault
    commandUnsetPermsVault
      ○ skipped should un-share a vault
    commandVaultPermissions
      ○ skipped should get permissions of a vault
    commandPullVault
      ○ skipped should clone a vault
      ○ skipped should pull a vault
    commandScanVault
      ○ skipped should scan a node for vaults
    commandVaultVersion
      ✓ should switch the version of a vault (13425 ms)
      ✓ should switch the version of a vault to the latest version (14519 ms)
      ✓ should handle invalid version IDs (2452 ms)
      ✓ should throw an error if the vault is not found (77 ms)
    commandVaultLog
      ✓ Should get all commits (21788 ms)
      ✕ should get a part of the log (23204 ms)
      ✓ should get a specific commit (17663 ms)
      ✎ todo test formatting of the output

  ● CLI vaults › commandVaultLog › should get a part of the log

    Timeout - Async callback was not invoked within the 20000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 20000 ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:27:45)

  ● CLI vaults › commandVaultLog › should get a part of the log

    expect(received).toContain(expected) // indexOf

    Expected substring: "821749c0d5cc1aa267d1f3847c015595ad92fdb6"
    Received string:    "commit ff3b7b30da40134efaeeaa33530865b140dd967d
    committer v05ro48c0l893rl18bnqreutai37atrqf5d7rsb3mlqr532mr4vsg
    Date: Fri Dec 17 2021
    secret2 deleted·
    commit 714aefa27daf815900d04e9f5af58bb5655db071
    committer v05ro48c0l893rl18bnqreutai37atrqf5d7rsb3mlqr532mr4vsg
    Date: Fri Dec 17 2021
    secret2 added·
    "

      643 |       expect(result.stdout).not.toContain(commit1Oid);
      644 |       expect(result.stdout).toContain(commit2Oid);
    > 645 |       expect(result.stdout).toContain(commit3Oid);
          |                             ^
      646 |     });
      647 |     test('should get a specific commit', async () => {
      648 |       const command = [

      at Object.<anonymous> (tests/bin/vaults.test.ts:645:29)
          at runMicrotasks (<anonymous>)

 PASS  tests/bin/agent/lock.test.ts (5.377 s)
  lock
    ✓ lock deletes the session token (1766 ms)
    ✓ lock ensures reauthentication is required (2323 ms)

 PASS  tests/bin/utils.retryAuth.test.ts
  bin/utils retryAuthentication
    ✓ no retry on success (2 ms)
    ✓ no retry on generic error (5 ms)
    ✓ no retry on unattended call with PK_TOKEN and PK_PASSWORD (2 ms)
    ✓ no retry on unattended call with PK_TOKEN (2 ms)
    ✓ no retry on unattended call with PK_PASSWORD (8 ms)
    ✓ retry once on clientErrors.ErrorClientAuthMissing (4 ms)
    ✓ retry 2 times on clientErrors.ErrorClientAuthDenied (2 ms)
    ✓ retry 2+ times on clientErrors.ErrorClientAuthDenied until generic error (3 ms)

 PASS  tests/bin/polykey.test.ts
  polykey
    ✓ default help display (37 ms)

 PASS  tests/bin/utils.test.ts
  bin/utils
    ✓ list in human and json format (2 ms)
    ✓ table in human and in json format (2 ms)
    ✓ dict in human and in json format (2 ms)

 PASS  tests/bin/agent/unlock.test.ts (7.238 s)
  unlock
    ✓ unlock acquires session token (1730 ms)

 FAIL  tests/bin/bootstrap.test.ts (142.26 s)
  bootstrap
    ✓ bootstraps node state (24169 ms)
    ✕ bootstrapping occupied node state (52779 ms)
    ✕ concurrent bootstrapping are coalesced (21117 ms)
    ✕ bootstrap when interrupted, requires fresh on next bootstrap (40574 ms)

  ● bootstrap › bootstrapping occupied node state

    : Timeout - Async callback was not invoked within the 40000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 40000 ms timeout specified by jest.setTimeout.Error:

      54 |     global.defaultTimeout * 2,
      55 |   );
    > 56 |   test(
         |   ^
      57 |     'bootstrapping occupied node state',
      58 |     async () => {
      59 |       const password = 'password';

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (tests/bin/bootstrap.test.ts:56:3)

  ● bootstrap › concurrent bootstrapping are coalesced

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 1

      103 |         dataDir,
      104 |       ));
    > 105 |       expect(exitCode).toBe(0);
          |                        ^
      106 |       const recoveryCode = stdout.trim();
      107 |       expect(
      108 |         recoveryCode.split(' ').length === 12 ||

      at Object.<anonymous> (tests/bin/bootstrap.test.ts:105:24)

  ● bootstrap › bootstrap when interrupted, requires fresh on next bootstrap

    : Timeout - Async callback was not invoked within the 40000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 40000 ms timeout specified by jest.setTimeout.Error:

      184 |     global.defaultTimeout * 2,
      185 |   );
    > 186 |   test(
          |   ^
      187 |     'bootstrap when interrupted, requires fresh on next bootstrap',
      188 |     async () => {
      189 |       const password = 'password';

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (tests/bin/bootstrap.test.ts:186:3)

  ● bootstrap › bootstrap when interrupted, requires fresh on next bootstrap

    ENOTEMPTY: directory not empty, rmdir '/tmp/polykey-test-jHNa1T/polykey/state/keys'



INFO:KeyManager:Started KeyManager
INFO:KeyManager:Created KeyManager
INFO:DB:Creating DB
INFO:DB:Starting DB
INFO:DB:Setting DB path to /tmp/polykey-test-jHNa1T/polykey/state/db
INFO:DB:Started DB
INFO:DB:Created DB
INFO:IdentitiesManager:Creating IdentitiesManager
INFO:IdentitiesManager:Starting IdentitiesManager
INFO:IdentitiesManager:Started IdentitiesManager
INFO:IdentitiesManager:Created IdentitiesManager
INFO:Sigchain:Creating Sigchain
INFO:Sigchain:Starting Sigchain
INFO:Sigchain:Started Sigchain
INFO:Sigchain:Created Sigchain
INFO:ACL:Creating ACL
INFO:ACL:Starting ACL
INFO:ACL:Started ACL
INFO:ACL:Created ACL
INFO:GestaltGraph:Creating GestaltGraph
INFO:GestaltGraph:Starting GestaltGraph
INFO:GestaltGraph:Started GestaltGraph
INFO:GestaltGraph:Created GestaltGraph
INFO:ForwardProxy:Creating Forward Proxy
INFO:ForwardProxy:Created Forward Proxy
INFO:ReverseProxy:Creating Reverse Proxy
INFO:ReverseProxy:Created Reverse Proxy
INFO:NodeManager:Creating NodeManager
INFO:NodeManager:Starting NodeManager
INFO:NodeManager:Creating NodeGraph
INFO:NodeManager:Starting NodeGraph
INFO:NodeManager:Started NodeGraph
INFO:NodeManager:Created NodeGraph
INFO:NodeManager:Started NodeManager
INFO:NodeManager:Created NodeManager
INFO:VaultManager:Creating VaultManager
INFO:VaultManager:Created VaultManager
INFO:VaultManager:Starting VaultManager
INFO:VaultManager:Removing vaults directory at '/tmp/polykey-test-jHNa1T/polykey/state/vaults'
INFO:DB:Creating DB
INFO:DB:Starting DB
INFO:DB:Setting DB path to /tmp/polykey-test-jHNa1T/polykey/state/vaults
INFO:DB:Started DB
INFO:DB:Created DB
INFO:VaultManager:Starting EncryptedFS
INFO:VaultManager:Started EncryptedFS
INFO:VaultManager:Started VaultManager
INFO:NotificationsManager:Creating NotificationsManager
INFO:NotificationsManager:Starting NotificationsManager
INFO:NotificationsManager:Started NotificationsManager
INFO:NotificationsManager:Created NotificationsManager
INFO:SessionManager:Creating SessionManager
INFO:SessionManager:Starting SessionManager
INFO:SessionManager:Generating sessions key
INFO:SessionManager:Started SessionManager
INFO:SessionManager:Created SessionManager
INFO:polykey:Begin Status STOPPING
INFO:polykey:Writing Status file to /tmp/polykey-test-jHNa1T/polykey/status.json
INFO:polykey:Status is STOPPING
INFO:SessionManager:Stopping SessionManager
INFO:SessionManager:Stopped SessionManager
INFO:NotificationsManager:Stopping NotificationsManager
INFO:NotificationsManager:Stopped NotificationsManager
INFO:VaultManager:Stopping VaultManager
INFO:VaultManager:Stopping EncryptedFS
INFO:DB:Stopping DB
INFO:DB:Stopped DB
INFO:VaultManager:Stopped EncryptedFS
INFO:VaultManager:Stopped VaultManager
INFO:NodeManager:Stopping NodeManager
INFO:NodeManager:Stopping NodeGraph
INFO:NodeManager:Stopped NodeGraph
INFO:NodeManager:Stopped NodeManager
INFO:GestaltGraph:Stopping GestaltGraph
INFO:GestaltGraph:Stopped GestaltGraph
INFO:ACL:Stopping ACL
INFO:ACL:Stopped ACL
INFO:Sigchain:Stopping Sigchain
INFO:Sigchain:Stopped Sigchain
INFO:IdentitiesManager:Stopping IdentitiesManager
INFO:IdentitiesManager:Stopped IdentitiesManager
INFO:DB:Stopping DB
INFO:DB:Stopped DB
INFO:KeyManager:Stopping KeyManager
INFO:KeyManager:Stopped KeyManager
INFO:Schema:Stopping Schema
INFO:Schema:Stopped Schema
INFO:polykey:Stopping Status
INFO:polykey:Writing Status file to /tmp/polykey-test-jHNa1T/polykey/status.json
INFO:polykey:Status is DEAD
INFO:polykey:Bootstrapped /tmp/polykey-test-jHNa1T/polykey
(node:146958) UnhandledPromiseRejectionWarning: Error: Caught error after test environment was torn down

expect(received).toBe(expected) // Object.is equality

Expected: true
Received: false
(Use `node --trace-warnings ...` to show where the warning was created)
(node:146958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:146958) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
judge impulse disease elite ivory swamp gun child ask weather slow pupil enter blame symbol slide arctic vessel vacuum assist ginger brave timber sun
INFO:ReverseProxy:Stopped Reverse Proxy
INFO:ForwardProxy:Stopping Forward Proxy Server
INFO:ForwardProxy:Stopped Forward Proxy Server
INFO:GRPCServerAgent:Stopping GRPCServer
INFO:GRPCServerAgent:Stopped GRPCServer
INFO:GRPCServerClient:Stopping GRPCServer
INFO:GRPCServerClient:Stopped GRPCServer
INFO:GestaltGraph:Stopping GestaltGraph
INFO:GestaltGraph:Stopped GestaltGraph
INFO:ACL:Stopping ACL
INFO:ACL:Stopped ACL
INFO:Sigchain:Stopping Sigchain
INFO:Sigchain:Stopped Sigchain
INFO:IdentitiesManager:Stopping IdentitiesManager
INFO:IdentitiesManager:Stopped IdentitiesManager
INFO:DB:Stopping DB
INFO:DB:Stopped DB
INFO:KeyManager:Stopping KeyManager
INFO:KeyManager:Stopped KeyManager
INFO:Schema:Stopping Schema
INFO:Schema:Stopped Schema
INFO:Status:Stopping Status
INFO:Status:Writing Status file to /tmp/polykey-test-bin/status.json
INFO:Status:Status is DEAD
INFO:PolykeyAgent:Stopped PolykeyAgent
 PASS  tests/bin/agent/lockall.test.ts (32.631 s)
  lockall
    ✓ lockall deletes the session token (1469 ms)
    ✓ lockall ensures reauthentication is required (2675 ms)
    ✓ lockall causes old session tokens to fail (1762 ms)

 PASS  tests/bin/agent/start.test.ts (154.22 s)
  start
    ✓ start in foreground (16053 ms)
    ✓ start in background (17966 ms)
    ✓ concurrent starts are coalesced (10150 ms)
    ✓ concurrent bootstrap is coalesced (7685 ms)
    ✓ start with existing state (20025 ms)
    ✓ start when interrupted, requires fresh on next start (27912 ms)
    ✓ start from recovery code (44367 ms)
    ✓ start with network configuration (8061 ms)

 PASS  tests/bin/secret.test.ts (86.285 s)
  CLI secrets
    commandCreateSecret
      ✓ should create secrets (8533 ms)
    commandDeleteSecret
      ✓ should delete secrets (10543 ms)
    commandGetSecret
      ✓ should retrieve secrets (7254 ms)
    commandListSecrets
      ✓ should list secrets (19434 ms)
    commandNewDir
      ✓ should make a directory (13623 ms)
    commandRenameSecret
      ✓ should rename secrets (7031 ms)
    commandUpdateSecret
      ✓ should update secrets (4864 ms)
    commandNewDirSecret
      ✓ should add a directory of secrets (4110 ms)

 PASS  tests/bin/nodes.test.ts (163.39 s)
  CLI Nodes
    commandClaimNode
      ✓ Should send a gestalt invite (834 ms)
      ✓ Should send a gestalt invite (force invite) (1053 ms)
      ✓ Should claim remote node (455 ms)
    commandPingNode
      ✓ Should return failure when pinging an offline node (43196 ms)
      ✓ Should return failure if can't find the node (42267 ms)
      ✓ Should return success when pinging a live node (330 ms)
    commandFindNode
      ✓ Should find an online node (463 ms)
      ✓ Should find an offline node (269 ms)
      ✓ Should fail to find an unknown node (41615 ms)
    commandAddNode
      ✓ Should add the node (35 ms)
      ✓ Should fail to add the node (invalid node ID) (22 ms)
      ✓ Should fail to add the node (invalid IP address) (25 ms)

Test Suites: 2 failed, 15 passed, 17 total
Tests:       4 failed, 7 skipped, 1 todo, 112 passed, 124 total
Snapshots:   0 total
Time:        163.709 s, estimated 176 s
Ran all test suites matching /tests\/bin\//i.
GLOBAL TEARDOWN
Destroying global.keyPairDir: /tmp/polykey-test-keypair
Destroying global.binAgentDir: /tmp/polykey-test-bin
npm ERR! Test failed.  See above for more details.
----------------------------------------------------
```

</details>

* tests/client: all passing

<details>

```
~/Documents/Projects/js-polykey(identities-augment*) » npm test -- tests/client 

> @matrixai/polykey@1.0.0 test /home/josh/Documents/Projects/js-polykey
> jest "tests/client"

Determining test suites to run...
GLOBAL SETUP
Creating global.keyPairDir: /tmp/polykey-test-keypair
Creating global.binAgentDir: /tmp/polykey-test-bin
 PASS  tests/client/rpcIdentities.test.ts (24.281 s)
  Identities Client service
    ✓ should authenticate an identity (337 ms)
    ✓ should manipulate tokens for providers (177 ms)
    ✓ should list providers. (51 ms)
    ✓ should list connected Identities. (50 ms)
    ✓ should get identity info. (67 ms)
    ✓ should claim an identity. (116 ms)

 PASS  tests/client/GRPCClientClient.test.ts (24.789 s)
  GRPCClientClient
    ✓ cannot be called when destroyed (150 ms)
    ✓ can get status (2313 ms)

 PASS  tests/client/rpcGestalts.test.ts (30.325 s)
  Client service
    ✓ should get all gestalts (436 ms)
    ✓ should set independent node and identity gestalts (134 ms)
    ✓ should get gestalt from Node. (230 ms)
    ✓ should get gestalt from identity. (269 ms)
    ✓ should discover gestalt via Node. (220 ms)
    ✓ should discover gestalt via Identity. (57 ms)
    ✓ should get gestalt permissions by node. (147 ms)
    ✓ should get gestalt permissions by Identity. (159 ms)
    ✓ should set gestalt permissions by node. (174 ms)
    ✓ should set gestalt permissions by Identity. (225 ms)
    ✓ should unset gestalt permissions by node. (152 ms)
    ✓ should unset gestalt permissions by Identity. (156 ms)

 PASS  tests/client/rpcAgent.test.ts (7.749 s)
  Agent client service
    ✓ stopping the agent (49 ms)

 PASS  tests/client/rpcSessions.test.ts (8.323 s)
  Sessions client service
    ✓ can request a session (38 ms)
    ✓ can lock all sessions (34 ms)

 PASS  tests/client/rpcKeys.test.ts (36.999 s)
  Keys client service
    ✓ should get root keypair (137 ms)
    ✓ should reset root keypair (7038 ms)
    ✓ should renew root keypair (5158 ms)
    ✓ should encrypt and decrypt with root keypair (262 ms)
    ✓ should sign and verify with root keypair (290 ms)
    ✓ should get the root certificate and chains (91 ms)

 PASS  tests/client/rpcVaults.test.ts (37.368 s)
  Vaults client service
    Vaults
      ○ skipped should get vaults
      ○ skipped should create vault
      ○ skipped should delete vaults
      ○ skipped should rename vaults
      Version
        ○ skipped should switch a vault to a version
        ○ skipped should fail to find a non existent version
      Vault Log
        ○ skipped should get the full log
        ○ skipped should get a part of the log
        ○ skipped should get a specific commit
    Secrets
      ✓ should add a directory of secrets in a vault (12326 ms)
      ○ skipped should make a directory in a vault
      ○ skipped should list secrets in a vault
      ○ skipped should delete secrets in a vault
      ○ skipped should edit secrets in a vault
      ○ skipped should get secrets in a vault
      ○ skipped should rename secrets in a vault
      ○ skipped should add secrets in a vault

 PASS  tests/client/rpcNotifications.test.ts (39.998 s)
  Notifications client service
    Notifications RPC
      ✓ should send notifications. (631 ms)
      ✓ should read all notifications. (730 ms)
      ✓ should read a single notification. (146 ms)
      ✓ should clear all notifications. (117 ms)

ERROR:rpcNodes Test:Failed CONNECT to 127.0.0.2:22222 - ErrorConnectionStartTimeout
  console.error
    Failed to connect to 127.0.0.2:22222/?nodeId=vi3et1hrpv2m2lrplcm7cu913kr45v51cak54vm68anlbvuf83ra0 through proxy 127.0.0.1:39955 with status 400

      at Object.<anonymous>.exports.log (node_modules/@grpc/grpc-js/src/logging.ts:57:13)
      at ClientRequest.<anonymous> (node_modules/@grpc/grpc-js/src/http_proxy.ts:269:9)

 FAIL  tests/client/rpcNodes.test.ts (88.455 s)
  Client service
    ✓ should add a node (123 ms)
    ✕ should ping a node (online + offline) (34158 ms)
    ✓ should find a node (local) (13 ms)
    ✓ should find a node (contacts remote node) (202 ms)
    ✓ should fail to find a node (contacts remote node) (20261 ms)
    ✓ should send a gestalt invite (no existing invitation) (32 ms)
    ✓ should send a gestalt invite (existing invitation) (227 ms)
    ✓ should claim node (123 ms)

  ● Client service › should ping a node (online + offline)

    ErrorUtilsPollTimeout:

      118 |     while (true) {
      119 |       if (timer?.timedOut) {
    > 120 |         throw new utilsErrors.ErrorUtilsPollTimeout();
          |               ^
      121 |       }
      122 |       try {
      123 |         result = await f();

      at poll (src/utils/utils.ts:120:15)
      at Object.waitFor (src/status/Status.ts:150:24)
      at Object.<anonymous> (tests/client/rpcNodes.test.ts:203:7)

Test Suites: 1 failed, 8 passed, 9 total
Tests:       1 failed, 16 skipped, 41 passed, 58 total
Snapshots:   0 total
Time:        88.76 s
Ran all test suites matching /tests\/client/i.
GLOBAL TEARDOWN
Destroying global.keyPairDir: /tmp/polykey-test-keypair
Destroying global.binAgentDir: /tmp/polykey-test-bin
npm ERR! Test failed.  See above for more details.

```

</details>

* tests/identities: all passing after small fix

<details>

```
~/Documents/Projects/js-polykey(identities-augment*) » npm test -- tests/identities

> @matrixai/polykey@1.0.0 test /home/josh/Documents/Projects/js-polykey
> jest "tests/identities"

Determining test suites to run...
GLOBAL SETUP
Creating global.keyPairDir: /tmp/polykey-test-keypair
Creating global.binAgentDir: /tmp/polykey-test-bin
 PASS  tests/identities/IdentitiesManager.test.ts
  IdentitiesManager
    ✓ IdentitiesManager readiness (21 ms)
    ✓ get, set and unset tokens (19 ms)
    ✓ start and stop preserves state (5 ms)
    ✓ fresh start deletes all state (5 ms)
    ✓ register and unregister providers (9 ms)
    ✓ using TestProvider (19 ms)

Test Suites: 1 passed, 1 total
Tests:       6 passed, 6 total
Snapshots:   0 total
Time:        1.55 s, estimated 4 s
Ran all test suites matching /tests\/identities/i.
GLOBAL TEARDOWN
Destroying global.keyPairDir: /tmp/polykey-test-keypair
Destroying global.binAgentDir: /tmp/polykey-test-bin

```

</details>

* sigchain: all passed

<details>

```
~/Documents/Projects/js-polykey(identities-augment*) » npm test -- tests/sigchain  

> @matrixai/polykey@1.0.0 test /home/josh/Documents/Projects/js-polykey
> jest "tests/sigchain"

Determining test suites to run...
GLOBAL SETUP
Creating global.keyPairDir: /tmp/polykey-test-keypair
Creating global.binAgentDir: /tmp/polykey-test-bin
 PASS  tests/sigchain/Sigchain.test.ts (14.317 s)
  Sigchain
    ✓ session readiness (883 ms)
    ✓ async start initialises the sequence number (1540 ms)
    ✓ adds and retrieves a cryptolink, verifies signature (1568 ms)
    ✓ adds and retrieves 2 cryptolinks, verifies signatures and hash (1449 ms)
    ✓ adds an existing claim (1858 ms)
    ✓ retrieves chain data (1333 ms)
    ✓ retrieves all cryptolinks (nodes and identities) from sigchain (in expected lexicographic order) (2425 ms)

Test Suites: 1 passed, 1 total
Tests:       7 passed, 7 total
Snapshots:   0 total
Time:        14.342 s
Ran all test suites matching /tests\/sigchain/i.
GLOBAL TEARDOWN
Destroying global.keyPairDir: /tmp/polykey-test-keypair
Destroying global.binAgentDir: /tmp/polykey-test-bin

```

</details>

* discovery: all passed (the console.logs are fixed in #292)

<details>

```
~/Documents/Projects/js-polykey(identities-augment*) » npm test -- tests/discovery 

> @matrixai/polykey@1.0.0 test /home/josh/Documents/Projects/js-polykey
> jest "tests/discovery"

Determining test suites to run...
GLOBAL SETUP
Creating global.keyPairDir: /tmp/polykey-test-keypair
Creating global.binAgentDir: /tmp/polykey-test-bin
  console.log
    WARN:ConnectionReverse 127.0.0.1:46816:Connection Error: Error [ERR_STREAM_WRITE_AFTER_END]: write after end

      at ConsoleHandler.emit (node_modules/@matrixai/logger/dist/handlers/ConsoleHandler.js:9:17)

  console.log
    WARN:ConnectionReverse 127.0.0.1:58831:Connection Error: Error [ERR_STREAM_WRITE_AFTER_END]: write after end

      at ConsoleHandler.emit (node_modules/@matrixai/logger/dist/handlers/ConsoleHandler.js:9:17)

  console.log
    WARN:ConnectionReverse 127.0.0.1:58831:Connection Error: Error [ERR_STREAM_WRITE_AFTER_END]: write after end

      at ConsoleHandler.emit (node_modules/@matrixai/logger/dist/handlers/ConsoleHandler.js:9:17)

 PASS  tests/discovery/Discovery.test.ts (34.712 s)
  Discovery
    Basic manager tests.
      ✓ Constructs. (2 ms)
      ✓ Starts and stops (1 ms)
    Discovery process
      ✓ discoverGestaltByNode by NodeId (1331 ms)
      ✓ discoverGestaltByNode by IdentityId (472 ms)
      ✓ discovery readiness (12 ms)
    End-to-end discovery between two gestalts
      ✓ Gestalt1 discovers Gestalt2 (655 ms)
      ✓ Gestalt2 discovers Gestalt1 (962 ms)

Test Suites: 1 passed, 1 total
Tests:       7 passed, 7 total
Snapshots:   0 total
Time:        34.737 s
Ran all test suites matching /tests\/discovery/i.
GLOBAL TEARDOWN
Destroying global.keyPairDir: /tmp/polykey-test-keypair
Destroying global.binAgentDir: /tmp/polykey-test-bin

```

</details>

**Comment by joshuakarp** [comment]
Squashed and ready for merge.
