### PR TITLE
`Provider.checkToken` will no longer treat empty `refreshToken` strings as invalid tokens and fixed use of `__proto__` as `identityId` in `IdentitiesManager`

### LINKED ISSUE #608: Prototype Pollution of `getToken` and `putToken` when `identityId`is `__proto__`
### Describe the bug
Due to JS reserving the use of the `__proto__` key on objects, and `getToken` and `setToken` using an object to store the tokens for all connected identities for any given provider, prototype pollution will occur.

### To Reproduce

```ts
testProp(
    'get, set and unset tokens',
    [identitiesTestUtils.identitiyIdArb, identitiesTestUtils.providerTokenArb],
    async (identityId, providerToken) => {
      const identitiesManager = await IdentitiesManager.createIdentitiesManager(
        {
          db,
          keyRing: dummyKeyRing,
          gestaltGraph: dummyGestaltGraph,
          sigchain: dummySigchain,
          logger,
          fresh: true,
        },
      );
      const providerId = 'test-provider' as ProviderId;
     // identityId = '__proto__';
      await identitiesManager.putToken(providerId, identityId, providerToken);
      const providerToken_ = await identitiesManager.getToken(
        providerId,
        identityId,
      );
      expect(providerToken).toStrictEqual(providerToken_);
      await identitiesManager.delToken(providerId, identityId);
      await identitiesManager.delToken(providerId, identityId);
      const providerToken__ = await identitiesManager.getToken(
        providerId,
        identityId,
      );
      expect(providerToken__).toBeUndefined();
      await identitiesManager.stop();
    }, { seed: 568365398 }
  );
```

### Expected behavior
Using `__proto__` as the identityId should correctly set the token.

### Screenshots
```
  ● IdentitiesManager › get, set and unset tokens (with seed=568365398)

    Property failed after 5 tests
    { seed: 568365398, path: "4:84:84:84:84:84:84:84:84:84:84:84:84:84", endOnFailure: true }
    Counterexample: ["__proto__",{"accessToken":"          ","refreshToken":"","accessTokenExpiresIn":0,"refreshTokenExpiresIn":0}]
    Shrunk 13 time(s)
    Got error: expect(received).toStrictEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 6

    - Object {}
    + Object {
    +   "accessToken": "          ",
    +   "accessTokenExpiresIn": 0,
    +   "refreshToken": "",
    +   "refreshTokenExpiresIn": 0,
    + }

      120 |         identityId,
      121 |       );
    > 122 |       expect(providerToken).toStrictEqual(providerToken_);
          |                             ^
      123 |       await identitiesManager.delToken(providerId, identityId);
      124 |       await identitiesManager.delToken(providerId, identityId);
      125 |       const providerToken__ = await identitiesManager.getToken(

      at toStrictEqual (tests/identities/IdentitiesManager.test.ts:122:29)
      at AsyncProperty.run (node_modules/fast-check/lib/check/property/AsyncProperty.generic.js:49:28)
      Hint: Enable verbose mode in order to have the list of all failing values encountered during the run
      at buildError (node_modules/fast-check/lib/check/runner/utils/RunDetailsFormatter.js:131:15)
      at asyncThrowIfFailed (node_modules/fast-check/lib/check/runner/utils/RunDetailsFormatter.js:148:11)

  ● IdentitiesManager › start and stop preserves state (with seed=568365398)

    Property failed after 5 tests
    { seed: 568365398, path: "4:84:84:84:84:84:84:84:84:84:84:84:84:84", endOnFailure: true }
    Counterexample: ["__proto__",{"accessToken":"          ","refreshToken":"","accessTokenExpiresIn":0,"refreshTokenExpiresIn":0}]
    Shrunk 13 time(s)
    Got error: expect(received).toStrictEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 6

    - Object {}
    + Object {
    +   "accessToken": "          ",
    +   "accessTokenExpiresIn": 0,
    +   "refreshToken": "",
    +   "refreshTokenExpiresIn": 0,
    + }

      161 |         identityId,
      162 |       );
    > 163 |       expect(providerToken).toStrictEqual(providerToken_);
          |                             ^
      164 |       expect(identitiesManager.getProviders()).toStrictEqual({
      165 |         [testProvider.id]: testProvider,
      166 |       });

      at toStrictEqual (tests/identities/IdentitiesManager.test.ts:163:29)
      at AsyncProperty.run (node_modules/fast-check/lib/check/property/AsyncProperty.generic.js:49:28)
      Hint: Enable verbose mode in order to have the list of all failing values encountered during the run
      at buildError (node_modules/fast-check/lib/check/runner/utils/RunDetailsFormatter.js:131:15)
      at asyncThrowIfFailed (node_modules/fast-check/lib/check/runner/utils/RunDetailsFormatter.js:148:11)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 5 passed, 7 total
Snapshots:   0 total
Time:        11.233 s
Ran all test suites matching /.\/tests\/identities\//i.
GLOBAL TEARDOWN
Destroying Global Data Dir: /tmp/polykey-test-global-X7tBig
```

### Platform (please complete the following information)
 - Device: Dell Precision 3470
 - OS: NixOS
 - Version: Node v20.5.1

### Notify maintainers

@amydevs

### PR DESCRIPTION
**Pull request by amydevs**
#### Provider

The `handleClaimIdentity` test in `tests/identities/IdentitiesManager.test.ts` was failing on `handleClaimIdentity`. This was because it was treating refreshTokens of empty strings as invalid tokens. This is no longer the case.

```
FAIL  tests/identities/IdentitiesManager.test.ts
  IdentitiesManager
    ✓ IdentitiesManager readiness (85 ms)
    ✓ get, set and unset tokens (with seed=-201149676) (395 ms)
    ✓ start and stop preserves state (with seed=-201149676) (234 ms)
    ✓ fresh start deletes all state (with seed=-201149676) (255 ms)
    ✓ register and unregister providers (39 ms)
    ✓ using TestProvider (with seed=-201149676) (1553 ms)
    ✕ handleClaimIdentity (with seed=1486144507) (939 ms)

  ● IdentitiesManager › handleClaimIdentity (with seed=1486144507)

    Property failed after 1 tests
    { seed: 1486144507, path: "0:0:0:0:0:0:0:0:0:0:0:0:0:3:0:1:1:0:3:0:0:0:1:1:0:1:3:2:0:1", endOnFailure: true }
    Counterexample: ["",{"accessToken":"          ","refreshToken":"","accessTokenExpiresIn":1698190047,"refreshTokenExpiresIn":0}]
    Shrunk 29 time(s)
    Got ErrorProviderUnimplemented:

      64 |
      65 |   public async refreshToken(): Promise<ProviderToken> {
    > 66 |     throw new identitiesErrors.ErrorProviderUnimplemented();
         |           ^
      67 |   }
      68 |
      69 |   public async getAuthIdentityIds(): Promise<Array<IdentityId>> {

      at TestProvider.refreshToken (tests/identities/TestProvider.ts:66:11)
      at TestProvider.refreshToken [as checkToken] (src/identities/Provider.ts:85:25)
      at TestProvider.checkToken [as publishClaim] (tests/identities/TestProvider.ts:152:16)
      at src/identities/IdentitiesManager.ts:272:39
      at constructor_.addClaim (src/sigchain/Sigchain.ts:449:20)
      at withF (node_modules/@matrixai/resources/src/utils.ts:24:12)
      at constructor_.handleClaimIdentity (src/identities/IdentitiesManager.ts:261:5)
      at numRuns (tests/identities/IdentitiesManager.test.ts:361:7)
      at AsyncProperty.run (node_modules/fast-check/lib/check/property/AsyncProperty.generic.js:49:28)
      Hint: Enable verbose mode in order to have the list of all failing values encountered during the run
      at buildError (node_modules/fast-check/lib/check/runner/utils/RunDetailsFormatter.js:131:15)
      at asyncThrowIfFailed (node_modules/fast-check/lib/check/runner/utils/RunDetailsFormatter.js:148:11)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 6 passed, 7 total
Snapshots:   0 total
Time:        4.02 s
Ran all test suites matching /.\/tests\/identities\/IdentitiesManager.test.ts/i.
GLOBAL TEARDOWN
Destroying Global Data Dir: /tmp/polykey-test-global-weOx7R
```

It is also defined now that any expiry values in AccessToken set to 0, now have their related tokens treated as never-expiring. This was already the case before this PR, but inline comments have been added to document this.

```ts
public async checkToken(
    providerToken: ProviderToken,
    identityId?: IdentityId,
  ): Promise<ProviderToken> {
    const now = Math.floor(Date.now() / 1000);
    // this will mean that accessTokenExpiresIn = 0 will be false
    if (
      providerToken.accessTokenExpiresIn &&
      providerToken.accessTokenExpiresIn >= now
    ) {
      if (providerToken.refreshToken == null) {
        throw new identitiesErrors.ErrorProviderUnauthenticated(
          'Access token expired',
        );
      }
      // this will mean that refreshTokenExpiresIn = 0 does not throw
      if (
        providerToken.refreshTokenExpiresIn &&
        providerToken.refreshTokenExpiresIn >= now
      ) {
        throw new identitiesErrors.ErrorProviderUnauthenticated(
          'Refresh token expired',
        );
      }
      return await this.refreshToken(providerToken, identityId);
    }
    return providerToken;
  }
```

#### Prototype Pollution

During testing, I noticed two other tests in `IdentitiesManager.test.ts` failing. This was because of fastcheck sometimes generating a string value of `__proto__` for the `identityId`. The `identityId` is used as the key for the object that comes out of RocksDB, there is a problem with prototype pollution. This is not only a security issue, but also that `JSON.stringify` does not serialize the `__proto__` property of an object, so certain the provider keys for that identity will never work. This PR uses `Object.defineProperty`to correctly set the `__proto__` property on the `providerTokens` object.

### Issues Related
* https://github.com/MatrixAI/Polykey-CLI/issues/40#issuecomment-1778016364
* Fixes #608 

### Tasks

- [x] 1. Fix conditional check of valid `refreshToken`
- [x] 2. Inline documentation
- [x] 3. Define implementation for `TestProvider.refreshToken`
- [x] 4. Add errors to throw when prototype pollution of `identityId` is attempted

### Final checklist

* [x] Domain specific tests
* [x] Full tests
* [x] Updated inline-comment documentation
* [x] Lint fixed
* [x] Squash and rebased
* [x] Sanity check the final build

### CODE REVIEW

**Comment by CMCDragonkai** [comment]
If this works, proceed to squash down, no need to keep unnecessary lintfix commits around, and merge in. Are you waiting for something here?

File: src/identities/Provider.ts [hunk 1]
```diff
@@ -58,21 +58,25 @@ abstract class Provider {
...
    * If you pass in identityId, expect that the new token will be persisted.
+   * If either `providerToken.accessTokenExpiresIn` or `providerToken.refreshTokenExpiresIn` is set to 0,
+   * their related tokens will be treated as never-expiring.
    */
   public async checkToken(
     providerToken: ProviderToken,
     identityId?: IdentityId,
   ): Promise<ProviderToken> {
     const now = Math.floor(Date.now() / 1000);
+    // This will mean that if accessTokenExpiresIn = 0, the token never exoures
```
Comment (CMCDragonkai) [inline src/identities/Provider.ts]: Typo here.

File: src/identities/errors.ts [hunk 2]
```diff
@@ -59,6 +64,7 @@ export {
   ErrorIdentitiesManagerRunning,
   ErrorIdentitiesManagerNotRunning,
   ErrorIdentitiesManagerDestroyed,
+  ErrorIdentitiesManagerInvalidIdentityId,
```
Comment (CMCDragonkai) [inline src/identities/errors.ts]: Prefer IdentityIdInvalid. Usually describing word at the end.

File: tests/identities/IdentitiesManager.test.ts [hunk 3]
```diff
@@ -114,19 +114,27 @@ describe('IdentitiesManager', () => {
...
-      );
-      expect(providerToken).toStrictEqual(providerToken_);
-      await identitiesManager.delToken(providerId, identityId);
-      await identitiesManager.delToken(providerId, identityId);
-      const providerToken__ = await identitiesManager.getToken(
-        providerId,
-        identityId,
-      );
-      expect(providerToken__).toBeUndefined();
+      if (identityId === '__proto__') {
```
Comment (CMCDragonkai) [inline tests/identities/IdentitiesManager.test.ts]: So, this `__proto__` thing is special to `JSON.stringify`? Are there other keys that are special too? Seems very strange.

**Review by CMCDragonkai — CHANGES_REQUESTED** [review]

**Comment by CMCDragonkai** [comment]
https://chat.openai.com/share/caaac780-4de6-4b1a-ab6a-68cd4ed58cd8

This explains that explicitly set `__proto__` would be accepted as a property. So why is it a problem?

**Comment by CMCDragonkai** [comment]
In #608 I've explained how you can support `__proto__` as a proper key instead of special casing it. Who knows, somebody might really have a username being `__proto__` just to screw with people. This is the modern XKCD:

image

**Comment by CMCDragonkai** [comment]
**To summarise for safety reasons, if the key is coming from an untrusted source, or a randomised source where you don't know what it could be, there's 2 safe ways of doing this:**

1. `o = {[untrustedString]: 123 }`
2. `Object.defineProperty(o, untrustedString, { value: 123, writable: true, enumerable: true, configurable: true }`

It is not safe to do `o[untrustedString] = 123` although `o[untrustedString]` can be used to look up the property once it is defined. And of course a literal `o = { __proto__: 123 }` also does not work!!

**Comment by CMCDragonkai** [comment]
Can you fix it that way, and add an inline comment describing the reason.

**Comment by amydevs** [comment]
> Can you fix it that way, and add an inline comment describing the reason.
```ts
// This has to be done in case the key is `__proto__`.
    // Otherwise, the object will not be correctly serialized.
    // https://github.com/MatrixAI/Polykey/issues/608
    Object.defineProperty(providerTokens, identityId, {
      value: providerToken,
      writable: true,
      enumerable: true,
      configurable: true,
    });
```

File: tests/identities/IdentitiesManager.test.ts (hunk 3 above)
Comment (amydevs) [reply tests/identities/IdentitiesManager.test.ts]: i think stuff like `__defineSetter__` and `__defineGetter__` should be the same. However, Object.defineProperty should solve all that

File: src/identities/errors.ts (hunk 2 above)
Comment (amydevs) [reply src/identities/errors.ts]: removed in favor of using Object.defineProperty

File: src/identities/Provider.ts (hunk 1 above)
Comment (amydevs) [reply src/identities/Provider.ts]: fixed
