### PR TITLE
Extracting Node Connection Management out of `NodeManager` to  `NodeConnectionManager`

### LINKED ISSUE #216: Extend automated tests for NodeConnection
### Specification

Some extra functionality has been brought into `NodeConnection` from !195. Tests need to be added for them.

### Tasks

Add tests for:
1. `getRootCertChain`/`getExpectedPublicKey`
2. `getChainData`

### LINKED ISSUE #224: Propagate networking connection error handling into NodeConnection error handling
### Specification

When errors are encountered in the `network` domain for a particular connection, we expect these errors to propagate up to the higher-level `NodeConnection`. In this process, an active `NodeConnection` object that experiences a lower-level failure from the `network` domain must also be destroyed and garbage collected, as the underlying connection is no longer valid.

As per Roger's comment here https://github.com/MatrixAI/js-polykey/issues/224#issuecomment-952568847, the `network` domain can be seen to be operating in a separate space to the more procedural elements of the source code. The network components are singleton instances that operate and handle errors in isolation. So, how do we propagate these errors to the higher level `NodeConnection`?

NodeConnection error propagation (Cropped)

> So the problem here is that the `NodeManager` or `NodeConnection` uses `GRPCClientAgent` which extends from `GRPCClient`.
> 
> The `GRPCClient` is what encapsulates the underlying `Client` object provided by `grpc-js`.
> 
> At this current point in time, in the source code for `GRPCClient`, there's no provision for asynchronous handlers in the case where the GRPC connection breaks.
> 
> The GRPC connection can break when the networking domain has an error, or this may also happen in #276.
> 
> But there would no way of handling this error event automatically. Instead I believe an exception would only occur at the point of calling another client method. This is obviously not suitable for our `NodeManager` as we need to handle when the connections are dead and garbage collect them.
> 
> We need to investigate the source code, issues and docs for `grpc-js` https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/client.ts to see where we can add a handler for these GRPC client problems.
> 
> If we cannot do this, the alternative is to do interval pings, which are unary calls and this should trigger an exception if the connection has been broken. We already do this inside the `network` domain at a low level. But this would a GRPC-level ping, which uses a full GRPC message. This would trigger exceptions to occur as well.
> 
> Also in reference to the #225, we have to make a choice of whether `NodeManager` is the primary way to access, or `NodeConnection`. If users are using `NodeConnection`, then it would be expected that they call `NodeManager` to reconnect if there are problems. It seems `NodeManager` is the better choice, but this makes it a different architecture from how we are doing it in `VaultManager`. Which is fine, because vaults do not represent objects over a network. Networks are always more flakier. So we don't expect one to lose a connection to a vault. But we do expect losing connections to nodes. Which is why it may be better to have `NodeManager` handle all the complexity.
> 
> Check this https://github.com/grpc/grpc-node/search?q=connection+drop+handle&type=issues

### Additional context

* https://github.com/MatrixAI/js-polykey/issues/225#issuecomment-899921000 original comment about potentially implementing error handlers at the `NodeConnection` level

### Tasks

1. Investigate the current network connection errors that arise in the lower-level `network` domain: how do these arise? Where do they currently bubble up to?
2. Investigate existing code, issues, and docs for `grpc-js` for how to handle connection errors. Are there existing functions that could provide error handlers?
3. If no handlers exist at the GRPC level, look into how to perform internal pings (very similar to the keep-alive packets in the lower level `network` domain). We expect that these exceptions may only arise after a call is made, so these internal pings will be a means of assessing the connection status (i.e. no GRPC call error, connection is still active; GRPC call error, connection is no longer active, so destroy `NodeConnection` object)

### LINKED ISSUE #225: Refactoring Nodes Domain: NodeConnection & NodeConnectionManager and Fixing Bugs
### Specification

The Nodes domain is an integration of all the other domains that enables Polykey to be a distributed and decentralised application. Right now it's design is causing its tests and its code to be quite brittle as other domains are being iterated on. This is slowing down our development process. At the same time, it has a number of functionalities that time to do such as pinging, these are now causing very slow tests up to 60 or 80 seconds for a single test to just do pinging.

The nodes domain require a significant refactoring to ensure stability and robustness and performance going into the future.

After a small review over the nodes codebase, here is the new proposed structure.

* NodeManager
  - requires `NodeConnectionManager`
  - encapsulates `NodeGraph` (optional dependency)
  - provides high-level nodes management such as `claimNode`
* NodeConnectionManager
  - manages the lifecycle of `NodeConnection` in a pool of node connections
  - provides a context higher-order function `withConnection` to run an asynchronous callback that uses `NodeConnection`
     * this means that all domains that currently rely on the `NodeManager`'s "wrapper" functions that perform `NodeConnection` operations would instead create their own internal functions (within their own domains) that use this higher-order function `withConnection` to perform their connection functionality. `NodeManager` should not have any of this anymore
  - applies a TTL to each `NodeConnection` and closes the connection after timeout
  - resets TTL on every connection use
  - uses a lock to ensure connections cannot be timed out when they are in-use
* NodeConnection
  - represents a connection to the agent service of another keynode
  - wrapper around `GRPCClientAgent`, and provides some lifecycle features specific to the node connection
  - class extension of `GRPCClientAgent` or es6 proxy or wrapper class
  - if wrapper class, then must provide access to the `client` property
  - used by other domains to call the agent service
* NodeGraph
  - data structure implementation of Kademlia
  - stores the `NodeId` -> `NodeAddress` mappings in a keynode
  - persistent uses DB and may require transactions

Both `NodeManager` and `NodeConnectionManager` should be exposed at the high level in `PolykeyAgent` and provided to `createClientService`.

Furthermore, the following lists the current usage of `NodeManager` for `NodeConnection` operations (i.e. the places where `NodeConnectionManager` would instead need to be injected):
* `Discovery`
* `NodeManager`
* `NodeGraph` - this is a special case that will need some potential refactoring, see https://github.com/MatrixAI/js-polykey/issues/225#:~:text=in%3A%20%23224%20(comment)-,NodeGraph,-NodeGraph%20is%20a
* `NotificationsManager`
* `VaultManager`

The following diagram depicts these dependencies:

```
                       ┌───────────────────────┐            ┌─────────┐
┌─────────────┐        │                       ◄────────────┤Discovery│
│             │        │ NodeConnectionManager │            └─────────┘
│ NodeManager ├────────►                       │
│             │        │     ┌─────────────┐   │       ┌────────────────────┐
│ ┌─────────┐ │        │    ┌┴────────────┐│   ◄───────┤NotificationsManager│
│ │NodeGraph├─┼────────►  ┌─┴────────────┐├┘   │       └────────────────────┘
│ └─────────┘ │        │  │NodeConnection├┘    │
│             │        │  └──────────────┘     │           ┌────────────┐
└─────────────┘        │                       ◄───────────┤VaultManager│
                       └───────────────────────┘           └────────────┘
```

#### NodeManager

The `NodeManager` manages nodes, but does not manage the node connections.

It is expected that `NodeManager` requires `NodeConnectionManager` which is shared as singleton with other domains.

Operations relating to manipulating nodes should be on `NodeManager` such as `claimNode` and related operations.

Most of the time this will be called by GRPC handlers, but some domains like discovery might be using the nodes domain. It is also what encapsulates access and mutation to the `NodeGraph`.

#### NodeConnectionManager

The `NodeConnectionManager` manages a pool of node connections. This is what is being shared as a singleton to all the domains that need to contact a node and call their handlers. For example `VaultManager` would not use `NodeManager` but only `NodeConnectionManager`. This also includes notifications domain.

The connections are shared between each node connection.

Notice the lock being used to ensure that connection establishment and connection closure is serialised. Refer to: 
https://gist.github.com/CMCDragonkai/f58f08e7eaab0430ed4467ca35527a42 for example. This pattern is also used in the vault manager.

A draft mock of the class:

```ts
class NodeConnectionManager {

  connections: Map<NodeId, {
    conn?: NodeConnection;
    lock: MutexInterface;
  }>;

  public constructor(nodeGraph) {}

  public getNodeId(); // lots of connection-related requests need this (get from KeyManager)

  // refreshes the timeout at the end
  public withConnection(targetNodeId, async function());

  // these are used by `withConnection`
  // reusing terms from network domain:
  // connConnectTime - timeout for opening the connection
  // connTimeoutTime  - TTL for the connection itself
  protected createConnection();
  protected destroyConnection();

}
```

In the `withConnection` call, this is the only way to acquire a connection to be used by other domains. If this is to be similar to the `VaultManager`, that mean that `VaultManager.withVault` would need to exist.

The locking side effects could be done in `NodeConnectionManager` or inside the `NodeConnection`. However since this problem also exists in the `VaultManager`, I believe we want to do the side-effects as much as possible in the `NodeConnectionManager`. If locking during creation and destruction needs to occur, then it has to occur via callbacks that are passed into the `NodeConnection`.

#### NodeConnection

```ts
class NodeConnection extends GRPCClientAgent {
  // timeout acts like a TTL
  // the timeout must be refreshed everytime it is used
  // and while `withConnection` is in use, we can use a lazy lock for this
  public constructor(timeout) {
  }

  // every call is available here
  // but this is a public API
}
```

There may be a `NodeConnectionInternal` to have the actual methods while `NodeConnection` maybe a public interface similar to `Vault` and `VaultInternal`.

##### Usage

Any call to another keynode has to go through the `NodeConnection`. It is expected that callers will perform something like this:

```ts
async function doSomethingWithAnotherNode(nodeId) {
  await this.nodeConnManager.withConn(
    nodeId, 
    async (conn: NodeConnection) => {
      await conn.client.doSomething();
    }
  );
}
```

Such usage would occur in both `NodeManager` and other domains such as `VaultManager`.

Note that the `conn.client.doSomething()` may be `conn.doSomething()` instead. This depends on how `NodeConnection` is written.

Either way it is expected that `doSomething` is the same gRPC call available in `GRPCClientAgent`.

This means it is up to the domains to manage and handle gRPC call behaviour which includes the usage of async generators, metadata and exceptions. Refer to #249 for details on this.

The reason we are doing this is that abstractions on the gRPC call side are domain-specific behaviour. We wouldn't want to centralise all of the domain call gRPC abstractions into the nodes domain, that would be quite brittle.

This means the vaults domain could if they wanted to create their own wrapper over the connection object such as:

```ts
this.nodeConnManager.withConn(
    nodeId, 
    async (conn: NodeConnection) => {
        // vaultClient adds vault-specific abstractions on the gRPC calls
        const client = vaultClient(conn.client);
        await client.doSomethingWithVaults();
    }
);
```

Right now we shouldn't do any gRPC abstractions until #249 is addressed.

##### Lifecycle

The `withConn` method provides a "resource context". It's a higher order function that takes the asynchronous action that is to be performed with the connection.

It has a similar pattern to our `poll`, `retryAuth`, `transact`, `transaction`, `_transaction` wrapper functions.

The advantage of this pattern is that the node connection will not be closed (by the TTL) while the action is being executed.

The `withConn` will need to use the `RWLock` pattern as provided in `src/utils.ts`. It has to acquire a read lock when executing the action.

This enables multiple `withConn` to be executing concurrently without blocking each other.

At the end of each `withConn`, the `TLL` should be reset.

When the TLL is expired, it may attempt to close the connection. To do this, a write lock is attempted. If the lock is already locked, then we skip. If we acquire the write lock, we can close the connection.

If the client were to be closed or terminated due to other reasons, then an exception should be thrown when accessing the `client` or its methods.

This would be `ErrorNodeConnectionNotRunning` or `ErrorGRPCClientAgentNotRunning` or `ErrorGRPCClientNotRunning`.

Other domains should not be keeping around references to `NodeConnection` it should only be used inside the `withConn` context.

##### Hole Punching Relay

Hole punching is done between the `ForwardProxy` and `ReverseProxy`. Hole punching is not done explicitly in the `NodeConnectionManager` or `NodeConnection`.

Instead, hole punching _relay_ is what is done by `NodeConnectionManager`. This means you relay a hole punching message across the network so that the target Node will perform reverse hole punching in case we need it. This process should be done at the same time as a connection is established.

This means `NodeConnectionManager` requires the `NodeGraph`, the same `NodeGraph` that is used by `NodeManager`.

The graph is needed to do optimal routing of the the hole punching relay message.

This means `NodeConnectionManager` would need to be used by `createAgentService` as the current keynode may be in the middle of a chain of relaying operations.

##### Public Interface

The public interface of `NodeConnection` can be a limited version of the internal class. This can hide methods like `destroy` from the users of `NodeConnection`. This ensures that only `NodeConnectionManager` can destroy the connection.

##### Dealing with Termination/Errors

The underlying `GRPCClientAgent` may close/terminate for various reasons. In order to capture this behaviour, you must hook into the state changes in the `Client` object. This will require changes to `src/grpc/GRPCClient.ts`, as it currently does not expose the `Client` object. Discussions on how to do this are in: https://github.com/matrixai/js-polykey/issues/224#issuecomment-966770905

#### NodeGraph

NodeGraph is a complex data structure. It appears to be needed by both `NodeManager` and `NodeConnectionManager`, but itself also needs to perform operations on `NodeManager`. Whenever there is mutual recursion, it can be factored out as another common dependency "absract the commonality". However if this is not suitable, then it can be done by passing `NodeManager` as `this` into `NodeGraph`.

However if `NodeConnectionManager` needs `NodeGraph` as well, then this is not possible unless `NodeConnectionManager` was also produced by `NodeManager`.

Further investigation is needed into the `NodeGraph` to understand how we can turn it into a data structure. Perhaps we can use a pattern of hooks where `NodeGraph` exposes a number of hook points which can be configured by `NodeManager` and thus allow `NodeGraph` to "callback" `NodeManager` and `NodeConnectionManager`.

If `NodeGraph` can be made purely a data structure/database, then:

1. The `getClosestLocalNodes` and `getClosestGlobalNodes` could be part of the `NodeManager`, and not the `NodeGraph`.
2. The seed nodes marshalling could occur in the `NodeManager`, and instead you just plug it with actual values.

There's only 3 places where `NodeGraph` is calling out to the world. All 3 can be done in `NodeManager` instead. That means `NodeGraph` no longer needs `NodeConnectionManager`.

#### Testing

For `NodeConnectionManager` and `NodeConnection`, it's essential that we don't duplicate tests for `GRPCClientAgent` as that would be handled by `tests/agent`. It must focus on just testing the connection related functionality. This is where mocks should be useful here, since we want to delay integration testing until the very end.

There are 4 kinds of mocks we have to use here.

1. Timer mocks - many code relies on timeouts, we must use timer mocking https://jestjs.io/blog/2020/05/05/jest-26#new-fake-timers to ensure that don't wait for the timeout.
2. Function mocks - as used in `tests/bin/utils.retryAuth.test.ts`, function mocks can be very useful way of providing a dummy function that we can later instrument. This can be useful if we pursue a hook pattern with `NodeGraph`.
3. Module/class mocks - as used in `tests/bin/utils.retryAuth.test.ts` (`jest.mock('prompts')`) this is high level mocking that should only be used when no other methods can be done. This is more complicated, but you can mock **anything** this way.
4. DI mocking, all of the dependencies talked about here should be DI-able, this should be used first before making use of `Module/class` mocks.

The tests for the nodes domain should be robust, reproducible, not flaky and complete within 10 - 30 seconds.

Larger integration tests should be done at a higher level, which will help us achieve #264.

This should ensure that nodes domain is more stable and does not break every time we change stuff in other domains.

### Additional context

* #281 - Async Init Fixes that is applied in CARL & Session Management MR: https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/213
* #194 - Seed Nodes Integration, application of DNS resolution is relevant here
* #249 - GRPC API Review
* #264 - Concurrent Testing Scalability

### Tasks

1. Create `NodeConnectionManager`
2. Refactor `NodeConnection` into `NodeConnectionManager` and `NodeManager`
   1. Add lock acquisition to `destroy` call of `NodeConnection` (the same process as construction): https://github.com/MatrixAI/js-polykey/issues/225#issuecomment-984262851
3. Factor out the commonality to prevent mutual recursion in `NodeGraph` and `NodeManager` and `NodeConnectionManager`
4. Introduce timer mocking to nodes testing.
5. Implement mocking for `NodeConnection` and `NodeConnectionManager` testing. Remove any tests that test agent service handling or forward proxy and reverse proxy usage. Rely on the other domain tests to handle this.
6. Fix up all domains that use `NodeConnection` to acquire their connections from `NodeConnectionManager`.

### LINKED ISSUE #254: Refactor `NodeId` as a proxy/singleton instance
### Specification

The node ID of a Polykey keynode is the public key fingerprint (based on the root keypair of the keynode). As such, on a key renewal/refresh, the node ID of the keynode will also change. Therefore, the node ID can be seen as dynamic state.

Currently we've had to be careful when we retrieve the node ID. We shouldn't be storing it as local, static state, otherwise this state needs to be updated when the root key changes.

The current solution has been to inject the `KeyManager` into any class where we require the node ID to be retrieved, such that we can call `getNodeId` to compute the node ID directly from the root key. This isn't the ideal solution: we shouldn't have to expose all of the `KeyManager` whenever we need just the node ID.

We should look into changing the node ID to be similar to the `Id` class in `js-id`, or making use of the `js-permaproxy` library to do this (https://github.com/matrixai/js-permaproxy). Therefore, only the node ID's proxy instance would need to be injected where we need the node ID.

Would we expose any other functionality other than a getter? If we wanted to do an "update" functionality, we'd actually need to perform an update on the root key itself (given that the node ID is derived from the public key). So perhaps instead, we could look into abstracting the root key as a proxy, such that a key update/renewal can be called without the `KeyManager`... this is potentially completely unnecessary though.

### Additional context

* original discussion of changing the node ID to be a proxy/singleton instance https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/205#note_708488228
* previous thread from !209 (nodes claims) discussing the problems arising in the `nodes` domain when injecting the node ID as a local, static property https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/209#note_675531967
* #312 - Propagate keypair changes to other domains
* #299 - NodeId applied to the `js-id`

### Tasks

1. ...
2. ...
3. ...

### LINKED ISSUE #274: Investigate and fix random `NodeGraph` test failures
### Describe the bug

The tests in `NodeGraph` can intermittently fail across runs. We'd experienced some similar failures in the past, and I thought I'd resolved them. The past failures were to do with some test utility functions that generate node IDs for a specific bucket index, such that they can be used for dynamic testing. They were previously causing failures by generating node IDs that overflowed into a different bucket index.

If this is still the cause of failure, now that we can use the 32 byte array as a node ID, I can potentially make these test utilities a bit more robust. Previously, they were just incrementing a character in the node ID to force an expected XOR value.

### To Reproduce

The test failures only occur randomly. It took me 5 runs of `NodeGraph.test.ts` to experience a failure in the tests. Some instances of these:

<details>

```
[nix-shell:~/Documents/MatrixAI/js-polykey]$ npm test -- tests/nodes/NodeGraph.test.ts 

> @matrixai/polykey@1.0.0 test /home/josh/Documents/MatrixAI/js-polykey
> jest "tests/nodes/NodeGraph.test.ts"

Determining test suites to run...
GLOBAL SETUP
 FAIL  tests/nodes/NodeGraph.test.ts (5.69 s)
  NodeGraph
    ✓ finds correct node address (11 ms)
    ✓ unable to find node address (6 ms)
    ✓ adds a single node into a bucket (5 ms)
    ✕ adds multiple nodes into the same bucket (16 ms)
    ✓ adds a single node into different buckets (6 ms)
    ✓ deletes a single node (and removes bucket) (6 ms)
    ✕ deletes a single node (and retains remainder of bucket) (14 ms)
    ✓ enforces k-bucket size, removing least active node when a new node is discovered (83 ms)
    ✓ retrieves all buckets (in expected lexicographic order) (13 ms)
    ✓ refreshes buckets (2050 ms)
    ✓ finds a single closest node (3 ms)
    ✓ finds 3 closest nodes (8 ms)
    ✓ finds the 20 closest nodes (92 ms)
    ✓ updates node (6 ms)

  ● NodeGraph › adds multiple nodes into the same bucket

    expect(received).toEqual(expected) // deep equality

    Expected: {"address": {"ip": "6.6.6.6", "port": 6666}, "lastUpdated": Any<Date>}
    Received: undefined

      222 |         lastUpdated: expect.any(Date),
      223 |       });
    > 224 |       expect(bucket[newNode3Id]).toEqual({
          |                                  ^
      225 |         address: { ip: '6.6.6.6', port: 6666 },
      226 |         lastUpdated: expect.any(Date),
      227 |       });

      at Object.<anonymous> (tests/nodes/NodeGraph.test.ts:224:34)

  ● NodeGraph › deletes a single node (and retains remainder of bucket)

    expect(received).toEqual(expected) // deep equality

    Expected: {"address": {"ip": "6.6.6.6", "port": 6666}, "lastUpdated": Any<Date>}
    Received: undefined

      305 |         lastUpdated: expect.any(Date),
      306 |       });
    > 307 |       expect(bucket[newNode3Id]).toEqual({
          |                                  ^
      308 |         address: { ip: '6.6.6.6', port: 6666 },
      309 |         lastUpdated: expect.any(Date),
      310 |       });

      at Object.<anonymous> (tests/nodes/NodeGraph.test.ts:307:34)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 12 passed, 14 total
Snapshots:   0 total
Time:        5.726 s, estimated 6 s
Ran all test suites matching /tests\/nodes\/NodeGraph.test.ts/i.
GLOBAL TEARDOWN
npm ERR! Test failed.  See above for more details.


Determining test suites to run...
GLOBAL SETUP
 FAIL  tests/nodes/NodeGraph.test.ts (6.165 s)
  NodeGraph
    ✓ finds correct node address (12 ms)
    ✓ unable to find node address (6 ms)
    ✓ adds a single node into a bucket (5 ms)
    ✕ adds multiple nodes into the same bucket (16 ms)
    ✓ adds a single node into different buckets (8 ms)
    ✓ deletes a single node (and removes bucket) (6 ms)
    ✕ deletes a single node (and retains remainder of bucket) (13 ms)
    ✓ enforces k-bucket size, removing least active node when a new node is discovered (85 ms)
    ✕ retrieves all buckets (in expected lexicographic order) (14 ms)
    ✓ refreshes buckets (1996 ms)
    ✓ finds a single closest node (3 ms)
    ✓ finds 3 closest nodes (8 ms)
    ✓ finds the 20 closest nodes (93 ms)
    ✓ updates node (6 ms)

  ● NodeGraph › adds multiple nodes into the same bucket

    expect(received).toEqual(expected) // deep equality

    Expected: {"address": {"ip": "5.5.5.5", "port": 5555}, "lastUpdated": Any<Date>}
    Received: undefined

      218 |         lastUpdated: expect.any(Date),
      219 |       });
    > 220 |       expect(bucket[newNode2Id]).toEqual({
          |                                  ^
      221 |         address: { ip: '5.5.5.5', port: 5555 },
      222 |         lastUpdated: expect.any(Date),
      223 |       });

      at Object.<anonymous> (tests/nodes/NodeGraph.test.ts:220:34)

  ● NodeGraph › deletes a single node (and retains remainder of bucket)

    expect(received).toEqual(expected) // deep equality

    Expected: {"address": {"ip": "5.5.5.5", "port": 5555}, "lastUpdated": Any<Date>}
    Received: undefined

      301 |         lastUpdated: expect.any(Date),
      302 |       });
    > 303 |       expect(bucket[newNode2Id]).toEqual({
          |                                  ^
      304 |         address: { ip: '5.5.5.5', port: 5555 },
      305 |         lastUpdated: expect.any(Date),
      306 |       });

      at Object.<anonymous> (tests/nodes/NodeGraph.test.ts:303:34)

  ● NodeGraph › retrieves all buckets (in expected lexicographic order)

    expect(received).toBe(expected) // Object.is equality

    Expected: 4
    Received: 5

      412 |
      413 |     const buckets = await nodeGraph.getAllBuckets();
    > 414 |     expect(buckets.length).toBe(4);
          |                            ^
      415 |     // Buckets should be returned in lexicographic ordering (using hex keys to
      416 |     // ensure the bucket indexes are in numberical order)
      417 |     expect(buckets).toEqual([

      at Object.<anonymous> (tests/nodes/NodeGraph.test.ts:414:28)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 11 passed, 14 total
Snapshots:   0 total
Time:        6.199 s
Ran all test suites matching /tests\/nodes\/NodeGraph.test.ts/i.
GLOBAL TEARDOWN
npm ERR! Test failed.  See above for more details.

```

</details>

I've found it useful to use the `!#` in the terminal to repeat the command (repeats everything prior). e.g. `npm test -- tests/nodes/NodeGraph.test.ts; !# !#` to run the tests 4 times.

### Additional context

* original thread in `vaultsrefactoring` MR about `NodeGraph` test failures: https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/205#note_695753874
* another instance of test failures https://github.com/MatrixAI/js-polykey/pull/263#issuecomment-951786278

### PR DESCRIPTION
**Pull request by joshuakarp**
### Description

The refactoring effort to make our nodes domain more robust.

```
                              ┌──────────┐
                              │ Sigchain │
                              └────▲─────┘
                                   │
                                   │
                                   │
                            ┌──────┴──────┐
                            │ NodeManager ├──────────────────┐
                            └──────┬──────┘                  │
                                   │                         │
                                   │                         │
                                   │                         │
                       ┌───────────▼───────────┐             │
┌──────────────┐       │                       │             │
│ ForwardProxy ◄───────┤ NodeConnectionManager │             │
└──────────────┘       │                       │       ┌─────▼─────┐
                       │   ┌──────────────┐    ├───────► NodeGraph │
┌──────────────┐       │   │NodeConnection│    │       └───────────┘
│ ReverseProxy ◄───────┤   └──────────────┘    │
└──────────────┘       │                       │
                       └─────▲─────▲────▲──────┘
                             │     │    │
                             │     │    │
                  ┌──────────┘     │    └─────────────┐
                  │                │                  │
             ┌────┴────┐    ┌──────┴─────┐  ┌─────────┴──────────┐
             │Discovery│    │VaultManager│  │NotificationsManager│
             └─────────┘    └────────────┘  └────────────────────┘
```

### Issues Fixed

* Fixes #225
* Fixes #224
* Fixes #254 
* Fixes #274
* Fixes #216

### Tasks

1. `NodeConnectionManager`:
   - draft API plan:
   ```ts
   class NodeConnectionManager {
      // creates/retrieves a connection, and uses to perform passed f
      public withConnection<T>(targetNodeId, f: (conn: NodeConnection => Promise<T>)): Promise<T>;
      // simply creates a connection, but doesn't use it for anything yet
      public createConnection(targetNodeId): Promise<void>;
      public destroyConnection(targetNodeId): Promise<void>;
      // Migrated from NodeManager:
      // helper function to create and set a NodeConnection (called twice in createConnection)
      protected establishNodeConnection(targetNodeId, lock): Promise<void>;
      public findNode(targetNodeId): Promise<NodeAddress>;
      public openConnection(egressHost, egressPort, timer): Promise<void>;
      // Migrated from NodeGraph:
      public getClosestLocalNodes(targetNodeId): Promise<Array<NodeData>>;
      public getClosestGlobalNodes(targetNodeId): Promise<NodeAddress | undefined>;
   }
   ```
   - [x] - Determine most appropriate async-init pattern https://github.com/MatrixAI/js-polykey/pull/310#issuecomment-1000034595
   - [x] - Integrate `RWLock`:
      * [x] - `withConnection`
      * [x] - `createConnection`
      * [x] - `destroyConnection`
   - [x] - Migrate from `NodeManager`:
      * [x] - `openConnection`
      * [x] - `findNode`
   - [x] - Migrate from `NodeGraph`:
      * [x] - `getClosestLocalNodes`
      * [x] - `getClosestGlobalNodes`
   - [x] - Rework the usage of seed nodes (currently in `NodeManager`) https://github.com/MatrixAI/js-polykey/pull/310#issuecomment-1000042319
   - [x] @joshuakarp Create a function and generator version of withConnection. refer to https://github.com/MatrixAI/js-polykey/pull/310#issuecomment-1001820924 https://github.com/MatrixAI/js-polykey/pull/310#issuecomment-1022729447
   - [x] If a nodeConnection dies, make sure it is removed from the `NodeConnectionManager`. this is triggered by the `NodeConnection` itself.

2. `NodeConnection`:
   - draft API plan:
   ```ts
   class NodeConnection {
     // publicly exposed client, such that NodeConnectionManager.withConnection can do calls
     // such as conn.client.doSomething()
     public client: GRPCClientAgent;
     // does everything that NodeConnection.start currently does
     public create/start();
     // removes itself from the reference it has to NodeConnectionManager's connection map
     public destroy()/stop();
     // Retained from current NodeConnection:
     public getRootCertChain();
     public getExpectedPublicKey();
   }
   ```
   - [x] - Determine most appropriate async-init pattern https://github.com/MatrixAI/js-polykey/pull/310#issuecomment-1000034595
   - [x] - Move all internal function implementations to use `withConnection` in relevant domain (and remove from `NodeConnection` after moving):
      * [x] - `getClosestNodes`: to `NodeConnectionManager.getClosestGlobalNodes`
      * [x] - `sendHolePunchMessage`: to `NodeConnectionManager`?
      * [x] - `sendNotification`: to `NotificationsManager.sendNotification`
      * [x] - `getChainData`: to `NodeManager.requestChainData`
      * [x] - `claimNode`: to `NodeManager.claimNode`
      * [x] - `scanVaults`: to `NodeManager`/`VaultManager`? Will need rebase on #266 when merged to bring this in
     
   - [x] Node connection needs to properly close in all cases where the client connection fails. if the client still exists when the connection should be dead then we have a resource leak.
      
3. `NodeGraph`:
   - draft API plan:
   ```ts
   class NodeGraph {
     // no changes to current API, except the function removals as listed below
   }
   ```
   - [x] - Determine most appropriate async-init pattern https://github.com/MatrixAI/js-polykey/pull/310#issuecomment-1000034595
   - [x] - Remove the following:
      * [x] - `getClosestLocalNodes`
      * [x] - `getClosestGlobalNodes`
      * [x] - `syncNodeGraph`? This currently utilises connections, so will potentially need to be moved to `NodeConnectionManager`.
4. `NodeManager`:
   - draft API plan:
   ```ts
   class NodeManager {
     // Retaining the following existing functions:
     public getNodeId();
     public knowsNode(targetNodeId);
     public pingNode(targetNodeId);
     // or could even move this to KeyManager now - gets the target node's public key
     public getPublicKey(targetNodeId); 
     // queries the encapsulated sigchain
     public getChainData();
     // queries a target node's sigchain
     public requestChainData(targetNodeId);
     public claimNode(targetNodeId);
   }
   ```
   - [x] - Determine most appropriate async-init pattern https://github.com/MatrixAI/js-polykey/pull/310#issuecomment-1000034595
   - [x] - Investigate removing the forwarding calls to `NodeGraph` https://github.com/MatrixAI/js-polykey/pull/310#issuecomment-1000051174
4. confirm issues have been addressed
   - [x] #225  
   - [x] @tegefaulkes #224 
   - ~~#254~~ being handled in #318
   - [x] #274
   - [x] #216 
4. things to double check.
   - [x] - check that `@ready` errors are correct in `NodeGraph`, `NodeManager` and `NodeConnectionManager`
   - [x] - review `NodeManager`. `NodeGraph`, `NodeConnectionManager` and `NodeConnection` tests and update where needed.
   - [x] - All node errors have appropriate sysexit numbers and descriptions.
   - ~~review based on this comment. https://github.com/MatrixAI/js-polykey/issues/299#issuecomment-1014120940~~ addressed by #318.
   - [x] - Update js-id version to 3.0.0. https://github.com/MatrixAI/js-polykey/pull/266#issuecomment-1015087695
   - [x] - @joshuakarp Review all nodes tests for any missing test cases
   - @joshuakarp Review connection state handling + diagramming https://github.com/MatrixAI/js-polykey/pull/310#issuecomment-1022722372
   - [x] - @tegefaulkes Remove any dependency cycles from the `nodes` domain. https://github.com/MatrixAI/js-polykey/pull/310#issuecomment-1022723186. This may apply to other domains, but we decided to leave that for the scope of other PRs. Related: https://github.com/MatrixAI/js-polykey/pull/318#issuecomment-1022711139

### Final checklist

* [x] Domain specific tests
* [x] Full tests
* [x] Updated inline-comment documentation
* [x] Lint fixed
* [x] Squash and rebased
* [x] Sanity check the final build

Once this is merged, it's time to do Testnet Deployment! #194

### CODE REVIEW

**Comment by joshuakarp** [comment]
From yesterday's discussions, the plan for the `NodeConnectionManager` locking is as follows:

```ts
class NodeConnectionManager {
  public withConnection() {
    // if conn exists, lock = its read lock
    // otherwise, lock = a new write lock
    createConnection(lock)
    // release lock
  }

  public createConnection(lock?) {
    if (lock == null) newLock = new write lock
    // do connection creation
    if (lock == null) release newLock
  }
}
```

As a result of this, the expectation is that we'd only really pass in our own lock when you know what you're doing, and that you've already acquired the lock that you're passing in. That seems like somewhat ambiguous behaviour to me. I feel like all of this locking behaviour shouldn't be publicly exposed at all. I know that it's an optional parameter, but we don't want other domains to need to think about this lock parameter at all.

Alternatively, we could do the following:

```ts
class NodeConnectionManager {
  public withConnection() {
    createConnection()
    // now we know a connection must exist
    // so simply get the connAndLock, acquire its read lock and do the operation
  }

  public createConnection() {
    // this should basically be identical behaviour to what getConnectionToNode currently is
    // however, it shouldn't return the NodeConnection: 
    get connAndLock
    if connAndLock != null
      if conn != null: return
      acquire write lock
      if conn != null after acquiring: return
      otherwise create connection
      release write lock
    if connAndLock == null:
      create lock and acquire write
      set lock in connections map
      create conn
      set conn in connections map
      release write lock
  }
}
```

**Comment by joshuakarp** [comment]
With the current committed usage of `RWLock`, I've been able to verify concurrent connection behaviour:

<details>

```ts
  public async withConnection<T>(
    targetNodeId,
    f: (conn: NodeConnection) => Promise<T>,
  ): Promise<T> {
    // Ensure a connection exists
    await this.createConnection(targetNodeId);
    const connAndLock = this.connections.get(targetNodeId);
    // Unexpected behvaiour: between call to create connection and retrieval, 
    // the conn or conn entry was deleted
    // if (connAndLock == null || connAndLock.connection == null) {
    //   throw new Error();
    // }
    // The above is commented out such that we don't need to create a NodeConnection - just testing the locking mechanisms
    // Acquire the read lock (allowing concurrent connection usage)
    return await connAndLock!.lock.read<T>(async () => {
      return await f(connAndLock!.connection!);
    });
  };

  // these are used by `withConnection`
  // reusing terms from network domain:
  // connConnectTime - timeout for opening the connection
  // connTimeoutTime  - TTL for the connection itself
  public async createConnection(targetNodeId: NodeId): Promise<void> {
    let connection: NodeConnection | undefined;
    let lock: utils.RWLock;
    let connAndLock = this.connections.get(targetNodeId);
    if (connAndLock != null) {
      ({ connection, lock } = connAndLock);
      // Connection already exists, so return
      if (connection != null) return;
      // Acquire the write (creation) lock
      await lock.write(async () => {
        // Once lock is released, check again if the conn now exists
        connAndLock = this.connections.get(targetNodeId);
        if (connAndLock != null && connAndLock.connection != null) return;
        // TODO: create the connection and set in map
        console.log('existing lock: created connection');
      });
    } else {
      lock = new utils.RWLock();
      connAndLock = { lock };
      this.connections.set(targetNodeId, connAndLock);
      await lock.write(async () => {
        // TODO: create the connection and set in map
        console.log('no existing entry: created connection');
      });
    }
  }
```

</details>

With the following test.ts:

```ts
import { NodeConnectionManager } from './src/nodes';
import type { NodeId } from './src/nodes/types';
import { sleep } from './src/utils';

async function main() {
  const connManager = new NodeConnectionManager();
  await connManager.createConnection('a' as NodeId);
  await Promise.race([
    connManager.withConnection('a' as NodeId, async () => {
      console.log('1.0');
      await sleep(1000);
      console.log('1.1');
      await sleep(1000);
      console.log('1.2');
      await sleep(1000);
      console.log('1.3');
      await sleep(1000);
      console.log('1.4');
    }),
    connManager.withConnection('a' as NodeId, async () => {
      console.log('2.0');
      await sleep(1000);
      console.log('2.1');
      await sleep(1000);
      console.log('2.2');
      await sleep(1000);
      console.log('2.3');
      await sleep(1000);
      console.log('2.4');
    }),
  ]);
}

main();
```

We get:

```
[nix-shell:~/Documents/MatrixAI/js-polykey]$ npm run ts-node -- test-node.ts 

> @matrixai/polykey@1.0.0 ts-node /home/josh/Documents/MatrixAI/js-polykey
> ts-node --require tsconfig-paths/register "test-node.ts"

no existing entry: created connection
existing lock: created connection
existing lock: created connection
1.0
2.0
1.1
2.1
1.2
2.2
1.3
2.3
1.4
2.4
```

Changing the `return await connAndLock!.lock.read<T>` to a write lock, ` return await connAndLock!.lock.write<T>` in `withConnection`, we get:

```
[nix-shell:~/Documents/MatrixAI/js-polykey]$ npm run ts-node -- test-node.ts 

> @matrixai/polykey@1.0.0 ts-node /home/josh/Documents/MatrixAI/js-polykey
> ts-node --require tsconfig-paths/register "test-node.ts"

no existing entry: created connection
existing lock: created connection
existing lock: created connection
1.0
1.1
1.2
1.3
1.4
2.0
2.1
2.2
2.3
2.4
```

This is expected, as the write lock should block concurrent usage.

**Comment by joshuakarp** [comment]
There needs to be some further discussion concerning the async-init patterns we use for the nodes domain.

Original comment from @CMCDragonkai about this here https://github.com/MatrixAI/js-polykey/issues/225#issuecomment-997658224:

> * `NodeGraph` - CDSS - because this is now shared between `NodeConnectionManager` and `NodeManager`, this has to be created outside of `NodeManager` as a singleton and shared - created first
> * `NodeConnectionManager` - SS or CDSS or CD - created second
> * `NodeManager` - SS or CDSS or CD - created third

`NodeGraph` (currently CDSS):
* should be CDSS, as it has persistent data storage that should be initialised on create/start, and completely wiped on destroy
* ultimately just a data structure now, akin to `ACL`/`GestaltGraph` (which also use CDSS)

`NodeConnection` (currently CDSS):
* potentially this only needs to be a CD pattern - this would also follow the usage of the CD pattern with `GRPCClientAgent` 
* I don't foresee any problems with migrating the current `start` into `createNodeConnection` instead. `start` currently:
   - creates the `GRPCClientAgent`
   - sends hole punching message to the target node (using the seed connections)
* this could also relate to the choices made in #293 

`NodeConnectionManager`:
* most likely dependent on what `NodeConnection` is - if it remains as CDSS, then this will also likely be CDSS (stops the `NodeConnection`s on `stop`, and destroys on `destroy`), otherwise this could also be CD

`NodeManager` (currently CDSS):
* given that `NodeGraph` will no longer be an encapsulated dependency on `NodeManager`, there's also some flexibility with what this will need to be. Previously, we had to propagate the `NodeGraph.destroy` into the `NodeManager.destroy`, but this will no longer be the case

Also worthwhile to recall this comment from me regarding a problem with ordering on `PolykeyAgent` startup https://github.com/MatrixAI/js-polykey/pull/289#issuecomment-991994067 and the discussion of using the start-stop pattern as a way to mitigate this https://github.com/MatrixAI/js-polykey/issues/225#issuecomment-992053076.

**Comment by joshuakarp** [comment]
We'll also need to slightly rework the usage of seed node connections.

At the moment, we have a function `NodeManager.getConnectionsToSeedNodes` that establishes/retrieves the connections to each of our seed nodes. This is used in a few places:
* `PolykeyAgent.start`: for initially establishing the connections. This is currently separated from the regular `NodeManager.start` as a result of some ordering issues discussed here https://github.com/MatrixAI/js-polykey/pull/289#issuecomment-991994067. Ultimately, this problem should be aimed to be resolved in this nodes refactoring effort.
* `NodeConnection.start`: the seed node connections are passed in every `createNodeConnection` call. This is currently done to allow hole punching messages to be sent to the seed nodes, and then relayed to the target node to allow the connection to be established. Calls `NodeConnection.sendHolePunchMessage`.
* `NodeGraph.syncNodeGraph`: for initially populating a new `NodeGraph` with some initial nodes closest to it. We ask the seed nodes for the closest nodes to our newly created node. Calls `NodeConnection.getClosestNodes`.

This shouldn't require too much of a rework. Initially thinking about this, we can instead statically store the seed node IDs in `NodeConnectionManager`, and just call `withConnection` on each of these IDs with the appropriate functionality we require.

**Comment by joshuakarp** [comment]
There's also the problem of code repetition when using `withConnection`. For example, we currently have a `getClosestNodes` function in `NodeConnection`. This is called in 2 places:
1. `NodeGraph.syncNodeGraph`
2. `NodeGraph.getClosestGlobalNodes`

Both places connect to a remote node and retrieve a set of closest nodes (i.e. the same functionality).

We'll no longer be wrapping this common functionality within a `NodeConnection` function. Instead, we could wrap it as a common function in some other class like so:

```ts
class NodeConnectionManager {
  public requestClosestNodes(targetNodeId) {
    return this.withConnection(targetNodeId, async () => {
      // functionality to get the closest nodes
    });
  }
  
  public syncNodeGraph() {
    // ...
    this.requestClosestNodes(this.keyManager.getNodeId());
  }

  public getClosestGlobalNodes(targetNodeId) {
    // ...
    this.requestClosestNodes(targetNodeId);
  }
}
```

Although I am wary that this starts to lean towards the issues that we're currently trying to solve (where `NodeConnection` has multiple functions that simply construct GRPC messages and relay calls to the GRPC client). Here, we seem to just be pulling this problem out of `NodeConnection` and into some other domain.

**Comment by joshuakarp** [comment]
Given that `NodeGraph` will no longer be treated as an encapsulated dependency of `NodeManager`, we also have the opportunity to remove the forwarding calls in `NodeManager` that simply query the `NodeGraph`. For example:

```ts
  public async getNode(targetNodeId: NodeId): Promise<NodeAddress | undefined> {
    return await this.nodeGraph.getNode(targetNodeId);
  }
```

We have similar functions for setting a node, getting all the node buckets, getting the closest global nodes, and refreshing the buckets.

This would mean that we would instead inject `NodeGraph` into the domains that it would need to be used. 

So 2 alternatives here:
1. We retain the forwarding functions in `NodeManager`, and keep it as is where we inject `NodeManager` everywhere it's necessary to query/add to the `NodeGraph`
2. We remove the forwarding functions, and instead inject `NodeGraph` everywhere we need it. This greatly simplifies the API of `NodeManager`, but means we'd need to expose `NodeGraph` in lots of different places

**Comment by CMCDragonkai** [comment]
Regarding with contexts and general resource management patterns.

In OOP we have RAII, and this is being done through the js-async-init. But it's fairly a manual process with `createX`, `destroy`, `start`, `stop` being used. In our overall app architecture this is put together as matroska dolls and nesting the create, start, stop, destroy.

In imperative programming, we have the `try` `finally` pattern that interacts with RAII. Basically create the resource initially, then in `finally` destroy the resource. This works well with RAII. And it's also really flexible, since it can be used pretty much anywhere.

In functional programming we have additional pattern: with contexts or known as the bracketing pattern. This is a higher order function that takes a callback and injects it the resource, and when the callback is done, it will release/destroy the resource. We have used this in a number of places as it's a nicer interface for interacting with resources and it automates the destruction as it scopes the resource lifecycle to the function callstack/scope. We have used this in a number of places and intend to use it for things like `withConn`, `withVault`, `withLock`... etc.

One issue with using brackets, is that JS has 2 kinds of async functions (assume that such resource management always takes place asynchronously), ones that return a promise, and ones that return an async generator. And this would require 2 different variants of the bracket function like `withConnF` and `withConnG`. Additionally nesting brakets/with contexts can lead to a callback mountain which isn't as nice, in which case a generalised `with` combinator or promise-based chaining system should be used.

For example a general `with` combinator would look like this:

```ts
// similar to python's with Context() as a, Context() as b:
withF([resource, resource], (a, b) => {

});
// need a async generator variant
withG([resource, resource], async function* () {

});
```

To do the above, the resources must all have a similar expected interface. Perhaps something like:

```ts
// the T may be optional, in that it may not actually be available
// locking resource doesn't give any lock resource to the callback
type Resource<T> = () => Promise<[T, () => Promise<void>]>
```

This would allow the with combinator to always work any resource such as those exposed via imperative APIs.

```ts
let count = 0;
withF([
  async () => {
    ++count;
    return [count, async () => { --count; }]
  }
], (c) => {
  console.log(c);
})
```

The with combinator signature might be complicated, since you have to accumulate the types of resources that will be acquired, and expect a function to be passed in that takes those types. This would be similar to the signature for `Promise.all` since it also has to take an array of arbitrary types and then spread it into the `then` callback.

A promise chaining system would be similar to how promises can chain stuff:

```ts
resourceA().with(resourceB).with(resourceC).then((a, b, c) => {
});
```

But I can't really see this being much better than what is discussed above.

@tegefaulkes @joshuakarp relevant to our discussions about the right API for nodes and vaults.

**Comment by CMCDragonkai** [comment]
If `withF` and `withG` are generalised utility functions. Then we wouldn't expect each class/domain to expose it. Instead each domain would need to expose a "resource API" as per the example given:

```
type Resource<T> = () => Promise<[T, () => Promise<void>]>
```

So imagine for `ACL`, instead of `transaction`, you expose the ability to lock the ACL.

```ts
class ACL {
  public function acquireLock() {
    await this.lock.acquire();
    return [undefined, () => {
      release();
    }];
  }
}
```

Then external users could then use `withF([acl.acquireLock()], ...);`.

**Comment by tegefaulkes** [comment]
Right now NodeConnection requires a `Map<NodeId, NodeConnection>. this doesn't work with the `withConnection()` method of using the connections. I could use `withConnection()` inside of the `NodeConnection` but having the `NodeConnection` keep a reference back to the `NodeConnectionManager` doesn't feel quite right.

**Comment by CMCDragonkai** [comment]
It's totally fine for node connection to keep a reference back to the manager. We do this already in the networking proxies.

**Comment by CMCDragonkai** [comment]
We would normally want the collection to be weakly referenced. But it's not possible in JS even with weak map. So you'll have to use Map with a reverse reference for garbage collecting it's reference.

**Comment by CMCDragonkai** [comment]
The RWLock should be changed over to write-preferring to prevent write-starvation. Example of this is here: https://gist.github.com/CMCDragonkai/4de5c1526fc58dac259e321db8cf5331#file-rwlock-write-ts

I've already used this in js-async-init to great effect. The current RWLock in js-polykey is read-preferring is not the best way to do it.

**Comment by CMCDragonkai** [comment]
Priorities:

1. NodeConnectionManager - this is the centerpiece
2. NodeManager - moving functionality out of this into `NodeConnectionManager` and also using `NodeConnectionManager` when interacting with nodes
3. NodeGraph - changing this to being a data structure and move out some functionality into `NodeConnectionManager`
4. Then address the error handling, first in `GRPCClient` and watching the connectivity state, then in `NodeConnection`, look into ready method wrapping as well when other users end up calling on a "broken"/"dead" node connection
5. Finally look at all the other domains that need to call other keynode's agent service like `VaultManager`.. etc and how they should be changed accordingly to use `withConn` or our generic `with` combinator

**Comment by tegefaulkes** [comment]
I've created an interface that exposes only the needed functionality from NodeConnectionManager for NodeConnection. This includes a personalised callback to handle destroying and removing itself from the connection map.

**Comment by CMCDragonkai** [comment]
Rebase please!

**Comment by CMCDragonkai** [comment]
@tegefaulkes can you make sure this PR removes this:

```
[nix-shell:~/Projects/js-polykey/tests]$ ag 'failedConnectionTimeout'
global.d.ts
11:declare var failedConnectionTimeout: number;

bin/nodes/ping.test.ts
114:    global.failedConnectionTimeout * 2,
136:    global.failedConnectionTimeout * 2,

bin/nodes/find.test.ts
195:    global.failedConnectionTimeout * 2,

bin/nodes/add.test.ts
98:    global.failedConnectionTimeout,
117:    global.failedConnectionTimeout,

client/rpcNodes.test.ts
230:    global.failedConnectionTimeout * 2,
275:    global.failedConnectionTimeout * 2,
301:    global.failedConnectionTimeout * 2,

nodes/NodeManager.test.ts
265:      global.failedConnectionTimeout * 2,
315:    global.failedConnectionTimeout * 2,
391:    global.failedConnectionTimeout * 2,
```

This should no longer be necessary once you have timeouts dependency injected, or timer mocking. Once done, remove the variable from `jest.config.js`.

**Comment by CMCDragonkai** [comment]
I've added #274, #216, #254 to this PR @tegefaulkes since these are all related together, it's best to refactor these together.

**Comment by tegefaulkes** [comment]
Re-based on master.

**Comment by CMCDragonkai** [comment]
There's some confusion between all these methods that we should make clearer.

* withConnection - with wrapper, should have promise and async generator variant
* createConnection - public methods to create a connection but doesn't return the connection
* destroyConnection - public method to destroy a connection
* establishNodeConnection - wrapped function that actually creates the connection
* openConnection - hole punch for reverse proxy
* fwdOpenConnection - hole punch for forward proxy

These are all quite confusing, we should be renaming these accordingly.

1. Investigate whether `createConnection` should really be public or not, and this has a relationship with the seed nodes synchronisation, it may not be necessary anymore
2. Maybe `createConnection` should actually be `getConnection`, in this case the connection object is actually returned. But this becomes a manual usage.
3. The `establishNodeConnection` which is a protected function should be renamed so that it's clearer that it is a wrapper worker function. This is based on the object map pattern which was originally called `createObject`, and if `2` can be addressed, then `establishNodeConnection` can be `createConnection`
4. The hole punching functions shouldn't be called `openConnection`... etc, they can be called `holePunchForward` or `holePunchReverse`

@tegefaulkes I think it's a good idea for you to review in detail the design of 2 things:

1. The kademlia node graph so you have an idea how the contact database is being synchronised
2. How the hole punching ICE logic is supposed to work

**Comment by tegefaulkes** [comment]
When moving some functionality about I keep getting to the question "Do I put it in the `NodeManager` or the `NodeConnectionManager`?".  It seems to me that the `NodeConnectionManager` should solely handle the `NodeConnection`s and their life cycle. So maybe all functionality such as `getClosestLocalNodes`, `sendHolePunchMessage` or `findNode` should be in the `NodeManager`?

Also to note, there are two functions for `getClosestLocalNodes`. One that calls the GRPC and one that is called by the service. Like above I think they should both be in the `NodeManager`. However I need a good way to tell them apart by name.

**Comment by CMCDragonkai** [comment]
Connection-related work is indeed in the `NodeConnectionManager`. So if there are functions relating to managing connections, doing hole punching.

Note in the diagram https://github.com/MatrixAI/js-polykey/issues/225#issuecomment-997658224 `NodeManager` requires `NodeConnectionManager` but not the other way around. So this has some implications for how sending notifications needs to occur. It's possible that `NodeConnectionManager` needs `NotificationsManager` to do it. But there's a recursive dependency here too.

This mutually recursive dependency has to be resolved by further abstraction, or some sort of normalisation. Prototype how it can be done with sending notifications.

For `getClosestLocalNodes`... you have the sender and receiver. One is to ask another node what their closest local nodes are, and another is to give back what the closest local nodes are. You could centralise it by giving it a parameter, where if the `nodeId` is undefined, then it assumes it means itself. Or separate the 2 functions entirely by different names.

**Comment by tegefaulkes** [comment]
NodeManager has a `getNodeId()` method that just wraps the `KeyManager.getNodeId()` maybe we should get this directly from the KeyManager?

**Comment by CMCDragonkai** [comment]
> NodeManager has a `getNodeId()` method that just wraps the `KeyManager.getNodeId()` maybe we should get this directly from the KeyManager?

That would have to be addressed by clarifying the spec in https://github.com/MatrixAI/js-polykey/issues/254 and the associated https://github.com/MatrixAI/js-polykey/issues/312

**Comment by tegefaulkes** [comment]
`NodeManager` has a few methods wrapping methods from the `NodeGraph`. Since `NodeGraph` is now outside of `NodeManager` I'll look at removing these and calling the `NodeGraph` directly where needed.

**Comment by tegefaulkes** [comment]
Looks like I can completely remove the `nodeGraph` from `NodeManager`. The only thing left in there was the `syncNodeGraph()` and it makes sense to keep that with the `getClosestNodes()` functionality in `NodeConnectionManager`.

**Comment by tegefaulkes** [comment]
I'm going to remove `getConnectionsToSeedNodes()` from `NodeConnectionManager` and just inline the functionality where needed. All it really does is establish connections to the seed nodes and returns a list of nodes that it connected too.

**Comment by tegefaulkes** [comment]
Looking into async-init patterns for `NodeConnectionManager`, `NodeManager` and `NodeGraph`.
there is some previous discussion on this here. https://github.com/MatrixAI/js-polykey/pull/310#issuecomment-1000034595

#### NodeConnectionManager:
This only handles the lifecycle `NodeConnections`, some utility with the connnections and finding the closest nodes. In terms of it's lifecycle it's adding `seedNodes` to the `nodeGraph` and closing all the connections when stopping. Given that, this could purely be a `SS` pattern to match the rest of the newtorking but currently it is `CDSS` to match the lifecycle of `PolykeyAgent`.

#### NodeGraph:
Since this is just a data structure now we could just use a `CD` But we may need a way to clear it at certain points of `PolykeyAgent`'s life cycle, So `CD`+ clear.

Currently it is `CDSS` where we have the option to clear with `start({fresh})` and clear with destroy. We may just need to keep this `CDSS`.

#### NodeManager:
`NodeManager` is currently `CDSS` but doesn't do anything during creation, start, stop or destroy. Given that it could just be created with `new NodeManager()`. In fact it looks like most of the functionality left in there can be moved elsewhere.

`pingNode`, `getPublicKey` and`requestChainData` could be moved into `NodeConnectionManager`.  `scanNodeVaults` should just be removed. `getChainData` is just a wrapper for a sigchain method and the transactions and locking are not used anymore.

It looks like only `claimNode` doesn't fit elsewhere. May need to look into this more.


#### In summary:
- i'll likely change `NodeConnectionManager` to `SS` to match the other networking domains.
- NodeGraph should stay as `CDSS`
- Depending on what we can do with `claimNode` it's possible we should just remove the `NodeManager` all together.

Can you give some input on the @CMCDragonkai?

**Comment by tegefaulkes** [comment]
One aspect of this PR that still needs speccing out. How do we handle connection TTL timing out?
- We need a way for a timer to destroy the connection. We need to be able to update the timer when the connection is used. Need to destroy the timer if the connection is already destroyed.
- We need a way to destroy/remove the connection from `NodeConnectionManager` if the connection dies of its own accord. We already have an interface providing a function for that to the `NodeConnection`, we just need to call it when the connection dies.

It seems to me that we can add the timer to the object map. when `destroyConnection()` happens we can kill the timer along with the connection and utilize the locking that comes with that. If the connection is already dead then the `destroyConnection` should be a noop.

Looks like we can use setTimeout() for the timer.
```ts
// Starting the timer
const timer = setTimeout(() => {/*do thing*/}, timeoutDelay);

// if we want to extend the timer by the same delay
timer.refresh()

// If we want to kill the timer.
clearTimeout(timer);
```

Overall this fits our use very well.

So the spec here is.
- `establishConnection` creates a timeout with `const timer = setTimeout(() => {this.destroyConnection(nodeId)}, timeoutDelay)` that calls `destroyConnection` and adds it to the connectionMap with the lock and connection.
- 'destroyConnection' will clear the timeout with `clearTimeout(timer)` when the connection is destroyed.
- 'withConnection' will refresh the timeout with `timer.refresh()` when used.

**Comment by tegefaulkes** [comment]
With the TTL implemented I need to work out how to trigger the removal of the connection from the NodeConnectionManager. Right now I am unclear on how a GRPCClient dies and how that is handled.

**Comment by tegefaulkes** [comment]
I also need to explore the connection error handling in more depth and understand how the error are propagated and handled.

**Comment by tegefaulkes** [comment]
I've expanded `NodeConnectionManager.test.ts` with some `test.todo`s. I need to review the other nodes tests for any tests that need to be moved or updated.

**Comment by CMCDragonkai** [comment]
> I also need to explore the connection error handling in more depth and understand how the error are propagated and handled.

1. The networking domain cannot bubble exceptions to the grpc client nor nodes.
2. The networking domain provides proxies which are listening on the host computer network stack.
3. `NodeConnection` uses `GRPCClient` to do the actual connection.
4. `GRPCClient` connects via HTTP 1.1 CONNECT proxy protocol to the forward proxy.
5. At the TCP layer, there are only 2 errors you will have to address in `GRPCClient`, timeouts and abnormal termination.
6. `GRPCClient` requires a state handler integrated so it can watch for when the underlying connection state changes.
7. You must create tests in the grpc domain that simulate what happens when connection timeout occurs in both pre-start and also after the connection has started as well during abnormal connection termination. These tests must use a mocked or extended ForwardProxy that simulates these behaviours. There are examples of simulating network behaviour in the networking tests already.
8. Custom exceptions must be integrated into grpc domain regarding these connection errors.
9. When these errors occur they can be propagated to the `NodeConnection` which then changes its state and then should result in propagating the exception to the caller of `nodeConn`.

**Comment by CMCDragonkai** [comment]
> With the TTL implemented I need to work out how to trigger the removal of the connection from the NodeConnectionManager. Right now I am unclear on how a GRPCClient dies and how that is handled. 

#224 has information on the handler we need to install into grpc upstream in order to watch for state changes. You need to prototype this before we begin because you need to see how this can work before integrating into the code. Start with a `test-client.ts` and `test-server.ts` then observe logging from the state handlers while changing the behaviour of the server. First happy case, then abnormal cases like having a TCP server never answer, or immediately destroy socket or send an end FIN packet.

**Comment by CMCDragonkai** [comment]
> One aspect of this PR that still needs speccing out. How do we handle connection TTL timing out?
> - We need a way for a timer to destroy the connection. We need to be able to update the timer when the connection is used. Need to destroy the timer if the connection is already destroyed.
> - We need a way to destroy/remove the connection from `NodeConnectionManager` if the connection dies of its own accord. We already have an interface providing a function for that to the `NodeConnection`, we just need to call it when the connection dies.
> 
> It seems to me that we can add the timer to the object map. when `destroyConnection()` happens we can kill the timer along with the connection and utilize the locking that comes with that. If the connection is already dead then the `destroyConnection` should be a noop.
> 
> Looks like we can use setTimeout() for the timer.
> ```ts
> // Starting the timer
> const timer = setTimeout(() => {/*do thing*/}, timeoutDelay);
> 
> // if we want to extend the timer by the same delay
> timer.refresh()
> 
> // If we want to kill the timer.
> clearTimeout(timer);
> ```
> 
> Overall this fits our use very well.
> 
> So the spec here is.
> - `establishConnection` creates a timeout with `const timer = setTimeout(() => {this.destroyConnection(nodeId)}, timeoutDelay)` that calls `destroyConnection` and adds it to the connectionMap with the lock and connection.
> - 'destroyConnection' will clear the timeout with `clearTimeout(timer)` when the connection is destroyed.
> - 'withConnection' will refresh the timeout with `timer.refresh()` when used.

We currently have an API for timers. We use it already in networking. And the utility function comes from `src/utils.ts`.

Note that we have 2 ways of parameterizing timeouts. One is with a second integer count and another is with the timer object. The timer object is more composable and may be more suitable when there is nesting. Second integer counts are more suitable for construction/creation parameter configuration.

See networking domain for inspiration.

**Comment by CMCDragonkai** [comment]
> Looking into async-init patterns for `NodeConnectionManager`, `NodeManager` and `NodeGraph`.
> there is some previous discussion on this here. https://github.com/MatrixAI/js-polykey/pull/310#issuecomment-1000034595
> 
> #### NodeConnectionManager:
> This only handles the lifecycle `NodeConnections`, some utility with the connnections and finding the closest nodes. In terms of it's lifecycle it's adding `seedNodes` to the `nodeGraph` and closing all the connections when stopping. Given that, this could purely be a `SS` pattern to match the rest of the newtorking but currently it is `CDSS` to match the lifecycle of `PolykeyAgent`.
> 
> #### NodeGraph:
> Since this is just a data structure now we could just use a `CD` But we may need a way to clear it at certain points of `PolykeyAgent`'s life cycle, So `CD`+ clear.
> 
> Currently it is `CDSS` where we have the option to clear with `start({fresh})` and clear with destroy. We may just need to keep this `CDSS`.
> 
> #### NodeManager:
> `NodeManager` is currently `CDSS` but doesn't do anything during creation, start, stop or destroy. Given that it could just be created with `new NodeManager()`. In fact it looks like most of the functionality left in there can be moved elsewhere.
> 
> `pingNode`, `getPublicKey` and`requestChainData` could be moved into `NodeConnectionManager`.  `scanNodeVaults` should just be removed. `getChainData` is just a wrapper for a sigchain method and the transactions and locking are not used anymore.
> 
> It looks like only `claimNode` doesn't fit elsewhere. May need to look into this more.
> 
> 
> #### In summary:
> - i'll likely change `NodeConnectionManager` to `SS` to match the other networking domains.
> - NodeGraph should stay as `CDSS`
> - Depending on what we can do with `claimNode` it's possible we should just remove the `NodeManager` all together.
> 
> Can you give some input on the @CMCDragonkai?

I think `NodeManager` is still needed. There are high level calls to nodes database that must be only exposed via `NodeManager` such as the management of the contact database. And interactions with the sigchain as well.

**Comment by CMCDragonkai** [comment]
> I'm going to remove `getConnectionsToSeedNodes()` from `NodeConnectionManager` and just inline the functionality where needed. All it really does is establish connections to the seed nodes and returns a list of nodes that it connected too.

Can also use a protected method if it's a good idea to label that block of code.

**Comment by CMCDragonkai** [comment]
> Looks like I can completely remove the `nodeGraph` from `NodeManager`. The only thing left in there was the `syncNodeGraph()` and it makes sense to keep that with the `getClosestNodes()` functionality in `NodeConnectionManager`.

We don't actually want to expose node graph outside nodes domain. So `NodeManager` is still needed as a public interface.

**Comment by CMCDragonkai** [comment]
> 7. You must create tests in the grpc domain that simulate what happens when connection timeout occurs in both pre-start and also after the connection has started as well during abnormal connection termination. These tests must use a mocked or extended ForwardProxy that simulates these behaviours. There are examples of simulating network behaviour in the networking tests already.

Expanding you want to use a `net.createServer` to create TCP server first. This will allow you to test these variants:

1. What happens when the TCP server just receives the connection then does nothing - expect a timeout here during the `waitForReady`
2. What happens if the TCP server receives the connection and immediately terminates it with `end(); destroy();` - should also affect `waitForReady()`

Next bring in a GRPC server, but not `src/grpc/GRPCServer.ts`, use the `tests/grpc/utils`, which allows you to create raw GRPC servers. In this case you can start to do other things...

1. Start a grpc server with the test service. Then in your test handler, you want to do `process.exit()`. See what happens here. - expect something to break while the client is calling it, like a unary call
2. Try with a handler that takes a LOOONG time. Like a big sleep, and then you send a SIGKILL to the process. - same expectation as 1.
3. Do it again with async generator/stream. What happens to the stream and connectivity state? - Probably the same as 1., but the stream itself ends up being "destroyed". But check the stream booleans/async generator booleans, and also if you try to do `next()`, there should be an exception.

What we don't want to see is resource leaks occurring on the client side when the server side fails.

Final set of variants depends on the ForwardProxy. There you can re-use some of the tests from `networking/ForwardProxy.test.ts` and use those but with a real GRPC client to see what happens. One of the variants should be dealing with when the proxy itself fails due to incorrect HTTP CONNECT protocol. See test `HTTP CONNECT bad request failures to the forward proxy` and `connection to port 0 fails`.

**Comment by tegefaulkes** [comment]
After discussion with @CMCDragonkai I'm converting `NodeConnection` to `CreateDestroy` and `NodeManager` to a plain class.

**Comment by tegefaulkes** [comment]
Cool, it took a little bit but now I'm able to see the connection state using `watchConnectivityState`. Looks like under normal operation the states are IDLE -> CONNECTING -> READY -> SHUTDOWN. this is to be expected. Now I can experiment with breaking the connection.

But from here I can easily watch for the SHUTDOWN state and call a shutdown callback to properly close out the connection and handle removing it from the `NodeConnectionManager`.

**Comment by tegefaulkes** [comment]
I've run into a small problem with connectivity state. While it's easy to call a callback that destroys the `NodeConnection` from the `NodeConnectionManager`. `watchConnectivityState` doesn't take a async callback. But `NodeConnectionManager.destroyConnection` is async and due to async rot the `shutdownCallback` needs to be async as well. 

So while it _does_ properly run the callback and close the connection from the `NodeConnectionManager` if we close the connection using `NodeConnectionManager.destroyConnection` we end up with a race condition where we're running `destroyConnection` twice. This is not a major problem it does have the weird quirk of `destroyConnection` returning but a AWOL `destroyConnection` still holding the lock.

So far I've solved this by adding a `_destroying` flag to `NodeConnection` and only running `shutdownCallback` if the `NodeConnection` isn't currently being destroyed.

Like I said, this wasn't a major problem just weird behaviour. Locking would've handled any actual problems.

**Comment by tegefaulkes** [comment]
Odd, if we close the end the connection from the TCP server  we end up with the states IDLE->CONNECTING->TRANSIENT_FAILURE->IDLE.  But `NodeConnection does throw a `ErrorNodeConnectionTimeout` error so we are aware that the connection failed to connect. It may not be shutting down properly after that. Looking into it.

**Comment by tegefaulkes** [comment]
Seems to be a bug. When we get an error connecting when creating the connection the client isn't properly destroyed.

**Comment by tegefaulkes** [comment]
Found it, when the client is created and `waitForReady` fails then the client is never cleaned up. this is an edge case where we connect to an agent but the connection is rejected. Calling `client.close()` when `waitForReady` fails seems to fix this.

**Comment by tegefaulkes** [comment]
I have a good basis for testing now but I need to test some scenarios with connection problems in the middle of active GRPC commands. to have better control over this I should use a test client. Right now `GRPCClientAgent` is hard coded into `NodeConnection`.

 It would be great if I could override the client being used by providing the client class as a parameter but the `createX` constructor for each client has a different name. Maybe I can provided id as a lamda function `(params) => { return GRPCClientX.createX(params)}`. I may need to explore this.
 
Alternatively I could extend a testNodeConnection and override it's `createX` to use the test client. but that's replicating code and will lead to errors if implementation changes.

I can add test RPC calls to the `GRPCClientAgent` client and use them for the tests.

Any thoughts @CMCDragonkai ?

**Comment by CMCDragonkai** [comment]
> I have a good basis for testing now but I need to test some scenarios with connection problems in the middle of active GRPC commands. to have better control over this I should use a test client. Right now GRPCClientAgent is hard coded into NodeConnection.

Do you mean `NodeConnection` is hardcoded to use `GRPCClientAgent`? The `GRPCClientAgent` isn't supposed to know about `NodeConnection`.

**Comment by tegefaulkes** [comment]
Yes, that's what I meant.

**Comment by CMCDragonkai** [comment]
You may need to do module mocking for this then. Module mock the `GRPCClientAgent` that gets used inside `NodeConnection`.

But this is after you are already testing `GRPCClientAgent` right? Most network connection failure tests can be done with `GRPCClientAgent` first.

**Comment by tegefaulkes** [comment]
Found another bug. after connecting to a `PolykeyAgent` and then the `PolykeyAgent` stops the `NodeConenction` is not closing properly.

```
INFO:nodeConnection:Creating NodeConnection
INFO:GRPCClientAgent:Creating GRPCClientAgent connecting to 0.0.0.0:45568
INFO:connectionState:State is now IDLE
INFO:connectionState:State is now CONNECTING
INFO:connectionState:State is now READY
INFO:GRPCClientAgent:Created GRPCClientAgent connecting to 0.0.0.0:45568
INFO:nodeConnection:Created NodeConnection
// Stopping PolykeyAgent here
INFO:connectionState:State is now IDLE
WARN:ConnectionReverse 127.0.0.1:11110:Server Error: ErrorConnectionEndTimeout
WARN:ConnectionReverse 127.0.0.1:11110:Reverse Error: ErrorConnectionEndTimeout
```
Not sure what's happening here. connection is trying to close gracefully but the client never sees the connection ending.

**Comment by tegefaulkes** [comment]
The `ForwardConnection` seems to be closing properly, but the client connection's state returns to IDLE and remains open..

**Comment by tegefaulkes** [comment]
This seems to be a combination of two things. when the AgentService is stopped it doesn't close the client connection through the proxies. likewise, when the fwdProxy's forward connection closes it doesn't close the corresponding client connection.

@CMCDragonkai can you chime in with what is expected to happen?  I think you mentioned that the client and service break the connection and then the proxies break the connection outwards in. I think the connection chain should break like a bubble from where the connection is closed or fails.

**Comment by CMCDragonkai** [comment]
For the proxies, they handle closing from any origin point, whether from forward, reverse or from client and server.

There are tests in the networking domain that demonstrate this. Look for the tests closing from server side, client side... etc.

So agent service should be doing the same.

Note that closing requires calling `.end()` if you aren't doing that, then you're just destroying the socket, which means you're not completing the handshake.

It's better to complete the full handshake, by calling `end()` then expecting to receive an end event from the other side.

Review the network tests to fully understand, it's a bit tricky.

**Comment by tegefaulkes** [comment]
When the server is stopped we do see the FIN ACK packets closing the connection. this corresponds with the channel transitioning to IDLE.
 
```
IDLE
CONNECTING
READY
// server shutdown, 
// server initiates end.
IDLE
```

in the TCPserver test the connection last long enough for the client to reject the SSL certificate and the client initiates the end.

```
IDLE
CONNECTING
// client rejects cert
// client initiates end
TRANSIENT_FAILURE
SHUTDOWN
```


If the TCP server closes the connection immediately then it sends a HTTP 502 BAD GATEWAY. the client then ends the connection.

```
IDLE
CONNECTING
// Server closes connection immedietly.
// Server sends a 502 BAD GATEWAY
// client initiates end.
TRANSIENT_FAILURE
SHUTDOWN
```

 So far the impression I'm getting is that to reach shutdown the client needs to close. 
Refering to https://grpc.github.io/grpc/core/md_doc_connectivity-semantics-and-api.html shows us that shutdown is triggered via the application. Be it case 2 where we close after rejecting the cert or case 3 where we receive a bad gateway HTTP packet.

Case 1 we see that the connection is closing but the client's channel is in an IDLE state. I think this just means no active connections but the client hasn't shutdown yet. and likely wont until we either close the client or we attempt a GRPC call and the new connection times out.

I'm exploring this further.

**Comment by tegefaulkes** [comment]
The connection timing out takes longer than 6 minuets. So far as I can tell, the channel state doesn't change to `SHUTDOWN` unless the client itself starts the shutdown procedure. If a connection fails or ends then the channel state enters `IDLE`.

`IDLE` means there is no active connection. when we start a client we start in `IDLE` we can also enter `IDLE` if the channel times out and closes the connection to release resources. we will also enter `IDLE` if the channels connection is closed from the outside.

if we attempt another GRPC call from `IDLE` we will enter `CONNECTING` and if the connection can't be established we will get a timeout error. we could use this to determine that we want to close the client. 

So I think the options for determining if the client should shutdown is...
1. entering the `SHUTDOWN` state means the client has already shutdown, no further action is needed but if the client triggered `SHUTDOWN` itself then we can initiate destruction of the connection for `NodeConnection` and `NodeConnectionManager`
2. a transition from `READY->IDLE` state means the connection was closed or timed out. we can close the client in this case. if it was a timeout then the connection could close before our own TTL closes it.
3. a transition from `READY->IDLE` state means the connection was closed or timed out. we can attempt to start up the connection right away and if we get a connectionTimeout error we can then close the client otherwise keep the connection open. our own TTL can close the connection.

1 and 3 seem like the best option to me.

**Comment by tegefaulkes** [comment]
So far I have a working solution. there may be some quirks to iron out so I'm expanding tests tests currently. so far all tests where the connection fails during creation or during a live connection are working. looking into what happens when a connection fails during a stream and unary call.

**Comment by tegefaulkes** [comment]
Not really a problem but I'm running into a small issue. when the connection fails during a `withConnection` an error is thrown as expected but the connection is not removed from the `NodeConnectionManager` right away. this won't cause any major problems but it's untidy. a new `withConnection` could be attempted before the destruction of the connection is attempted.

I may have to catch the connection errors inside of `WithConnection` and remove the connection from the `NodeConnectionManager` before the `withConnection` returns.

**Comment by CMCDragonkai** [comment]
Why isn't it removed right away? If we catch the error we can remove the connection object.

**Comment by tegefaulkes** [comment]
Looking at that now.

**Comment by tegefaulkes** [comment]
Most of the testing relating to connection failure conditions are done now. For expediency sake I implemented the test RPC commands in the `AgentService`. looking at moving them into the testing service now.

**Comment by tegefaulkes** [comment]
I'm trying to work out how to spawn a `TestServer` as a separate process. I suppose I could create a test module for it and fork it.

**Comment by CMCDragonkai** [comment]
You could re-use how we do it for `pkSpawn`. It would have to be a separate script. However `fork` could also be used like we do in `polykey-agent`.

**Comment by tegefaulkes** [comment]
So far I've converted the `NodeConnection` class to take the type of GRPC client as a generic parameter. I'm in the process of updating the tests to use the test client now.

There is a problem with converting the `NodeConnectionManager` to use a generic `NodeConnection`. It expects specifically a `GRPCClientAgent` for some of the methods such as `getRemoteNodeClosestNodes()`. So i'm trying to work around this without complicating the code too much for the sake of testing.

The things that come to mind that I could try are;
1. Split up the `NodeConnectionManager` into a `GenericConnectionManager` and extend that to a `NodeConnectionManager` so I can run connection tests on the `GenericConnectionManager`. but this is complicating the `NodeConnectionManager` for little benefit.
2. Use typescript hackery to trick the `NodeConnectionManager` into using a test client.
3. I had the test GRPC calls implemented in the agentService and working. but this leaves a unused GRPC method that can just crash the Node at anytime in production if someone decided to call it.

I'll try out 2 first.

**Comment by CMCDragonkai** [comment]
Since we split up the service tests. It's possible to give only a single method that you care about to the grpc server for testing. Maybe that is possible with the client as well, not sure. It's just a matter of telling TS and asserting a type and in the tests not touching those methods.

Moreover is this because you want to do mocking? Are there tests you can just do by running a full agent/grpc server on the other side and just mock the service handler side?

**Comment by tegefaulkes** [comment]
This is for testing what happens with `NodeConnectionManage` and `withConnection()` when the connection fails. the tests themselves use a simple echo unary or echo stream calls but both will crash the process in 3 ways.
1. echo contains `exit` will call `process.exit()`
2. echo contains `kill` will call `process.kill()`
3. echo contains `sigkill` will call `process.kill(9)`

So there are 3 things I need to do  to get this testing working.
1. [x] have `NodeConnection` use the `GRPCClientTest`
2. [x] set up a functioning `TestServer` and connect.
3. [x] Have the `TestServer` run in it's own process.

**Comment by tegefaulkes** [comment]
All of the testing for connection failures is implemented now.

**Comment by tegefaulkes** [comment]
Odd behaviour when starting a `NodeConnection` When connecting to an IPV6 `::1` that doesn't exist the `waitForReady()` timeout doesn't work. The connection sits on `CONNECTING` forever and strangely the jest doesn't timeout properly.

**Comment by CMCDragonkai** [comment]
IPv6 doesn't work with the UTP atm. But you're saying that GRPC client directly doesn't work with IPv6? If so it's an upstream bug and should be reported with a reproducible snippet.

**Comment by tegefaulkes** [comment]
Looks like the proxy is using the `::1` IP in this case. so it means that the client isn't timing out when connecting to the proxy in this case. Not sure why, I'll have to look deeper into it later.

**Comment by CMCDragonkai** [comment]
There was a test for this regarding the proxy. Was a regression on that test or is this a new situation?

**Comment by tegefaulkes** [comment]
I haven't looked at the proxy tests yet. This problem showed up in a new test I created where we check if we can handle a seed node being offline.

I can look into it deeper but I'm fixing other tests tests right now.

**Comment by tegefaulkes** [comment]
Fixed the random failures in the `NodeGraph.test.ts` tests. one of the test functions for creating a NodeID for a specific bucket had a small chance of creating a NodeId outside of the bucket.

**Comment by tegefaulkes** [comment]
Looking at this comment https://github.com/MatrixAI/js-polykey/issues/299#issuecomment-1014120940. The NodeId type is currently `type NodeId = Opaque<'NodeId', IdString>;` so it currently exists as a string. I can look into fixing it up but that is a lot of  small changes across the code base including fixing a lot of tests that make use of dummy NodeIds. I'd prefer to keep that work inside it's own issue/PR.

**Comment by tegefaulkes** [comment]
Adding #276 to the list of fixed issues. It's already mostly handled, just need to fix up how the errors are thrown.

Edit:
Actually, this doesn't quite fit the scope of this PR so I'll remove it. 
But changes in this PR relate to that issue. Such as the addition of `shutdownCallback?: () => Promise<void>;` parameter to the `GRPCClient` which will be called when a connection failure is detected. I'll make a comment on the issue.

**Comment by tegefaulkes** [comment]
I am not sure how to approach #254 right now. I don't know if #312 and #311 are affecting it right now.

Currently the `NodeId` is gotten directly from the `KeyManager` but that means anything that needs the `NodeId` will directly or indirectly need a dependency on the `KeyManager`. Alternatively we can pass around a lamda function that will get the `NodeId` from the `KeyManager`

```ts
const getNodeId = async () => {
    return KeyManager.getNodeId();
}
```

**Comment by CMCDragonkai** [comment]
Let me get my vault Id changes in first. The main theme there is removing all the magic and replacing it with just using 2 forms:

* ~`type NodeId = Id` which is just an alias. This is because `Id` is something that can be used in POJOs, Maps, and DB without any transformation.~ - I just remembered that the node id is generated from public keys. It's special case then.
* ~`type NodeIdEncoded` which may or may not be needed, because I'm still seeing if it's really needed for vault id. The only reason for transformation is for other special properties which are domain-specific. I believe when showing NodeIds to the end user, you're going to need to encode it using `base32hex` because it's fixed size, and most importantly it preserves lexicographic order of the underlying bytes/bits (https://github.com/MatrixAI/js-id/issues/9 - when sortable base64 is available we can choose that too). But you don't use this for the node graph, because the node graph should be using the raw buffer form of `Id`.~ - Becuase `NodeId` is actually derived from a public key, the encoded form can still use base32hex.

There's a usecase for using `Opaque`, however that should be done at the very end to differentiate different `Id` manifestations like preventing misuse of `VaultId` in place of `NodeId`... etc.

With respect #254, now that we are propagating NodeId changes where push-comms is needed, and pulling from KeyManager in other areas, this should mean we don't need to proxy `NodeId` at all. Especially because the same type `NodeId` is being used for both the agent's own node id, and other node ids from other agents in the node graph. So perhaps #254 is a `wontfix`, not sure yet.

---

This should eventually remove any need to use `GenericIdTypes.ts` as well. For reasons as I mentioned in https://github.com/MatrixAI/js-polykey/issues/299#issuecomment-1016047272

---

Remember we know where `NodeId` will be used, and when its encoded form may be used. This way no generic decoding is needed. The encoded form will always be a multi-base encoded form.

**Comment by CMCDragonkai** [comment]
Apologies I forgot that `NodeId` is actually from a public key generation. This means that `NodeId` should instead be a "buffer" form of the public key. More details here: https://github.com/MatrixAI/js-polykey/issues/254#issuecomment-1016163310

**Comment by CMCDragonkai** [comment]
@tegefaulkes Please rebase on master, we cherry picked a few of the test splits and `master` now has the `EventBus` implemented too.

**Comment by tegefaulkes** [comment]
Re-based, applying fixes now. 

It was mentioned before that `NodeManager` should wrap `NodeGraph` calls. I had removed that since `NodeManager` doesn't manage the `NodeGraph` directly anymore. anything that needed to use the `NodeGraph` calls it directly now. 

But do we want any calls to the `NodeGraph` from outside the nodes domain to go through the `NodeManager`?

**Comment by tegefaulkes** [comment]
### NodeId changes.
The NodeId type needs to be updated to be an opaque type alias of ID. we will need to spec out the changes for this and possibly create a new PR. 

All usages of `NodeId` must be updated to use the `ID` form of `NodeId` instead of a string form. `NodeIdEncoded` will only be used when a string form is explicitly needed. The nodeId will have two forms;
1. NodeId - Opaque alias of ID.
2. NodeIdEncoded - opaque type of String, taking the form of a `base32hex` string.

Examples of it's usage can be found here https://github.com/MatrixAI/js-polykey/issues/254#issuecomment-1016205861.

NodeId will not use `GenericIdTypes.ts` and that will eventually be removed. conversion functions will be simplified and moved to the nodes domain. possible kept along side the types themselves.

How the node's `NodeId` is obtained must be updated. right now anything that needs the `NodeId` needs `KeyManager` as a direct or indirect dependency. we can potentially use a lamda function `const getNodeId = keyManager.getNodeId.bind(keyManager);`.

**Comment by CMCDragonkai** [comment]
> Re-based, applying fixes now. 
> 
> It was mentioned before that `NodeManager` should wrap `NodeGraph` calls. I had removed that since `NodeManager` doesn't manage the `NodeGraph` directly anymore. anything that needed to use the `NodeGraph` calls it directly now. 
> 
> But do we want any calls to the `NodeGraph` from outside the nodes domain to go through the `NodeManager`?

Yes this is what I was expecting for NodeManager to mediate calls to NodeGraph. I personally haven't reviewed NodeGraph in depth but I suspect that there are important functionality that NodeManager must manage in addition to state mutation of the NodeGraph.

An example of this would be distributed/decentralised hole punching https://hypercore-protocol.org/protocol/#hyperswarm

**Comment by CMCDragonkai** [comment]
Can you see where you can apply `withF` and `withG` utility functions to where transactions and `withConnection` is being used here? The main thing is to create methods that fulfill the `ResourceAcquire` type.

**Comment by tegefaulkes** [comment]
I can have a look.

**Comment by tegefaulkes** [comment]
Reminder to review #226 when back to working on this.

**Comment by CMCDragonkai** [comment]
@joshuakarp please do a deep review over the connection state handling starting from this comment: https://github.com/MatrixAI/js-polykey/pull/310#issuecomment-1011891501.

This behaviour should be properly specced out in a state machine diagram which shows all the possible transitions for our `NodeConnection`. So the diagram should have the state of the node connection and how it is changing from one state to another. For our states (from async-init):

* running = true | false
* destroyed = true | false
* status = starting | stopping | destroying

Our `NodeConnection` state is hierarchically encapsulating the `GRPCClient` state which itself is encapsulating the `Client` state of `TRANSIENT_FAILURE`, `SHUTDOWN`... etc. You don't have to document all of it. It's just what's relevant to us. To represent this in the diagram, use encapsulated box for this. The plantuml supports substates and state descriptions that we can use for this.

Make sure that the tests are covering all of our transitions in the diagram.

**Comment by CMCDragonkai** [comment]
The `NodeId` has to apply to this as well PR as well, the task list should be updated above and fleshed out for node id changes from #318.

Also ensure that the nodes are following this structure:

```
     ┌──────────────────┐
     │                  │
     │                  │
Errors────►Types ──┐    │
  │         │      │    │
  │         │      │    │
  ▼         │      │    │
Utils ◄─────┘      │    │
  │                ▼    │
  └─────────► Classes ◄─┘
```

**Comment by CMCDragonkai** [comment]
> Can you see where you can apply `withF` and `withG` utility functions to where transactions and `withConnection` is being used here? The main thing is to create methods that fulfill the `ResourceAcquire` type.

Here's an example of integrating `withF`. Let's say you have this right now:

```ts
class NodeConnectionManager {
  public withConnection (x, y) { ... }
}
```

As an alternative using `withF`, you do this instead:

```ts
class NodeConnectionManager {
  public acquireConn: ResourceAcquire<NodeConnection> = async () => {
    return [async () => { ... }, conn];
  };
}
```

However the `x` and `y` parameters are lost. So if we need to parametise this, it is possible by returning the resource acquisition function.

```ts
class NodeConnectionManager {
  public acquireConn(x, y): ResourceAcquire<NodeConnection> {
    return async () => {
      return [async () => { }, conn];
    };
  }
}
```

The end result is that the user can now do this:

```ts
withF([nodeConnMgr.acquireConn(x, y)], async (conn) => {

});
```

I suggest that `withConn` method should still exist as an convenience function and can be implemented in terms of `withF`.

```ts
class NodeConnectionManager {
  public acquireConn(x, y): ResourceAcquire<NodeConnection> {
    return async () => {
      return [async () => { }, conn];
    };
  }
  public withConn(x, y, f) {
    return withF([this.acquireConn(x, y)], f);
  }
}
```

But now you can see that `withConn` is just a convenience function, whereas the `acquireConn` is alot more composable, so that subsequent users can compose resource acquisitions together.

```ts
withF([
  nodeConnMgr.acquireConn(x, y), 
  nodeConnMgr.acquireConn(x, y), 
  acl.acquireLock, 
  gestaltGraph.acquireLock
], async (conn) => {
  // very composable
});

// you can also use `withG` when you need the generator version
```

Later if we see that `withConn` is not really even used, it can be removed, and this also means all the classes that have resources, no longer needs to create their `with` variants at all, and they just always rely on the `withF` and `withG` combinators.

**Comment by CMCDragonkai** [comment]
#226 and #244 may be impacted by this PR. It's worth reading over those issues, and making sure the design of this PR currently can lead to fixing those 2 issues either within this PR or in subsequent PRs.

**Comment by joshuakarp** [comment]
Based on above comments and discussion with Roger earlier, I'll be able to work on "Create a function and generator version of `withConnection`. refer to Nodes refactoring: `NodeConnectionManager`, ... #310 (comment)" from the top-level `NodeConnectionManager` tasks.

**Comment by CMCDragonkai** [comment]
A note to remove all cycles in nodes mentioned here: https://github.com/MatrixAI/js-polykey/pull/318#issuecomment-1022711139

**Comment by tegefaulkes** [comment]
With #318 Merged I'm going to re-base this now.

**Comment by tegefaulkes** [comment]
Re-based, still some pending fixes.

**Comment by joshuakarp** [comment]
Monday will be completing https://github.com/MatrixAI/js-polykey/pull/310#issuecomment-1022729447 here.

**Comment by joshuakarp** [comment]
Based on the ZenHub board and discussions in sprint meeting today, there's a few residual issues that need to be fixed:
* #244 
* #161
* #224

**Comment by CMCDragonkai** [comment]
@joshuakarp #224 should already be targeted in this PR. But #244 is optional, it's more make sure this PR is ready for working on that. The #161 can be done after testnode deployment.

**Comment by tegefaulkes** [comment]
Residual TODOs;
- @tegefaulkes post merge fix-up.
- @joshuakarp  update with connection to use WithF and add a WithG version. add a way to obtain the connection `resource` that fits with the API for WithF and WithG.
- @tegefaulkes Evaluate if #224 has been addressed in this PR.
- @joshuakarp review all nodes tests for any missing test cases.
- @tegefaulkes I think `review based on this comment.` has been addressed by #318, but double check.
- @joshuakarp review connection state handling. https://github.com/MatrixAI/js-polykey/pull/310#issuecomment-1022722372
- @tegefaulkes Remove any dependency cycles. https://github.com/MatrixAI/js-polykey/pull/310#issuecomment-1022723186. This may apply to other domains but is that the scope of this PR? related: https://github.com/MatrixAI/js-polykey/pull/318#issuecomment-1022711139

**Comment by CMCDragonkai** [comment]
#321 should be done by today. I have a prototype for `parse` and it will replace these one-off validation exceptions. This can then rebase on top so beware of that.

Can you add in ETAs when possible here @joshuakarp @tegefaulkes

**Comment by joshuakarp** [comment]
Going to add these tasks to the top-level description as a checklist @tegefaulkes. Will also add ETAs for my tasks today.

**Comment by tegefaulkes** [comment]
Something else to add to the TODO, check that `NodeGraph` and `SigChain` are not accessed directly outside of nodes domain. If anything needs to use them then they need to go through `NodeManager`

**Comment by CMCDragonkai** [comment]
@tegefaulkes I think the sigchain should be exposed. Since you want to be able to read/write to your own sigchain. And we may have other operations that expand the decentralized trust. So public methods should still be there. We should differentiate our sigchain from other node's sigchain. Our sigchain we can read/write, other sigchains we can only read. We could create 2 classes for this that extend from an abstract class to represent this.

**Comment by tegefaulkes** [comment]
Ok, I'll leave Sigchain as-is for now.

**Comment by tegefaulkes** [comment]
Shortlist of failing tests. 24 are failing across
- ping.test.ts
- find.test.ts
- notificationsManager.test.ts
- vaultManager.test.ts
- claim.test.ts
- notificationsSend.test.ts
- GRPCClientAgent.test.ts
- notifications.test.ts

We should address in this PR.
- ping.test.ts
- find.test.ts
- claim.test.ts
- GRPCClientAgent.test.ts

Should be addressed in vaults PR
- vaultManager.test.ts

may be addressed in tests splitting? I'll take a closer look.
- notifications.test.ts
- notificationsSend.test.ts
- notificationsManager.test.ts

**Comment by emmacasolin** [comment]
> may be addressed in tests splitting? I'll take a closer look.
> 
> * notifications.test.ts
> * notificationsSend.test.ts
> * notificationsManager.test.ts

Now that there have been changes to `NotificationsManager` in this PR, the fixes I made for `NotificationsManager.test.ts` over in the test splitting PR are no longer relevant. Probably best to fix those tests in this PR, especially since it looks like `NotificationsManager` is actually broken rather than the tests (just from a quick lookover `this.nodeConnectionManager` is never set to anything, but is used in `sendNotification()`).

**Comment by tegefaulkes** [comment]
Ok, I'll have a look and fix it soon.

**Comment by tegefaulkes** [comment]
@emmacasolin I've fixed most of the notifications tests. Just `tests/client/service/notificationsSend.test.ts:193` is failing but I think the test itself needs to be revised with how `mockedSendNotification` works.

**Comment by tegefaulkes** [comment]
All tests are passing except 
- notificationsSend.test.ts
- vaultManager.test.ts

**Comment by tegefaulkes** [comment]
`NodeGraph` has some methods that seems like they should be protected. Such as `setNodeOps` `unsetNodeOps` etc. Unless there is any reason they should be public I'll change them to protected.

**Comment by joshuakarp** [comment]
Pushed the `acquireConnection` functionality up that serves to resolve usage of `withF` with `NodeConnectionManager`. Will need to refactor `withConnection` accordingly to make use of `withF`, such that it becomes more of a "nice" convenience function to be called externally.

**Comment by joshuakarp** [comment]
> `NodeGraph` has some methods that seems like they should be protected. Such as `setNodeOps` `unsetNodeOps` etc. Unless there is any reason they should be public I'll change them to protected.

I don't recall there being a reason for these being public. I was likely just basing them off the `GestaltGraph` function signatures, which are also public. But it does seem unnecessary.

**Comment by tegefaulkes** [comment]
One problem that comes to mind with the resource API. `withConnection` needs to catch certain errors and remove the connection from the `connections` map. how do we support this within `withF` or `withG`? Do we handle it manually when using the `with` functions?

**Comment by CMCDragonkai** [comment]
Any exception thrown in the wrapped function will propagate upwards and the resource will be released upon the end of execution.

**Comment by CMCDragonkai** [comment]
If you later need to do work after calling `withF` that's fine you just do it right after the call. But it depends on what exceptions you're talking about.

**Comment by joshuakarp** [comment]
> If you later need to do work after calling `withF` that's fine you just do it right after the call. But it depends on what exceptions you're talking about.

@CMCDragonkai I believe @tegefaulkes is referring to the `catch`  with `ErrorNodeConnectionDestroyed` etc currently in `withConnection`:

```ts
  @ready(new nodesErrors.ErrorNodeConnectionManagerNotRunning())
  public async withConnection<T>(
    targetNodeId: NodeId,
    f: (conn: NodeConnection<GRPCClientAgent>) => Promise<T>,
  ): Promise<T> {
    // Ensure a connection exists
    await this.createConnection(targetNodeId);
    const connAndLock = this.connections.get(targetNodeId.toString());
    // Unexpected behaviour: between call to create connection and retrieval,
    // the conn or conn entry was deleted
    if (connAndLock == null || connAndLock.connection == null) {
      throw new Error(); // FIXME: proper error
    }
    // Acquire the read lock (allowing concurrent connection usage)
    this.logger.info(
      `attempting to lock connection for ${nodesUtils.encodeNodeId(
        targetNodeId,
      )}`,
    );
    try {
      return await connAndLock.lock.withRead(async () => {
        this.logger.info(
          `Acquired lock for ${nodesUtils.encodeNodeId(targetNodeId)}`,
        );
        const result = await f(connAndLock.connection!);
        // Resetting TTL timer.
        connAndLock.timer?.refresh();
        return result;
      });
    } catch (err) {
      if (
        err instanceof nodesErrors.ErrorNodeConnectionDestroyed ||
        err instanceof grpcErrors.ErrorGRPC ||
        err instanceof agentErrors.ErrorAgentClientDestroyed
      ) {
        // Error with connection, shutting connection down.
        await this.destroyConnection(targetNodeId);
      }
      throw err;
    }
  }
```

Because `withF` will be calling `acquireConnection` and then calling `f` externally now, I don't see a way to handle the call to `destroyConnection` internally. Is there something I'm missing?

**Comment by tegefaulkes** [comment]
That's what I was getting at. the catch there is not strictly needed since the channel watcher will handle it in the background. but it does ensure that when `withConnection` ends with a connection error the connection is destroyed and removed from the map before `withConnection` completes. otherwise it will take a little bit of time after `withConnection` for that to happen.

**Comment by CMCDragonkai** [comment]
Where would it throw that exception? There are many ways to do this.

Catch it in a wrapper by wrapping `f`. Catching it in the `acquireConnection` or in the release. Or catch it in your `withConnection` call that calls `withF`. Using `withF` doesn't prevent exception bubbling from working.

**Comment by CMCDragonkai** [comment]
Example:

```
withConn () {
  try {
    r = await withF();
  } catch (e) { }
  return r;
}
```

**Comment by joshuakarp** [comment]
> Where would it throw that exception? There are many ways to do this.
> 
> Catch it in a wrapper by wrapping `f`. Catching it in the `acquireConnection` or in the release. Or catch it in your `withConnection` call that calls `withF`. Using `withF` doesn't prevent exception bubbling from working.

My intention is to set up the following:

```ts
class NodeConnectionManager {
  public acquireConnection(targetNodeId): ResourceAcquire<NodeConnection> {
    return async () => {
      await this.createConnection(targetNodeId);
      const connAndLock = this.connections.get(targetNodeId.toString());
      // Unexpected behaviour: between call to create connection and retrieval,
      // the conn or conn entry was deleted
      if (connAndLock == null || connAndLock.connection == null) {
        throw new Error(); // FIXME: proper error
      }
      // Acquire the read lock and the release function
      const release = await connAndLock.lock.acquireRead();
      // Resetting TTL timer
      connAndLock.timer?.refresh();
      // Return tuple of [ResourceRelease, Resource]
      return [
        async () => {
          release();
        },
        connAndLock.connection,
      ];
    };
  }

  public withConnection(targetNodeId, f) {
    return withF([this.acquireConn(targetNodeId)], f);
  }
}
```

Therefore, I'd like to catch it in the `acquireConnection`, so that we don't need to repeat it in `withConnection`.

**Comment by joshuakarp** [comment]
Will play with this.

**Comment by tegefaulkes** [comment]
Looking at the dependency cycles again and there are a lot. But most of them contain `nodes/index.ts > nodes/NodeConnection.ts > agent/index.ts`. and is usually formed by importing `nodes/utils` for the encode/decodeNodeId at some point. But I'm not sure this is actually a problem? Like the tool is getting false positives because it thinks that `nodes/index.ts > nodes/NodeConnection.ts` is part of the cycle but actually we are just getting `nodes/index.ts > nodes/utils.ts`.

**Comment by CMCDragonkai** [comment]
> Looking at the dependency cycles again and there are a lot. But most of them contain `nodes/index.ts > nodes/NodeConnection.ts > agent/index.ts`. and is usually formed by importing `nodes/utils` for the encode/decodeNodeId at some point. But I'm not sure this is actually a problem? Like the tool is getting false positives because it thinks that `nodes/index.ts > nodes/NodeConnection.ts` is part of the cycle but actually we are just getting `nodes/index.ts > nodes/utils.ts`.

Some tips:

1. Outside modules should import like `import type { NodeConnection } from '../nodes';` or `import { NodeConnectionManager } from '../nodes';`.
2. Internally, the `utils` is not supposed to import the classes, but the classes should be importing the utils. You should refactor the function logic to do so.

**Comment by CMCDragonkai** [comment]
@joshuakarp 

You can only catch the exception in `acquireConn` if that's where the exception will be thrown. If the exception is to be thrown while executing `f()`, then you must catch it when calling `withF`.

**Comment by joshuakarp** [comment]
> @joshuakarp
> 
> You can only catch the exception in `acquireConn` if that's where the exception will be thrown. If the exception is to be thrown while executing `f()`, then you must catch it when calling `withF`.

Based on the exception handling from @tegefaulkes here in the current `withConnection` then:

```ts
    try {
      return await connAndLock.lock.withRead(async () => {
        this.logger.info(
          `Acquired lock for ${nodesUtils.encodeNodeId(targetNodeId)}`,
        );
        const result = await f(connAndLock.connection!);
        // Resetting TTL timer.
        connAndLock.timer?.refresh();
        return result;
      });
    } catch (err) {
      if (
        err instanceof nodesErrors.ErrorNodeConnectionDestroyed ||
        err instanceof grpcErrors.ErrorGRPC ||
        err instanceof agentErrors.ErrorAgentClientDestroyed
      ) {
        // Error with connection, shutting connection down.
        await this.destroyConnection(targetNodeId);
      }
      throw err;
    }
```

It seems that these connections are expected to be thrown when we attempt to perform `f` with the connection. Therefore, it doesn't seem that we can be handling these exceptions in `acquireConnection`.

Consequently, a call to `acquireConnection` (and then using this externally with `withF`) could cause one of these connection exceptions to bubble up elsewhere - this seems to be the core problem.

Any ideas @tegefaulkes? Can we handle the exceptions on connection acquisition instead? It seems like they require the connection to attempt to do work before any exception is thrown.

**Comment by CMCDragonkai** [comment]
> > Looking at the dependency cycles again and there are a lot. But most of them contain `nodes/index.ts > nodes/NodeConnection.ts > agent/index.ts`. and is usually formed by importing `nodes/utils` for the encode/decodeNodeId at some point. But I'm not sure this is actually a problem? Like the tool is getting false positives because it thinks that `nodes/index.ts > nodes/NodeConnection.ts` is part of the cycle but actually we are just getting `nodes/index.ts > nodes/utils.ts`.
> 
> Some tips:
> 
> 1. Outside modules should import like `import type { NodeConnection } from '../nodes';` or `import { NodeConnectionManager } from '../nodes';`.
> 2. Internally, the `utils` is not supposed to import the classes, but the classes should be importing the utils. You should refactor the function logic to do so.

Just a note I found that utils should import utils directly. So `keys/utils` should import `nodes/utils` rather than getting `import { utils as nodesUtils } from '../nodes';`. This prevents some cycles too.

**Comment by CMCDragonkai** [comment]
> > @joshuakarp
> > You can only catch the exception in `acquireConn` if that's where the exception will be thrown. If the exception is to be thrown while executing `f()`, then you must catch it when calling `withF`.
> 
> Based on the exception handling from @tegefaulkes here in the current `withConnection` then:
> 
> ```ts
>     try {
>       return await connAndLock.lock.withRead(async () => {
>         this.logger.info(
>           `Acquired lock for ${nodesUtils.encodeNodeId(targetNodeId)}`,
>         );
>         const result = await f(connAndLock.connection!);
>         // Resetting TTL timer.
>         connAndLock.timer?.refresh();
>         return result;
>       });
>     } catch (err) {
>       if (
>         err instanceof nodesErrors.ErrorNodeConnectionDestroyed ||
>         err instanceof grpcErrors.ErrorGRPC ||
>         err instanceof agentErrors.ErrorAgentClientDestroyed
>       ) {
>         // Error with connection, shutting connection down.
>         await this.destroyConnection(targetNodeId);
>       }
>       throw err;
>     }
> ```
> 
> It seems that these connections are expected to be thrown when we attempt to perform `f` with the connection. Therefore, it doesn't seem that we can be handling these exceptions in `acquireConnection`.
> 
> Consequently, a call to `acquireConnection` (and then using this externally with `withF`) could cause one of these connection exceptions to bubble up elsewhere - this seems to be the core problem.
> 
> Any ideas @tegefaulkes? Can we handle the exceptions on connection acquisition instead? It seems like they require the connection to attempt to do work before any exception is thrown.

This doesn't make any sense.

Your code snippet demonstrates that the exception can be raised while doing this:

```
      return await connAndLock.lock.withRead(async () => {
        this.logger.info(
          `Acquired lock for ${nodesUtils.encodeNodeId(targetNodeId)}`,
        );
        const result = await f(connAndLock.connection!);
        // Resetting TTL timer.
        connAndLock.timer?.refresh();
        return result;
      });
```

Therefore, as long as you catch around the `withF`, the result should be the same.

**Comment by tegefaulkes** [comment]
The exceptions we want to catch are thrown when making a GRPC call. So I don't see how we can handle it in the acquire.

But handling these exceptions are not strictly needed. we catching them in `withConnection` so that we can make sure that the connection is destroyed and removed from the connection map _before_ `withConnection` returns. If we don't handle it in `withConnection` then the channel watcher will eventually do that process for us. but since the watcher is working asynchronously in the background it will take an undefined amount of time to do it's thing.

This could leave us with the situation where `withConnection` failing due to a connection error and then a 2nd `withConnection` running and failing the same way before the `NodeConnection` is destroyed and removed from the map.

So it's not strictly needed but a nice to have. if it's too hard to implement nicely with `withF` using the resource then we can do without if we decide it's not actually needed. Alternatively we can implement an optional error interceptor/callback in the resource that can handle any errors that get thrown?

**Comment by joshuakarp** [comment]
Based on discussion with @CMCDragonkai:
* we inherently need to treat `acquireConnection` as a lower-level construct (a lower level imperative API - user beware! Ideally would need to handle these expected resource usage exceptions (see below), but not completely essential based on https://github.com/MatrixAI/js-polykey/pull/310#issuecomment-1026445796)
* conversely, `withConnection` is the higher-level construct, wrapped around `withF` and `acquireConnection`, for easy public consumption
* consider the separation of responsibilities:
   - `acquireConnection` purely acquires the connection. Therefore, any exceptions coming solely from the allocation/deallocation of this resource should be handled in `acquireConnection`
   - `withConnection` expected to perform operations on the connection. Any connection-related exceptions for while this resource is being used are expected to be handled here. These are exactly the current exceptions we already handle in `withConnection`:
   ```ts
   try {
     return await withF();
   } catch (err) {
     // all of our expected exceptions we already have: ErrorNodeConnectionDestroyed, etc
     // otherwise, bubble up exception
   }
   ```

---

`withConnection` is going to be extended to be `withConnF` and `withConnG` (using `withF` and `withG` respectively). 

If we really wanted to, we could do extend `withConnF` like the following:

```ts
withConnF (acquires, f) {
  return await withF([...acquires, this.acquireConn], f);
}
```

or 

```ts
withConnF (acquires, f) {
  return await withF([this.acquireConn, ...acquires], f);
}
```

but we'll just keep it simple as `withConnF(f)` for now.

**Comment by joshuakarp** [comment]
Also discussed: it's too verbose to have `withConnectionF` and `withConnectionG`. Therefore, at the very end of the PR @tegefaulkes , we'll do a full rename for `NodeConnectionManager` to prefer the shortened `conn` over `connection` in each of the function signatures. 

e.g. `withConnF`, `withConnG`, `createConn`, `destroyConn`, `acquireConn`, `establishConn`, etc

**Comment by CMCDragonkai** [comment]
> > > Looking at the dependency cycles again and there are a lot. But most of them contain `nodes/index.ts > nodes/NodeConnection.ts > agent/index.ts`. and is usually formed by importing `nodes/utils` for the encode/decodeNodeId at some point. But I'm not sure this is actually a problem? Like the tool is getting false positives because it thinks that `nodes/index.ts > nodes/NodeConnection.ts` is part of the cycle but actually we are just getting `nodes/index.ts > nodes/utils.ts`.
> > 
> > 
> > Some tips:
> > 
> > 1. Outside modules should import like `import type { NodeConnection } from '../nodes';` or `import { NodeConnectionManager } from '../nodes';`.
> > 2. Internally, the `utils` is not supposed to import the classes, but the classes should be importing the utils. You should refactor the function logic to do so.
> 
> Just a note I found that utils should import utils directly. So `keys/utils` should import `nodes/utils` rather than getting `import { utils as nodesUtils } from '../nodes';`. This prevents some cycles too.

Disregard this comment. I'm still fixing some things #318.

**Comment by tegefaulkes** [comment]
Well I've checked the dependencies in the Nodes domain and that seems to all be in order. I think we will need a separate PR for checking all imports and dependencies across all domains. 

I get the impression that the cycles are resulting from the utils imports. I agree that we should really import utils directly as apposed to using `{utils as nodesUtils} from '../nodes';` so that should cut down most of the cycles.

**Comment by joshuakarp** [comment]
`withConnF` and `withConnG` pushed up, as per discussion https://github.com/MatrixAI/js-polykey/pull/310#issuecomment-1026452007. Need to add some basic tests for these.

Furthermore, will also need to remove `withConnection` and replace all usage of `withConnection` with `withConnF`. This will need to be reflected in the tests too.

**Comment by CMCDragonkai** [comment]
While working on #318, I noticed that `findNode` throws an exception. Can this be changed to return `Promise<NodeAddress | undefined>`. Remember most of our getters should return undefined when it cannot be found, rather than throwing exceptions. See how this is done in all the other domains.

**Comment by tegefaulkes** [comment]
Is `NodeConnection` even needed at this point? besides extending `GRPCClientAgent` the only functionalty left in it is `getRootCertChain`, `getExpectedPublicKey` and holding onto address information. we could move that functionality into `NodeConnectionManager` and use `GRPCClientAgent` in the connection map directly. What do you think @CMCDragonkai @joshuakarp ?

**Comment by CMCDragonkai** [comment]
It was discussed before about how exactly it does wrapping. Leave it as a class for now and we can change it later if necessary.

**Comment by CMCDragonkai** [comment]
> Well I've checked the dependencies in the Nodes domain and that seems to all be in order. I think we will need a separate PR for checking all imports and dependencies across all domains.
> 
> I get the impression that the cycles are resulting from the utils imports. I agree that we should really import utils directly as apposed to using `{utils as nodesUtils} from '../nodes';` so that should cut down most of the cycles.

It is possible that non-direct imports are causing some cycles. But I'm not entirely sure about this. Hold off on changing this until I have better evidence.

**Comment by tegefaulkes** [comment]
Small problem with `withConnG()`. If an error is thrown by the generator provided to it, it isn't caught by the try block in `withConnG()`. so the connection isn't getting removed from the connection map.

I thought it was because `withG()` wasn't awaited but that doesn't fix it so I'm not sure how to handle this.

**Comment by CMCDragonkai** [comment]
@tegefaulkes can you give me a minimal reproducible example using **only** `withG`? I thought I tested this and ensured that exceptions are caught.

**Comment by tegefaulkes** [comment]
The problem is likely with how we're using `withG` in `withConnG`. I'm looking into it now.

**Comment by emmacasolin** [comment]
Like how the forward and reverse proxies have optional configs that can be set when creating a new polykey agent, could something like this be added as well for `NodeConnectionManager`'s `connTimeout` (and potentially `timeoutDelay`) properties? This would allow us to speed up the CLI and service handler tests for `findNode` and `pingNode` by setting `connTimeout` to something small like 500ms.

**Comment by tegefaulkes** [comment]
Ah, sure I can add that in.

**Comment by tegefaulkes** [comment]
@emmacasolin `PolykeyAgent` now takes an optional `nodeConnectionManagerConfig` where you can set the `connTimeout` and `timeoutDelay`.

File: test-node.ts [hunk 1]
```diff
@@ -0,0 +1,34 @@
+import { NodeConnectionManager } from './src/nodes';
```
Comment (tegefaulkes) [inline test-node.ts]: I think this file should be removed.

Comment (joshuakarp) [reply test-node.ts]: Yep, this can be removed. Accidental commit by me - was just testing the `RWLock` with this.

Comment (joshuakarp) [reply test-node.ts]: Removed

**Comment by tegefaulkes** [comment]
This is very close to done now. Just waiting on #321 to be merged so we can rebase on that and make the relevant changes. We can start the general code review process now aswell.

**Comment by CMCDragonkai** [comment]
Ok, should be doable today. Can you start squashing to a select few semantic commits.

File: src/nodes/NodeConnectionManager.ts [hunk 2]
```diff
@@ -0,0 +1,685 @@
...
+  } // Hole-punching
+
+  public async holePunchForward(
+    nodeId: NodeId,
+    ingressHost: Host,
+    ingressPort: Port,
+    timer?: Timer,
+  ): Promise<void> {
+    await this.fwdProxy.openConnection(nodeId, ingressHost, ingressPort, timer);
+  }
```
Comment (tegefaulkes) [inline src/nodes/NodeConnectionManager.ts:408]: This is only used in `NodeManager:pingNode`. I'd expect this to be used as part of the hole punch process when `holePunchReverse` is used but from the other side. I can't see that anywhere unless the forward connection is done automatically by the `ForwardProxy` when the `NodeConnection` is created and tries to connect? @joshuakarp any insights?

**Comment by tegefaulkes** [comment]
squashed and cleaned up commit history. The majority of the changes are in the 5127577 commit since we've squashed and rebased twice before. I could split up that commit but it doesn't seem necessary since we're not cherry picking anything.

I've reviewed the code so far and made some updates here and there. But without review from a 3rd party I'm out of things in the code to address.

**Comment by CMCDragonkai** [comment]
@joshuakarp has made a list of temporary fixes regarding node id usage in the nodes domain in #321 here https://github.com/MatrixAI/js-polykey/pull/321#issuecomment-1029493528.

They will need to be fixed here after this PR rebases.

File: src/nodes/NodeConnectionManager.ts (hunk 2 above)
Comment (joshuakarp) [reply src/nodes/NodeConnectionManager.ts:408]: Yeah, I'm pretty sure this whole function is completely unnecessary, because when we use the `ForwardProxy` to establish the connection within `NodeConnection`, it starts sending hole-punching packets to the target from the `ForwardProxy` internals (no need to call this function).

Comment (CMCDragonkai) [reply src/nodes/NodeConnectionManager.ts:408]: What about when receiving a hole punch request message? That is on the receiving side you have to hole punch back?

**Comment by CMCDragonkai** [comment]
Suggest changing to selective imports in this PR for the domains it's touching based on this comment: https://github.com/MatrixAI/js-polykey/pull/321#issuecomment-1029631104

**Comment by tegefaulkes** [comment]
I'm going to squash and re-base this now and then;
1. [x] fix any conflicts, temp nodeId stuff and test failures
2. [x] Update all of the nodes domain and related tests to use selective imports.
3. [x] Fix any TODOs for NodeId validation. https://github.com/MatrixAI/js-polykey/pull/321#issuecomment-1029493528
3. [x] make sure anything that needs the keynode nodeId get's it from the KeyManager directly instead of wrapping it or getting it from the NodeManager.

File: src/nodes/NodeConnectionManager.ts (hunk 2 above)
Comment (joshuakarp) [reply src/nodes/NodeConnectionManager.ts:408]: That's handled in a separate function and uses the `ReverseProxy`:

```ts
  // NodeConnectionManager
  @ready(new nodesErrors.ErrorNodeConnectionManagerNotRunning())
  public async holePunchReverse(
    egressHost: Host,
    egressPort: Port,
    timer?: Timer,
  ): Promise<void> {
    await this.revProxy.openConnection(egressHost, egressPort, timer);
  }
```

**Comment by tegefaulkes** [comment]
I think all the relevant tests are fixed now. Looking at selective imports for the nodes domain now.

**Comment by CMCDragonkai** [comment]
After this is merged:

* #266 rebases on top of this - the `VaultManager` sits on top of `NodeManager` and relies on the new node connection refactoring - @CMCDragonkai and @tegefaulkes 
* #311 rebases on top of this and starts splitting out the tests for nodes - @emmacasolin 
* @joshuakarp needs to create a new PR to address #324 and all the issues in https://github.com/MatrixAI/js-polykey/issues?q=is%3Aissue+is%3Aopen+testnet

**Comment by CMCDragonkai** [comment]
Make sure that the only tests failing here would be resolved by #266 and #311.

**Comment by emmacasolin** [comment]
> * [CLI and Client & Agent Service test splitting #311](https://github.com/MatrixAI/js-polykey/pull/311) rebases on top of this and starts splitting out the tests for nodes - @emmacasolin

#311 is actually already rebased on this (not recently though so there are a lot of merge conflicts) and I've split all of the relevant nodes tests. The only nodes tests that I haven't split yet are the agent service tests for `nodesChainDataGet`, `nodesClosestLocalNode`, and `nodesHolePunchMessage` because there are no tests for those written yet.

**Comment by CMCDragonkai** [comment]
> > * [CLI and Client & Agent Service test splitting #311](https://github.com/MatrixAI/js-polykey/pull/311) rebases on top of this and starts splitting out the tests for nodes - @emmacasolin
> 
> #311 is actually already rebased on this (not recently though so there are a lot of merge conflicts) and I've split all of the relevant nodes tests. The only nodes tests that I haven't split yet are the agent service tests for `nodesChainDataGet`, `nodesClosestLocalNode`, and `nodesHolePunchMessage` because there are no tests for those written yet.

@joshuakarp can you address these in your new PR?

**Comment by tegefaulkes** [comment]
There seems to be an issue with the selective imports and mocking the keypair generation via 
```ts
// Mocks
jest.mock('@/keys/utils', () => ({
  ...jest.requireActual('@/keys/utils'),
  generateDeterministicKeyPair:
    jest.requireActual('@/keys/utils').generateKeyPair,
}));
```

Switching to using `spyon` works better and gives us more control over the mocking.
```ts
const mockedGenerateDeterministicKeyPair = jest
  .spyOn(keysUtils, 'generateDeterministicKeyPair');

mockedGenerateDeterministicKeyPair.mockImplementation((bits, _) => {
    return keysUtils.generateKeyPair(bits);
})
```

**Comment by tegefaulkes** [comment]
Switching to selective imports will probably have to be done for the whole code base at once. I just fixed it for the nodes domain and tests and I'm running into new issues. I think doing it in separate PRs will lead to the same kinds of issues cropping up over and over again.

**Comment by CMCDragonkai** [comment]
Yep, that's probably because `jest.mock` works on the module level, and so applies to the entire import. Note that it's hoisted above all the import statements.

However we've been using this in other code:

```ts
    const globalKeyPair = await testUtils.setupGlobalKeypair();
    mockedGenerateKeyPair = jest
      .spyOn(keysUtils, 'generateKeyPair')
      .mockResolvedValue(globalKeyPair);
    mockedGenerateDeterministicKeyPair = jest
      .spyOn(keysUtils, 'generateDeterministicKeyPair')
      .mockResolvedValue(globalKeyPair);
```

See `grpc/GRPCServer.test.ts`. If you can swap to using the same global keypair, the tests will be alot faster.

Alternatively if you need to generate new keypairs, do it once in the `beforeAll`, then save it the mock resolved value. We should keep all the mocking consistent.

**Comment by CMCDragonkai** [comment]
> Switching to selective imports will probably have to be done for the whole code base at once. I just fixed it for the nodes domain and tests and I'm running into new issues. I think doing it in separate PRs will lead to the same kinds of issues cropping up over and over again.

Issues involving mocking or otherwise?

Because changing to selective imports should otherwise have no side-effects. It's the same thing at the end of the day.

**Comment by tegefaulkes** [comment]
I think mocking in the nodes domain is a special case since we're comparing different generated `NodeId`s is part of the testing.

the problems are coming down to the cyclic imports and type errors when extending classes. its a very hard problem to debug and fix and It will crop up randomly when mixing selective and index imports. But that shouldn't be a problem if we switch the whole code base over to selective imports at once.

**Comment by CMCDragonkai** [comment]
The `nodes` domain doesn't have cyclic imports anymore right? This PR should have fixed that.

I'd prefer you start from `nodes` domain and incrementally change to selective imports and remove any cycles from there rather than starting from the top. Just to keep the commit log a bit cleaner.

**Comment by CMCDragonkai** [comment]
> I think mocking in the nodes domain is a special case since we're comparing different generated `NodeId`s is part of the testing.
> 
> the problems are coming down to the cyclic imports and type errors when extending classes. its a very hard problem to debug and fix and It will crop up randomly when mixing selective and index imports. But that shouldn't be a problem if we switch the whole code base over to selective imports at once.

If you're only testing `NodeManager`, you should be able to just pre-generate keys and their related node ids.

**Comment by CMCDragonkai** [comment]
One way to do this is to use the `jest.spyOn` and return a list of resolved values. Like https://jestjs.io/docs/mock-function-api#mockfnmockresolvedvalueoncevalue.

So you can give it 10 resolved keys and default on the global keypair.

File: src/network/ConnectionForward.ts [hunk 3]
```diff
@@ -23,7 +23,6 @@ interface ConnectionForward extends StartStop {}
 @StartStop()
 class ConnectionForward extends Connection {
   public readonly nodeId: NodeId;
-  public readonly endTime: number;
```
Comment (CMCDragonkai) [inline src/network/ConnectionForward.ts:26]: What's happening here? The `endTime` is still being used in a number of functions.

Comment (CMCDragonkai) [reply src/network/ConnectionForward.ts:26]: Oh right this is because it's already available in `Connection.ts`. This should be extracted to a separate commit to make it clearer.

File: src/bin/nodes/CommandFind.ts [hunk 4]
```diff
@@ -71,7 +71,7 @@ class CommandFind extends CommandPolykey {
             result.port as Port,
           )}`;
         } catch (err) {
-          if (!(err instanceof nodesErrors.ErrorNodeGraphNodeNotFound))
+          if (!(err instanceof nodesErrors.ErrorNodeGraphNodeIdNotFound))
             throw err;
```
Comment (CMCDragonkai) [inline src/bin/nodes/CommandFind.ts:75]: Need to change this to `{ }`. Thinking I'll add in a eslint rule for `curly` here.

File: src/network/ConnectionForward.ts (hunk 3 above)
Comment (tegefaulkes) [reply src/network/ConnectionForward.ts:26]: it's defined in Connection, no need to redefine it there.

**Comment by CMCDragonkai** [comment]
1. Removed the `Creating` and `Created` log messages from the constructor of `NodeManager` and `NodeConnectionManager`, these are meant to be only used by the `createX` static methods.
2. The `NodeManager` `logger` is now optional, and is constructed by default.
3. Merged some imports.

File: src/PolykeyAgent.ts [hunk 5]
```diff
@@ -575,9 +620,9 @@ class PolykeyAgent {
         ingressPort: networkConfig_.ingressPort,
         tlsConfig,
       });
-      await this.nodeManager.start({ fresh });
-      await this.nodeManager.getConnectionsToSeedNodes();
-      await this.nodeManager.syncNodeGraph();
+      await this.nodeConnectionManager.start();
+      await this.nodeGraph.start({ fresh });
+      await this.nodeConnectionManager.syncNodeGraph();
```
Comment (CMCDragonkai) [inline src/PolykeyAgent.ts:628]: Now with the new architecture, does the synchronisation of the node graph have to be a separate step now? Can it be built into `nodeConnectionManager.start()` or `nodeGraph.start()`?

File: src/bin/nodes/CommandFind.ts (hunk 4 above)
Comment (CMCDragonkai) [reply src/bin/nodes/CommandFind.ts:75]: This is done now, the `curly` rule is built into it and will autofix these things. There weren't that many places.

File: src/bootstrap/utils.ts [hunk 6]
```diff
@@ -138,21 +139,35 @@ async function bootstrapState({
...
+    });
+    const nodeConnectionManager = new NodeConnectionManager({
+      keyManager,
+      nodeGraph,
+      // SeedNodes: undefined, // I don't think this is needed for bootstrapping.
       fwdProxy,
       revProxy,
+      logger: logger.getChild(NodeConnectionManager.name),
+    });
+    await nodeConnectionManager.start();
```
Comment (CMCDragonkai) [inline src/bootstrap/utils.ts]: Does this need to be started? If the side-effects of starting the `NodeConnectionManager` isn't persistent, it doesn't actually need to be started. Remember the bootstrap process just shutsdown immediately after setting all the on-disk side-effects.

File: src/discovery/Discovery.ts [hunk 7]
```diff
@@ -117,8 +117,7 @@ class Discovery {
         if (nodeId.equals(this.nodeManager.getNodeId())) {
           const vertexChainDataEncoded = await this.nodeManager.getChainData();
           // Decode all our claims - no need to verify (on our own sigchain)
-          for (const c in vertexChainDataEncoded) {
-            const claimId = c as ClaimIdEncoded;
+          for (const claimId in vertexChainDataEncoded) {
```
Comment (CMCDragonkai) [inline src/discovery/Discovery.ts]: This would be `ClaimIdString`, not `ClaimIdEncoded`. I'm going to add that type into `claims/types.ts` in case you want to use it.

Comment (CMCDragonkai) [reply src/discovery/Discovery.ts]: It's better to name this `claimIdString` instead of `claimId` to be clear.

File: src/bootstrap/utils.ts (hunk 6 above)
Comment (tegefaulkes) [reply src/bootstrap/utils.ts]: I suppose it doesn't have to be started there.

**Comment by tegefaulkes** [comment]
TODOs corresponding to "All internal usage of decoding functions uses `!`:
1. [x] `NodeManager.requestChainData`: remove `!` assertion on `const endNodeId = nodesUtils.decodeNodeId(payload.data.node2)!;` and handle exception
2. [x] `Provider.parseClaim`: need to validate the node ID of the claim (attempt a decode, and return undefined if invalid)
3. [x] `NodeManager.relayHolePunchMessage`: remove `!` assertions on `srcId` and `targetId`, and just don't relay the message if the either node ID is invalid? Could also look at sending a message back to sender. 
6. [x] `NodeConnection.getClosestNodes` (fix the new equivalent in #310): validate the node IDs of the received nodes (remove the assertion)

File: src/PolykeyAgent.ts (hunk 5 above)
Comment (joshuakarp) [reply src/PolykeyAgent.ts:628]: I'd assume that we can integrate this into one of those start functions.

@tegefaulkes take a look at https://github.com/MatrixAI/js-polykey/pull/289#issuecomment-987412188 if you're not sure what this refers to. Otherwise, we can have a chat about this.

File: tests/nodes/utils.ts [hunk 8]
```diff
@@ -10,11 +10,14 @@ import { IdInternal } from '@matrixai/id';
...
+  alt: number = 0,
+): NodeId {
   const lowerBoundDistance = BigInt(2) ** BigInt(bucketIndex);
   const bufferId = Buffer.from(nodeId.toBuffer());
-  // Console.log(bufferId);
-  const bufferDistance = bigIntToBuffer(lowerBoundDistance);
+  const bufferDistance = bigIntToBuffer(lowerBoundDistance + BigInt(alt));
   // Console.log(bufferDistance);
   // Console.log('Distance buffer:', bufferDistance);
   // console.log('Node ID buffer:', bufferId);
```
Comment (CMCDragonkai) [inline tests/nodes/utils.ts]: What does the `alt` parameter do? Can you add an explanation into the comments there.

There's also some `console.log` being used here that should be removed.

Comment (CMCDragonkai) [reply tests/nodes/utils.ts]: Note to self, the reason to use `BigInt` is because the key size is 256 bits, so we have numbers up to `2^256`. If we ever change our key size, then this keyspace size will change, so that's why `BigInt` is necessary.

File: src/discovery/Discovery.ts (hunk 7 above)
Comment (CMCDragonkai) [reply src/discovery/Discovery.ts]: What I'm checking this now, and this is incorrect.

The `vertexChainDataEncoded` is acquired from `await this.nodeManager.getChainData()`.

The type of `getChainData` is:

```
type ChainDataEncoded = Record<ClaimIdEncoded, ClaimEncoded>;
```

Which would mean that the keys are `ClaimIdEncoded` and not `ClaimId`.

Therefore, they are encoded strings. Is that intentional? Or do we want them to be binary string form?

**Comment by joshuakarp** [comment]
> > > * [CLI and Client & Agent Service test splitting #311](https://github.com/MatrixAI/js-polykey/pull/311) rebases on top of this and starts splitting out the tests for nodes - @emmacasolin
> > 
> > 
> > #311 is actually already rebased on this (not recently though so there are a lot of merge conflicts) and I've split all of the relevant nodes tests. The only nodes tests that I haven't split yet are the agent service tests for `nodesChainDataGet`, `nodesClosestLocalNode`, and `nodesHolePunchMessage` because there are no tests for those written yet.
> 
> @joshuakarp can you address these in your new PR?

Yep, can do this. Have made a note to do so here https://github.com/MatrixAI/js-polykey/issues/194#issuecomment-1032173720.

File: src/discovery/Discovery.ts (hunk 7 above)
Comment (CMCDragonkai) [reply src/discovery/Discovery.ts]: Furthermore, `nodeManager.getChainData()` is just a proxy to `sigchain.getChainData()`. Let's avoid proxying calls in `NodeManager` that are unnecessary and just fetch it from `Sigchain`.

Same with `getNodeId()`.

Comment (tegefaulkes) [reply src/discovery/Discovery.ts]: I think you mentioned that the `SigChain` should use the encoded form since that would likely be seen by users at some point?

I think you also stated that the sigchain should be proxied same ans the nodeGraph calls.

Comment (joshuakarp) [reply src/discovery/Discovery.ts]: @CMCDragonkai and I were discussing how sigchain's `getChainData` is a bit incorrect.

Currently, `getChainData` returns the `ChainDataEncoded` type: `type ChainDataEncoded = Record<ClaimIdEncoded, ClaimEncoded>;`

However, @CMCDragonkai pointed out that the `Record` type does not preserve order. This is an issue for the sigchain data, as in order to verify a claim, we need to compute the hash of the chronologically previous claim, and compare with the hash stored in the current claim.

(It slightly confuses me how my tests were passing with this then - I'd need to take a closer look at the tests to see why they'd be passing.)

Suggestions to improve this:
* create a `getChain` function that returns the claims on the sigchain as an **array** of `Claim` types (i.e. the unencoded POJO , retaining the chronological order of the sigchain. This would be expected to be used for all internal functions for the local keynode (i.e. not to be transferred across the wire). i.e. the following:
    ```
    [
      { payload: { ... }, signatures: { ... } },
      { payload: { ... }, signatures: { ... } },
      ...
    ]
    ```
* extend this with a `seek` and `limit` functionality to be able to acquire a specific claim (according to ID/sequence number), and limit the number of claims returned, respectively.
* create a `getChainEncoded` function that returns the claims on the sigchain as an **array** of `ClaimEncoded` types (i.e. the encoded base64 string version of the claim), but still retaining the chronological order of the sigchain. This would be used when transferring across the network, such that the receiving keynode can correctly verify the received sigchain by chronologically moving through it

**Comment by tegefaulkes** [comment]
tests fixed, addressing reviews now.

File: src/nodes/NodeConnectionManager.ts (hunk 2 above)
Comment (tegefaulkes) [reply src/nodes/NodeConnectionManager.ts:408]: Ok, I think that answers my question. So do I leave this as is or embed it into `NodeManager.pingNode()`?

File: src/PolykeyAgent.ts (hunk 5 above)
Comment (tegefaulkes) [reply src/PolykeyAgent.ts:628]: Made it so it's called by `NodeConnectionManager.start()`.

File: src/bootstrap/utils.ts (hunk 6 above)
Comment (tegefaulkes) [reply src/bootstrap/utils.ts]: It would add the seedNodes to the `NodeGraph` but I don't think that's needed for bootstrapping. I've removed it.

File: tests/nodes/utils.ts (hunk 8 above)
Comment (tegefaulkes) [reply tests/nodes/utils.ts]: Added description for alt into the inline documentation. Removed the commented console.logs

**Comment by tegefaulkes** [comment]
Just 3 revew items left,
- https://github.com/MatrixAI/js-polykey/pull/310#discussion_r801260505 needs a decision and possibly changes.
- https://github.com/MatrixAI/js-polykey/pull/310#discussion_r801248769 I don't think changes for this are happening this PR?
- https://github.com/MatrixAI/js-polykey/pull/310#discussion_r801191754 not a changes, but possibly something to do during commit cleaning before merge.

File: src/PolykeyAgent.ts (hunk 5 above)
Comment (tegefaulkes) [reply src/PolykeyAgent.ts:628]: We can't sync the node Graph in the `start` method since it depends on some public methods. I'm going to revert the changes for now.

**Comment by tegefaulkes** [comment]
Failing test files;
- bin/identities/identities.test.ts - addressed in #311 ?
- client/service/notificationsSend.test.ts - also 311
- vaults/VaultManager.test.ts - addressed in #266 ?

File: src/discovery/Discovery.ts (hunk 7 above)
Comment (tegefaulkes) [reply src/discovery/Discovery.ts]: I was mistaken. this comment https://github.com/MatrixAI/js-polykey/pull/310#issuecomment-1025303139 states that `Sigchain` should be used directly.

File: src/nodes/NodeConnectionManager.ts (hunk 2 above)
Comment (joshuakarp) [reply src/nodes/NodeConnectionManager.ts:408]: We do have the symmetry with having both `holePunchForward` and `holePunchReverse`, but given that we do the hole-punching with `ForwardProxy` internally anyway, perhaps it's best just to remove this to cause least confusion down the track?

File: src/PolykeyAgent.ts (hunk 5 above)
Comment (CMCDragonkai) [reply src/PolykeyAgent.ts:628]: So when this happened before, I resolved this by factoring out common code and making it a protected function that is used by both the public method and the start method. However if the code is simple, it's easy to just copy paste the functionality, DRY is not an ironclad rule.

File: src/discovery/Discovery.ts (hunk 7 above)
Comment (CMCDragonkai) [reply src/discovery/Discovery.ts]: So `Sigchain` class API should be changed in a later PR, but not this PR. This PR I just needed to ensure the right keywords are being used during iteration, at first I thought it was `ClaimIdString` but actually it's `ClaimIdEncoded`. So it should be `for (const claimIdEncoded in vertexChainDataEncoded) { ... }` for now.

Comment (CMCDragonkai) [reply src/discovery/Discovery.ts]: Put this into a new issue in #327.

Comment (CMCDragonkai) [reply src/discovery/Discovery.ts]: BTW, when doing `for (const x in record) {` the `x` is always inferred to be a `string`. Then `record[x];` is always an `any` type. But if you do:

```
let x: SomeId;
for (x in record) {
  record[x];
}
```

The `record[x]` is always inferred to be the record's value type.

Or:

```
record[x as KeyType];
```

Comment (CMCDragonkai) [reply src/discovery/Discovery.ts]: Ok updated this to `claimIdEncoded`.

This is a temporary fix, because the whole discovery has been changed by @emmacasolin in a later PR anyway. And we are going to change the sigchain API anyway in #327.

Note that I also benchmarked `for .. in` vs `Object.entries`, and the former is about 50% faster than the latter in the chrome browser.

File: src/nodes/NodeConnectionManager.ts (hunk 2 above)
Comment (CMCDragonkai) [reply src/nodes/NodeConnectionManager.ts:408]: If this is being used by `pingNode` leave the method as is. Make sure to write docblock comment for both that explains how they are meant to be used, and that `holePunchForward` is not used when making regular connections because the `ForwardProxy` will automatically start hole punching upon a connection request.

**Comment by CMCDragonkai** [comment]
Please review any commented out code as well, remove useless comments, and replace `//...` comments with docblocks where appropriate. The `//...` is only meant to be inline comments.

File: tests/nodes/utils.ts (hunk 8 above)
Comment (CMCDragonkai) [reply tests/nodes/utils.ts]: Ok I just read the document, I need you to explain to me how exactly does `alt` specify a deterministic alternative node ID, that still doesn't make sense to me.

Secondly.. this seems unnecessary:

```
  const bufferId = Buffer.from(nodeId.toBuffer());
```

Just use `nodeId.toBuffer();`

Also the `bigIntToHexBuffer`, please provide a type for that. That's a `Uint8Array`, and what is a "hex buffer". Is it a buffer of hexadecimal digits? In that case, that's just a string buffer. Or is a buffer of something else? Because looking at the utility function it appears to be doing something else.

Whenever you do these operations, inline comments should be done. For example adding leading `0` should be a `// Padding with leading 0s`.

Also the function seems to be converting it to a binary number. It's not really a hex buffer is it? It's just a binary version of an arbitrary sized number. Normally we would write a 32 bit number, 64 bit number. But big int is arbitrary sized. So you should call this `bigIntToBuffer` and do you want to use Node buffers or `Uint8Array`? If `Uint8Array`, it might be better to call it `bigIntToUint8Array`, and this seems like a useful utility we can stick in `utils.ts`.

According to https://www.npmjs.com/package/bigint-buffer, docblock comments about whether this is Big Endian or Little Endian would also be helpful.

File: src/PolykeyAgent.ts (hunk 5 above)
Comment (CMCDragonkai) [reply src/PolykeyAgent.ts:628]: I'd need a deeper explanation about this. Wednesday we're both in, so let's get over it @joshuakarp @tegefaulkes.

File: tests/nodes/utils.ts (hunk 8 above)
Comment (joshuakarp) [reply tests/nodes/utils.ts]: > Ok I just read the document, I need you to explain to me how exactly does alt specify a deterministic alternative node ID, that still doesn't make sense to me.

I've taken a look, and the following is my understanding of it:

Remember with Kademlia, a node is stored in bucket `i` where `2^i <= distance (from current node) < 2^(i+1)`. And also remember that `distance = nodeId1 XOR nodeId2`.

So this line:

```ts
const lowerBoundDistance = BigInt(2) ** BigInt(bucketIndex);
```

This calculates that `2^i` value - so its our lower bound of the distance. Therefore, assuming we have some known `nodeId1`, then we can calculate a `nodeId2` by performing `nodeId2 = lowerBoundDistance XOR nodeId1`. `nodeId2` would refer to the node ID with that `lowerBoundDistance` from `nodeId1`.

So when we do:

```ts
const bufferDistance = bigIntToBuffer(lowerBoundDistance + BigInt(alt));
```

All we're doing is adding some integer value to this lower bound, such that we can calculate a different node ID in the same bucket. e.g.

```
nodeId3 = (lowerBoundDistance + 1) XOR nodeId1
nodeId4 = (lowerBoundDistance + 2) XOR nodeId1
nodeId5 = (lowerBoundDistance + 3) XOR nodeId1
...
```

File: src/nodes/NodeConnectionManager.ts [hunk 9]
```diff
@@ -0,0 +1,710 @@
...
+   * so we should investigate performing this in the background if possible.
+   * Alternatively, we can also just add the nodes to our database without
+   * establishing connection.
+   * This has been removed from start() as there's a chicken-egg scenario
+   * where we require the NodeGraph instance to be created in order to get
+   * connections.
+   */
+  @ready(new nodesErrors.ErrorNodeConnectionManagerNotRunning())
+  public async syncNodeGraph() {
+    const backupSeedNodes = this.seedNodes;
```
Comment (CMCDragonkai) [inline src/nodes/NodeConnectionManager.ts]: This reassignment of `this.seedNodes` can be changed to just checking whether the target node is in the seed node first and branching the logic in connecting to seed node vs connecting to non-seed node. This avoids this mutation of the `this.seedNodes` which can cause race conditions.

Comment (CMCDragonkai) [reply src/nodes/NodeConnectionManager.ts]: Once this is changed, the `this.seedNodes` becomes a static property and doesn't change. Decentralised hole punching may change this logic later in the future.

Comment (CMCDragonkai) [reply src/nodes/NodeConnectionManager.ts]: And I need to change the async-init to bring in `ready` decorator that works while the class is also starting, this should make our `start()` more flexible and be able to call public methods. It will be however the programmer's responsibility to know when it is appropriate to call the public method, as it will depend on the `start` imperative order of side-effects.

File: src/PolykeyAgent.ts (hunk 5 above)
Comment (CMCDragonkai) [reply src/PolykeyAgent.ts:628]: Ok for now this is fine. A longer term fix would be in `js-async-init` where we allow `ready` to have additional specification about it being callable while `starting` or `stopping`... etc.

File: src/nodes/NodeConnectionManager.ts (hunk 9 above)
Comment (CMCDragonkai) [reply src/nodes/NodeConnectionManager.ts]: @tegefaulkes please resolve this when done.

File: src/PolykeyAgent.ts (hunk 5 above)
Comment (CMCDragonkai) [reply src/PolykeyAgent.ts:628]: I've created a new issue here: https://github.com/MatrixAI/js-async-init/issues/7 to address the flexibility of `ready` which would allow the usage of `syncNodeGraph` inside the `ready` method.

**Comment by tegefaulkes** [comment]
That's the last of my changes for now. I'm going to look at vaults PR now.

File: src/nodes/NodeConnectionManager.ts [hunk 10]
```diff
@@ -0,0 +1,706 @@
...
+  protected readonly seedNodes: NodeMapping;
+  // Max parallel connections (a.k.a. alpha constant from kademlia)
+  public readonly maxConcurrentNodeConnections: number = 3;
+
+  public constructor({
+    nodeGraph,
+    keyManager,
+    fwdProxy,
+    revProxy,
+    seedNodes = {},
```
Comment (CMCDragonkai) [inline src/nodes/NodeConnectionManager.ts:77]: If the `seedNodes` is empty. There's no way to add new seed nodes into the system. Does that mean any kind of relayed connection just doesn't work? As in it will only be capable of direct connections?

File: src/nodes/NodeConnectionManager.ts [hunk 11]
```diff
@@ -0,0 +1,706 @@
...
+
+interface NodeConnectionManager extends StartStop {}
+@StartStop()
+class NodeConnectionManager {
+  protected nodeGraph: NodeGraph;
+  protected keyManager: KeyManager;
+  protected fwdProxy: ForwardProxy;
+  protected revProxy: ReverseProxy;
+  protected logger: Logger;
+  // Reusing terms from network domain:
```
Comment (CMCDragonkai) [inline src/nodes/NodeConnectionManager.ts]: These comments should be docblock comments. Not line comments. Line comments are only used inline of a function/procedure.

File: src/nodes/types.ts [hunk 12]
```diff
@@ -13,7 +13,7 @@ type NodeAddress = {
 };
 
 type NodeMapping = {
-  [key: string]: NodeAddress;
+  [key: NodeId]: NodeAddress;
 };
```
Comment (CMCDragonkai) [inline src/nodes/types.ts]: This `NodeMapping` is only used for seed nodes. The name of the type suggests more generic usage.

File: src/nodes/NodeConnectionManager.ts [hunk 13]
```diff
@@ -0,0 +1,706 @@
...
+ * to provide necessary features. The main one being `killSelf` to allow the
+ * `NodeConnection` to tell the `NodeConnectionManager` to destroy the
+ * connection thus removing it from  the connection map.
+ */
+export interface NodeConnectionManagerInterface {
+  withConnF: typeof NodeConnectionManager.prototype.withConnF;
+  getSeedNodes: typeof NodeConnectionManager.prototype.getSeedNodes;
+  sendHolePunchMessage: typeof NodeConnectionManager.prototype.sendHolePunchMessage;
+  killSelf(): Promise<void>;
+}
```
Comment (CMCDragonkai) [inline src/nodes/NodeConnectionManager.ts]: This type can be done more simply.

```
withConnF: NodeConnectionManager['withConnF']
getSeedNodes: NodeConnectionManager['getSeedNodes']
```

I've done the same in #266 for the filesystem types.

File: src/nodes/NodeConnectionManager.ts [hunk 14]
```diff
@@ -0,0 +1,706 @@
...
+      },
+      getSeedNodes: () => {
+        return this.getSeedNodes();
+      },
+      killSelf: async () => {
+        await this.destroyConnection(nodeId);
+      },
+    };
+  }
+}
```
Comment (CMCDragonkai) [inline src/nodes/NodeConnectionManager.ts]: Don't think this is necessary. It should suffice to just pass `this` in, and rely on TS type checking to prevent using the wrong functions.

Only issue is the `killSelf` thing. I'm pretty sure this can be done in a better way like how network does it with `ConnectionForward` and `ConnectionReverse`.

File: src/nodes/NodeConnectionManager.ts [hunk 15]
```diff
@@ -0,0 +1,706 @@
...
+  // Reusing terms from network domain:
+  protected connTimeoutTime: number; // - timeout for opening the connection
+  protected connConnectTime: number | undefined; // - TTL for the connection itself
+
+  // Active connections to other nodes
+  protected connections: NodeConnectionMap = new Map();
+  // Node ID -> node address mappings for the seed nodes
+  protected readonly seedNodes: NodeMapping;
+  // Max parallel connections (a.k.a. alpha constant from kademlia)
+  public readonly maxConcurrentNodeConnections: number = 3;
```
Comment (CMCDragonkai) [inline src/nodes/NodeConnectionManager.ts]: Public properties should be moved up top as `public readonly`, and this is a confusing name, it's the number of parallel connections to nodes when searching for a node in the kademlia graph. Should rename it.

File: src/nodes/NodeConnectionManager.ts [hunk 16]
```diff
@@ -0,0 +1,706 @@
...
+@StartStop()
+class NodeConnectionManager {
+  protected nodeGraph: NodeGraph;
+  protected keyManager: KeyManager;
+  protected fwdProxy: ForwardProxy;
+  protected revProxy: ReverseProxy;
+  protected logger: Logger;
+  // Reusing terms from network domain:
+  protected connTimeoutTime: number; // - timeout for opening the connection
+  protected connConnectTime: number | undefined; // - TTL for the connection itself
```
Comment (CMCDragonkai) [inline src/nodes/NodeConnectionManager.ts]: Why is this potentially `undefined`? Shouldn't we **always** have a TLL for our connections?

File: src/nodes/NodeConnectionManager.ts [hunk 17]
```diff
@@ -0,0 +1,706 @@
...
+   */
+  @ready(new nodesErrors.ErrorNodeConnectionManagerNotRunning())
+  public async syncNodeGraph() {
+    for (const seedNodeId of this.getSeedNodes()) {
+      // Check if the connection is viable
+      try {
+        await this.createConnection(seedNodeId);
+      } catch (err) {
+        continue;
+      }
```
Comment (CMCDragonkai) [inline src/nodes/NodeConnectionManager.ts]: Prefer using booleans or if conditionals when checking things like this. If catching exceptions you must check if the exception is the instance you expect, otherwise throw the error.

File: src/nodes/NodeConnectionManager.ts (hunk 10 above)
Comment (tegefaulkes) [reply src/nodes/NodeConnectionManager.ts:77]: I presume so since the `NodeConnection` sends a hole punch relay message to each seed node when the connection is created. So yeah, only direct connections if there is no seed node to relay the message.

I don't think there is currently a way to add seed nodes except during the creation of the NodeConnectionManager but that is an easy change.

File: src/nodes/NodeConnectionManager.ts (hunk 13 above)
Comment (tegefaulkes) [reply src/nodes/NodeConnectionManager.ts]: Oh, I wasn't aware of that. I'll use that in the future.

File: src/nodes/types.ts (hunk 12 above)
Comment (tegefaulkes) [reply src/nodes/types.ts]: If it's only used for the seed nodes then it could use a more specific name. However the type itself is pretty generic and could be used elsewhere if needed.

File: src/nodes/NodeConnectionManager.ts (hunk 16 above)
Comment (tegefaulkes) [reply src/nodes/NodeConnectionManager.ts]: `NodeConnection` sets a default value if it receives an undefined. `NodeConnectionManager` just passes the value along to `NodeConnectionManager` I opted to just handle the default value in one place.

File: src/nodes/NodeConnectionManager.ts (hunk 17 above)
Comment (tegefaulkes) [reply src/nodes/NodeConnectionManager.ts]: Ok.

File: src/nodes/NodeConnectionManager.ts (hunk 15 above)
Comment (tegefaulkes) [reply src/nodes/NodeConnectionManager.ts]: It was moved here from `NodeGraph` since it's only used here.

File: src/nodes/NodeConnectionManager.ts (hunk 14 above)
Comment (tegefaulkes) [reply src/nodes/NodeConnectionManager.ts]: The interface was to limit what the `NodeConnection` could access. I was thinking about the rule of least privilege here.

File: src/nodes/NodeConnectionManager.ts (hunk 16 above)
Comment (CMCDragonkai) [reply src/nodes/NodeConnectionManager.ts]: I use the defaults for both in this case.

Comment (CMCDragonkai) [reply src/nodes/NodeConnectionManager.ts]: The keep alive time for network connections is already 20 seconds. But that's if there's no response on the network with the keep alive messages. The 20s was originally derived from the behaviour of UTP I think.

The `connTimeoutTime` here then can be longer therefore, since it's more about when there's no activity on the network connection. It can be 1 minute. Since we don't really bother with holding long-running connections for now reason.

So now we have:

1. `NodeConnectionManager` `connConnectTime`
2. `NodeConnection` `connConnectTime`
3. `GRPCClient` `timeout`

And that's all at the GRPC level.

The low level UTP has a lower default of 20s. I wonder if it makes sense to keep the timeouts the same, or to make the node connection/grpc client timeouts a little longer by default.

It doesn't quite make sense for the node connection timeouts to be less than the network timeouts. So at the very least they are the same, or they are longer.

Comment (CMCDragonkai) [reply src/nodes/NodeConnectionManager.ts]: Note to self `ConnectionForward` is `StartStop`, while `NodeConnection` is `CreateDestroy`. There was an attempt to move `ConnectionForward` to `CreateDestroy`, but it was made difficult by some things.

In both cases, the `connConnectTime` is not a property of each class. But instead the property of their respective managers. `ForwardProxy` and `NodeConnectionManager`. Therefore the default should be on the managers first, before on the lower level classes.

File: src/nodes/types.ts (hunk 12 above)
Comment (CMCDragonkai) [reply src/nodes/types.ts]: Ok but it's also incorrect in its type. The `NodeId` is not a valid type in POJO keys. So I've changed it to:

```ts
type NodeMapping = Record<NodeIdString, NodeAddress>;
```

Comment (CMCDragonkai) [reply src/nodes/types.ts]: However I don't like how `NodeMapping` is assuming that it is `NodeIdString`.

This `NodeMapping` is likely to be user-configurable, and later in the future we would put it in our `config.ts`.

Very likely we would configure it to use a fully encoded ID, not the binary string because it comes from the outside world.

I would prefer this be called `type SeedNodes = Record<NodeIdEncoded, NodeAddress>;` instead.

This is one of the few exceptions to use the encoded versions instead of the binary string from since it is exposed to the outside world.

File: src/nodes/NodeConnectionManager.ts (hunk 15 above)
Comment (CMCDragonkai) [reply src/nodes/NodeConnectionManager.ts]: I've changed this to:

```
  /**
   * Alpha constant for kademlia
   * The number of closest nodes to contact initially
   */
  public readonly initialClosestNodes : number = 3;
```

File: src/nodes/NodeConnectionManager.ts (hunk 14 above)
Comment (CMCDragonkai) [reply src/nodes/NodeConnectionManager.ts]: The interface is fine, but I'm talking about creating a synthetic proxy object for it. No need when we can rely on TS type checking.

Comment (tegefaulkes) [reply src/nodes/NodeConnectionManager.ts]: True, but we would have to replace `killSelf` with just `destroyConnection`

File: src/nodes/types.ts (hunk 12 above)
Comment (CMCDragonkai) [reply src/nodes/types.ts]: This has been changed over, as well as changes to `src/bin/utils/parsers.ts`, tests and how the NCM processes them.

File: src/nodes/NodeConnectionManager.ts (hunk 10 above)
Comment (CMCDragonkai) [reply src/nodes/NodeConnectionManager.ts:77]: That's fine for now.

File: src/nodes/NodeConnectionManager.ts (hunk 17 above)
Comment (CMCDragonkai) [reply src/nodes/NodeConnectionManager.ts]: What is the exact error classes you're expecting here?

Comment (tegefaulkes) [reply src/nodes/NodeConnectionManager.ts]: We should see an `ErrorNodeConnectionTimeout` error here if it fails to connect.

File: src/nodes/NodeConnectionManager.ts (hunk 16 above)
Comment (CMCDragonkai) [reply src/nodes/NodeConnectionManager.ts]: This is now defaulted.

**Comment by CMCDragonkai** [comment]
The `calculateDistance` and `calculateBucketIndex` functions have both been refactored to use the the binary utilities.

The `calculateBucketIndex` is also acquiring the latest bucket index based on the most significant bit position in the most significant byte in the distance array.

If 2 of the same node ids are passed into `calculateBucketIndex`, this results in a `RangeError`, because the distance calculated will be all 0s.

**Comment by CMCDragonkai** [comment]
Everyonce and a while I see these weird logging messages:

```
    Failed to connect to 127.0.0.1:37445/?nodeId=vi3et1hrpv2m2lrplcm7cu913kr45v51cak54vm68anlbvuf83ra0 through proxy 127.0.0.1:38231 with status 526
```

These are coming from upstream `grpc-js` library, and that's because `node_modules/@grpc/grpc-js/src/logging.ts` uses the its own logger, and is affected by the logging verbosity.

It's a bit annoying when log messages are meant to be going to our logger system.

However I found out that it is possible to set that logger: https://github.com/grpc/grpc-node/blob/a0f298c514c6ac56e33c149f8477d35deecbb4d2/packages/grpc-js/src/logging.ts#L59-L61

This would be done like this:

```ts
import Logger from '@matrixai/logger';
import * as grpc from '@grpc/grpc-js';

grpc.setLogger(new Logger('grpc') as unknown as Partial<Console>);
```

Some issues with this:

1. This is a module-level property, which means it is set once globally for all grpc imports. Where would we do this? It would have to be done everywhere GRPC is imported. If we do it once at the entry-point of our program, like `index.ts`, but this wouldn't affect anything that doesn't end up using the `index.ts`, and we would to affect our tests as well.
2. The logger object it expects needs to match this API:
   ```ts
   const DEFAULT_LOGGER: Partial<Console> = {
     error: (message?: any, ...optionalParams: any[]) => {
       console.error('E ' + message, ...optionalParams);
     },
     info: (message?: any, ...optionalParams: any[]) => {
       console.error('I ' + message, ...optionalParams);
     },
     debug: (message?: any, ...optionalParams: any[]) => {
       console.error('D ' + message, ...optionalParams);
     },
   }
   ```
3. While our `Logger` does support `error`, `info` and `debug`, it doesn't have all the other optional parameters. To do so we would have to adapt it. By creating a proxy object before calling `logger`.
    ```ts
    grpc.setLogger(
      {
        error: (...data: Array<any>) => logger.error(data.map(d => d.toString()).join(' ')),
        info: (...data: Array<any>) => logger.info(data.map(d => d.toString()).join(' ')),
        debug: (...data: Array<any>) => logger.debug(data.map(d => d.toString()).join(' ')),
      }
    )
    ```
4. We would also need to convert our logging verbosity to `grpc.setLogVerbosity(grpc.logVerbosity.INFO)`... etc.

File: tests/grpc/utils/TestServer.ts [hunk 18]
```diff
@@ -0,0 +1,18 @@
...
+  process.stdout.write(`${port}`);
+  process.stdin.on('data', () => {
+    server.forceShutdown();
+  });
+}
+
+main().then(
+  () => {},
+  () => {},
+);
```
Comment (CMCDragonkai) [inline tests/grpc/utils/TestServer.ts]: What is this file? If it is a script, it should have a lower case name. Upper case names are always referred to things exporting classes.

But also why does this require a separate process during testing?

**Comment by CMCDragonkai** [comment]
It appears moving to selective imports can cause problems in testing. Here's a very small example.

This line is in `src/keys/utils.ts`.

```ts
import { utils as nodesUtils } from '../nodes';
```

If changed to:

```ts
import * as nodesUtils from '../nodes/utils';
```

Then you run `npm test -- ./tests/grpc/utils.test.ts`, it will show this error:

```

    TypeError: Class extends value undefined is not a constructor or null

      20 | interface GRPCClientAgent extends CreateDestroy {}
      21 | @CreateDestroy()
    > 22 | class GRPCClientAgent extends GRPCClient<AgentServiceClient> {
         |                               ^
      23 |   /**
      24 |    * Creates GRPCClientAgent
      25 |    * This connects to the agent service

      at Object.<anonymous> (src/agent/GRPCClientAgent.ts:22:31)
      at Object.<anonymous> (src/nodes/NodeConnection.ts:16:1)
```

The `tests/grpc/utils` currently has very circular imports. Did you see this before @tegefaulkes?

File: src/nodes/NodeConnectionManager.ts (hunk 14 above)
Comment (CMCDragonkai) [reply src/nodes/NodeConnectionManager.ts:713]: > Everyonce and a while I see these weird logging messages:
> 
> ```
>     Failed to connect to 127.0.0.1:37445/?nodeId=vi3et1hrpv2m2lrplcm7cu913kr45v51cak54vm68anlbvuf83ra0 through proxy 127.0.0.1:38231 with status 526
> ```
> 
> These are coming from upstream `grpc-js` library, and that's because `node_modules/@grpc/grpc-js/src/logging.ts` uses the its own logger, and is affected by the logging verbosity.
> 
> It's a bit annoying when log messages are meant to be going to our logger system.
> 
> However I found out that it is possible to set that logger: https://github.com/grpc/grpc-node/blob/a0f298c514c6ac56e33c149f8477d35deecbb4d2/packages/grpc-js/src/logging.ts#L59-L61
> 
> This would be done like this:
> 
> ```ts
> import Logger from '@matrixai/logger';
> import * as grpc from '@grpc/grpc-js';
> 
> grpc.setLogger(new Logger('grpc') as unknown as Partial<Console>);
> ```
> 
> Some issues with this:
> 
> 1. This is a module-level property, which means it is set once globally for all grpc imports. Where would we do this? It would have to be done everywhere GRPC is imported. If we do it once at the entry-point of our program, like `index.ts`, but this wouldn't affect anything that doesn't end up using the `index.ts`, and we would to affect our tests as well.
> 2. The logger object it expects needs to match this API:
>    ```ts
>    const DEFAULT_LOGGER: Partial<Console> = {
>      error: (message?: any, ...optionalParams: any[]) => {
>        console.error('E ' + message, ...optionalParams);
>      },
>      info: (message?: any, ...optionalParams: any[]) => {
>        console.error('I ' + message, ...optionalParams);
>      },
>      debug: (message?: any, ...optionalParams: any[]) => {
>        console.error('D ' + message, ...optionalParams);
>      },
>    }
>    ```
> 3. While our `Logger` does support `error`, `info` and `debug`, it doesn't have all the other optional parameters. To do so we would have to adapt it. By creating a proxy object before calling `logger`.
>    ```ts
>    grpc.setLogger(
>      {
>        error: (...data: Array<any>) => logger.error(data.map(d => d.toString()).join(' ')),
>        info: (...data: Array<any>) => logger.info(data.map(d => d.toString()).join(' ')),
>        debug: (...data: Array<any>) => logger.debug(data.map(d => d.toString()).join(' ')),
>      }
>    )
>    ```
> 4. We would also need to convert our logging verbosity to `grpc.setLogVerbosity(grpc.logVerbosity.INFO)`... etc.

This is now used in `src/bin/polykey-agent.ts` and `src/bin/CommandPolykey.ts`. These are 2 places where they are global entrypoints to the PK program, and the GRPC upstream logger is now set appropriately. However this won't affect testing. So when we are testing things that may involve GRPC. we should manually do this:

```ts
import grpcSetLogger from '@/grpc/utils/setLogger';

describe('...', () => {
  const logger = new Logger('NodeGraph Test', LogLevel.ERROR, [
    new StreamHandler(),
  ]);
  grpcSetLogger(logger.getChild('grpc'));
});
```

@joshuakarp @tegefaulkes @emmacasolin - this applies to any test using node connection, grpc client, grpc server... etc.

**Comment by CMCDragonkai** [comment]
> Everyonce and a while I see these weird logging messages:
> 
> ```
>     Failed to connect to 127.0.0.1:37445/?nodeId=vi3et1hrpv2m2lrplcm7cu913kr45v51cak54vm68anlbvuf83ra0 through proxy 127.0.0.1:38231 with status 526
> ```
> 
> These are coming from upstream `grpc-js` library, and that's because `node_modules/@grpc/grpc-js/src/logging.ts` uses the its own logger, and is affected by the logging verbosity.
> 
> It's a bit annoying when log messages are meant to be going to our logger system.
> 
> However I found out that it is possible to set that logger: https://github.com/grpc/grpc-node/blob/a0f298c514c6ac56e33c149f8477d35deecbb4d2/packages/grpc-js/src/logging.ts#L59-L61
> 
> This would be done like this:
> 
> ```ts
> import Logger from '@matrixai/logger';
> import * as grpc from '@grpc/grpc-js';
> 
> grpc.setLogger(new Logger('grpc') as unknown as Partial<Console>);
> ```
> 
> Some issues with this:
> 
> 1. This is a module-level property, which means it is set once globally for all grpc imports. Where would we do this? It would have to be done everywhere GRPC is imported. If we do it once at the entry-point of our program, like `index.ts`, but this wouldn't affect anything that doesn't end up using the `index.ts`, and we would to affect our tests as well.
> 2. The logger object it expects needs to match this API:
>    ```ts
>    const DEFAULT_LOGGER: Partial<Console> = {
>      error: (message?: any, ...optionalParams: any[]) => {
>        console.error('E ' + message, ...optionalParams);
>      },
>      info: (message?: any, ...optionalParams: any[]) => {
>        console.error('I ' + message, ...optionalParams);
>      },
>      debug: (message?: any, ...optionalParams: any[]) => {
>        console.error('D ' + message, ...optionalParams);
>      },
>    }
>    ```
> 3. While our `Logger` does support `error`, `info` and `debug`, it doesn't have all the other optional parameters. To do so we would have to adapt it. By creating a proxy object before calling `logger`.
>    ```ts
>    grpc.setLogger(
>      {
>        error: (...data: Array<any>) => logger.error(data.map(d => d.toString()).join(' ')),
>        info: (...data: Array<any>) => logger.info(data.map(d => d.toString()).join(' ')),
>        debug: (...data: Array<any>) => logger.debug(data.map(d => d.toString()).join(' ')),
>      }
>    )
>    ```
> 4. We would also need to convert our logging verbosity to `grpc.setLogVerbosity(grpc.logVerbosity.INFO)`... etc.

This is now used in `src/bin/polykey-agent.ts` and `src/bin/CommandPolykey.ts`. These are 2 places where they are global entrypoints to the PK program, and the GRPC upstream logger is now set appropriately. However this won't affect testing. So when we are testing things that may involve GRPC. we should manually do this:

```ts
import grpcSetLogger from '@/grpc/utils/setLogger';

describe('...', () => {
  const logger = new Logger('NodeGraph Test', LogLevel.ERROR, [
    new StreamHandler(),
  ]);
  grpcSetLogger(logger.getChild('grpc'));
});
```

@joshuakarp @tegefaulkes @emmacasolin - this applies to any test using node connection, grpc client, grpc server... etc.

File: src/agent/service/nodesChainDataGet.ts [hunk 19]
```diff
@@ -1,24 +1,22 @@
...
     callback: grpc.sendUnaryData<nodesPB.ChainData>,
   ): Promise<void> => {
     try {
       const response = new nodesPB.ChainData();
-      const chainData = await nodeManager.getChainData();
+      const chainData = await sigchain.getChainData();
       // Iterate through each claim in the chain, and serialize for transport
-      for (const c in chainData) {
-        const claimId = c as ClaimIdEncoded;
+      for (const claimId in chainData) {
```
Comment (CMCDragonkai) [inline src/agent/service/nodesChainDataGet.ts]: This is `claimIdEncoded`. @tegefaulkes please change this to:

```ts
let claimIdEncoded: ClaimIdEncoded;
for (claimIdEncoded in chainData) { ... }
```

File: src/agent/GRPCClientAgent.ts [hunk 20]
```diff
@@ -52,6 +54,7 @@ class GRPCClientAgent extends GRPCClient<AgentServiceClient> {
         tlsConfig,
         proxyConfig,
         timeout,
+        channelCloseCallback,
```
Comment (CMCDragonkai) [inline src/agent/GRPCClientAgent.ts]: I need to go through this in-person @tegefaulkes @joshuakarp.

File: src/grpc/utils/utils.ts [hunk 21]
```diff
@@ -482,6 +482,59 @@ function promisifyDuplexStreamCall<TRead, TWrite>(
...
 }
 
+/**
+ * This adds a watcher for connection state change that logs the state transitions.
+ */
+function watchForChannelClose(
+  client: Client,
+  destructionCallback: () => Promise<void>,
+  logger: Logger = new Logger(watchForChannelClose.name),
+) {
```
Comment (CMCDragonkai) [inline src/grpc/utils/utils.ts]: This function appears to be a procedure. And since it is only used in `GRPCClient`, I believe this should be embedded in `GRPCClient`. That way there's no need for this awkward `logger` parameter.

(I know I use it in the tests, but that's an exception to the rule).

File: src/identities/Provider.ts [hunk 22]
```diff
@@ -95,10 +98,23 @@ abstract class Provider {
...
+          [['nodeId'], () => validationUtils.parseNodeId(value)],
+          [['nodeId1'], () => validationUtils.parseNodeId(value)],
+          [['nodeId2'], () => validationUtils.parseNodeId(value)],
+          () => value,
+        );
+      }, claim);
+    } catch (e) {
+      if (!(e instanceof validationErrors.ErrorParse)) return;
+      throw e;
+    }
```
Comment (CMCDragonkai) [inline src/identities/Provider.ts]: This doesn't make sense to me.

The `claim` is __claimed__ to be a `Claim` data structure.

This would be:

```ts
type Claim = {
  payload: {
    hPrev: string | null; // Hash of the previous claim (null if first claim)
    seq: number; // Sequence number of the claim
    data: ClaimData; // Our custom payload data
    iat: number; // Timestamp (initialised at JWS field)
  };
  signatures: Record<NodeIdEncoded, SignatureData>; // Signee node ID -> claim signature
};
```

This doesn't have anything like `nodeId`, or `nodeId1` ... etc.

What is this method for?  It's for basically doing a JSON parse and schema validate check on the claim string that is coming from the identity provider.

The schema check cannot check for node id, so this is meant to be a second-line of defense check on the node id.

Ok makes sense, however I'm not sure if this `claim` value even has those patterns at all.

File: src/keys/utils.ts [hunk 23]
```diff
@@ -30,7 +30,9 @@ import {
 import * as bip39 from 'bip39';
 import { IdInternal } from '@matrixai/id';
 import * as keysErrors from './errors';
+// TODO: weird problem here
 import { utils as nodesUtils } from '../nodes';
+// import * as nodesUtils from '../nodes/utils';
```
Comment (CMCDragonkai) [inline src/keys/utils.ts]: This causes a weird error involving `GRPCClientAgent`.

```
    TypeError: Class extends value undefined is not a constructor or null

      20 | interface GRPCClientAgent extends CreateDestroy {}
      21 | @CreateDestroy()
    > 22 | class GRPCClientAgent extends GRPCClient<AgentServiceClient> {
         |                               ^
      23 |   /**
      24 |    * Creates GRPCClientAgent
      25 |    * This connects to the agent service

      at Object.<anonymous> (src/agent/GRPCClientAgent.ts:22:31)
      at Object.<anonymous> (src/nodes/NodeConnection.ts:16:1)
```

Details in: https://github.com/MatrixAI/js-polykey/pull/310#issuecomment-1034784547

File: src/network/Connection.ts [hunk 24]
```diff
@@ -2,7 +2,7 @@ import type UTP from 'utp-native';
 import type { Host, Port, Address, TLSConfig } from './types';
 import Logger from '@matrixai/logger';
 import * as networkUtils from './utils';
-import { promisify } from '../utils';
+import { promisify } from '../utils/utils';
```
Comment (CMCDragonkai) [inline src/network/Connection.ts]: These sorts of index imports are fine. No need to make these selective.

File: tests/grpc/utils/testService.ts [hunk 25]
```diff
@@ -178,6 +179,46 @@ function createTestService({
...
+        const message = call.request.getChallenge();
+        if (message === 'exit') process.exit(0);
+        if (message === 'kill') process.kill(process.pid);
+        if (message === 'sigkill') process.kill(process.pid, 9);
+        await sleep(2000);
+        callback(null, new utilsPB.EchoMessage().setChallenge('hello!'));
+      } catch (err) {
+        callback(grpcUtils.fromError(err));
+      }
+    },
```
Comment (CMCDragonkai) [inline tests/grpc/utils/testService.ts]: Let's call these `unaryFail` and `serverStreamFail` to align with the names of the other calls on this `testService`.

Also please add inline comments on each type of failure detailing what kind of failure it is.

Does this align with the different failure tests according to the diagrams in https://github.com/MatrixAI/js-polykey/issues/224#issuecomment-1033257102

File: src/network/ConnectionForward.ts (hunk 3 above)
Comment (CMCDragonkai) [reply src/network/ConnectionForward.ts:26]: Ok other priorities are becoming more important, resolving this for now.

**Comment by CMCDragonkai** [comment]
The NCM import ordering is a bit messy. Our eslint import sorting isn't smart enough. Keep all the same modules together @tegefaulkes.

And check the way I'm importing right now for `tests/nodes/NodeConnectionManager.test.ts`.

**Comment by CMCDragonkai** [comment]
> The NCM import ordering is a bit messy. Our eslint import sorting isn't smart enough. Keep all the same modules together @tegefaulkes.
> 
> And check the way I'm importing right now for `tests/nodes/NodeConnectionManager.test.ts`.

And don't mix individual imports with `* as ...` imports. Only import from a file once!

File: tests/utils.ts [hunk 26]
```diff
@@ -172,7 +172,6 @@ async function setupGlobalAgent(
 }
 
 function generateRandomNodeId(): NodeId {
-  // Make it easy to read with an identifier
   const random = keysUtils.getRandomBytesSync(16).toString('hex');
   return IdInternal.fromString<NodeId>(random);
 }
```
Comment (CMCDragonkai) [inline tests/utils.ts:177]: This is still generating only 16 bytes. Our NodeIds are 32 bytes. I believe this needs to be fixed.

I removed the comment as it is no longer relevant. @tegefaulkes please make the change and fix up any tests.

**Comment by CMCDragonkai** [comment]
The new setting of the GRPC logger is working in the tests when running in the `NodeConnectionManager` (these 2 lines appear to occur in sync):

```
ERROR:fwdProxy:Failed CONNECT to 127.0.0.1:48313 - ErrorCertChainUnclaimed: Node ID is not claimed by any certificate
ERROR:grpc:Failed to connect to 127.0.0.1:48313/?nodeId=vi3et1hrpv2m2lrplcm7cu913kr45v51cak54vm68anlbvuf83ra0 through proxy 127.0.0.1:33791 with status 526
```

@tegefaulkes can you set it all the other locations as well, post here which test files you believe need it. Please also clean up your imports as here https://github.com/MatrixAI/js-polykey/pull/310#issuecomment-1034832415 and https://github.com/MatrixAI/js-polykey/pull/310#issuecomment-1034835694

One of the problems I have is not knowing if these error messages are actually indicative of an error, or if these messages are expected to occur. I know I made use of these error messages in the past, looking for these as they were what I wanted, such as in the `networking` domain, but I wonder if it's a good idea here in the nodes domain to look into suppressing these errors selectively for each test when it is expected that they will be failing.

File: tests/nodes/NodeConnectionManager.test.ts [hunk 27]
```diff
@@ -0,0 +1,1819 @@
...
+      // Information on remotes are found
+      expect(await nodeGraph.getNode(nodeId1)).toBeDefined();
+      expect(await nodeGraph.getNode(nodeId2)).toBeDefined();
+    } finally {
+      await nodeConnectionManager?.stop();
+    }
+  });
+
+  // Connection failure conditions
+  describe('should destroy and remove connection if...', () => {
```
Comment (CMCDragonkai) [inline tests/nodes/NodeConnectionManager.test.ts]: This is a nested describe. It should only be used when we have a necessary shared/expensive shared context not relevant to the other tests.

In such a case, the `describe` should have a better name.

It should be the `NodeConnectionManager test with ...`. Similar to `tests/bin/status.test.ts`. You should name what the shared context is.

Also better to use:

```
`${NodeConnectionManager.name} test`
```

As it statically ensures that we are naming what we are testing correctly.

File: tests/nodes/NodeConnectionManager.test.ts [hunk 28]
```diff
@@ -0,0 +1,1819 @@
...
+
+describe('NodeConnectionManager test', () => {
+  const logger = new Logger('NodeGraph Test', LogLevel.ERROR, [
+    new StreamHandler(),
+  ]);
+  grpcUtils.setLogger(logger.getChild('grpc'));
+
+  const nodeConnectionManagerLogger = logger.getChild(
+    'nodeConnectionManagerUT',
+  );
```
Comment (CMCDragonkai) [inline tests/nodes/NodeConnectionManager.test.ts]: These logger names are incorrect. Also in all other tests, we don't bother with creating child loggers unless actually necessary. We just use the test logger in the first `describe`.

I do use it in network tests because I'm trying to see concurrent logs and see how they do what they're doing. But that I don't think that's what is happening here for `nodeConnectionManagerLogger`.

See `tests/acl/ACL.test.ts` at the beginning:

```
describe(ACL.name, () => {
  const logger = new Logger(`${ACL.name} test`, LogLevel.WARN, [
    new StreamHandler(),
  ]);
```

This probably requires fixing in the other new test files you've created.

**Comment by CMCDragonkai** [comment]
The `NodeConnectionManager` test is very large. 1800+ lines. Should we consider splitting these up like we do in EFS? Like `NodeConnectionManager.X.test.ts` and `NodeConnectionManager.Y.test.ts`.

File: src/identities/Provider.ts (hunk 22 above)
Comment (joshuakarp) [reply src/identities/Provider.ts]: Those node ID fields come from the `ClaimData` type within the `Claim`:

```ts

// Claims can currently only be a cryptolink to a node or identity
type ClaimData = ClaimLinkNode | ClaimLinkIdentity;

// Cryptolink (to either a node or an identity)
type ClaimLinkNode = {
  type: 'node';
  node1: NodeIdEncoded;
  node2: NodeIdEncoded;
};
type ClaimLinkIdentity = {
  type: 'identity';
  node: NodeIdEncoded;
  provider: ProviderId;
  identity: IdentityId;
};
```

Remember we perform an HTTP request to get claims from providers (i.e. no GRPC). This `parseClaim` function seemed to be the best "boundary" to perform node ID validation.

File: tests/grpc/utils/TestServer.ts (hunk 18 above)
Comment (tegefaulkes) [reply tests/grpc/utils/TestServer.ts]: The running the tests that use `testUnaryFail` and `testStreamFail` we need the service to kill it's own process. Thus we have a `testServer` in a separate process. I'll fix the name.

Comment (CMCDragonkai) [reply tests/grpc/utils/TestServer.ts]: Use this at the very end:

```ts
if (require.main === module) {
  (async () => {
    await main();
  })();
}

export default main;
```

File: src/identities/Provider.ts (hunk 22 above)
Comment (CMCDragonkai) [reply src/identities/Provider.ts]: The return type of this function is:

```ts
  public parseClaim(identityClaimData: string): Claim | undefined
```

That doesn't align with the expectation that `claim` is a `ClaimData` as you say.

**Comment by tegefaulkes** [comment]
> 

When I was fixing up the imports I was only focusing on the nodes domain for this PR. As I've said before we want to be thorough then we should update the imports of all domains at once. otherwise we will end up with errors like that.

File: src/agent/service/nodesChainDataGet.ts (hunk 19 above)
Comment (tegefaulkes) [reply src/agent/service/nodesChainDataGet.ts]: Fixed it.

File: src/identities/Provider.ts (hunk 22 above)
Comment (joshuakarp) [reply src/identities/Provider.ts]: No, you're correct - `claim` is a `Claim` type. But, the `ClaimData` should be part of the `Claim` itself. We want to validate the node ID/s from that nested part of the claim.

e.g. a claim might be something like:

```
{
  payload: {
    hPrev: ...,
    seq: ...,
    data: {
      type: 'identity',
      node: 'someNodeIdToBeValidated',
      provider: ...,
      identity: ...
    },
    iat: ...,
  },
  signatures: { ... },
}
```

So, should it be something like this?:

```ts
    try {
      validateSync((keyPath, value) => {
        return matchSync(keyPath)(
          [['nodeId'], () => validationUtils.parseNodeId(value)],
          [['nodeId1'], () => validationUtils.parseNodeId(value)],
          [['nodeId2'], () => validationUtils.parseNodeId(value)],
          () => value,
        );
      }, claim.payload.data); // only pass the ClaimData value here?
```

Comment (joshuakarp) [reply src/identities/Provider.ts]: Furthermore, we can simplify this too. We never expect to have a `nodeId1`/`nodeId2` field, because the claims on providers are **always** going to be claims from node to identity. i.e. with `ClaimData` of the type:

```ts
type ClaimLinkIdentity = {
  type: 'identity';
  node: NodeIdEncoded;
  provider: ProviderId;
  identity: IdentityId;
};
```

File: tests/nodes/NodeConnectionManager.test.ts (hunk 28 above)
Comment (CMCDragonkai) [reply tests/nodes/NodeConnectionManager.test.ts]: Also note that `LogLevel` should default to `WARN` in our test modules.

Additionally, there are these log messages occurring that isn't using the new GRPC logger:

```
ERROR:FwdProxy:Failed CONNECT to 128.0.0.1:12345 - ErrorConnectionStart: Send failed (status: -22)
  console.error
    Failed to connect to 128.0.0.1:12345/?nodeId=v4nsohs20h7in6rmhrmok5l4hn1p0sl2lh8fa4d5ab1qclakocqk0 through proxy 127.0.0.1:45499 with status 502

      at Object.<anonymous>.exports.log (node_modules/@grpc/grpc-js/src/logging.ts:57:13)
      at ClientRequest.<anonymous> (node_modules/@grpc/grpc-js/src/http_proxy.ts:269:9)

ERROR:FwdProxy:Failed CONNECT to 127.0.0.1:55047 - ErrorCertChainUnclaimed: Node ID is not claimed by any certificate
  console.error
    Failed to connect to 127.0.0.1:55047/?nodeId=v5niu2rtbmaue1d63ihb43u7tpp4cjdsas7difrrnb1uvhrc3gv10 through proxy 127.0.0.1:38395 with status 526

      at Object.<anonymous>.exports.log (node_modules/@grpc/grpc-js/src/logging.ts:57:13)
      at ClientRequest.<anonymous> (node_modules/@grpc/grpc-js/src/http_proxy.ts:269:9)

ERROR:FwdProxy:Failed CONNECT to 127.0.0.1:35982 - ErrorConnectionStart: Client network socket disconnected before secure TLS connection was established
  console.error
    Failed to connect to 127.0.0.1:35982/?nodeId=vias3m3pv3rcev1a38jlv6j6386p9gqb2us9lhsafqn2tsltr2cm0 through proxy 127.0.0.1:38193 with status 502

      at Object.<anonymous>.exports.log (node_modules/@grpc/grpc-js/src/logging.ts:57:13)
      at ClientRequest.<anonymous> (node_modules/@grpc/grpc-js/src/http_proxy.ts:269:9)

ERROR:fwdProxy:Failed CONNECT to 125.0.0.1:55555 - ErrorConnectionStartTimeout
ERROR:grpc:Failed to connect to 125.0.0.1:55555/?nodeId=vi3et1hrpv2m2lrplcm7cu913kr45v51cak54vm68anlbvuf83ra0 through proxy 127.0.0.1:41575 with status 504
```

Usually any logs coming from `logger` should be above the the test logs shown by `jest`. But this was above `NodeManager.test.ts`.

Comment (CMCDragonkai) [reply tests/nodes/NodeConnectionManager.test.ts]: This has been fixed with `NodeConnection.test.ts`.

Comment (CMCDragonkai) [reply tests/nodes/NodeConnectionManager.test.ts]: Update the logger names as well and describe names to use the static names like `Class.name` as well @tegefaulkes

File: src/keys/utils.ts (hunk 23 above)
Comment (CMCDragonkai) [reply src/keys/utils.ts]: @tegefaulkes this seems to coming from `tests/grpc/utils`, since the other parts are all using selective imports.

Toggle these lines:

```ts
// TODO: weird problem here
// import { utils as nodesUtils } from '../nodes';
import * as nodesUtils from '../nodes/utils';
```

In `src/keys/utils.ts` and run `npm test -- ./tests/grpc/utils.test.ts` to see if it is passing.

It appears selective imports can affect import ordering, and these side-effects are quite sneaky so only by mass-changing a bunch of selective imports in a particular domain can help.

File: tests/utils.ts (hunk 26 above)
Comment (CMCDragonkai) [reply tests/utils.ts:177]: This should be `IdInternal.fromBuffer<NodeId>(random);` where `random` should be `32` bytes.

**Comment by CMCDragonkai** [comment]
Don't use `_destroyed` from `js-async-init`, just use the `destroyed` symbol. Does the same thing.

File: src/identities/Provider.ts (hunk 22 above)
Comment (CMCDragonkai) [reply src/identities/Provider.ts]: So the keypath should be `['payload', 'data', 'nodeId']`. Use the full keypath in case we need to validate other parts of the `claim`.

File: src/grpc/utils/utils.ts (hunk 21 above)
Comment (CMCDragonkai) [reply src/grpc/utils/utils.ts]: So some notes from discussion:

1. Move this back into `GRPCClient` as a method (possibly static method).
2. Use the ENUMs when checking the connectivity state `grpc.connectivityState.*`.
3. Don't just catch errors or `if (err)`, you need to check if the error is an instance of the expected exception, and if it is not either throw the error, or we can do something similar to the `handleError` that occurs under the `network/ConnectionForward.ts`.
4. Don't use `setImmediate`, just register the handler immediately. No need to make it asynchronous.
5. Some of the logger messages can be quite noisy. They should be debug messages if necessary.
6. Change the name to be `watchChannelState`.

Comment (CMCDragonkai) [reply src/grpc/utils/utils.ts]: The current architecture of this is quite complex.

An alternative is to pass a `destroyCallback` down from NCM to NC, to GCA and GC. And this `destroyCallback` is actually called by the `destroy()` at `GC`.

The NC can augment the `destroyCallback` with additional operations prior.

Then the `watchConnectivityState` can call `destroy()` on GC directly instead of having a separate path towards destroying things.

This would have be done in the GCA since you don't have access to the GC instance until you do your async creation. This should work as long as there's no further async ops after waiting for a ready connection. Otherwise the GC/GCA would need to be a StartStop pattern.

Comment (CMCDragonkai) [reply src/grpc/utils/utils.ts]: The advantage here is that it avoids race conditions between the `channelCloseCallback` and `destroy`. Any side-effects always occur in a deterministic order.

File: tests/utils.ts (hunk 26 above)
Comment (tegefaulkes) [reply tests/utils.ts:177]: We're doing it this way so the raw string of the nodeId looks like a hex string.  So we can tell it apart when debugging. Just using the random bytes directly gives us a hard to read string.

File: src/identities/Provider.ts (hunk 22 above)
Comment (joshuakarp) [reply src/identities/Provider.ts]: I believe it should be `['payload', 'data', 'node']` - based on the type's field names.

File: tests/utils.ts (hunk 26 above)
Comment (CMCDragonkai) [reply tests/utils.ts:177]: Ah right. Ok well just add a comment explaining that `hex` string is more readable, and that 16 bytes creates 32 hex digits.

**Comment by CMCDragonkai** [comment]
Once all items above are resolved, proceed to squash/lint/merge to avoid blocking. Further changes can be done elsewhere.

File: src/nodes/NodeConnectionManager.ts (hunk 17 above)
Comment (tegefaulkes) [reply src/nodes/NodeConnectionManager.ts]: Now checking for a `nodesErrors.ErrorNodeConnectionTimeout` here.

File: tests/grpc/utils/TestServer.ts (hunk 18 above)
Comment (tegefaulkes) [reply tests/grpc/utils/TestServer.ts]: Added.

File: src/identities/Provider.ts (hunk 22 above)
Comment (tegefaulkes) [reply src/identities/Provider.ts]: I've fixed this.

File: tests/nodes/NodeConnectionManager.test.ts (hunk 28 above)
Comment (tegefaulkes) [reply tests/nodes/NodeConnectionManager.test.ts]: I've updated the logger names inside the nodes tests.

File: tests/utils.ts (hunk 26 above)
Comment (tegefaulkes) [reply tests/utils.ts:177]: I'm leaving it as is for now.

File: src/keys/utils.ts (hunk 23 above)
Comment (tegefaulkes) [reply src/keys/utils.ts]: Switching the grpc domain to selective imports seemed to fix this... this time.

File: src/nodes/NodeConnectionManager.ts (hunk 14 above)
Comment (tegefaulkes) [reply src/nodes/NodeConnectionManager.ts]: If we remove the killSelf ( now called `destroyCallback`) then we can remove this function can cast the interface directly. the `destroyCallback` will need to be created separately.

File: src/grpc/utils/utils.ts (hunk 21 above)
Comment (tegefaulkes) [reply src/grpc/utils/utils.ts]: I've mostly implemented this now. However there is a deadlock problem between the NCM and the NC when NCM.destroyConnection() -> NC.destroy() -> NC.destroyCallback() -> NCM.destroyConnection(). calling destroy on something that is destroyed is a NOP, but it still locks when it's in the process of destroying. if we have a cycle like this then it is a deadlock. I've fixed this between NodeConnection and GRPCClientAgent by checking if its destroying. But I'm not sure that's the best way so take a look at that.

**Comment by tegefaulkes** [comment]
I've done almost everything now. only things left are 
- refactoring the destroyedCallback stuff is mostly complete, just have to fix a small problem with it. I've made a comment about it. but it's getting too late to finish now.
- the NCM.getInterface() method can be removed and replaced with casting to the interface. But we will have to extract the destroyCallback from it and create that separately.

File: src/nodes/NodeConnectionManager.ts [hunk 29]
```diff
@@ -0,0 +1,716 @@
...
+     *   if conn != null:
+     *     acquire lock
+     *     destroy the conn
+     *     // if we destroy here, we need to ensure that any action using the conn must also
+     *     // acquire the lock, otherwise we could be performing an action whilst the conn
+     *     // is being destroyed
+     *     // we also need to consider a thread that may be waiting for the lock to be released
+     *     // if we destroy the conn and the lock, then what happens to the waiting thread?
+     *     delete from connections
+     */
```
Comment (joshuakarp) [inline src/nodes/NodeConnectionManager.ts]: We should be able to remove this block comment now. These were old notes by me.

File: src/nodes/NodeConnectionManager.ts [hunk 30]
```diff
@@ -0,0 +1,716 @@
...
+    const connAndLock = this.connections.get(targetNodeId.toString());
+    if (connAndLock == null) return;
+    const connection = connAndLock.connection;
+    if (connection == null) return;
+    const lock = connAndLock.lock;
+
+    // If the connection exists then we lock, destroy and remove it from the map
+    // @ts-ignore
+    await lock.withWrite(async () => {
```
Comment (joshuakarp) [inline src/nodes/NodeConnectionManager.ts]: Not sure that we need this `@ts-ignore` either.

File: src/nodes/NodeConnectionManager.ts (hunk 29 above)
Comment (tegefaulkes) [reply src/nodes/NodeConnectionManager.ts]: Removed

File: src/grpc/utils/utils.ts (hunk 21 above)
Comment (tegefaulkes) [reply src/grpc/utils/utils.ts]: The refactored `destroyCallback` is working now. I fixed the deadlocks by checking if the we're already destroying before calling `destroy()` in the callbacks. I'm not sure if this is the best solution.

**Comment by CMCDragonkai** [comment]
Regarding the `NodeConnectionManagerInterface`, once you have removed the `destroyCallback` from the interface, you can do:

1. Remove the `getInterface` method entirely. You can just use structural type to satisfy the interface.
2. Move the `NodeConnectionManagerInterface` into `NodeConnection.ts`, it is the receiver that cares about this type, not the sender in this case.
3. The `NodeConnectionManagerInterface` can just be private type to `NodeConnection.ts`, no need to export it. It's equivalent to an embedded type in the function signature to `NodeConnection.createNodeConnection`.

This means the `destroyCallback` is passed separately.

File: src/nodes/NodeConnectionManager.ts [hunk 31]
```diff
@@ -0,0 +1,714 @@
...
+
+/**
+ * Data structure to store all NodeConnections. If a connection to a node n does
+ * not exist, no entry for n will exist in the map. Alternatively, if a
+ * connection is currently being instantiated by some thread, an entry will
+ * exist in the map, but only with the lock (no connection object). Once a
+ * connection is instantiated, the entry in the map is updated to include the
+ * connection object.
+ */
+type NodeConnectionMap = Map<string, ConnectionAndLock>;
```
Comment (CMCDragonkai) [inline src/nodes/NodeConnectionManager.ts]: Because this is a `Map`, it does not need its key to be a string.
Instead you can use `Map<NodeId, ConnectionAndLock>`.

Then in all subsequent operations, you don't need to convert to and back to binary string.

Maps can use objects as keys, and it uses object identity. Which is exactly what we can do here.

File: src/nodes/NodeConnectionManager.ts [hunk 32]
```diff
@@ -0,0 +1,714 @@
...
+  }
+
+  public async stop() {
+    this.logger.info(`Stopping ${this.constructor.name}`);
+    for (const [nodeId, connAndLock] of this.connections) {
+      if (connAndLock == null) continue;
+      if (connAndLock.connection == null) continue;
+      // It exists so we want to destroy it
+      await this.destroyConnection(IdInternal.fromString<NodeId>(nodeId));
+    }
```
Comment (CMCDragonkai) [inline src/nodes/NodeConnectionManager.ts:120]: Like here when it iterates over the `this.connections`. You can just do `await this.destroyConnection(nodeId);` instead.

File: src/nodes/NodeConnectionManager.ts (hunk 14 above)
Comment (tegefaulkes) [reply src/nodes/NodeConnectionManager.ts]: I've removed the `getInterface` method. the `NodeConnectionManagerInterface` type was moved to `NodeConnection.ts`. `destroyCallback` has been seperated out of the interface and passed separately to `NodeConnection`.

File: src/nodes/NodeConnectionManager.ts (hunk 31 above)
Comment (CMCDragonkai) [reply src/nodes/NodeConnectionManager.ts]: Ok so apparently we need to compare on string equality due to functions like `createConnection`. So to make this clearer, it should be `Map<NodeIdString, ConnectionAndLock>;`.

File: src/nodes/NodeConnectionManager.ts [hunk 33]
```diff
@@ -0,0 +1,714 @@
...
+   */
+  public readonly initialClosestNodes: number;
+
+  protected logger: Logger;
+  protected nodeGraph: NodeGraph;
+  protected keyManager: KeyManager;
+  protected fwdProxy: ForwardProxy;
+  protected revProxy: ReverseProxy;
+  protected seedNodes: SeedNodes;
+  protected connections: NodeConnectionMap = new Map();
```
Comment (CMCDragonkai) [inline src/nodes/NodeConnectionManager.ts]: Move `NodeConnectionMap` type to be embedded directly here. And then you can move the above docblock comment here too.

File: src/nodes/NodeConnectionManager.ts (hunk 32 above)
Comment (CMCDragonkai) [reply src/nodes/NodeConnectionManager.ts:120]: Ok once this is changed to `NodeIdString`, you will need to cast the string form. But probably not during `IdInternal.fromString`, only during `toString`. Like `nodeId.toString() as NodeIdString`.

File: src/nodes/NodeConnectionManager.ts (hunk 31 above)
Comment (tegefaulkes) [reply src/nodes/NodeConnectionManager.ts]: This uses NodeIdString now. as mentioned using NodeId for the key in the map leads to issues where we can fail to .get(nodeId) even when we have the same nodeId. this comes up in testing a lot and possibly general use.

File: src/nodes/NodeConnectionManager.ts (hunk 32 above)
Comment (tegefaulkes) [reply src/nodes/NodeConnectionManager.ts:120]: Not applicable since we're using NodeIdString for the key now.

File: src/nodes/NodeConnectionManager.ts (hunk 33 above)
Comment (tegefaulkes) [reply src/nodes/NodeConnectionManager.ts]: This is done.

**Comment by CMCDragonkai** [comment]
Some more issues I'm working on:

1. [x] The placement of the `watchConnectivityState` should be in the `GRPCClient.constructor` because it needs to have access the instance to be able to call `this.destroy`. - DONE
2. [x] Whether to do wrapping of `destroyCallback` in NC or not. I figured that no, because each class can handle their own responsibility here.
3. [x] How should we be checking whether to call the `destroyCallback` or not, either by checking the status `'destroying'` and also when it is already `destroyed`. - Now also checking `&& !client[asyncInit.destroyed]`.
4. [x] The errors that can come into `checkState`. According to grpc-js, the only possible errors are: `new Error('Deadline passed without connectivity state change')` and possibly an exception when the client is stopped. See `grpc-node/packages/grpc-js/src/channel.ts`. What is the exception when it is stopped? - Many exception checks were removed, because no exceptions could be thrown there. Some are undefined behaviour because the error should never be thrown.
5. [x] Should be able to remove the usage of `setImmediate` from `watchConnectivityState` it should be able to register the handler synchronously. - Now we just call `checkState` immediately, but we may require a eslint comment to allow it to pass the linting.
6. [x] Changed to use `connectivityState` enum, rather than the numbers.

**Comment by CMCDragonkai** [comment]
Still need to add a test that tests the READY to IDLE transition.

**Comment by joshuakarp** [comment]
> Still need to add a test that tests the READY to IDLE transition.

See this comment https://github.com/MatrixAI/js-polykey/issues/224#issuecomment-1033253718

Any transition from `READY` to `IDLE` is going to kill the connection with the current implementation. At this point, I believe there's only 2 cases where this transition is observable:
1. when the server closes the connection (already have a test for this)
2. when the underlying GRPC TTL times out (no test for this yet)

At the moment, the GRPC TTL is internally something like 6 minutes according to @tegefaulkes. I can look into how to override this, but note that with the current implementation, it's just going to close the connection. 

If we want to support the transition cycle between `IDLE` and `READY` (when the GRPC TTL expires), then some extra logic is necessary (I could chat to @tegefaulkes about this).

**Comment by CMCDragonkai** [comment]
Pushed up some changes to the `NodeConnection` hierarchy. @tegefaulkes please adjust the changes in the `NodeConnectionManager` and update test for it as well. There was a lot of un-used parameters for `NodeConnection`.

**Comment by joshuakarp** [comment]
There's a `GRPC_ARG_CLIENT_IDLE_TIMEOUT_MS` https://grpc.github.io/grpc/core/group__grpc__arg__keys.html#ga51ab062269cd81298f5adb6fd9a45e99

> Timeout after the last RPC finishes on the client channel at which the channel goes back into IDLE state.
> 
> Int valued, milliseconds. INT_MAX means unlimited. The default value is 30 minutes and the min value is 1 second.

But there doesn't seem to be a field for this in `ChannelOptions`.

**Comment by CMCDragonkai** [comment]
> > Still need to add a test that tests the READY to IDLE transition.
> 
> See this comment [#224 (comment)](https://github.com/MatrixAI/js-polykey/issues/224#issuecomment-1033253718)
> 
> Any transition from `READY` to `IDLE` is going to kill the connection with the current implementation. At this point, I believe there's only 2 cases where this transition is observable:
> 
> 1. when the server closes the connection (already have a test for this)
> 2. when the underlying GRPC TTL times out (no test for this yet)
> 
> At the moment, the GRPC TTL is internally something like 6 minutes according to @tegefaulkes. I can look into how to override this, but note that with the current implementation, it's just going to close the connection.
> 
> If we want to support the transition cycle between `IDLE` and `READY` (when the GRPC TTL expires), then some extra logic is necessary (I could chat to @tegefaulkes about this).

Yes we want a test for 2., see this: https://grpc.github.io/grpc/core/group__grpc__arg__keys.html. According to the docs (https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md) a `IDLE_TIMEOUT` should exist. But I cannot find this parameter in the GRPC js codebase.

Maybe @tegefaulkes just run a test and leave it running for 10-15 minutes... etc, and see?

**Comment by CMCDragonkai** [comment]
Once we find out how to trigger it, we can always use timer mocking to make it to grpc that the time has passed alot!

**Comment by CMCDragonkai** [comment]
@tegefaulkes at any case, if we cannot find a quick fix to that, we can add that as a later issue. And just fix up the final code based on my changes, and then we can lint/squash merge.

**Comment by CMCDragonkai** [comment]
Will also create a new issue for resolving the cycle in `NodeConnection` when it has to create the node connection instance before it creates the client instance. Obviously we would want to create the client instance first. But creating the client instance requires the `destroyCallback`, and the destroy callback requires a reference to the node instance.

A similar situation occurs in `GRPCClient,` which was resolved by calling `this.watchConnectivityState` inside the constructor, so it has access to the instance as well.

But in this case, the async creation of the derived `GRPCClient` classes requires the `destroyCallback`, because they are constructing the instance.

It seems like the proper solution is to change to `StartStop`, or `CreateDestroyStartStop` for these connection classes and make it similar to `network` domain's `ConnectionForward` and `ConnectionReverse`. The `CreateDestroy` pattern here is just a bit inflexible.

New issue started here #333.

**Comment by joshuakarp** [comment]
> There's a `GRPC_ARG_CLIENT_IDLE_TIMEOUT_MS` https://grpc.github.io/grpc/core/group__grpc__arg__keys.html#ga51ab062269cd81298f5adb6fd9a45e99
> 
> > Timeout after the last RPC finishes on the client channel at which the channel goes back into IDLE state.
> > Int valued, milliseconds. INT_MAX means unlimited. The default value is 30 minutes and the min value is 1 second.
> 
> But there doesn't seem to be a field for this in `ChannelOptions`.

There's a few mentions of this in the C-based GRPC: https://github.com/grpc/grpc/search?q=GRPC_ARG_CLIENT_IDLE_TIMEOUT_MS&type=code

**Comment by CMCDragonkai** [comment]
> > There's a `GRPC_ARG_CLIENT_IDLE_TIMEOUT_MS` https://grpc.github.io/grpc/core/group__grpc__arg__keys.html#ga51ab062269cd81298f5adb6fd9a45e99
> > > Timeout after the last RPC finishes on the client channel at which the channel goes back into IDLE state.
> > > Int valued, milliseconds. INT_MAX means unlimited. The default value is 30 minutes and the min value is 1 second.
> > 
> > 
> > But there doesn't seem to be a field for this in `ChannelOptions`.
> 
> There's a few mentions of this in the C-based GRPC: https://github.com/grpc/grpc/search?q=GRPC_ARG_CLIENT_IDLE_TIMEOUT_MS&type=code

Can you make a question on grpc-js about this parameter.

**Comment by joshuakarp** [comment]
I've posted a question on their discussion channel https://groups.google.com/g/grpc-io/c/yq4pmBGaXOQ

**Comment by tegefaulkes** [comment]
Everything is fixed now.
I've run all the tests and only 3 tests files are failing.
- tests/bin/identities/identities.test.ts - should be fixed in test splitting #311 
- tests/client/service/notificationsSend.test.ts - ditto
- tests/vaults/VaultManager.test.ts - should be fixed in #266 

I'm going to start the squash and merge process now.

**Comment by CMCDragonkai** [comment]
Ok I'll add create a new issue regarding the idle timeout. #332.
