### PR TITLE
Growing the Gestalt Graph and Implementing Social Discovery

### LINKED ISSUE #316: Implement Social Discovery to add found DIs to the Gestalt Graph
### Specification
Currently, most of the Gestalts CLI commands do not work in isolation as they expect nodes and identities to have already been set in the Gestalt Graph. The commands will fail with an `ErrorGestaltsGraphNodeIdMissing` or `ErrorGestaltsGraphIdentityIdMissing` error, or will return no data. ~This is because `identitiesInfoGetConnected`, which is supposed to add found connected identities to the gestalt graph, is currently incomplete and is inaccessible to the CLI.~ (outdated)

When choosing to trust a node/identity (i.e. to send notifications/vault share), this should add the node/identity to our gestalt graph. This can be done inside the handlers for these commands. Once done, this should trigger discovery on the added node/identity.

We don't want to have to await this discovery, so the `Discovery` domain needs to be converted from `CreateDestroy` to `CreateDestroyStartStop` so that it can have underlying state that it can crawl in the background.

### Additional context
- Example test failure: https://github.com/MatrixAI/js-polykey/pull/311#issuecomment-1004387583
- Original discussion of how to grow the gestalt graph: https://gitlab.com/MatrixAI/Engineering/Polykey/js-polykey/-/merge_requests/144#note_501361799

### Tasks
1. Expose `identitiesInfoGetConnected` to the CLI
2. Implement functionality for adding trusted nodes/identities to the gestalt graph
3. Add spider-crawling to the Discovery domain
3. Modify/extend existing tests to match this behaviour

### PR DESCRIPTION
**Pull request by emmacasolin**
### Description
The PR will change the way that the gestalt graph grows and shrinks by exposing this to the CLI. The `identities trust` and `vaults share` commands will add the trusted node/identity to the gestalt graph and the discovery domain crawl these to build the gestalt graph. This will involve converting the `Discovery` domain from `CreateDestroy` to `CreateDestroyStartStop`, such that it has underlying state (a queue of nodes/identities to crawl) and constantly discovers gestalts in the background.

This PR will also expose `indentitiesInfoGetConnected` to the CLI such that users can search providers for identities, which can then subsequently be trusted and crawled.

### Issues Fixed
* Fixes https://github.com/MatrixAI/js-polykey/issues/316
* Allows https://github.com/MatrixAI/js-polykey/pull/311 to continue with splitting gestalts tests

### Tasks
1. [x] Create a CLI command for `identitiesInfoGetConnected`
2. [x] Create separate handlers for `identities trust` which are injected with the `GestaltGraph` to allow trusted nodes/identities to be added to the gestalt graph
3. [ ] Inject `GestaltGraph` into the handler for `vaults share` to allow trusted nodes/identities to be added to the gestalt graph (wait until https://github.com/MatrixAI/js-polykey/pull/266 is merged)
3. [x] Convert the `Discovery` domain to `CreateDestroyStartStop` and add a queue of nodes/identities to discover
4. [x] Implement the ability for discovery to happen continuously in the background once `start` is called
4. [x] Full tests for `identitiesInfoGetConnected` and discovery tests

### Final checklist
* [x] Domain specific tests
* [x] Full tests
* [x] Updated inline-comment documentation
* [x] Lint fixed
* [x] Squash and rebased
* [x] Sanity check the final build

### CODE REVIEW

**Comment by emmacasolin** [comment]
Previously I had been confused as to why some of the `Provider` methods have both an `authIdentityId` and `identityId` parameter but I've just figured it out - `authIdentityId` is always your own, authenticated identity id (since you need to be authenticated in order to access sensitive data) and `identityId` is the identity that you want to retrieve data about. So `authIdentityId` and `identityId` are only the same if you're trying to retrieve data about yourself.

**Comment by emmacasolin** [comment]
While I had originally thought that we would need to call `discoverGestaltByIdentity()` in order to add the claims on found identities to our gestalt graph, I realise now that we could get around this by simply including the claims when we set the identity into our gestalt graph since this method takes an `IdentityInfo` as its parameter, which is a conjunction of `IdentityData`:
```ts
type IdentityData = {
  providerId: ProviderId;
  identityId: IdentityId;
  name?: string;
  email?: string;
  url?: string;
};
```
and `IdentityClaims` (a map of claim ids to identity -> keynode claims). We can get these claims straight from the provider by calling `getClaims()`.

The benefit to doing it this way is that we don't need to inject `Discovery` into `identitiesInfoGetConnected` or set up an event to call it automatically, however, the down-side is that `getClaims()` does not verify the signatures on the claims (as opposed to `discoverGestaltByIdentity()`, which does).

**Comment by emmacasolin** [comment]
In terms of the CLI command for `identitiesInfoGetConnected`, I think that the current command for `identitiesInfoGet` should be repurposed for `identitiesInfoGetConnected`. `identitiesInfoGet` is currently called by `CommandSearch`, the description of which is 'Searches a Provider for any Connected Identities', however, this name and description is better suited for `identitiesInfoGetConnected`. `identitiesInfoGet` simply returns the first authenticated identity id on the provider, so what would be an appropriate CLI command for that? Is one even necessary?

**Comment by emmacasolin** [comment]
Since we want to check that an identity is authenticated (similarly for nodes being valid) before adding it to our gestalt graph, we would need to throw some sort of error back to the client if the provided identity is invalid/unauthenticated.

There is an existing error `ErrorClientInvalidProvider` for if the given provider is not supported, so would `ErrorClientInvalidIdentity` be an appropriate error to throw if the identity you want to trust is not authenticated?

**Comment by emmacasolin** [comment]
Since `identities trust` is now setting nodes/identities into the gestalt graph, should `identities untrust` unset them? Otherwise it's not a reversible operation.

**Comment by CMCDragonkai** [comment]
> Previously I had been confused as to why some of the `Provider` methods have both an `authIdentityId` and `identityId` parameter but I've just figured it out - `authIdentityId` is always your own, authenticated identity id (since you need to be authenticated in order to access sensitive data) and `identityId` is the identity that you want to retrieve data about. So `authIdentityId` and `identityId` are only the same if you're trying to retrieve data about yourself.

Yep this is worth giving a comment on.

**Comment by CMCDragonkai** [comment]
> Since `identities trust` is now setting nodes/identities into the gestalt graph, should `identities untrust` unset them? Otherwise it's not a reversible operation.

No, untrusting doesn't delete it from the GG, it just removes the trust relationship. GG garbage collection can be a separate issue.

**Comment by CMCDragonkai** [comment]
> Since we want to check that an identity is authenticated (similarly for nodes being valid) before adding it to our gestalt graph, we would need to throw some sort of error back to the client if the provided identity is invalid/unauthenticated.
> 
> There is an existing error `ErrorClientInvalidProvider` for if the given provider is not supported, so would `ErrorClientInvalidIdentity` be an appropriate error to throw if the identity you want to trust is not authenticated?

Not sure what you mean by checking if it is authenticated. Yes you need to check if the identity exists. And in some cases you need to check if cryptolink claim that led you there is valid. If if someone is specifically pointing to a given identity to add to the gestalt graph, there is no cryptolink to check.

As for exceptions, new exceptions could be added into the identities domain when checking for the existence of an identity. Perhaps a new method on our identity providers? I reckon getIdentityInfo is sufficient. Also in this case no exception is needed if you're returning the info only, simply return the sentinel value. Only have exceptions if it the returned value is expected to exist and carried to another procedure.

**Comment by CMCDragonkai** [comment]
> In terms of the CLI command for `identitiesInfoGetConnected`, I think that the current command for `identitiesInfoGet` should be repurposed for `identitiesInfoGetConnected`. `identitiesInfoGet` is currently called by `CommandSearch`, the description of which is 'Searches a Provider for any Connected Identities', however, this name and description is better suited for `identitiesInfoGetConnected`. `identitiesInfoGet` simply returns the first authenticated identity id on the provider, so what would be an appropriate CLI command for that? Is one even necessary?

Can you show this through possible PK CLI commands. It's a bit hard to visualise the workflow.

**Comment by CMCDragonkai** [comment]
> While I had originally thought that we would need to call `discoverGestaltByIdentity()` in order to add the claims on found identities to our gestalt graph, I realise now that we could get around this by simply including the claims when we set the identity into our gestalt graph since this method takes an `IdentityInfo` as its parameter, which is a conjunction of `IdentityData`:
> ```ts
> type IdentityData = {
>   providerId: ProviderId;
>   identityId: IdentityId;
>   name?: string;
>   email?: string;
>   url?: string;
> };
> ```
> and `IdentityClaims` (a map of claim ids to identity -> keynode claims). We can get these claims straight from the provider by calling `getClaims()`.
> 
> The benefit to doing it this way is that we don't need to inject `Discovery` into `identitiesInfoGetConnected` or set up an event to call it automatically, however, the down-side is that `getClaims()` does not verify the signatures on the claims (as opposed to `discoverGestaltByIdentity()`, which does).

I think we discussed over Skype. The discovery module is like a background spidering process. So we should be able to push a job/task onto the queue which will be iterated on in the background.

**Comment by emmacasolin** [comment]
> Not sure what you mean by checking if it is authenticated. Yes you need to check if the identity exists. And in some cases you need to check if cryptolink claim that led you there is valid. If if someone is specifically pointing to a given identity to add to the gestalt graph, there is no cryptolink to check.

Yeah just checking that an identity is valid. If we want to trust an identity we first need to add it to the gestalt graph, but we need to check it's a valid identity before doing so since it's just user-entered data.

> As for exceptions, new exceptions could be added into the identities domain when checking for the existence of an identity. Perhaps a new method on our identity providers? I reckon getIdentityInfo is sufficient. Also in this case no exception is needed if you're returning the info only, simply return the sentinel value. Only have exceptions if it the returned value is expected to exist and carried to another procedure.

There's already a method called `getIdentityData()` which does this, however it just returns undefined if the identity can't be found. I could make it return an error instead though? It's only used inside discovery but I could just catch the error there instead of checking if `identityData == null`. There does need to be an error thrown when it gets called by `identities trust` since if the identity doesn't exist we don't want to add it to the gestalt graph, which means the permission can't be set.

**Comment by emmacasolin** [comment]
> > In terms of the CLI command for `identitiesInfoGetConnected`, I think that the current command for `identitiesInfoGet` should be repurposed for `identitiesInfoGetConnected`. `identitiesInfoGet` is currently called by `CommandSearch`, the description of which is 'Searches a Provider for any Connected Identities', however, this name and description is better suited for `identitiesInfoGetConnected`. `identitiesInfoGet` simply returns the first authenticated identity id on the provider, so what would be an appropriate CLI command for that? Is one even necessary?
> 
> Can you show this through possible PK CLI commands. It's a bit hard to visualise the workflow.

Yeah sure. So currently the `identities search [providerId]` command returns your own identity id (if you have any authenticated identities for the provider) or if you have no authenticated identities it returns nothing and logs 'No Connected Identities found for Provider'.

My suggestion is that instead of returning your own identity id, `identities search` is used for finding connected identities (as its description suggests). So example usage would be something like:
```
pk identities search [providerId] [...searchTerms]

Provider: [providerId] // this probably isn't needed considering you have to pass in a provider to search on so all identities will be on that provider
Identity: [identityId]
Name: [name]
Email: [email]
URL: [url]

... repeat for remaining connected identities

-------------------------------------------------------------------------

pk identities search [providerIdInvalid] [...searchTerms]

INFO: No Connected Identities found for Provider
```

I can't think of a use case for needing to retrieve your own authenticated identity id(s), unless you wanted to check if you were authenticated? But in that case it should probably be a functionality that's part of `identities authenticate`. The `identities search` command doesn't seem like the right place for that.

**Comment by emmacasolin** [comment]
There's actually a problem with setting identities into the GG in the same handler as trusting the identity. This is because you can't just trust an identity on its own - you're trusting a gestalt BY one of its identities. So if an identity has only just been set into the GG (and is not connected to any nodes, since we expect this to be done in the background by Discovery), then we won't be able to set permissions for it. This is only a problem for identities (not nodes), but I think the process of trusting should be the same for both identities and nodes so if it doesn't work for identities we should come up with a different solution for both.

**Comment by CMCDragonkai** [comment]
> > Not sure what you mean by checking if it is authenticated. Yes you need to check if the identity exists. And in some cases you need to check if cryptolink claim that led you there is valid. If if someone is specifically pointing to a given identity to add to the gestalt graph, there is no cryptolink to check.
> 
> Yeah just checking that an identity is valid. If we want to trust an identity we first need to add it to the gestalt graph, but we need to check it's a valid identity before doing so since it's just user-entered data.
> 
> > As for exceptions, new exceptions could be added into the identities domain when checking for the existence of an identity. Perhaps a new method on our identity providers? I reckon getIdentityInfo is sufficient. Also in this case no exception is needed if you're returning the info only, simply return the sentinel value. Only have exceptions if it the returned value is expected to exist and carried to another procedure.
> 
> There's already a method called `getIdentityData()` which does this, however it just returns undefined if the identity can't be found. I could make it return an error instead though? It's only used inside discovery but I could just catch the error there instead of checking if `identityData == null`. There does need to be an error thrown when it gets called by `identities trust` since if the identity doesn't exist we don't want to add it to the gestalt graph, which means the permission can't be set.

Returning undefined is the correct response here. We don't use exceptions to indicate non-existence if the command is about fetching something.  Value based errors is better in these scenarios.

An exception could be thrown inside the service handler as that's where the exception is, the expectation that identity exists is not fulfilled.

**Comment by CMCDragonkai** [comment]
> There's actually a problem with setting identities into the GG in the same handler as trusting the identity. This is because you can't just trust an identity on its own - you're trusting a gestalt BY one of its identities. So if an identity has only just been set into the GG (and is not connected to any nodes, since we expect this to be done in the background by Discovery), then we won't be able to set permissions for it. This is only a problem for identities (not nodes), but I think the process of trusting should be the same for both identities and nodes so if it doesn't work for identities we should come up with a different solution for both.

A gestalt can be consist of just a single identity. In fact all vertexes start out single and then progressively build up relationships after that. So if the gestalt is just 1 identity then a permission can still be added. When that gestalt builds, the permissions are merged together.

**Comment by CMCDragonkai** [comment]
> > > In terms of the CLI command for `identitiesInfoGetConnected`, I think that the current command for `identitiesInfoGet` should be repurposed for `identitiesInfoGetConnected`. `identitiesInfoGet` is currently called by `CommandSearch`, the description of which is 'Searches a Provider for any Connected Identities', however, this name and description is better suited for `identitiesInfoGetConnected`. `identitiesInfoGet` simply returns the first authenticated identity id on the provider, so what would be an appropriate CLI command for that? Is one even necessary?
> > 
> > 
> > Can you show this through possible PK CLI commands. It's a bit hard to visualise the workflow.
> 
> Yeah sure. So currently the `identities search [providerId]` command returns your own identity id (if you have any authenticated identities for the provider) or if you have no authenticated identities it returns nothing and logs 'No Connected Identities found for Provider'.
> 
> My suggestion is that instead of returning your own identity id, `identities search` is used for finding connected identities (as its description suggests). So example usage would be something like:
> 
> ```
> pk identities search [providerId] [...searchTerms]
> 
> Provider: [providerId] // this probably isn't needed considering you have to pass in a provider to search on so all identities will be on that provider
> Identity: [identityId]
> Name: [name]
> Email: [email]
> URL: [url]
> 
> ... repeat for remaining connected identities
> 
> -------------------------------------------------------------------------
> 
> pk identities search [providerIdInvalid] [...searchTerms]
> 
> INFO: No Connected Identities found for Provider
> ```
> 
> I can't think of a use case for needing to retrieve your own authenticated identity id(s), unless you wanted to check if you were authenticated? But in that case it should probably be a functionality that's part of `identities authenticate`. The `identities search` command doesn't seem like the right place for that.

I think there are several possible uses here:

* Looking up a specific identity, this is where you know the `<ProviderId>` and the `<IdentityId>`
* Looking up all connected identities across all providers.
* Looking up all connected identities for a single provider.
* Searching across all providers for a given search term, this is where you know the `<ProviderId>`
* Searching across a single provider for a given search term.

Should a single command be capable of doing them all or separate these ideas?

```
# --provider could be optional and limit the search to to a specific set of providers (see commander options for this)
# search is limited to "connected identities" by default, but an additional flag can be set to be unbound, and search any identity that exists - certain providers may not allow this to occur
pk identities search --provider <ProviderId> --provider <ProviderId> term1 term2
pk identities search --provider <ProviderId> <ProviderId> term1 term2
pk identities search term1 term2
pk identities search --disconnected term1 term2

# there are other commands that are available too
pk identities list
pk identities discover

# other possible keywords that haven't been used
pk identities find
pk identities lookup
```

BTW, I remember now that we made a decision to group all gestalt-related functionality within the `identities` subcommand. So there is no `pk gestalts` subcommand. This was a UX decision so that users don't have to know what "gestalt" means. We can reverse this decision, but for now most of what we want to do will be identity focused.

**Comment by emmacasolin** [comment]
> > There's actually a problem with setting identities into the GG in the same handler as trusting the identity. This is because you can't just trust an identity on its own - you're trusting a gestalt BY one of its identities. So if an identity has only just been set into the GG (and is not connected to any nodes, since we expect this to be done in the background by Discovery), then we won't be able to set permissions for it. This is only a problem for identities (not nodes), but I think the process of trusting should be the same for both identities and nodes so if it doesn't work for identities we should come up with a different solution for both.
> 
> A gestalt can be consist of just a single identity. In fact all vertexes start out single and then progressively build up relationships after that. So if the gestalt is just 1 identity then a permission can still be added. When that gestalt builds, the permissions are merged together.

At the moment, the GG pretty much just acts as an interface for the ACL. So it won't allow you to set permissions for just an identity since the ACL only stores permissions for nodes and vaults. For example this is the method for setting permissions by identity (this is the closest method in the GG to setting permissions _for_ an identity, which I think is slightly different):
```ts
@ready(new gestaltsErrors.ErrorGestaltsGraphNotRunning())
  public async setGestaltActionByIdentity(
    providerId: ProviderId,
    identityId: IdentityId,
    action: GestaltAction,
  ): Promise<void> {
    return await this._transaction(async () => {
      return await this.acl._transaction(async () => {
        const identityKey = gestaltsUtils.keyFromIdentity(
          providerId,
          identityId,
        );
        if (
          (await this.db.get<IdentityInfo>(
            this.graphIdentitiesDbDomain,
            identityKey,
          )) == null
        ) {
          throw new gestaltsErrors.ErrorGestaltsGraphIdentityIdMissing();
        }
        const gestaltKeySet = (await this.db.get(
          this.graphMatrixDbDomain,
          identityKey,
        )) as GestaltKeySet;
        let nodeId: NodeId | undefined;
        for (const nodeKey in gestaltKeySet) {
          nodeId = gestaltsUtils.ungestaltKey(nodeKey as GestaltNodeKey).nodeId;
          break;
        }
        // If there are no linked nodes, this cannot proceed
        if (nodeId == null) {
          throw new gestaltsErrors.ErrorGestaltsGraphNodeIdMissing();
        }
        await this.acl.setNodeAction(nodeId, action);
      });
    });
  }
```
It needs to find a linked node to set the permissions for. If we want to be able to set permissions for just an identity on its own then we need to rethink the current methods in the GG.

**Comment by emmacasolin** [comment]
> BTW, I remember now that we made a decision to group all gestalt-related functionality within the `identities` subcommand. So there is no `pk gestalts` subcommand. This was a UX decision so that users don't have to know what "gestalt" means. We can reverse this decision, but for now most of what we want to do will be identity focused.

I was thinking about this and was wondering if maybe the gestalts-related behaviour could go under something like `permissions`? So example commands would be
```
// Allow permission on gestalt by node/identity
pk permissions allow <gestaltId> <permissions>

// Disallow permission on gestalt by node/identity
pk permissions disallow <gestaltId> <permissions>

// Discover a gestalt by node/identity
pk permissions discover <gestaltId>

// Get a gestalt by node/identity
pk permissions get <gestaltId>

// Get all gestalts (and associated permissions)
pk permissions list

// Get the permissions for a gestalt by node/identity
pk permissions permissions <gestaltId>

// Trust a gestalt by node/identity
pk permissions trust <gestaltId>

// Untrust a gestalt by node/identity
pk permissions untrust <gestaltId>
```
It works better for some than others, but I think it's still clearer than using `identities`, expecially considering a lot of this behaviour operates on nodes.

**Comment by emmacasolin** [comment]
> I think there are several possible uses here:
> 
> * Looking up a specific identity, this is where you know the `<ProviderId>` and the `<IdentityId>`
> * Looking up all connected identities across all providers.
> * Looking up all connected identities for a single provider.
> * Searching across all providers for a given search term, this is where you know the `<ProviderId>`
> * Searching across a single provider for a given search term.
> 
> Should a single command be capable of doing them all or separate these ideas?
> 
> ```
> # --provider could be optional and limit the search to to a specific set of providers (see commander options for this)
> # search is limited to "connected identities" by default, but an additional flag can be set to be unbound, and search any identity that exists - certain providers may not allow this to occur
> pk identities search --provider <ProviderId> --provider <ProviderId> term1 term2
> pk identities search --provider <ProviderId> <ProviderId> term1 term2
> pk identities search term1 term2
> pk identities search --disconnected term1 term2
> 
> # there are other commands that are available too
> pk identities list
> pk identities discover
> 
> # other possible keywords that haven't been used
> pk identities find
> pk identities lookup
> ```

How's something like this?
```
Usage: polykey identities search [options] <searchTerms...>

Searches a Provider for any Connected Identities

Arguments:
  searchTerms                  (optional) Search parameters to apply to connected identities

Options:
  -pi, --provider-id <id>      Digital identity provider(s) to search on
  -i, --identity-id <id>       Name of the digital identity to search for
  -d, --disconnected           Include disconnected identities in search
  -n, --number <number>        Number of search results to display (default: "all")
```

Example usage:
```
// Look for a specific identity given the provider id and identity id
pk identities search --provider-id <providerId> --identity-id <identityId>

// Look up all connected identities across all providers
pk identities search

// Look up all connected identities for a single provider
pk identities search --provider-id <providerId>

// Search across all providers for a given search term
pk identities search [term1] [term2]

// Search across a single provider for a given search term
pk identities search --provider-id <providerId> [term1] [term2]

// Unbound search for a particular identity across all providers
pk identities search --identity-id <identityId> --disconnected

// Unbounded search across two providers for a given search term, displaying 20 (or fewer) results
pk identities search --provider-id <providerId> <providerId> --number 20 --disconnected [searchTerm]
```

**Comment by CMCDragonkai** [comment]
Interesting. So this means using `--identity-id` means looking up a specific identity rather than searching.

But if you combine it with search terms it would have to apply the filter to the resulting list of identities even if that list only has 1 identity.

I suggest that `--identity-id` be `-ii`as words are always single characters.

Also this command should stream out the results which means output formatter has to be used in a loop. That is rather than outputting the entire array in own go, you would output it line by line in a stream as you read off from the grpc stream.

**Comment by CMCDragonkai** [comment]
Also standardised names for limiting results is `--limit`.

**Comment by CMCDragonkai** [comment]
> > BTW, I remember now that we made a decision to group all gestalt-related functionality within the `identities` subcommand. So there is no `pk gestalts` subcommand. This was a UX decision so that users don't have to know what "gestalt" means. We can reverse this decision, but for now most of what we want to do will be identity focused.
> 
> I was thinking about this and was wondering if maybe the gestalts-related behaviour could go under something like `permissions`? So example commands would be
> ```
> // Allow permission on gestalt by node/identity
> pk permissions allow <gestaltId> <permissions>
> 
> // Disallow permission on gestalt by node/identity
> pk permissions disallow <gestaltId> <permissions>
> 
> // Discover a gestalt by node/identity
> pk permissions discover <gestaltId>
> 
> // Get a gestalt by node/identity
> pk permissions get <gestaltId>
> 
> // Get all gestalts (and associated permissions)
> pk permissions list
> 
> // Get the permissions for a gestalt by node/identity
> pk permissions permissions <gestaltId>
> 
> // Trust a gestalt by node/identity
> pk permissions trust <gestaltId>
> 
> // Untrust a gestalt by node/identity
> pk permissions untrust <gestaltId>
> ```
> It works better for some than others, but I think it's still clearer than using `identities`, expecially considering a lot of this behaviour operates on nodes.

Not all gestalt related work has to do with permissions. And I think we do have an ACL subcommand. To prevent confusion it should either stay in identities or become its own subcommand as gestalts.

**Comment by CMCDragonkai** [comment]
Ok I must have forgotten how ACL works. But yes for now we can only set permissions on nodes. Therefore the identities we set permissions for must be augmented. We are meant to detect if the identity is augmented yet. I want to separate the job of finding identities from the job of querying the gestalt graph. So one can use the identity provider to know if an identity is augmented. It's the discovery modules job to build the gestalt graph and maintain it.

So if the identity is augmented you can give it a permission. If it isn't yet, you can't do it yet. Btw does this also mean notification permissions cannot be set for an identity too?

**Comment by emmacasolin** [comment]
> Ok I must have forgotten how ACL works. But yes for now we can only set permissions on nodes. Therefore the identities we set permissions for must be augmented. We are meant to detect if the identity is augmented yet. I want to separate the job of finding identities from the job of querying the gestalt graph. So one can use the identity provider to know if an identity is augmented. It's the discovery modules job to build the gestalt graph and maintain it.
> 
> So if the identity is augmented you can give it a permission. If it isn't yet, you can't do it yet. Btw does this also mean notification permissions cannot be set for an identity too?

Yeah that's correct - notification permissions cannot be set for an (unaugmented) identity. So how should setting permissions for identities work for the CLI? Because right now you can run `identities trust <nodeId>` to add a node to your GG and set the `notify` permission, however running `identities trust <identityId>` adds the identity to the GG but then throws an error when trying to set the `notify` permission.

**Comment by emmacasolin** [comment]
> > > BTW, I remember now that we made a decision to group all gestalt-related functionality within the `identities` subcommand. So there is no `pk gestalts` subcommand. This was a UX decision so that users don't have to know what "gestalt" means. We can reverse this decision, but for now most of what we want to do will be identity focused.
> > 
> > 
> > I was thinking about this and was wondering if maybe the gestalts-related behaviour could go under something like `permissions`? So example commands would be
> > ```
> > // Allow permission on gestalt by node/identity
> > pk permissions allow <gestaltId> <permissions>
> > 
> > // Disallow permission on gestalt by node/identity
> > pk permissions disallow <gestaltId> <permissions>
> > 
> > // Discover a gestalt by node/identity
> > pk permissions discover <gestaltId>
> > 
> > // Get a gestalt by node/identity
> > pk permissions get <gestaltId>
> > 
> > // Get all gestalts (and associated permissions)
> > pk permissions list
> > 
> > // Get the permissions for a gestalt by node/identity
> > pk permissions permissions <gestaltId>
> > 
> > // Trust a gestalt by node/identity
> > pk permissions trust <gestaltId>
> > 
> > // Untrust a gestalt by node/identity
> > pk permissions untrust <gestaltId>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It works better for some than others, but I think it's still clearer than using `identities`, expecially considering a lot of this behaviour operates on nodes.
> 
> Not all gestalt related work has to do with permissions. And I think we do have an ACL subcommand. To prevent confusion it should either stay in identities or become its own subcommand as gestalts.

There isn't an ACL subcommand yet as far as I can see, but I agree that `permissions` probably isn't the right word. But this PR probably isn't the place to do a naming review.

**Comment by emmacasolin** [comment]
> Interesting. So this means using `--identity-id` means looking up a specific identity rather than searching.
> 
> But if you combine it with search terms it would have to apply the filter to the resulting list of identities even if that list only has 1 identity.
> 
> I suggest that `--identity-id` be `-ii`as words are always single characters.
> 
> Also this command should stream out the results which means output formatter has to be used in a loop. That is rather than outputting the entire array in own go, you would output it line by line in a stream as you read off from the grpc stream.

Incorporating this feedback:
```
Usage: polykey identities search [options] <searchTerms...>

Searches a Provider for any Connected Identities

Arguments:
  searchTerms                  (optional) Search parameters to apply to connected identities

Options:
  -pi, --provider-id <id>      Digital identity provider(s) to search on
  -ii, --identity-id <id>      Name of the digital identity to search for
  -d, --disconnected           Include disconnected identities in search
  -l, --limit <number>         Limit the number of search results to display to a specific number
```

And yes, using `--identity-id` would just be looking up a specific identity, however if you didn't include `--provider-id` then you could search for the same handle across all providers.

**Comment by CMCDragonkai** [comment]
I reckon for now, if the identity isn't linked to a node, then you just aren't allowed to trust it yet. This is something we can change later. Once we review the full workflow end to end and consider the UX of the GUI too.

**Comment by emmacasolin** [comment]
I think I'll make a separate grpc handler to handle the case where `--identity-id` is set for `identities search`, since this would need to call a different method on the provider and I don't want the `identitiesInfoGetConnected` handler to get too big.

**Comment by emmacasolin** [comment]
With the `--disconnected` option for searching identities, this isn't currently possible using any of the existing methods in our `Provider` class. It would be pretty easy to implement it though (at least for github) so happy to add it in, but if so where should it go? Right now we have `getIdentityData()` (gets identity data for one identity) and `getConnectedIdentityDatas()` (streams identity data from all connected identities). I was thinking of either
1. Making a new provider method `Provider.getIdentityDatas()` which would stream identity data from all identities (very similar to `getConnectedIdentityDatas()` - it would only be requesting data from a different url) or
2. Simply adding a parameter to `getConnectedIdentityDatas()` to expand the search to include disconnected identities.

Option 1 is probably better for the case of providers that don't offer the ability to search disconnected identities, so these providers can simply not implement that method.

**Comment by CMCDragonkai** [comment]
The `--disconnected` option is for later. No need to implement it now.

**Comment by CMCDragonkai** [comment]
Review notes:

1. There may be 3 possible service handlers `identitiesInfoGetConnected` and `identitiesInfoGet` and `identitiesInfoGetDisconnected` for when `--disconnected` is implemented. BTW are these handler names correct? Should it be `identitiesInfoConnectedGet`?
2. Use `dict` or `json` for the output formatter rather than `line`.
3. The async queue to be used for `Discovery` can be derived from https://github.com/toolbuilder/await-for-it/blob/master/docs/queue.md and https://github.com/toolbuilder/await-for-it/blob/master/src/queue.js - it is important to get the async iterator and the push handlers done, one key trick is the usage of the `onPushedValue` promise property which is used a pause/unpause goto mechanism for the async iterator loop.

Important for you to spec out how the `Discovery` module will be done, and then also spec out which parts of PK send/push discovery tasks to the Discovery module. This allows us to break down what needs to be tested, and then create ETAs on them.

**Comment by emmacasolin** [comment]
> Review notes:
> 
> 1. There may be 3 possible service handlers `identitiesInfoGetConnected` and `identitiesInfoGet` and `identitiesInfoGetDisconnected` for when `--disconnected` is implemented. BTW are these handler names correct? Should it be `identitiesInfoConnectedGet`?

Good point, `identitiesInfoGetConnected` isn't following SOV order like the rest of the handlers are. `identitiesInfoConnectedGet` sounds a little off to me though - what about `identitiesConnectedInfoGet`? So the three handlers would be `identitiesInfoGet`, `identitiesConnectedInfoGet`, and `identitiesDisconnectedInfoGet`.

> 2. Use `dict` or `json` for the output formatter rather than `line`.

Fixed in latest commit.

> 3. The async queue to be used for `Discovery` can be derived from https://github.com/toolbuilder/await-for-it/blob/master/docs/queue.md and https://github.com/toolbuilder/await-for-it/blob/master/src/queue.js - it is important to get the async iterator and the push handlers done, one key trick is the usage of the `onPushedValue` promise property which is used a pause/unpause goto mechanism for the async iterator loop.
> 
> Important for you to spec out how the `Discovery` module will be done, and then also spec out which parts of PK send/push discovery tasks to the Discovery module. This allows us to break down what needs to be tested, and then create ETAs on them.

Going to install the `await-for-it` package and play around with it so I can understand how it works and how a similar mechanism could be integrated into the discovery domain. I think that will help me narrow down the ideas I have into a concrete plan.

**Comment by CMCDragonkai** [comment]
The `identitiesInfoConnected` is more correct because it is the connected `IdentityInfo` that we are returning.

**Comment by emmacasolin** [comment]
For the Discovery iterator, there are two possible ways of iterating through the discovery process that I've been thinking of using.

Option 1 is `setTimeout`, which would need to be used recursively, however the delay that is set would not include the time it takes for each iteration to complete (i.e. if one iteration of the discovery process takes 200ms, and the set delay is 200ms, the time between calls of the discovery process will be 400ms).

Option 2 is `setInterval` which wouldn't need to be used recursively since it is designed for scheduling a task to repeat after a set interval, however the interval includes the time it takes for each iteration to complete (i.e. if one iteration of the discovery process takes 200ms, and the set interval is 200ms, the time between calls of the discovery process will be 200ms).

I think option one is the safer of the two, especially if iterations of the discovery process can take different amounts of time (e.g. a node with 5 links should theoretically take longer to discover than a node with no links), however option 2 is a lot cleaner to implement.

**Comment by CMCDragonkai** [comment]
For the discovery iterator, you just need to loop it like:

```
for await (const task of tasks) {
  // ...
}
```

That's how it consumes the queue. Other domains can push tasks to the queue, and then it would activate.

Remember that the way the queue is designed, the above loop never finishes. So it just runs forever. You may need to add in async abort signal to abort the iterator though during the `stop()` call.

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of
* https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal

Additionally the `setInterval`, `setTimeout` loop you're talking about would not be called the iterator. We would call that a "regular scheduled job". So on top of the queue, you can have a time-scheduled job that repeatedly adds jobs into the queue in-order to "refresh" the gestalt graph. Think of it like a search engine spider.

But let's do one thing at a time. The order of things to work on should be:

1. Get the queue up and running
2. Get the iterator that pops tasks off the queue and runs
3. Get an abort signal
4. Then lastly think about the set timeout loop

The above tasks can be thought of in-sequence.

**Comment by CMCDragonkai** [comment]
Also don't worry about multi-threading the discovery process. As per the above loop, the whole thing runs single threaded, and even each discovery operation is blocked until first one is done. That's why it's a queue. We can raise the "max concurrency" as an option later, that allows multiple discovery operations to run at the same time, even within the same thread, since it's just concurrency and not parallelism, node is good at this. Finally later we can extend this to multi-threading with the worker pool at the very end. Each step entails greater programming sophistication regarding us to resolve race conditions and adding multithreaded concurrency control. But we can do that later.

**Comment by emmacasolin** [comment]
> For the discovery iterator, you just need to loop it like:
> 
> ```
> for await (const task of tasks) {
>   // ...
> }
> ```
>
> That's how it consumes the queue. Other domains can push tasks to the queue, and then it would activate.

This is how I originally tried designing the queue to work, however I was stuck on where this code would be executed from. Would it be inside a method in `Discovery` that gets called in `start` but not awaited? I'm not sure how to have a method continuously running in the background.

Additionally, would doing it this way mean that the iteration loop is unable to be paused and restarted? Because I thought the expected behaviour when stopping and restarting the discovery domain would be to continue discovery where we left off?

**Comment by emmacasolin** [comment]
> 1. Get the queue up and running
> 2. Get the iterator that pops tasks off the queue and runs

Just to make sure we're on the same page, what "tasks" would be in the queue? Because I can think of several possibilities here: 
1. Converting a nodeId/identityId+providerId that gets sent from another domain into a gestalt key that can be used by the discovery domain
2. Getting the next gestalt key from a queue of gestalt keys that we want to discover from
3. Converting gestalt keys into async generators that perform the discovery process (i.e. calling `Discovery.discoverGestalt([gestaltKey])`)
4. Performing one iteration of the discovery process given an async generator

Would there be separate queues for each of these tasks? Or would they all be combined into one?

There's also the decision of whether the queue(s) should be internal or external to the Discovery domain. If it's external then this is easier for other domains to push tasks (since they wouldn't need to have Discovery as a dependency), however if it's internal then we can incorporate persistence in the form of storing the queue in the DB so that we can continue discovery from where we left off between restarts.

**Comment by CMCDragonkai** [comment]
> > For the discovery iterator, you just need to loop it like:
> > ```
> > for await (const task of tasks) {
> >   // ...
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That's how it consumes the queue. Other domains can push tasks to the queue, and then it would activate.
> 
> This is how I originally tried designing the queue to work, however I was stuck on where this code would be executed from. Would it be inside a method in `Discovery` that gets called in `start` but not awaited? I'm not sure how to have a method continuously running in the background.
> 
> Additionally, would doing it this way mean that the iteration loop is unable to be paused and restarted? Because I thought the expected behaviour when stopping and restarting the discovery domain would be to continue discovery where we left off?

It's an asynchronous loop that gets started and assigned to a property. As in it should be in a method that gets called by `start`, but you don't await for it. You assign it to a property.

During `stop, you then use the abort signal to abort that promise. So it's a promise that never finishes.

**Comment by CMCDragonkai** [comment]
> > 1. Get the queue up and running
> > 2. Get the iterator that pops tasks off the queue and runs
> 
> Just to make sure we're on the same page, what "tasks" would be in the queue? Because I can think of several possibilities here:
> 
> 1. Converting a nodeId/identityId+providerId that gets sent from another domain into a gestalt key that can be used by the discovery domain
> 2. Getting the next gestalt key from a queue of gestalt keys that we want to discover from
> 3. Converting gestalt keys into async generators that perform the discovery process (i.e. calling `Discovery.discoverGestalt([gestaltKey])`)
> 4. Performing one iteration of the discovery process given an async generator
> 
> Would there be separate queues for each of these tasks? Or would they all be combined into one?
> 
> There's also the decision of whether the queue(s) should be internal or external to the Discovery domain. If it's external then this is easier for other domains to push tasks (since they wouldn't need to have Discovery as a dependency), however if it's internal then we can incorporate persistence in the form of storing the queue in the DB so that we can continue discovery from where we left off between restarts.

The queue is internal to the `Discovery`, but you are going to expose public methods that allow one to add tasks to the queue.

The only task I can think of is just the "discover" task. That is, here is a gestalt key (it could be a node id or provider id + identity id) and go discover it to build up the GG, or update the links. That's all there is to it.

When the loop iterates one step, it should add the child links to into the queue. That way the queue operates like a breadth first search algorithm.

**Comment by CMCDragonkai** [comment]
There should only be one queue.

Yes the queue could be persistent. That would mean streaming results from the queue, and then deleting it from the queue when you're done with it. The levelDB exposes read streams that can be converted to async generators.

I suggest doing this queue completely in-memory first until you have good idea.

This is easier to explain what to do with a whiteboard.

**Comment by CMCDragonkai** [comment]
feh_3219615_000001_IMG_20220131_152012

**Comment by CMCDragonkai** [comment]
Actually I realised you don't need the abort controller... at least for stopping the generator.  You can just use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator/return.

But abort signal can also abort IO. So that's the only key thing. See MatrixAI/Polykey#297 for details about this. I think to KISS you can just use `return` like above. But later we can resolve MatrixAI/Polykey#297 along with a bunch of other places that require this feature.

**Comment by CMCDragonkai** [comment]
The `discoverGestalt` algorithm does have a queue, and that queue should be factored out into the async queue we've been talking about.

As well as its BFS algorithm should be exploded and spread over the `Discovery` class.

**Comment by emmacasolin** [comment]
I think I've got the queue and iterator working, however there are some issues with the test provider that are making it difficult to test so I'll make it a bit more flexible (it's currently very hard-coded in terms of outputs).

**Comment by emmacasolin** [comment]
I thought there may have been a bug in the existing discovery algorithm, because the gestalt graph (when retrieved using `GestaltGraph.getGestalts()`) was incorrectly formed - for example a node might be connected to itself, or two nodes that are meant to be in the same gestalt might be in different ones.

However, it turns out that the discovery algorithm is correct, and the gestalt graph (as stored in the DB) is formed correctly - the bug is actually in `getGestalts()` itself. The name of this method is somewhat misleading, since it doesn't just retrieve the gestalts straight out of the DB and return them. Gestalts are stored in the DB as one giant object with no distinction between individual gestalts, meaning that `getGestalts()` has to iterate through this object and manually build up each gestalt one by one based on the data stored there.

Not sure if it would be more efficient to have the gestalts separated out in the DB itself (meaning that it would need to be updated anytime a new node/identity is set such that it gets put into the correct gestalt/a new gestalt) or keep this inside the `getGestalts()` method (meaning that the entire gestalt graph needs to be recreated whenever this method is called).

**Comment by emmacasolin** [comment]
Found and fixed the `getGestalts()` bug. It was from the line `const vertexKeys = gKs`, where `gKs` was the gestalt key set for a particular vertex `gK` (i.e. the linked nodes/identities to a given node/identity). The problem was that `gK` is the starting vertex from which we build up an individual gestalt, not necessarily the vertex we're currently iterating over, which is declared as `vertex` in the code. So now `vertexKeys` is correctly set to the gestalt key set belonging to `vertex` rather than `gK`.

**Comment by emmacasolin** [comment]
Unattended discovery is now functioning at a usable level with passing tests. Some key design choices for this version of discovery:
- Discovery now uses `CreateDestroyStartStop` instead of `CreateDestroy`
  - This ensures that unattended discovery can be stopped and restarted (using `start`/`stop` methods) without needing to destroy and recreate the entire domain
- Discovery now takes the DB as a dependency
  - This allows us to store the queue of gestalt keys we want to discover in the DB such that we can pick up discovery where we left off between restarts
  - Calling the `destroy` method clears the DB, and by extension the queue
- The type of the queue is `Array<GestaltKey>`
  - This means we don't need to create our own ADT for the queue and can make use of the in-built `shift` and `push` methods of the array
  - This also allows the queue to easily be stored in the DB as a single object
- The iterator for the discovery queue is started in the `start` method and stopped in the `stop` method of discovery
  - The iterator is started in two steps, `this.discoveryGenerator = this.discoverGestalt()` to store a reference to the async generator we use to perform discovery and then `this.discovery = this.doDiscovery()` to assign the async iterator for the generator to a separate property
  - The generator is stopped by calling `this.discoveryGenerator.return()` to exit the async generator
  - The iterator function is not explicitly stopped - this requires an abort signal and can be addressed in https://github.com/MatrixAI/js-polykey/issues/297
- `discoverGestaltByNode()` and `discoverGestaltByIdentity()` no longer return async generators
  - Instead, these functions add the node/identity to the queue of gestalt keys to discover
  - This means that you need to wait after calling these functions for discovery to happen in the background
- The queue and set of visited vertices from `discoverGestalt()` have been brought out into the class, with a few changes
  - `discoverGestalt()` still does everything inside a `while (true)` loop so that even if there are no vertices in the queue we don't exit the method, we just wait until new keys are added to the queue
  - The set of visited vertices was removed in order to allow previously discovered gestalts to be rediscovered
    - Since we are using a queue to store our list of gestalt keys to discover (as opposed to a stack), new gestalt keys are added to the end of the queue and the next key to discover is popped off the beginning. This means that we won't just loop eternally between the two closest nodes
    - This way, keys will continue to move through the queue in the order that they were added, and old keys will be rediscovered again once they reach the front of the queue again
    - This allows the gestalt graph to "auto update" whenever a new node/identity is added to a gestalt that has been previously discovered
    - Child vertices (i.e. discovered nodes/identities from the discovery process) will only be added into the queue if they are not already in it in order to prevent the queue from being overly repetitive and from becoming too long
    - This system could be optimised by making the queue into a priority queue, prioritising new gestalt keys over ones that have previously been discovered. A very simple implementation of this would be to put new gestalt keys from `discoverGestaltByNode()` and `discoverGestaltByIdentity()` at the front of the queue rather than the end.
- Support for discovering your own node was removed from `discoverGestalt()`, as we don't expect to perform discovery on our own gestalt.
  - If a gestalt key from the queue is discovered to be your own node it will now be skipped

There were a also few other non-queue-design related changes, e.g. replacing instances of `== null` with `=== undefined` as well as proper usage of the provider methods (`authIdentityId` and `identityId` were being treated as the same thing, this has been corrected and we now retrieve our own authenticated identity id in order to perform authenticated operations on the provider).

Next steps will be allowing other domains to add to the queue, as well as fixing up the discovery CLI/service handlers in order to match the new behaviour.

**Comment by CMCDragonkai** [comment]
> The type of the queue is `Array<GestaltKey>`
> * This means we don't need to create our own ADT for the queue and can make use of the in-built `shift` and `push` methods of the array
> * This also allows the queue to easily be stored in the DB as a single object

This is good for the initial prototype, but we should optimise this once everything is working. That is instead of using a JSON packed array, we should be using leveldb's own key-ordering system and subleveldown to create a sublevel just for the discovery queue. And then pop tasks out by reading the leveldb sublevel as a stream. My initial thinking is that the keys of the jobs has to be uniquely ordered, we could use `IdSortable` for this, as it ensures monotonic ordering.

**Comment by CMCDragonkai** [comment]
> There were a also few other non-queue-design related changes, e.g. replacing instances of `== null` with `=== undefined` as well as proper usage of the provider methods (`authIdentityId` and `identityId` were being treated as the same thing, this has been corrected and we now retrieve our own authenticated identity id in order to perform authenticated operations on the provider).

Are you sure this is correct? The `== null` is better than checking `=== undefined` even when you know the return value is `undefined`. This is consistent with the rest of the codebase.

**Comment by CMCDragonkai** [comment]
> Support for discovering your own node was removed from `discoverGestalt()`, as we don't expect to perform discovery on our own gestalt.

Without the ability to do gestalt gossip MatrixAI/Polykey#190, you may actually need to do this for now if other nodes acquire new identity links. But we may just need to sit down and figure this out fully.

**Comment by CMCDragonkai** [comment]
Great summary! Will review in more detail later.

**Comment by emmacasolin** [comment]
> Are you sure this is correct? The `== null` is better than checking `=== undefined` even when you know the return value is `undefined`. This is consistent with the rest of the codebase.

Ahh I thought it was the other way around (`=== undefined` being preferred) - will change it back

**Comment by emmacasolin** [comment]
I've squashed all of the commits here down to 3 commits:
1. [Fixed `identities search` command to search connected identities](https://github.com/MatrixAI/js-polykey/pull/320/commits/d7b4e944816fae6ba70067f83de3d6754620185b) - exposes social discovery to the CLI, allowing users to search for connected DIs that can subsequently be trusted and discovered
2. [Unattended background discovery for Discovery domain](https://github.com/MatrixAI/js-polykey/pull/320/commits/7afa5879c30fc706086a01aec95721f2a122ba7f) - unattended discovery implementation, including the update to use levelDB for the queue (no array)
3. [Adding trusted nodes/identities to the Gestalt Graph](https://github.com/MatrixAI/js-polykey/pull/320/commits/64c390a7e48dc249d9726025e5d6308e0c523b00) - adds functionality to the `identities trust` command so that when you trust a node/identity it gets added to your GG and added to the discovery queue

Everything is lintfixed and passes on my own machine, however it seems that some of the discovery tests are failing on the pipeline. This could just be a timing issue as I get the same errors when trying to run the tests at the same time as too many other tests.

The only thing still missing from this PR is adding the same functionality to `vaults share` as was added to `identities trust`, however this is blocked by MatrixAI/Polykey#266.

**Comment by CMCDragonkai** [comment]
You want to address all the timing issues too, tests should be able to run without timing out even if you do all of them. Many solutions have been applied in the past already. Things like mocking our timers, setting very low timeout configuration, or not doing an actual network call by mocking out the network call. The more reproducible the better, but of course we don't want to lose test coverage.

**Comment by emmacasolin** [comment]
Ok, I'll see if I can get all of the gestalts + identities + discovery tests running and passing at once on my machine.

Right now, running `npm run test gestalt identities discovery` gives me this output:

<details>

```
[nix-shell:~/Projects/js-polykey]$ npm run test gestalt identities discovery

> @matrixai/polykey@1.0.0 test /home/emma/Projects/js-polykey
> jest "gestalt" "identities" "discovery"

Debugger listening on ws://127.0.0.1:38149/af8220f5-9fcc-40db-beda-f52339b94f88
For help, see: https://nodejs.org/en/docs/inspector
read byte 1

Error activating auto attach, please report to https://aka.ms/js-dbg-issue
Determining test suites to run...
GLOBAL SETUP
Global Data Dir: /tmp/polykey-test-global-egU58V
 PASS  tests/client/service/identitiesProvidersList.test.ts (54.103 s)
  identitiesProvidersList
    ✓ lists providers (320 ms)

 PASS  tests/client/service/identitiesAuthenticate.test.ts (54.23 s)
  identitiesAuthenticate
    ✓ authenticates identity (427 ms)

 PASS  tests/client/service/identitiesClaim.test.ts (60.893 s)
  identitiesClaim
    ✓ claims identity (5621 ms)

 PASS  tests/identities/IdentitiesManager.test.ts (8.405 s)
  IdentitiesManager
    ✓ IdentitiesManager readiness (80 ms)
    ✓ get, set and unset tokens (153 ms)
    ✓ start and stop preserves state (71 ms)
    ✓ fresh start deletes all state (40 ms)
    ✓ register and unregister providers (81 ms)
    ✓ using TestProvider (142 ms)

 PASS  tests/client/service/identitiesInfoGet.test.ts (6.423 s)
  identitiesInfoGet
    ✓ gets an identity (110 ms)
    ✓ searches for a handle across providers (107 ms)
    ✓ searches for identities matching a search term (152 ms)
    ✓ gets no connected identities (87 ms)
    ✓ gets one connected identity (137 ms)
    ✓ cannot get more identities than available (114 ms)
    ✓ can only get from authenticated providers (71 ms)

 FAIL  tests/client/rpcGestalts.test.ts (17.358 s)
  Client service
    ✓ should get all gestalts (272 ms)
    ✓ should set independent node and identity gestalts (87 ms)
    ✓ should get gestalt from Node. (225 ms)
    ✓ should get gestalt from identity. (97 ms)
    ✓ should discover gestalt via Node. (46 ms)
    ✕ should discover gestalt via Identity. (172 ms)
    ✓ should get gestalt permissions by node. (154 ms)
    ✓ should get gestalt permissions by Identity. (221 ms)
    ✓ should set gestalt permissions by node. (154 ms)
    ✓ should set gestalt permissions by Identity. (312 ms)
    ✓ should unset gestalt permissions by node. (241 ms)
    ✓ should unset gestalt permissions by Identity. (234 ms)

  ● Client service › should discover gestalt via Identity.

    ErrorNodeGraphEmptyDatabase:

      518 |     // then we should throw an error. We aren't going to find any others.
      519 |     if (shortlist.length === 0) {
    > 520 |       throw new nodesErrors.ErrorNodeGraphEmptyDatabase();
          |             ^
      521 |     }
      522 |     // Need to keep track of the nodes that have been contacted.
      523 |     // Not sufficient to simply check if there's already a pre-existing connection

      at Object.getClosestGlobalNodes (src/nodes/NodeGraph.ts:520:13)
      at Object.findNode (src/nodes/NodeManager.ts:609:17)
      at Object.establishNodeConnection (src/nodes/NodeManager.ts:484:27)
      at Object.getConnectionToNode (src/nodes/NodeManager.ts:465:22)
      at Object.requestChainData (src/nodes/NodeManager.ts:297:24)
      at Object.discoverGestalt (src/discovery/Discovery.ts:204:31)
      at Object.doDiscovery (src/discovery/Discovery.ts:338:22)

 PASS  tests/gestalts/GestaltGraph.test.ts (11.201 s)
  GestaltGraph
    ✓ gestaltGraph readiness (217 ms)
    ✓ get, set and unset node (181 ms)
    ✓ get, set and unset identity (84 ms)
    ✓ setting independent node and identity gestalts (92 ms)
    ✓ start and stop preserves state (107 ms)
    ✓ link node to node (210 ms)
    ✓ link node to identity (82 ms)
    ✓ link node to node and identity (148 ms)
    ✓ getting all gestalts (278 ms)
    ✓ new node gestalts creates a new acl record (51 ms)
    ✓ new identity gestalts does not create a new acl record (63 ms)
    ✓ set and unset gestalt actions (133 ms)
    ✓ linking 2 new nodes results in a merged permission (98 ms)
    ✓ linking 2 existing nodes results in a merged permission (206 ms)
    ✓ link existing node to new node (158 ms)
    ✓ linking new node and new identity results in a merged permission (196 ms)
    ✓ linking existing node and existing identity results in merged permission (394 ms)
    ✓ link existing node to new identity (133 ms)
    ✓ link new node to existing identity (140 ms)
    ✓ splitting node and node results in split inherited permissions (324 ms)
    ✓ splitting node and identity results in split inherited permissions unless the identity is a loner (245 ms)
    ✓ removing a gestalt removes the permission (110 ms)

 PASS  tests/client/service/identitiesInfoConnectedGet.test.ts (8.249 s)
  identitiesInfoConnectedGet
    ✓ gets connected identities from a single provider (116 ms)
    ✓ gets connected identities from multiple providers (51 ms)
    ✓ gets connected identities from all providers (76 ms)
    ✓ searches for identities matching a search term (33 ms)
    ✓ searches for identities matching multiple search terms (87 ms)
    ✓ searches for identities matching a search term across multiple providers (85 ms)
    ✓ gets no connected identities (83 ms)
    ✓ gets one connected identity (60 ms)
    ✓ cannot get more identities than available (58 ms)
    ✓ can only get from authenticated providers (44 ms)
    ✓ gets disconnected identities (479 ms)

 PASS  tests/client/service/identitiesTokenPut.test.ts (5.532 s)
  identitiesTokenPut
    ✓ authenticates providers (69 ms)

 PASS  tests/client/service/identitiesTokenDelete.test.ts (6.015 s)
  identitiesTokenDelete
    ✓ un-authenticates providers (99 ms)

 PASS  tests/client/service/identitiesTokenGet.test.ts
  identitiesTokenGet
    ✓ gets provider tokens (44 ms)

 FAIL  tests/bin/identities/identities.test.ts (91.197 s)
  CLI Identities
    commandAllowGestalts
      ✓ Should allow permissions on node. (577 ms)
      ✓ Should allow permissions on Identity. (523 ms)
      ✓ Should fail on invalid inputs. (400 ms)
    commandDisallowGestalts
      ✓ Should disallow permissions on Node. (218 ms)
      ✓ Should disallow permissions on Identity. (243 ms)
      ✓ Should fail on invalid inputs. (719 ms)
    commandPermissionsGestalts
      ✓ Should get permissions on Node. (230 ms)
      ✓ Should get permissions on Identity. (251 ms)
    commandTrustGestalts
      ✓ Should set trust on Node. (184 ms)
      ✓ Should set trust on Identity. (273 ms)
      ✓ Should fail on invalid inputs. (164 ms)
    commandUntrustGestalts
      ✓ Should unset trust on Node. (216 ms)
      ✓ Should unset trust on Identity. (192 ms)
      ✓ Should fail on invalid inputs. (266 ms)
    commandClaimIdentity
      ✓ Should claim an identity. (253 ms)
      ✓ Should fail for unauthenticated identities. (174 ms)
    commandAuthenticateProvider
      ✓ Should authenticate an identity with a provider. (277 ms)
    commandGetGestalts
      ✓ Should list gestalt by Node (147 ms)
      ✓ Should list gestalt by Identity (225 ms)
    commandListGestalts
      ✓ Should list gestalts with permissions. (638 ms)
    commandSearchIdentities
      ✓ Should find a connected identity. (364 ms)
    commandDiscoverGestalts
      ✕ Should start discovery by Node (655 ms)
      ✓ Should start discovery by Identity (1216 ms)

  ● CLI Identities › commandDiscoverGestalts › Should start discovery by Node

    expect(received).toContain(expected) // indexOf

    Expected substring: "vc68mg4p7st56aqm5i0q97unqh55gqhdqu5np3rnfjfj50u7k7ao0"
    Received string:    "[{\"matrix\":{\"{\\\"identityId\\\":\\\"abc\\\",\\\"providerId\\\":\\\"github.com\\\",\\\"type\\\":\\\"identity\\\"}\":{\"{\\\"nodeId\\\":\\\"vrsc24a1er424epq77dtoveo93meij0pc8ig4uvs9jbeld78n9nl0\\\",\\\"type\\\":\\\"node\\\"}\":null},\"{\\\"nodeId\\\":\\\"vrsc24a1er424epq77dtoveo93meij0pc8ig4uvs9jbeld78n9nl0\\\",\\\"type\\\":\\\"node\\\"}\":{\"{\\\"identityId\\\":\\\"abc\\\",\\\"providerId\\\":\\\"github.com\\\",\\\"type\\\":\\\"identity\\\"}\":null}},\"nodes\":{\"{\\\"nodeId\\\":\\\"vrsc24a1er424epq77dtoveo93meij0pc8ig4uvs9jbeld78n9nl0\\\",\\\"type\\\":\\\"node\\\"}\":{\"id\":\"vrsc24a1er424epq77dtoveo93meij0pc8ig4uvs9jbeld78n9nl0\",\"chain\":{}}},\"identities\":{\"{\\\"identityId\\\":\\\"abc\\\",\\\"providerId\\\":\\\"github.com\\\",\\\"type\\\":\\\"identity\\\"}\":{\"providerId\":\"github.com\",\"identityId\":\"abc\",\"claims\":{}}}},{\"matrix\":{\"{\\\"nodeId\\\":\\\"v359vgrgmqf1r5g4fvisiddjknjko6bmm4qv7646jr7fi9enbfuug\\\",\\\"type\\\":\\\"node\\\"}\":{}},\"nodes\":{\"{\\\"nodeId\\\":\\\"v359vgrgmqf1r5g4fvisiddjknjko6bmm4qv7646jr7fi9enbfuug\\\",\\\"type\\\":\\\"node\\\"}\":{\"id\":\"v359vgrgmqf1r5g4fvisiddjknjko6bmm4qv7646jr7fi9enbfuug\",\"chain\":{}}},\"identities\":{}},{\"matrix\":{\"{\\\"nodeId\\\":\\\"vg08t6vinkot3ivaeuv811hcpcpqusf3utq189rt9ddfdmqr7j390\\\",\\\"type\\\":\\\"node\\\"}\":{}},\"nodes\":{\"{\\\"nodeId\\\":\\\"vg08t6vinkot3ivaeuv811hcpcpqusf3utq189rt9ddfdmqr7j390\\\",\\\"type\\\":\\\"node\\\"}\":{\"id\":\"vg08t6vinkot3ivaeuv811hcpcpqusf3utq189rt9ddfdmqr7j390\",\"chain\":{}}},\"identities\":{}},{\"matrix\":{\"{\\\"nodeId\\\":\\\"vrcacp9vsb4ht25hds6s4lpp2abfaso0mptcfnh499n35vfcn2gkg\\\",\\\"type\\\":\\\"node\\\"}\":{}},\"nodes\":{\"{\\\"nodeId\\\":\\\"vrcacp9vsb4ht25hds6s4lpp2abfaso0mptcfnh499n35vfcn2gkg\\\",\\\"type\\\":\\\"node\\\"}\":{\"id\":\"vrcacp9vsb4ht25hds6s4lpp2abfaso0mptcfnh499n35vfcn2gkg\",\"chain\":{}}},\"identities\":{}}]"

      747 |       expect(gestalt.length).not.toBe(0);
      748 |       const gestaltString = JSON.stringify(gestalt);
    > 749 |       expect(gestaltString).toContain(
          |                             ^
      750 |         nodesUtils.encodeNodeId(nodeB.nodeManager.getNodeId()),
      751 |       );
      752 |       expect(gestaltString).toContain(

      at Object.<anonymous> (tests/bin/identities/identities.test.ts:749:29)

 FAIL  tests/discovery/Discovery.test.ts (124.6 s)
  Discovery
    ✓ discovery readiness (31 ms)
    ✕ discovery by node (1087 ms)
    ✓ discovery by identity (1280 ms)
    ✓ auto-updates previously discovered gestalts (2416 ms)
    ✕ discovery persistence across restarts (1022 ms)

  ● Discovery › discovery by node

    expect(received).toHaveLength(expected)

    Expected length: 1
    Received length: 0
    Received array:  []

      228 |     await sleep(1000);
      229 |     const gestalt = await gestaltGraph.getGestalts();
    > 230 |     expect(gestalt).toHaveLength(1);
          |                     ^
      231 |     const gestaltMatrix = gestalt[0].matrix;
      232 |     const gestaltNodes = gestalt[0].nodes;
      233 |     const gestaltIdentities = gestalt[0].identities;

      at Object.<anonymous> (tests/discovery/Discovery.test.ts:230:21)

  ● Discovery › discovery persistence across restarts

    expect(received).toHaveLength(expected)

    Expected length: 3
    Received length: 4
    Received array:  ["{\"identityId\":\"other-gestalt\",\"providerId\":\"test-provider\",\"type\":\"identity\"}", "{\"nodeId\":\"vpgsfi7l2pnei3sr3ohus69vliqe8iegqqrhbk8ifsho3s8otgoeg\",\"type\":\"node\"}", "{\"nodeId\":\"volme4i8ftjiv7c4l52g2e8470er90qc5ii635hhj9r3jb99une6g\",\"type\":\"node\"}", "{\"identityId\":\"other-gestalt2\",\"providerId\":\"test-provider\",\"type\":\"identity\"}"]

      372 |     const gestaltNodes1 = gestalt1[0].nodes;
      373 |     const gestaltIdentities1 = gestalt1[0].identities;
    > 374 |     expect(Object.keys(gestaltMatrix1)).toHaveLength(3);
          |                                         ^
      375 |     expect(Object.keys(gestaltNodes1)).toHaveLength(2);
      376 |     expect(Object.keys(gestaltIdentities1)).toHaveLength(1);
      377 |     const gestaltString1 = JSON.stringify(gestalt1);

      at Object.<anonymous> (tests/discovery/Discovery.test.ts:374:41)

WARN:ConnectionForward 0.0.0.0:51171:Client Error: ErrorConnectionEndTimeout
 FAIL  tests/client/service/gestaltsGestaltTrustByNode.test.ts (132.211 s)
  gestaltsGestaltTrustByNode
    ✕ trusts a node (already set in gestalt graph) (22418 ms)
    ✕ trusts a node (new node) (20037 ms)
    ✕ cannot trust a node with invalid id (12827 ms)
    ✓ trust extends to entire gestalt (15301 ms)

  ● gestaltsGestaltTrustByNode › trusts a node (already set in gestalt graph)

    Timeout - Async callback was not invoked within the 20000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 20000 ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:27:45)

  ● gestaltsGestaltTrustByNode › trusts a node (already set in gestalt graph)

    TypeError: Cannot read property 'setNode' of undefined

      238 |   });
      239 |   test('trusts a node (already set in gestalt graph)', async () => {
    > 240 |     await gestaltGraph.setNode({
          |                        ^
      241 |       id: nodeId,
      242 |       chain: {},
      243 |     });

      at Object.<anonymous> (tests/client/service/gestaltsGestaltTrustByNode.test.ts:240:24)

  ● gestaltsGestaltTrustByNode › trusts a node (already set in gestalt graph)

    TypeError: Cannot read property 'destroy' of undefined

      220 |   });
      221 |   afterEach(async () => {
    > 222 |     await grpcClient.destroy();
          |                      ^
      223 |     await grpcServer.stop();
      224 |     await discovery.stop();
      225 |     await nodeManager.stop();

      at Object.<anonymous> (tests/client/service/gestaltsGestaltTrustByNode.test.ts:222:22)

  ● gestaltsGestaltTrustByNode › trusts a node (new node)

    Timeout - Async callback was not invoked within the 20000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 20000 ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:27:45)

  ● gestaltsGestaltTrustByNode › trusts a node (new node)

    TypeError: Cannot read property 'gestaltsGestaltTrustByNode' of undefined

      263 |     const request = new nodesPB.Node();
      264 |     request.setNodeId(nodeId);
    > 265 |     const response = await grpcClient.gestaltsGestaltTrustByNode(
          |                                       ^
      266 |       request,
      267 |       clientUtils.encodeAuthFromPassword(password),
      268 |     );

      at Object.<anonymous> (tests/client/service/gestaltsGestaltTrustByNode.test.ts:265:39)

  ● gestaltsGestaltTrustByNode › trusts a node (new node)

    TypeError: Cannot read property 'destroy' of undefined

      220 |   });
      221 |   afterEach(async () => {
    > 222 |     await grpcClient.destroy();
          |                      ^
      223 |     await grpcServer.stop();
      224 |     await discovery.stop();
      225 |     await nodeManager.stop();

      at Object.<anonymous> (tests/client/service/gestaltsGestaltTrustByNode.test.ts:222:22)

  ● gestaltsGestaltTrustByNode › cannot trust a node with invalid id

    OpenError: IO error: lock /tmp/polykey-test-v0K5gH/db/LOCK: already held by process

      at node_modules/levelup/lib/levelup.js:127:23
      at node_modules/abstract-leveldown/abstract-leveldown.js:41:14
      at onopen (node_modules/deferred-leveldown/deferred-leveldown.js:49:14)
      at node_modules/abstract-leveldown/abstract-leveldown.js:41:14
      at node_modules/abstract-leveldown/abstract-leveldown.js:41:14

WARN:ConnectionForward 0.0.0.0:32841:Client Error: ErrorConnectionEndTimeout
 FAIL  tests/client/service/gestaltsGestaltTrustByIdentity.test.ts (144.444 s)
  gestaltsGestaltTrustByIdentity
    ✕ trusts an identity (already set in gestalt graph) (22751 ms)
    ✕ trusts an identity (new identity) (20755 ms)
    ✕ cannot trust a disconnected identity (11671 ms)
    ✓ trust extends to entire gestalt (13324 ms)
    ✓ links trusted identity to an existing node (14643 ms)

  ● gestaltsGestaltTrustByIdentity › trusts an identity (already set in gestalt graph)

    Timeout - Async callback was not invoked within the 20000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 20000 ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:27:45)

  ● gestaltsGestaltTrustByIdentity › trusts an identity (already set in gestalt graph)

    TypeError: Cannot read property 'linkNodeAndIdentity' of undefined

      242 |   test('trusts an identity (already set in gestalt graph)', async () => {
      243 |     testProvider.users['disconnected-user'] = {};
    > 244 |     await gestaltGraph.linkNodeAndIdentity(
          |                        ^
      245 |       {
      246 |         id: nodeId,
      247 |         chain: {},

      at Object.<anonymous> (tests/client/service/gestaltsGestaltTrustByIdentity.test.ts:244:24)

  ● gestaltsGestaltTrustByIdentity › trusts an identity (already set in gestalt graph)

    TypeError: Cannot read property 'destroy' of undefined

      223 |   });
      224 |   afterEach(async () => {
    > 225 |     await grpcClient.destroy();
          |                      ^
      226 |     await grpcServer.stop();
      227 |     await discovery.stop();
      228 |     await nodeManager.stop();

      at Object.<anonymous> (tests/client/service/gestaltsGestaltTrustByIdentity.test.ts:225:22)

  ● gestaltsGestaltTrustByIdentity › trusts an identity (new identity)

    Timeout - Async callback was not invoked within the 20000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 20000 ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:27:45)

  ● gestaltsGestaltTrustByIdentity › trusts an identity (new identity)

    TypeError: Cannot read property 'gestaltsGestaltTrustByIdentity' of undefined

      280 |     // linked to a node via discovery
      281 |     await expect(
    > 282 |       grpcClient.gestaltsGestaltTrustByIdentity(
          |                  ^
      283 |         request,
      284 |         clientUtils.encodeAuthFromPassword(password),
      285 |       ),

      at Object.<anonymous> (tests/client/service/gestaltsGestaltTrustByIdentity.test.ts:282:18)

  ● gestaltsGestaltTrustByIdentity › trusts an identity (new identity)

    TypeError: Cannot read property 'destroy' of undefined

      223 |   });
      224 |   afterEach(async () => {
    > 225 |     await grpcClient.destroy();
          |                      ^
      226 |     await grpcServer.stop();
      227 |     await discovery.stop();
      228 |     await nodeManager.stop();

      at Object.<anonymous> (tests/client/service/gestaltsGestaltTrustByIdentity.test.ts:225:22)

  ● gestaltsGestaltTrustByIdentity › cannot trust a disconnected identity

    OpenError: IO error: lock /tmp/polykey-test-2qKobd/db/LOCK: already held by process

      at node_modules/levelup/lib/levelup.js:127:23
      at node_modules/abstract-leveldown/abstract-leveldown.js:41:14
      at onopen (node_modules/deferred-leveldown/deferred-leveldown.js:49:14)
      at node_modules/abstract-leveldown/abstract-leveldown.js:41:14
      at node_modules/abstract-leveldown/abstract-leveldown.js:41:14

A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks.
Test Suites: 5 failed, 10 passed, 15 total
Tests:       10 failed, 91 passed, 101 total
Snapshots:   0 total
Time:        145.73 s
Ran all test suites matching /gestalt|identities|discovery/i.
GLOBAL TEARDOWN
Destroying Global Data Dir: /tmp/polykey-test-global-egU58V
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @matrixai/polykey@1.0.0 test: `jest "gestalt" "identities" "discovery"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @matrixai/polykey@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/emma/.npm/_logs/2022-02-04T03_18_08_388Z-debug.log
```
</details>

So the failing tests are:
- `tests/client/rpcGestalts.test.ts` - should discover gestalt by identity
- `tests/bin/identities/identities.test.ts` - should start discovery by node
- `tests/discovery/Discovery.test.ts` - discovery by node + discovery persistence across restarts
- `tests/client/service/gestaltsGestaltTrustByNode.test.ts` - trusts a node (already set in gestalt graph) + trusts a node (new node) + cannot trust a node with invalid id
- `tests/client/service/gestaltsGestaltTrustByIdentity.test.ts` - trusts an identity (already set in gestalt graph) + trusts an identity (new identity) + cannot trust a disconnected identity

All of these failures go back to unattended discovery. I think most (if not all) of these failures are because we expect a node/identity to have been discovered, however it hasn't reached the front of the queue yet (the discovery iterator can't run as fast when there are multiple test suites running at the same time). In all of these tests I'm just using `await sleep()` to allow the discovery iterator some time to run before checking for expected results, however this is definitely not the most reliable way to go about this. I can try using the poll utility instead.

**Comment by emmacasolin** [comment]
After replacing all instances of `sleep` with `poll` in the tests, everything is now passing together except for `tests/client/service/gestaltsGestaltTrustByNode.test.ts` (trusts a node (already set in gestalt graph) and trusts a node (new node)). These tests both pass when the test suite is run on its own, so either there's some sort of interference between tests or there's still a lingering timeout issue somewhere. Will investigate further.

**Comment by emmacasolin** [comment]
Solved the problem - the timeouts were coming from the time needed to setup a second keypair for the node we wanted to trust. Was an easy fix by just doing it once for everything in the `beforeAll()` and mocking key generation to return these values

**Comment by CMCDragonkai** [comment]
Suggest changing to selective imports in this PR for the domains it's touching based on this comment: https://github.com/MatrixAI/js-polykey/pull/321#issuecomment-1029631104

**Comment by CMCDragonkai** [comment]
Notes on discovery design:

Some pseudocode first.

```
class Discovery {

  async start () {
    this.discoveryQueue = this.setupDiscoveryQueue();
    this.discoveryProcess = this.runDiscoveryQueue();
  }

  async stop () {
    this.discoveryQueue.return();
    delete this.discoveryProcess;
  }


  async setupDiscoveryQueue (): AsyncGenerator<> {
    while (true) {
        if (isThereAValue(DB)) {
            /// for await...
        } else {
            plug.lock();
            await plug.unlocked();
        }
    }
  }

  async runDiscoveryQueue (): Promise<void> {
    for (await const _ of this.discoveryProcess) () {
    }
  }

  async pushToTheQueue () {
    pushValueTotheQueue();
    this.plug.unlock();
  }

}
```

So basically:

* You need the setup queue and run queue functions simply because you need to be able to stop the async generator. If we just put them together as one function, we would need an abort controller from MatrixAI/Polykey#297 which is not yet designed.
* Use `async-mutex` to design a "plug" in order to pause and unpause the discovery queue, this prevents 100% CPU loops when there's nothing in the queue. Even if promises don't hold reference to the event loop, because other parts of the app will be running (and holding an event loop reference), it will be fine. Plug it when there's no data, and unplug it when new data is added in. Refer to https://github.com/toolbuilder/await-for-it/blob/master/src/queue.js
* When checking whether there's a value in the queue, if true you want to use use the read stream directly. And only delete the task off the queue because there's only 1 consumer to this queue. If there were multiple consumers, we couldn't do this, but that's not the case here.
* Don't re-add the same node back into the queue, instead a later issue should be created for adding TTLs or `lastVisited` tag to gestalt vertexes, and designing a policy for revisiting nodes when there's nothing in the queue.
* Should have another issue to design priority labels to the persistent queue so that when the user interactively wants to discover a gestalt vertex, it becomes the highest priority and gets executed first.
* Pushing things to the queue methods should start with `queue...()`.

**Comment by emmacasolin** [comment]
I've modified unattended discovery to follow the design of the pseudocode above. It's currently not fully working (I think there's an issue with pushing to the queue), however starting/stopping the discovery domain + locking/unlocking the queue when empty seems to be working as expected. The problem is that when new items are pushed to the queue it still thinks the queue is empty and locks it again, so I'll have to find out where this issue is coming from.

**Comment by CMCDragonkai** [comment]
Is this a sub-PR of MatrixAI/Polykey#311? If so, then this should be a dependency of MatrixAI/Polykey#311. I'll add it in now.

In which case you'll need to stack these 2 PRs together, and rebase MatrixAI/Polykey#311 first and then rebase this.

**Comment by CMCDragonkai** [comment]
Done here: 
image

As an alternative to stacking PRs, this could also be merged first, then have MatrixAI/Polykey#311 rebase on top of this merged state.

**Comment by emmacasolin** [comment]
> As an alternative to stacking PRs, this could also be merged first, then have MatrixAI/Polykey#311 rebase on top of this merged state.

Yeah I think it would be easiest to merge this first since MatrixAI/Polykey#311 is already on top of MatrixAI/Polykey#310 so stacking could get a bit messy.

**Comment by emmacasolin** [comment]
I'm currently rebasing on top of master with the changes from MatrixAI/Polykey#321 and was wondering what the correct way of validating a list would be?

For example, `identitiesInfoConnectedGet` and `identitiesInfoGet` both take in a list of provider ids in the request - what would be the best way to validate this list using the new validation system @CMCDragonkai?

```ts
let providers = call.request.getProviderIdList() as Array<ProviderId>;
```

**Comment by CMCDragonkai** [comment]
The validate function takes a parser which can take the array as the full value assuming you have the correct key pattern like `[providerIds]`. Validate the array by iterating over it and running `parseProviderId`. It's just functions all the way down.

**Comment by CMCDragonkai** [comment]
Like:

```
validateSync(
  (keyPath, value) => {
    return matchSync(keyPath)(
      [['providerIds'], () => value.map(parseProviderId)]
      () => value
    );
  },
  {
    providerIds: ...
  }
)
```

**Comment by emmacasolin** [comment]
I've got the new version of discovery working, however it only works if the line `this.discoveryQueue.return()` in `stop` is not awaited. So essentially the async generator that we're storing as a property (to iterate through somewhere else) can't be stopped using `return`. If you try to await that line the program gets stuck on it until it eventually times out.

**Comment by CMCDragonkai** [comment]
You may need to call return after switching the lock. The lock may be blocking the async generator from returning.

**Comment by emmacasolin** [comment]
> You may need to call return after switching the lock. The lock may be blocking the async generator from returning.

Yeah, I did some googling and found that what `.return()` is actually doing is causing the generator to act as if there was a `return` after the current (or next) `yield`, so if we're locked then we'll never reach another yield. I'll need to figure out the timing though so that we unlock when stopping and call return without ending up back in the loop and locking again.

**Comment by CMCDragonkai** [comment]
Remember when I said that pausing the async generator can make use of the async-mutex waiting for the lock to unlock without actually locking it. You can trigger an unlock when you call `Discovery.stop` as well.

Use this `await mutex.waitForUnlock();`. See: https://github.com/DirtyHairy/async-mutex

**Comment by emmacasolin** [comment]
> Remember when I said that pausing the async generator can make use of the async-mutex waiting for the lock to unlock without actually locking it. You can trigger an unlock when you call `Discovery.stop` as well.
> 
> Use this `await mutex.waitForUnlock();`. See: https://github.com/DirtyHairy/async-mutex

Yeah, I think I'm doing all of that already. The problem is that inside `Discovery.stop` we need to both unpause the generator and call return on it. If we call return first we enter an infinite loop because the generator is still paused, but if we unpause it first we loop back around and pause again. If we do both of these tasks inside a `Promise.all()` the tests fail randomly because sometimes the timing is right but sometimes it isn't. I'm not sure what the solution is here...

**Comment by emmacasolin** [comment]
Another problem I'm running into is that, because the `start` method doesn't await any of the queue setup and starting (which it can't because these processes are non-terminating), if `stop` is called too quickly after a `start` the queue may not be fully setup yet, causing problems when trying to exit it.

For example, a proper setup and teardown of the queue (in this example the queue is empty the whole time) would be:
1. **START** (Time A)
1. Start queue
2. Check if queue is empty (yes)
3. Lock queue
4. **STOP** (Time B)
4. Unlock queue
5. Exit queue

The problem is that checking whether the queue is empty is an async operation that takes time, so if we stop too early we get the following:
1. **START** (Time A)
2. Start queue
3. Check if queue is empty (wait)
4. **STOP** (Time B)
5. Unlock queue
6. *Find out that queue is empty now*
7. Lock queue
8. Cannot exit queue because it's locked

**Comment by emmacasolin** [comment]
> Another problem I'm running into is that, because the `start` method doesn't await any of the queue setup and starting (which it can't because these processes are non-terminating), if `stop` is called too quickly after a `start` the queue may not be fully setup yet, causing problems when trying to exit it.
> 
> For example, a proper setup and teardown of the queue (in this example the queue is empty the whole time) would be:
> 
> 1. **START** (Time A)
> 2. Start queue
> 3. Check if queue is empty (yes)
> 4. Lock queue
> 5. **STOP** (Time B)
> 6. Unlock queue
> 7. Exit queue
> 
> The problem is that checking whether the queue is empty is an async operation that takes time, so if we stop too early we get the following:
> 
> 1. **START** (Time A)
> 2. Start queue
> 3. Check if queue is empty (wait)
> 4. **STOP** (Time B)
> 5. Unlock queue
> 6. _Find out that queue is empty now_
> 7. Lock queue
> 8. Cannot exit queue because it's locked

> The problem is that inside Discovery.stop we need to both unpause the generator and call return on it. If we call return first we enter an infinite loop because the generator is still paused, but if we unpause it first we loop back around and pause again. If we do both of these tasks inside a Promise.all() the tests fail randomly because sometimes the timing is right but sometimes it isn't.

A potential solution to both of these problems would be to have some sort of `stopping` property that gets set when we're stopping the discovery domain. This way we can
1. Check to see if we're stopping before locking the queue - do not lock if stopping
2. Check if we're stopping at the end of each iteration of the discovery process - break if stopping

Edit: Actually, rather than creating a property for this, the `status` symbol could be used - just check whether it `=== 'stopping'`.

**Comment by CMCDragonkai** [comment]
There is a stopping property and also a stopping lock. See the async-init source code. You can acquire symbols to access them.

**Comment by emmacasolin** [comment]
Unattended discovery is now working and all relevant tests are passing. The only remaining failures out of the gestalts, discovery, and identities domains are in `tests/bin/identities/identities.test.ts`, which will be addressed in MatrixAI/Polykey#311. Everything has been linted as well so this PR is ready for review. (Note that there is still work that needs to wait until after MatrixAI/Polykey#266, however the remainder of this PR can be merged without causing any issues).

Will also create new issues for these sometime later today:
> - Don't re-add the same node back into the queue, instead a later issue should be created for adding TTLs or lastVisited tag to gestalt vertexes, and designing a policy for revisiting nodes when there's nothing in the queue.

Done here: https://github.com/MatrixAI/js-polykey/issues/328

> - Should have another issue to design priority labels to the persistent queue so that when the user interactively wants to discover a gestalt vertex, it becomes the highest priority and gets executed first.

Done here: https://github.com/MatrixAI/js-polykey/issues/329

**Comment by emmacasolin** [comment]
There were actually some problems with starting/stopping/destroying the discovery domain in the Polykey Agent which I've now fixed (not pushed up yet) that were causing a significant number of test failures. This is now fixed and the only remaining failures are the same as the ones on master except for the following four. All of these tests only fail when the entire test suite is run together, so it might just be a timeout issue and they might not fail on the pipeline.

`tests/keys`
- KeyManager > creates a recovery code and can recover from the same code
- KeyManager > create deterministic keypair with recovery code

`tests/bin/agent`
- stop > stopping is idempotent during concurrent calls and STOPPING or DEAD status
- stop > stopping starting agent results in error

**Comment by emmacasolin** [comment]
> There were actually some problems with starting/stopping/destroying the discovery domain in the Polykey Agent which I've now fixed (not pushed up yet) that were causing a significant number of test failures. This is now fixed and the only remaining failures are the same as the ones on master except for the following four. All of these tests only fail when the entire test suite is run together, so it might just be a timeout issue and they might not fail on the pipeline.
> 
> `tests/keys`
> 
> * KeyManager > creates a recovery code and can recover from the same code
> * KeyManager > create deterministic keypair with recovery code
> 
> `tests/bin/agent`
> 
> * stop > stopping is idempotent during concurrent calls and STOPPING or DEAD status
> * stop > stopping starting agent results in error

Yep, running the pipeline now and all of the failures are the same as on master, so none of the failures should be due to any of the changes here.

**Comment by emmacasolin** [comment]
This is now squashed + rebased and is ready for review/merge.

**Comment by CMCDragonkai** [comment]
What about the last tickbox?

BTW updating the inline documentation simply means using docblocks in the right places.

**Comment by emmacasolin** [comment]
> What about the last tickbox?

The "sanity check the final build" one? I'm not entirely sure what this refers to, but my assumption is it's the pipeline, in which case I've checked over that.

> BTW updating the inline documentation simply means using docblocks in the right places.

Oh ok! I'll double check all of that now.

**Comment by CMCDragonkai** [comment]
It's about running `npm run build`. Which should usually work if everything is passing.

File: src/client/service/gestaltsGestaltTrustByNode.ts [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+import type * as nodesPB from '../../proto/js/polykey/v1/nodes/nodes_pb';
+import type { NodeId } from '../../nodes/types';
+import { validateSync } from '../../validation';
+import { matchSync } from '../../utils';
+import * as grpcUtils from '../../grpc/utils';
+import * as validationUtils from '../../validation/utils';
+import * as utilsPB from '../../proto/js/polykey/v1/utils/utils_pb';
+import * as nodesUtils from '../../nodes/utils';
+
+function gestaltsGestaltTrustByIdentity({
```
Comment (joshuakarp) [inline src/client/service/gestaltsGestaltTrustByNode.ts]: Typo - I believe this should be `gestaltsGestaltTrustByNode` (same with the export statement at bottom of file).

File: src/client/service/identitiesInfoConnectedGet.ts [hunk 2]
```diff
@@ -0,0 +1,103 @@
...
+        const authIdentities = await provider.getAuthIdentityIds();
+        if (authIdentities.length === 0) {
+          break;
+        }
+        identities.push(
+          provider.getConnectedIdentityDatas(
+            authIdentities[0],
+            call.request.getSearchTermList(),
+          ),
+        );
```
Comment (joshuakarp) [inline src/client/service/identitiesInfoConnectedGet.ts]: `authIdentities[0]` assumes that we want to use the first authenticated identity to perform this search - but will this always be the case? What if I have multiple GitHub accounts? Would it be better to use all of our authenticated identities on some provider to inform the search?

File: src/client/service/gestaltsGestaltTrustByNode.ts (hunk 1 above)
Comment (emmacasolin) [reply src/client/service/gestaltsGestaltTrustByNode.ts]: Thanks for catching that! It's fixed now

File: src/client/service/identitiesInfoConnectedGet.ts (hunk 2 above)
Comment (emmacasolin) [reply src/client/service/identitiesInfoConnectedGet.ts]: Yeah that's a good point... previously the `authIdentityId` field wasn't being used correctly in most places where the provider was used (i.e. it was being treated as the same thing as `identityId`) so I just went with the easiest option to implement. Not sure if a better solution would be to iterate through all of your authenticated ids every time or whether setting a specifc one to use should be an argument of the `identities search` command (either optional or required)? @CMCDragonkai do you have a preference here?

File: src/client/service/identitiesInfoGet.ts [hunk 3]
```diff
@@ -18,40 +22,90 @@ function identitiesInfoGet({
...
+        // Get our own authenticated identity in order to query, skip provider
+        // if not authenticated
+        const authIdentities = await provider.getAuthIdentityIds();
+        if (authIdentities.length === 0) {
+          break;
+        }
+        // Get identity data
+        identities.push(
+          await provider.getIdentityData(authIdentities[0], identityId),
+        );
```
Comment (joshuakarp) [inline src/client/service/identitiesInfoGet.ts:83]: Another case where we only query one of the authenticated identities of the provider - this seems like a potentially worse case, where we only attempt to get an identity from one of our own authenticated identities. My assumption is that we can only get identity data of `identityId` if it's connected to the `authIdentity` passed?

File: src/client/service/identitiesInfoGet.ts [hunk 4]
```diff
@@ -18,40 +22,90 @@ function identitiesInfoGet({
...
-        const identities = await provider.getAuthIdentityIds();
-        response.setProviderId(providerId);
-        if (identities.length !== 0) {
-          response.setIdentityId(identities[0]);
+      // Process options that were set
+      if (providerIds.length === 0) {
+        Object.keys(identitiesManager.getProviders()).forEach((id) =>
+          providerIds.push(id as ProviderId),
+        );
+      }
```
Comment (joshuakarp) [inline src/client/service/identitiesInfoGet.ts:58]: Just confirming that this is desired - i.e. no providers provided, so we perform the search on **all** providers.

File: src/client/service/identitiesInfoGet.ts (hunk 3 above)
Comment (emmacasolin) [reply src/client/service/identitiesInfoGet.ts:83]: It's not really an issue for `identitiesInfoGet` since you're just querying the provider to get information about an identity. You don't need to be connected to it, you just need any authenticated identity in order to perform the request.

File: src/client/service/identitiesInfoGet.ts (hunk 4 above)
Comment (emmacasolin) [reply src/client/service/identitiesInfoGet.ts:58]: Yeah thats intended - the `providerId` is optional so if you don't provide one you're asking to search across all providers. So for the case of `identitiesInfoGet` you're searching for the same handle across all providers.

File: src/client/service/identitiesInfoGet.ts (hunk 3 above)
Comment (joshuakarp) [reply src/client/service/identitiesInfoGet.ts:83]: Great, wasn't too sure what info we were getting from the request, and whether it meant we'd need to be connected to it.

File: src/client/service/identitiesInfoGet.ts (hunk 4 above)
Comment (joshuakarp) [reply src/client/service/identitiesInfoGet.ts:58]: Great, resolved.

File: src/client/service/identitiesInfoGet.ts [hunk 5]
```diff
@@ -18,40 +22,90 @@ function identitiesInfoGet({
...
+      if (getDisconnected) {
+        // Currently this command performs the same way regardless of whether
+        // this option is set (i.e. always disconnected)
+      }
+      const identities: Array<IdentityData | undefined> = [];
+      for (const providerId of providerIds) {
+        // Get provider from id
+        const provider = identitiesManager.getProvider(providerId);
+        if (provider === undefined)
+          throw new identitiesErrors.ErrorProviderMissing();
```
Comment (joshuakarp) [inline src/client/service/identitiesInfoGet.ts]: @CMCDragonkai can potentially confirm this, but based on comments on other PRs, I think we're preferring the style of:

```ts
if (provider === undefined) {
  throw new identitiesErrors.ErrorProviderMissing();
}
```

Single line conditionals are fine too:

```ts
if (provider === undefined) throw new identitiesErrors.ErrorProviderMissing();
```

but I believe the linter will cause a newline because this line would be too long.

Comment (emmacasolin) [reply src/client/service/identitiesInfoGet.ts]: Yeah I think that was the linter - I'll add in brackets

File: src/discovery/Discovery.ts [hunk 6]
```diff
@@ -11,252 +12,400 @@ import type {
...
-            // Add this vertex to the queue if it hasn't already been visited
-            const linkedVertexGK =
-              gestaltsUtils.keyFromNode(linkedVertexNodeId);
-            if (!visitedVertices.has(linkedVertexGK)) {
-              vertexQueue.push(linkedVertexGK);
+            // Iterate over each of the claims in the chain (already verified)
+            // TODO: because we're iterating over keys in a record, I don't believe
+            // that this will iterate in lexicographical order of keys. For now,
+            // this doesn't matter though (because of the previous comment).
+            for (const claimId in vertexChainData) {
```
Comment (joshuakarp) [inline src/discovery/Discovery.ts:247]: This is directly related to #327. We don't currently have the need for ordering in our claims because our claims are only additions. But obviously this is going to be extended - so will be necessary for #327 to be completed before we can support revocations with discovery. I imagine that revocations will require this discovery process to iterate over claims in reverse chronological order.

Nothing to resolve in this PR though, just something to point out for future.

File: src/client/service/identitiesInfoConnectedGet.ts (hunk 2 above)
Comment (CMCDragonkai) [reply src/client/service/identitiesInfoConnectedGet.ts]: So we can default to the first auth identity id, and allow the user to select a different one in the parameters.

Is there a separate call that you can do to know what auth identity ids you have?

File: src/discovery/Discovery.ts (hunk 6 above)
Comment (CMCDragonkai) [reply src/discovery/Discovery.ts:247]: #327 can be solved in a later PR right after this one, as it will make changes to `Discovery` as well.

File: src/client/service/identitiesInfoConnectedGet.ts (hunk 2 above)
Comment (emmacasolin) [reply src/client/service/identitiesInfoConnectedGet.ts]: There's a method on the provider, so I'd just need to create a relevant command + handler to do it. For the naming maybe something like `identitiesAuthenticatedGet` and `identities authenticated`? Might be a bit too similar to `identities authenticate` though.

File: src/discovery/Discovery.ts (hunk 6 above)
Comment (emmacasolin) [reply src/discovery/Discovery.ts:247]: Ok, I'll resolve this then.

File: src/client/service/identitiesInfoConnectedGet.ts (hunk 2 above)
Comment (emmacasolin) [reply src/client/service/identitiesInfoConnectedGet.ts]: > So we can default to the first auth identity id, and allow the user to select a different one in the parameters.

There is actually one problem with doing this that I just realised - with our new validation system an identity id that is an empty string is considered invalid, however, if we don't set a parameter then the default proto value is an empty string. So this means the expected behaviour of an empty string being used to represent a value not being set will be considered a validation error. A simple solution would be just not validating the identity id, but this could cause problems in the future if we ever change the way that identity ids are validated.

Comment (emmacasolin) [reply src/client/service/identitiesInfoConnectedGet.ts]: The alternative would be to create an extra field in the `ProviderSearch` message to check for whether the auth identity id is set or not, and only validate it if this boolean is set, e.g.
```proto
message ProviderSearch {
  string auth_identity_id = 1;
  bool has_auth_identity_id = 2; // set this to true if the value above has been explicitly set
  string identity_id = 3;
  bool disconnected = 4;
  string limit = 5;
  repeated string search_term = 6;
  repeated string provider_id = 7;
}
```

Comment (CMCDragonkai) [reply src/client/service/identitiesInfoConnectedGet.ts]: I think the default value in our CLI arguments is actually `undefined`, not empty string. That is if you don't do `--param ...` then whatever that parameter is will just be `undefined`. Then that way you can check if it is `undefined`, if and so, just proceed to use the first auth identity.

Comment (emmacasolin) [reply src/client/service/identitiesInfoConnectedGet.ts]: The auth identities are stored inside `IdentitiesManager`, so we can't get the first auth identity from the client side (it has to be done on the server side). Becaue of this, a value might not be set for that field, in which case it would be an empty string.

Comment (CMCDragonkai) [reply src/client/service/identitiesInfoConnectedGet.ts]: Try using:

```
oneof identity_id {
  string string_value = 1;
}
```

If the `oneof` results in a potentially `undefined` value in the JS, then that can be your sentinel value.

Comment (CMCDragonkai) [reply src/client/service/identitiesInfoConnectedGet.ts]: We basically need an "explicit" `optional` for proto3. And I'm wondering if `oneof` is what we need for that situation: https://developers.google.com/protocol-buffers/docs/proto3#oneof

Otherwise `NullValue` from `struct.proto` could be used as that sentinel case.

Comment (CMCDragonkai) [reply src/client/service/identitiesInfoConnectedGet.ts]: According to this answer https://stackoverflow.com/a/42634681/582917, you can use `oneof` to represent this explicit optional. Also future versions of proto3 will reintroduce the explicit `optional` keyword that we can use. At least for now, the `oneof` is more semantically correct to represent an explicitly optional property of a message.

Comment (CMCDragonkai) [reply src/client/service/identitiesInfoConnectedGet.ts]: We're still in proto3 3.14. The next version of proto3 will have the explicit `optional` available. So we will use `oneof` for now.

Comment (CMCDragonkai) [reply src/client/service/identitiesInfoConnectedGet.ts]: Note that the name of the `oneof`. I'm not sure what the effect of each name will be. https://stackoverflow.com/a/46821842/582917

This answer suggests doing:

```
oneof optional_identity_id {
  string identity_id = 1;
}
```

You can try it out and see how it goes.

Comment (emmacasolin) [reply src/client/service/identitiesInfoConnectedGet.ts]: Using
```proto
oneof optional_auth_identity_id {
  string auth_identity_id = 1;
}
```
Generates the following
```ts
hasAuthIdentityId(): boolean;
clearAuthIdentityId(): void;
getAuthIdentityId(): string;
getOptionalAuthIdentityIdCase(): ProviderSearch.OptionalAuthIdentityIdCase;

export namespace ProviderSearch {
    export type AsObject = {
        authIdentityId: string,
        identityId: string,
        disconnected: boolean,
        limit: string,
        searchTermList: Array<string>,
        providerIdList: Array<string>,
    }

    export enum OptionalAuthIdentityIdCase {
        OPTIONAL_AUTH_IDENTITY_ID_NOT_SET = 0,
        AUTH_IDENTITY_ID = 1,
    }

}
```

So we can call `hasAuthIdentityId()` to check if it has been explicitly set, and if so we can validate the value of `getAuthIdentityId()`.

File: src/discovery/Discovery.ts [hunk 7]
```diff
@@ -1,262 +1,411 @@
...
+                // not equal to nodeId from above
+                const node1Id = nodesUtils.decodeNodeId(
+                  claim.payload.data.node1,
+                )!;
+                const node2Id = nodesUtils.decodeNodeId(
+                  claim.payload.data.node2,
+                )!;
+                const linkedVertexNodeId = node1Id.equals(nodeId)
+                  ? node2Id
+                  : node1Id;
```
Comment (joshuakarp) [inline src/discovery/Discovery.ts:262]: A quick note about this too. For all current node to node claim set-ups, I've set it such that `node1` refers to the node that the claim is appearing on (e.g. a claim from `A` to `B` on `A`'s sigchain will have `node1` set as `A`.

Obviously, this is a more robust solution though.

In the future, this could possibly be improved by giving more descriptive field names in the claim (e.g. `sourceNode`, `targetNode`, or some other variant).

File: src/discovery/utils.ts [hunk 8]
```diff
@@ -0,0 +1,19 @@
...
+import { makeId } from '../GenericIdTypes';
+
+function makeDiscoveryQueueId(arg: any) {
+  return makeId<DiscoveryQueueId>(arg);
+}
+
+function createDiscoveryQueueIdGenerator(
+  lastId?: DiscoveryQueueId,
+): DiscoveryQueueIdGenerator {
+  const idSortableGenerator = new IdSortable({
```
Comment (joshuakarp) [inline src/discovery/utils.ts:12]: Is there a reason why the `DiscoveryQueueId` is an `IdSortable`?

Comment (CMCDragonkai) [reply src/discovery/utils.ts:12]: It's a time-ordered ID stored in the DB. That's the primary reason. It's also monotonic, and you can also extract the timestamp out of it.

**Comment by joshuakarp** [comment]
I completed my review of this PR over the weekend - everything else looks fine to me.

~~Although, I've just ran the `Discovery` tests, and it appears they are failing at this stage:~~

<details>

```
josh@josh-XPS-13-9360:~/Documents/MatrixAI/js-polykey$ npm test tests/discovery/

> @matrixai/polykey@1.0.0 test
> jest "tests/discovery/"

Determining test suites to run...
GLOBAL SETUP
Global Data Dir: /tmp/polykey-test-global-KR4d9i
WARN: 0.0.0.0:51093:Forward Error: ErrorConnectionEndTimeout
 FAIL  tests/discovery/Discovery.test.ts (24.885 s)
  Discovery
    ✓ discovery readiness (10 ms)
    ✕ discovery by node (21 ms)
    ✕ discovery by identity (4 ms)
    ✕ updates previously discovered gestalts (4 ms)
    ✕ discovery persistence across restarts (6 ms)

  ● Discovery › discovery by node

    ErrorNodeGraphEmptyDatabase:

      518 |     // then we should throw an error. We aren't going to find any others.
      519 |     if (shortlist.length === 0) {
    > 520 |       throw new nodesErrors.ErrorNodeGraphEmptyDatabase();
          |             ^
      521 |     }
      522 |     // Need to keep track of the nodes that have been contacted.
      523 |     // Not sufficient to simply check if there's already a pre-existing connection

      at Object.getClosestGlobalNodes (src/nodes/NodeGraph.ts:520:13)
      at Object.findNode (src/nodes/NodeManager.ts:610:17)
      at Object.establishNodeConnection (src/nodes/NodeManager.ts:485:27)
      at Object.getConnectionToNode (src/nodes/NodeManager.ts:466:22)
      at Object.requestChainData (src/nodes/NodeManager.ts:297:24)
      at Object.setupDiscoveryQueue (src/discovery/Discovery.ts:216:33)
      at Object.runDiscoveryQueue (src/discovery/Discovery.ts:354:22)

  ● Discovery › discovery by identity

    ErrorNodeGraphEmptyDatabase:

      518 |     // then we should throw an error. We aren't going to find any others.
      519 |     if (shortlist.length === 0) {
    > 520 |       throw new nodesErrors.ErrorNodeGraphEmptyDatabase();
          |             ^
      521 |     }
      522 |     // Need to keep track of the nodes that have been contacted.
      523 |     // Not sufficient to simply check if there's already a pre-existing connection

      at Object.getClosestGlobalNodes (src/nodes/NodeGraph.ts:520:13)
      at Object.findNode (src/nodes/NodeManager.ts:610:17)
      at Object.establishNodeConnection (src/nodes/NodeManager.ts:485:27)
      at Object.getConnectionToNode (src/nodes/NodeManager.ts:453:22)
      at Object.requestChainData (src/nodes/NodeManager.ts:297:24)
      at Object.setupDiscoveryQueue (src/discovery/Discovery.ts:216:33)
      at Object.runDiscoveryQueue (src/discovery/Discovery.ts:354:22)

  ● Discovery › updates previously discovered gestalts

    ErrorNodeGraphEmptyDatabase:

      518 |     // then we should throw an error. We aren't going to find any others.
      519 |     if (shortlist.length === 0) {
    > 520 |       throw new nodesErrors.ErrorNodeGraphEmptyDatabase();
          |             ^
      521 |     }
      522 |     // Need to keep track of the nodes that have been contacted.
      523 |     // Not sufficient to simply check if there's already a pre-existing connection

      at Object.getClosestGlobalNodes (src/nodes/NodeGraph.ts:520:13)
      at Object.findNode (src/nodes/NodeManager.ts:610:17)
      at Object.establishNodeConnection (src/nodes/NodeManager.ts:485:27)
      at Object.getConnectionToNode (src/nodes/NodeManager.ts:453:22)
      at Object.requestChainData (src/nodes/NodeManager.ts:297:24)
      at Object.setupDiscoveryQueue (src/discovery/Discovery.ts:216:33)
      at Object.runDiscoveryQueue (src/discovery/Discovery.ts:354:22)

  ● Discovery › discovery persistence across restarts

    ErrorNodeGraphEmptyDatabase:

      518 |     // then we should throw an error. We aren't going to find any others.
      519 |     if (shortlist.length === 0) {
    > 520 |       throw new nodesErrors.ErrorNodeGraphEmptyDatabase();
          |             ^
      521 |     }
      522 |     // Need to keep track of the nodes that have been contacted.
      523 |     // Not sufficient to simply check if there's already a pre-existing connection

      at Object.getClosestGlobalNodes (src/nodes/NodeGraph.ts:520:13)
      at Object.findNode (src/nodes/NodeManager.ts:610:17)
      at Object.establishNodeConnection (src/nodes/NodeManager.ts:485:27)
      at Object.getConnectionToNode (src/nodes/NodeManager.ts:453:22)
      at Object.requestChainData (src/nodes/NodeManager.ts:297:24)
      at Object.setupDiscoveryQueue (src/discovery/Discovery.ts:216:33)
      at Object.runDiscoveryQueue (src/discovery/Discovery.ts:354:22)
      at Object.stop (src/discovery/Discovery.ts:147:5)
      at Object.stop (node_modules/@matrixai/async-init/src/CreateDestroyStartStop.ts:130:22)

Test Suites: 1 failed, 1 total
Tests:       4 failed, 1 passed, 5 total
Snapshots:   0 total
Time:        24.916 s, estimated 29 s
Ran all test suites matching /tests\/discovery\//i.
GLOBAL TEARDOWN
Destroying Global Data Dir: /tmp/polykey-test-global-KR4d9i
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.

```

</details>

~~I'll take a quick look at this.~~

Never mind - all fine, it was a problem on my end.

File: src/discovery/Discovery.ts (hunk 7 above)
Comment (emmacasolin) [reply src/discovery/Discovery.ts:262]: Ahh, yes I made this change when I was getting a weird bug where I was seeing node claims from nodes to themselves appearing in the gestalt graph (e.g. Node A claiming Node A). I thought that this is where the issue was coming from at first, however in the end I think the error was coming solely from the gestalt graph (https://github.com/MatrixAI/js-polykey/pull/320#issuecomment-1026394383). So this change can either remain or be reverted.

File: src/discovery/utils.ts (hunk 8 above)
Comment (emmacasolin) [reply src/discovery/utils.ts:12]: Yes, that's correct. The usage is exactly the same as in `NotificationsManager` with the `NotificationId` there.

File: src/discovery/Discovery.ts (hunk 7 above)
Comment (joshuakarp) [reply src/discovery/Discovery.ts:262]: That's fine - this can remain. I've made a comment about this here https://github.com/MatrixAI/js-polykey/issues/189#issuecomment-1038464478. Resolving this.

File: src/discovery/utils.ts (hunk 8 above)
Comment (joshuakarp) [reply src/discovery/utils.ts:12]: Great - resolving.

File: src/client/service/identitiesInfoConnectedGet.ts (hunk 2 above)
Comment (emmacasolin) [reply src/client/service/identitiesInfoConnectedGet.ts]: > There's a method on the provider, so I'd just need to create a relevant command + handler to do it. For the naming maybe something like `identitiesAuthenticatedGet` and `identities authenticated`? Might be a bit too similar to `identities authenticate` though.

I've created a CLI command and rpc handler for this, however I'm a little stuck on the naming. The handler is called `identitiesAuthenticatedGet`, so some potential options for the command are:
- `identities authenticated` - potentially too similar to `identities authenticate`?
- `identities linked`
- `identities connected` - might be confused with `identities search`
- `identities authorised`/`identities authorized`
- `identities authenticate --list` - make it a flag on the existing `identities authenticate` command
- Scrap the command and handler all together and just use `identities get [identityId]` to display own gestalt - requires user to know at least one of their authenticated identities + requires https://github.com/MatrixAI/js-polykey/issues/319

Comment (CMCDragonkai) [reply src/client/service/identitiesInfoConnectedGet.ts]: Something like this to fetch all the authenticated identities/tokens:

```
pk identities tokens
pk identities tokens --provider-id='...'
```

The `tokens` is what they are.

The GRPC call could be `identitiesTokensGet`. Maybe adapt the existing `identitiesTokenGet` call to it.

Comment (emmacasolin) [reply src/client/service/identitiesInfoConnectedGet.ts]: The `token`s stored in `IdentitiesManager` (what is retrieved by `identitiesTokenGet`) are actually `TokenData`s:
```ts
type TokenData = {
  accessToken: string;
  refreshToken?: string;
  accessTokenExpiresIn?: number;
  refreshTokenExpiresIn?: number;
};
```
I was also incorrect in my previous assumption that `identitiesTokenGet` was getting all tokens - you give it a `ProviderId` and an `IdentityId` and it returns the token for that identity id. Repurposing this handler for retrieving authenticated identity ids would also mean that `identitiesTokenPut` and `identitiesTokenDelete` would no longer have a corresponding 'getter'.

Is there a reason a user would need to be able to manipulate tokens at such a low level though? None of these handlers are exposed to the CLI anyway so maybe they should just all be removed? Then we can use the word 'token' to mean 'authenticated identity id' throughout the CLI without worrying about it being confused with `TokenData`?

Comment (CMCDragonkai) [reply src/client/service/identitiesInfoConnectedGet.ts]: I forgot about these other commands. If so, then you could keep it as `identitiesTokenGet` and `pk identities token` command instead.

We'll look into the overall CLI later, let's keep this simple for now and just token manipulation is fine. And it's a CLI, the GUI may further abstract.

Comment (emmacasolin) [reply src/client/service/identitiesInfoConnectedGet.ts]: Since this PR doesn't really deal with token manipulation, I think writing CLI commands for the token manipulation handlers can probably just wait until the general CLI review.

If we still want a command for listing the identities we currently have authenticated, then it sounds like this would be separate from the token manipulation commands. But in that case we're back to the original question of what should the command that does this be called. Again, this functionality isn't necessarily required in order to finish off this PR, and it can always be addressed later.

Comment (emmacasolin) [reply src/client/service/identitiesInfoConnectedGet.ts]: Going back to this
> BTW, I remember now that we made a decision to group all gestalt-related functionality within the identities subcommand. So there is no pk gestalts subcommand. This was a UX decision so that users don't have to know what "gestalt" means. We can reverse this decision, but for now most of what we want to do will be identity focused.

This PR probably isn't the place for it, but I think separating the identities and gestalts commands is something we will eventually need to do, and I think the naming difficulties we're having here are a good example of why. We already have `identities list` and `identities get` commands, either of these would be good options for a command that lists/gets your own auth identities, however they're already being used for gestalts-related subcommands. 

Again, this sort of thing is outside the scope of this PR, so I'm leaning towards creating a separate issue for reviewing the identities CLI specifically (including everything that has been brought up in this thread) and linking it to the general CLI review issue.

**Comment by emmacasolin** [comment]
Rebased on master. All tests are still passing and everything has been lintfixed again. All that's left for this PR is this remaining issue: https://github.com/MatrixAI/js-polykey/pull/320#discussion_r804223154

At the moment I've implented the ability to lookup your own authenticated identity ids using the command `pk identities authenticated`. The naming could probably be improved, but this is something that could be left to a later PR, as suggested here https://github.com/MatrixAI/js-polykey/pull/320#discussion_r805494454

File: src/bin/utils/parsers.ts [hunk 9]
```diff
@@ -72,4 +101,7 @@ export {
   parseSeedNodes,
   parseCoreCount,
   parseSecretPath,
+  parseProviderIdList,
+  parseIdentityId,
+  parseProviderId,
```
Comment (CMCDragonkai) [inline src/bin/utils/parsers.ts]: Get your exports in the same order as your definitions above.

File: src/bin/utils/parsers.ts [hunk 10]
```diff
@@ -21,6 +21,25 @@ function validateParserToArgParser<T>(
   };
 }
 
+/**
+ * Converts a validation parser to commander variadic argument parser
+ */
```
Comment (CMCDragonkai) [inline src/bin/utils/parsers.ts:27]: Can you make a comment about how variadic options/arguments are always space separated.

I would also just prototype and see what happens if you were to do something like `--variadic-option 'a b c' '123'` and `--variadic-option='a b c' --variadic-option=123`, to see how it handles spaces that are within the same item.

**Comment by CMCDragonkai** [comment]
This should fix https://github.com/MatrixAI/js-polykey/pull/310#issuecomment-1038640288

> tests/bin/identities/identities.test.ts

However the splitting of that will be in MatrixAI/Polykey#311.

Same with `tests/client/rpcGestalts`.

File: src/bin/utils/parsers.ts (hunk 9 above)
Comment (emmacasolin) [reply src/bin/utils/parsers.ts]: Fixed

File: src/bin/utils/parsers.ts (hunk 10 above)
Comment (emmacasolin) [reply src/bin/utils/parsers.ts:27]: Added a comment - will add tests for this when I continue test splitting in #311.

**Comment by emmacasolin** [comment]
> This should fix [#310 (comment)](https://github.com/MatrixAI/js-polykey/pull/310#issuecomment-1038640288)
> 
> > tests/bin/identities/identities.test.ts
> 
> However the splitting of that will be in MatrixAI/Polykey#311.
> 
> Same with `tests/client/rpcGestalts`.

`tests/bin/identities/identities.test.ts` is actually still failing here. I attempted to debug it, however there are many nested describes and instances of setting state in `beforeEach`/`afterEach` that make it incredibly difficult to work out where the errors are coming from. I think it will be easier to do this while splitting the tests in MatrixAI/Polykey#311, expecially considering there's a good chance that most of the errors are from inteference that splitting the tests removes anyway.

**Comment by CMCDragonkai** [comment]
Merged. @emmacasolin remember to avoid using full stops in our comments, mainly as it's not used in other places. Docblocks can use it for very long commentary, but I usually do this:

```
/**
 *  Something something something
 *  Beginning something something
 *  continuing the comment
 */
```

So no full stops ever used.

So MatrixAI/Polykey#311 will have more things to do, can you update the PR description there to include fixing tests:

1. `tests/bin/identities/identities.test.ts`
2. `tests/client/rpcGestalts.test.ts`

Also new issue(s) for `pk identities token` commands, remember to spec it out

File: src/client/service/identitiesInfoConnectedGet.ts (hunk 2 above)
Comment (emmacasolin) [reply src/client/service/identitiesInfoConnectedGet.ts]: This will be resolved in a new issue: https://github.com/MatrixAI/js-polykey/issues/334
